pkg add: libime
AOSC-Dev/aosc-os-abbs pull request #1495
Opened 2018-11-24 12:53 UTC by eatradish

https://gitlab.com/fcitx/libime

2018-11-24 19:23 UTC, liushuyu requested changes
Request changes

2018-11-24 19:23 UTC, liushuyu commented on extra-libs/libime/autobuild/defines
> +PKGDEP="fcitx5 boost"
```suggestion
PKGDEP="fcitx-5 boost"
```

Okay, you forgot to change the name to match your changes to the name of `fcitx-5`

2018-11-24 21:19 UTC, RedL0tus commented
Hmm... this library may belong to app-i18n (just like librime)?

2018-11-24 21:24 UTC, eatradish commented
> Hmm... this library may belong to extra-i18n (just like librime)?

maybe...

2018-11-24 21:25 UTC, RedL0tus requested changes

2018-11-24 21:25 UTC, RedL0tus commented on extra-libs/libime/autobuild/defines
> +PKGDES="This is a library to support generic input method implementation"
```suggestion
PKGSEC=libs
PKGDES="This is a library to support generic input method implementation"
```

Should have a PKGSEC.

2018-11-24 21:44 UTC, RedL0tus commented on extra-libs/libime/spec
> +GITSRC="https://gitlab.com/fcitx/libime"
```suggestion
GITSRC="https://gitlab.com/fcitx/libime"
GITCO="d612e0722a3fed5ede2138195c8b54d61dca4798"
```

Also GITCO here.

2018-11-25 04:10 UTC, liushuyu commented
Add the following to `autobuild/prepare`

```bash
LIBTOPDIR="$(pwd)/build/src/libime"
for i in core pinyin table; do
export LD_LIBRARY_PATH="${LIBTOPDIR}/${i}":$LD_LIBRARY_PATH
done
```

2018-11-25 05:34 UTC, liushuyu commented on extra-i18n/libime/autobuild/defines
> +PKGDEP="fcitx-5 boost"
Okay, you need to change this thing back to `fcitx5` again

```suggestion
PKGDEP="fcitx5 boost"
```

2018-11-25 05:34 UTC, liushuyu commented on extra-i18n/libime/autobuild/defines
> +BUILDEP="boost extra-cmake-modules git python-3"
For this part, dependencies that are already included in the `PKGDEP` don't need to be added again here.

```suggestion
BUILDEP="extra-cmake-modules git python-3"
```

2018-11-25 05:35 UTC, RedL0tus approved these changes

2018-11-25 05:36 UTC, liushuyu commented on extra-i18n/libime/autobuild/defines
> +PKGDES="This is a library to support generic input method implementation"
```suggestion
PKGDES="A library to support generic input method implementation"
```

2018-11-25 05:41 UTC, liushuyu commented on extra-i18n/libime/autobuild/defines
> +PKGDES="A library to support generic input method implementation"
```suggestion
PKGDES="A library to support generic input method implementation"
PKGSEC=libs
```

2018-11-25 05:41 UTC, liushuyu commented on extra-i18n/libime/autobuild/defines
> +PKGDES="A library to support generic input method implementation"
You need to add `PKGSEC`

2018-11-25 05:58 UTC, merged