pkg add: fcitx5-gtk
AOSC-Dev/aosc-os-abbs pull request #1496
Opened 2018-11-24 13:24 UTC by eatradish

https://gitlab.com/fcitx/fcitx5-gtk

2018-11-24 21:20 UTC, RedL0tus commented
Missing spec, and it should belong to extra-i18n(?

2018-11-24 21:28 UTC, eatradish commented
> Missing spec, and it should belong to extra-i18n(?

Yep, but I don't know where to put it.

2018-11-24 21:36 UTC, RedL0tus commented
> > Missing spec, and it should belong to extra-i18n(?
> 
> Yep, but I don't know where to put it.

Just like what you did to the other packages...

2018-11-25 03:11 UTC, liushuyu reviewed
Okay, you need to remove b0922ae9c14c44769a12e852da6cd02e1ff18ae4

2018-11-25 03:11 UTC, liushuyu commented on fcitx5-gtk/autobuild/defines
> +PKGDEP="fcitx5 gtk-2 gtk-3"
```suggestion
PKGDEP="fcitx-5 gtk-2 gtk-3"
```

Same issue here, and because you named the dependency `fcitx-5` so here you need to reflect that. Otherwise `apt` will complain about couldn't find the package named `fcitx5`

2018-11-25 06:28 UTC, liushuyu requested changes
Move `gtk-2 gtk-3` to `BUILDDEP`

2018-11-25 06:28 UTC, liushuyu commented on fcitx5-gtk/autobuild/defines
> +PKGDEP="fcitx-5 gtk-2 gtk-3"
```suggestion
PKGDEP="fcitx5"
```

2018-11-25 06:28 UTC, liushuyu commented on fcitx5-gtk/autobuild/defines
> +BUILDEP="extra-cmake-modules gobject-introspection git"
```suggestion
BUILDEP="gtk-2 gtk-3 extra-cmake-modules gobject-introspection git"
```

2018-11-25 07:13 UTC, liushuyu approved these changes

2018-11-25 07:13 UTC, merged