pkg add: kcm-fcitx5
AOSC-Dev/aosc-os-abbs pull request #1502
Opened 2018-11-26 00:03 UTC by eatradish

https://gitlab.com/fcitx/kcm-fcitx5

2018-11-26 00:05 UTC, liushuyu requested changes
`PKGSEC`?

2018-11-26 00:05 UTC, liushuyu commented on extra-i18n/kcm-fcitx5/autobuild/defines
> +PKGDEP="fcitx5 knewstuff kcmutils"
`PKGSEC`?

2018-11-26 00:06 UTC, eatradish commented on extra-i18n/kcm-fcitx5/autobuild/defines
> +PKGDEP="fcitx5 knewstuff kcmutils"
> `PKGSEC`?

OK...wait

2018-11-26 01:25 UTC, eatradish commented on extra-i18n/kcm-fcitx5/autobuild/defines
> +PKGDEP="fcitx5 knewstuff kcmutils"
> `PKGSEC`?

ok...added

2018-11-30 04:37 UTC, MingcongBai commented
Looks good to me. Thank you!

2018-11-30 04:37 UTC, merged