svxlink: new, 17.12.2
AOSC-Dev/aosc-os-abbs pull request #1886
Opened 2019-07-08 03:11 UTC by misaka4e21

https://www.svxlink.org/
VoIP for HAMs. Maybe an [EchoLink](http://www.echolink.org/) replacement on GNU/Linux.

Re-target #1885 to explosive branch.

2019-09-24 05:13 UTC, KexyBiscuit commented
Changing base to testing-proposed to reflect the new workflow.

2019-09-24 05:14 UTC, KexyBiscuit commented
Oops, sorry.

2020-01-31 21:12 UTC, MingcongBai requested changes

2020-01-31 21:12 UTC, MingcongBai commented on extra-radio/svxlink/autobuild/defines
> +CMAKE_AFTER=" -DUSE_QT=YES ../src"
This is an incorrect use of CMake ABTYPE. Please set `SUBDIR=svxlink-$PKGVER/src` in `spec`.

2020-01-31 21:12 UTC, MingcongBai commented on extra-radio/svxlink/autobuild/override/usr/lib/systemd/system/svxlink.service
> +
Please clean up extra newlines here.

2020-01-31 21:12 UTC, MingcongBai commented on extra-radio/svxlink/autobuild/postinst
> +/usr/bin/egrep -i "^svxlink" /etc/passwd >> /dev/zero
This is unsafe, what if there is `svxlink-daemon`? Could you please try and use `systemd-sysusers` here?

2020-01-31 21:12 UTC, MingcongBai commented on extra-radio/svxlink/autobuild/postrm
> +        groupdel svxlink
No need to remove users on uninstallation.

2020-10-25 05:42 UTC, MingcongBai commented
Closing - this is *not* a rejection.

We are switching to a topic-based maintenance system. Please re-create your PR against our `stable` branch, use our new Pull Request template, and work in accordance to our [maintenance guidelines](https://wiki.aosc.io/developer/packaging/topic-based-maintenance-guideline/).

2020-10-25 05:42 UTC, closed without merging