Introduce triehash to build apt
AOSC-Dev/aosc-os-abbs pull request #1957
Opened 2019-08-13 10:01 UTC by KexyBiscuit

Fix #1913.

> Fixed by introducing triehash, thanks to Debian/apt#68, close this after the PR gets merged.

2019-08-15 14:00 UTC, eatradish approved these changes

2019-08-15 15:35 UTC, MingcongBai requested changes
Sorry to waste your time, but there are two words that you should consider changing.

2019-08-15 15:35 UTC, MingcongBai commented on extra-devel/triehash/autobuild/build
> +abinfo "Build TrieHash"
Building.

2019-08-15 15:35 UTC, MingcongBai commented on extra-devel/triehash/autobuild/build
> +abinfo "Deploy files"
Deploying

2019-08-21 17:56 UTC, MingcongBai approved these changes

2019-08-22 02:06 UTC, merged