autojump-rs: new, 0.4.0
AOSC-Dev/aosc-os-abbs pull request #2215
Opened 2020-07-24 03:30 UTC by chenx97

Help me make a better `beyond` script, please

2020-07-26 21:30 UTC, MingcongBai requested changes

2020-07-26 21:30 UTC, MingcongBai commented on extra-utils/autojump-rs/autobuild/defines
> +PKGPROV=autojump
I'd add an empty line but suit yourself.

2020-07-26 21:30 UTC, MingcongBai commented on extra-utils/autojump-rs/autobuild/beyond
> +cat > release-$VER.sha256 << EOF
Use absolute path here.

2020-07-26 21:30 UTC, MingcongBai commented on extra-utils/autojump-rs/autobuild/beyond
> +00daf3698e17ac3ac788d529877c03ee80c3790472a85d0ed063ac3a354c37b1 release-v$VER.tar.gz
Where did this come from?

2020-07-26 21:30 UTC, MingcongBai commented on extra-utils/autojump-rs/autobuild/beyond
> +00daf3698e17ac3ac788d529877c03ee80c3790472a85d0ed063ac3a354c37b1 release-v$VER.tar.gz
Also absolute path here.

2020-07-26 21:30 UTC, MingcongBai commented on extra-utils/autojump-rs/autobuild/beyond
> +sha256sum -c release-$VER.sha256 || abdie "Failed checksuming."
Absolute path here.

2020-07-26 21:30 UTC, MingcongBai commented on extra-utils/autojump-rs/autobuild/beyond
> +sha256sum -c release-$VER.sha256 || abdie "Failed checksuming."
You could have not generated the checksum file here. See `extra-web/google-chrome` - I find that to be cleaner.

2020-07-26 21:30 UTC, MingcongBai commented on extra-utils/autojump-rs/autobuild/beyond
> +tar -xf release-v$VER.tar.gz
Verbose.

2020-07-26 21:30 UTC, MingcongBai commented on extra-utils/autojump-rs/autobuild/beyond
> +pushd autojump-release-v$VER
I generally discourage using pushd/popd. Absolute path.

2020-07-26 21:30 UTC, MingcongBai commented on extra-utils/autojump-rs/autobuild/beyond
> +# TODO figure out where to put files necessary for autojump to work with
Comments in build scripts are pointless. Use `abwarn` if attention is wanted.

2020-07-26 21:30 UTC, MingcongBai commented on extra-utils/autojump-rs/autobuild/beyond
> +install -Dvm644 bin/autojump.bash "$PKGDIR"/etc/bashrc.d/40-autojump-rs
Absolute path.

2020-07-27 01:58 UTC, chenx97 commented
changes committed.

2020-07-30 01:11 UTC, MingcongBai requested changes

2020-07-30 01:11 UTC, MingcongBai commented on extra-utils/autojump-rs/autobuild/beyond
> +install -Dvm644 "$SRCDIR"/../assets/autojump-release-*/bin/_j "$PKGDIR"/usr/share/zsh/site-functions/
That file name could be problematic. @liushuyu your insight would be much appreciated.

2020-07-30 01:27 UTC, merged