rclone: update to 1.53.2
AOSC-Dev/aosc-os-abbs pull request #2418
Opened 2020-10-27 06:51 UTC by eatradish

Topic Description
-----------------

rclone: update to 1.53.2

- Use SRCS

Package(s) Affected
-------------------

rclone 1.53.2

Security Update?
----------------

- [ ] Yes
- [x] No

Architectural Progress
----------------------

- [x] AMD64 `amd64`
- [ ] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2020-10-27 06:52 UTC, MingcongBai requested changes

2020-10-27 06:52 UTC, MingcongBai commented on extra-web/rclone/spec
> +SRCS="git::commit=89f2d43f17e60f38619fda797fb0a349ff819d7e::https://github.com/rclone/rclone/"
Try using tag here, describing a tag with a commit hash is confusing.

2020-10-27 06:57 UTC, MingcongBai approved these changes

2020-10-28 04:57 UTC, eatradish commented
In amd64, `rclone config` :

![Uploading image.png…]()

2020-10-28 05:04 UTC, merged

2020-10-28 05:05 UTC, MingcongBai commented
Post-Merge Architectural Progress
----------------------

<!-- Please remove any architecture to which this topic does not apply. -->

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`

<!-- If all package(s) affected by this topic is `noarch`, please use the stub below. -->
<!-- - [ ] Architecture-independent `noarch` -->

<!-- TODO: CI to auto-fill architectural progress. -->

Post-Merge Secondary Architectural Progress
--------------------------------

<!-- Please remove any architecture to which this topic does not apply. -->

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`