deno: update to 1.5.0
AOSC-Dev/aosc-os-abbs pull request #2428
Opened 2020-10-27 23:14 UTC by eatradish

Topic Description
-----------------

deno: update to 1.5.0

- Use gcc to fix build
- Disable LTO, because rust + gcc cannot enable LTO

Package(s) Affected
-------------------

deno 1.5.0

Security Update?
----------------

No

Architectural Progress
----------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

2020-10-28 00:45 UTC, eatradish commented
AArch64 FTBFS: http://fars.ee/xbK9

2020-10-28 00:54 UTC, eatradish commented
Install system llvm afer (USECLANG=0):

![image](https://user-images.githubusercontent.com/19554922/97377504-2e71cd00-18fb-11eb-8b9e-d074b2d65f69.png)

2020-10-28 04:52 UTC, MingcongBai commented
@liushuyu Would you mind taking a look at this?

2020-10-29 06:08 UTC, liushuyu approved these changes

2020-10-29 06:09 UTC, liushuyu commented
I will allow partial LTO using GCC in `autobuild3` soon.

2020-10-29 06:09 UTC, MingcongBai commented
@liushuyu Okay，

2020-10-29 06:10 UTC, MingcongBai commented
> I will allow partial LTO using GCC in `autobuild3` soon.

Okay, please ping us again here when it's done.

2020-10-29 06:13 UTC, MingcongBai commented
@liushuyu It seems that the issue might not be related to LTO? @eatradish has already disabled LTO, and the screenshot seems to suggest that an amd64 buildroot is used when building on AArch64.

2020-10-29 06:41 UTC, liushuyu requested changes

2020-10-29 06:41 UTC, liushuyu commented on extra-js/deno/autobuild/defines
> +NOLTO=1
```suggestion
USECLANG=1
```

2020-10-29 06:41 UTC, liushuyu commented on extra-js/deno/autobuild/prepare
>  export GN_ARGS="no_inline_line_tables=false use_lld=false"
```suggestion
export GN_ARGS="no_inline_line_tables=false use_lld=false is_clang=true"
```

2020-10-29 06:42 UTC, liushuyu commented
Please find suggested changes in the review

2020-10-29 06:44 UTC, MingcongBai commented
> Please find suggested changes in the review

Looks reasonable, but does it still reference the AMD64 buildroot?

2020-10-29 06:48 UTC, liushuyu commented
> > Please find suggested changes in the review
> 
> Looks reasonable, but does it still reference the AMD64 buildroot?

Yes, but it is not going to be used.

2020-10-29 06:48 UTC, MingcongBai commented
@liushuyu Okay, got it. @eatradish You are good to go with this PR.

2020-10-31 21:52 UTC, eatradish commented
Upstream release deno 1.5.1, switch to new PR, Closing...

2020-10-31 21:52 UTC, closed without merging