Ffmpeg enable nvenc
AOSC-Dev/aosc-os-abbs pull request #2433
Opened 2020-10-28 09:00 UTC by eatradish

Topic Description
-----------------

ffmpeg enable NVENC

Package(s) Affected
-------------------

ffmpeg 4.2.4-2
ffnvcodec 10.0.11.0

Security Update?
----------------

No

Build Order
-----------

ffnvcodec
ffmpeg

Architectural Progress
----------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    
 - [ ] 32-bit Optional Environment `optenv32` 

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

 - [ ] 32-bit Optional Environment `optenv32`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2020-10-28 19:56 UTC, MingcongBai requested changes

2020-10-28 19:56 UTC, MingcongBai commented on extra-multimedia/ffmpeg/autobuild/build
> +                --enable-nvenc \
`nvenc` should only be enabled in AMD64 and AArch64.

2020-10-28 19:56 UTC, MingcongBai commented on extra-multimedia/ffmpeg/autobuild/defines
> +BUILDDEP__AMD64="${BUILDDEP} yasm ffnvcodec"
Please also add `ffnvcodec` to `BUILDDEP__ARM64`.

2020-10-28 19:56 UTC, MingcongBai requested changes

2020-10-28 19:56 UTC, MingcongBai commented on extra-libs/ffnvcodec/spec
> +SRCS="git::commit=7a81595786463d1c7efcb03aa85def69fc2cad41::https://git.videolan.org/git/ffmpeg/nv-codec-headers.git"
Please use Git tag here.

2020-10-28 20:45 UTC, eatradish commented
In aarch64: (ffnvcodec installed):

```
ERROR: nvenc requested, but not all dependencies are satisfied: ffnvcodec                                                                                                 
                                                                                                                                                                          
If you think configure made a mistake, make sure you are using the latest                                                                                                 
version from Git.  If the latest version fails, report the problem to the                                                                                                 
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.                                                                                                   
Include the log file "ffbuild/config.log" produced by configure as this will help                                                                                         
solve the problem.                                                                                                                                                        
[ERROR]: Build error detected ^o^                          
```

ffnvcodec `dpkg -L` :

```
root@s-110003 [ tree@ffmpeg-enable-nvenc ] # dpkg -L ffnvcodec
/.
/usr
/usr/include
/usr/include/ffnvcodec
/usr/include/ffnvcodec/dynlink_cuda.h
/usr/include/ffnvcodec/dynlink_cuviddec.h
/usr/include/ffnvcodec/dynlink_loader.h
/usr/include/ffnvcodec/dynlink_nvcuvid.h
/usr/include/ffnvcodec/nvEncodeAPI.h
/usr/lib
/usr/lib/pkgconfig
/usr/lib/pkgconfig/ffnvcodec.pc
/usr/share
/usr/share/doc
/usr/share/doc/ffnvcodec

```

2020-10-28 20:47 UTC, MingcongBai commented
@eatradish Could you please paste your config.log somewhere?

2020-10-28 20:51 UTC, eatradish commented
@MingcongBai AArch64: http://fars.ee/_a8j
AMD64: http://fars.ee/vwLd

2020-10-28 20:53 UTC, eatradish commented
ffnvcodec.pc:

```
root@s-21685 [ ffmpeg-4.2.4 ] # cat /usr/lib/pkgconfig/ffnvcodec.pc
prefix=/usr
includedir=${prefix}/include

Name: ffnvcodec
Description: FFmpeg version of Nvidia Codec SDK headers
Version: 11.0.10.0
Cflags: -I${includedir}
```

2020-10-28 20:57 UTC, MingcongBai commented
@eatradish I couldn't see anything directly related to the detection error, it might be worth looking into how FFmpeg detects ffnvcodec.

2020-10-29 04:38 UTC, OriginCode commented
From `obs-studio-26.0.2` topic `obs-studio`:
```
[h264_nvenc @ 0x55574061ba00] Driver does not support the required nvenc API version. Required: 11.0 Found: 10.0
[h264_nvenc @ 0x55574061ba00] The minimum required Nvidia driver for nvenc is (unknown) or newer
```

2020-10-29 07:28 UTC, eatradish commented
```
info: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Desktop Audio)

info: ---------------------------------
info: [NVENC encoder: 'simple_h264_stream'] settings:
        rate_control: CBR
        bitrate:      2500
        cqp:          0
        keyint:       250
        preset:       hq
        profile:      high
        width:        1280
        height:       720
        2-pass:       false
        b-frames:     2
        GPU:          0

info: libfdk_aac encoder created
info: libfdk_aac bitrate: 160, channels: 2
info: ==== Recording Start ===============================================
info: [ffmpeg muxer: 'simple_file_output'] Writing file '/home/saki/2020-10-29 15-24-16.mkv'...
info: [ffmpeg muxer: 'simple_file_output'] Output of file '/home/saki/2020-10-29 15-24-16.mkv' stopped
info: Output 'simple_file_output': stopping
info: Output 'simple_file_output': Total frames output: 157
info: Output 'simple_file_output': Total drawn frames: 169

```

Everything ok.

2020-10-29 07:52 UTC, OriginCode commented
LGTM. (prime-run, NVENC enabled, recording without any error)
![image](https://user-images.githubusercontent.com/17294071/97540424-93fab200-19fe-11eb-83a9-34f76bd4a423.png)

2020-10-29 07:52 UTC, cthbleachbit approved these changes
```
info: [NVENC encoder: 'recording_h264'] settings:
        rate_control: CBR
        bitrate:      2500
        cqp:          0
        keyint:       250
        preset:       hq
        profile:      high
        width:        1920
        height:       1080
        2-pass:       false
        b-frames:     2
        GPU:          0
```

It works.

2020-10-29 07:53 UTC, MingcongBai commented
Thanks all!

@eatradish Please re-adjust NVENC enablement - disable it on AArch64 for now. This will be supported in FFmpeg 4.3.

2020-10-29 07:59 UTC, MingcongBai approved these changes

2020-10-31 07:20 UTC, merged