kdiskmark: new, 2.0.0
AOSC-Dev/aosc-os-abbs pull request #2442
Opened 2020-10-29 08:13 UTC by eatradish

Topic Description
-----------------

kdiskmark: new, 2.0.0

Package(s) Affected
-------------------

kdiskmark 2.0.0

Security Update?
----------------

No

Architectural Progress
----------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2020-10-29 08:14 UTC, MingcongBai requested changes

2020-10-29 08:14 UTC, MingcongBai commented on extra-kde/kdiskmark/autobuild/defines
> +BUILDDEP="extra-cmake-modules ecm"
What `ecm`?

2020-10-29 08:14 UTC, MingcongBai commented on extra-kde/kdiskmark/autobuild/defines
> +PKGDES="A simple open-source disk benchmark tool"
"Open-source" is probably redundant here.

2020-10-29 08:14 UTC, MingcongBai commented on extra-kde/kdiskmark/spec
> +CHKSUMS="sha256::x"
Update checksum here.

2020-10-29 23:45 UTC, eatradish commented
![image](https://user-images.githubusercontent.com/19554922/97643879-ca2e4500-1a83-11eb-9133-db615493f13c.png)

but why RND4K no data?

2020-10-30 05:32 UTC, MingcongBai requested changes

2020-10-30 05:32 UTC, MingcongBai commented on extra-utils/fio/autobuild/build
> +./configure --disable-native --enable-gfio --extra-cflags="$CFLAGS"
Please use absolute path here.

2020-10-30 05:32 UTC, MingcongBai commented on extra-utils/fio/autobuild/build
> +install -Dvm644 COPYING "$PKGDIR/usr/share/doc/$PKGNAME/COPYING"
`COPYING` is installed by default by Autobuild3.

2020-10-30 05:32 UTC, MingcongBai commented on extra-utils/fio/autobuild/build
> +install -vm644 HOWTO README REPORTING-BUGS SERVER-TODO "$PKGDIR/usr/share/doc/$PKGNAME"
Please use absolute path here.

2020-10-30 05:32 UTC, MingcongBai commented on extra-utils/fio/autobuild/build
> +install -Dvm644 MORAL-LICENSE "$PKGDIR/usr/share/doc/$PKGNAME/MORAL-LICENSE"
Please use absolute path here.

2020-10-30 05:59 UTC, MingcongBai commented
![图片](https://user-images.githubusercontent.com/5006263/97666218-67fd2200-1a3a-11eb-87ea-63598820673c.png)

On my POWER9 box (`ppc64el`), KDiskMark doesn't seem to anything after confirming removal of `~/.kdiskmark.tmp`. No verbose or logging option is available.

2020-10-30 06:02 UTC, MingcongBai commented
The confirmation above is referenced by this operation in source code.

https://github.com/JonMagon/KDiskMark/search?q=kdiskmark.tmp

2020-10-30 06:14 UTC, MingcongBai commented
Okay, I'm stupid... It's actually running, but it didn't tell me. Bad software, good pull.

2020-10-30 06:14 UTC, MingcongBai approved these changes

2020-10-30 06:15 UTC, merged