aiohttp: update to 3.7.2
AOSC-Dev/aosc-os-abbs pull request #2444
Opened 2020-10-29 09:57 UTC by OriginCode

Topic Description
-----------------

```
aiohttp => 3.7.2
yarl => 1.6.2
multidict => 5.0.0
```

Package(s) Affected
-------------------

aiohttp
yarl
multidict

Security Update?
----------------

No

Architectural Progress
----------------------

    

- [ ] Architecture-independent `noarch`

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] Architecture-independent `noarch`

2020-10-29 09:58 UTC, OriginCode commented
`yarl-1.6.2` FTBFS
![image](https://user-images.githubusercontent.com/17294071/97553377-52730280-1a10-11eb-8e75-9b87a0e96369.png)

2020-10-30 01:46 UTC, OriginCode commented
Test model:
```python
import aiohttp
import asyncio

async def main():
    async with aiohttp.ClientSession() as session:
        async with session.get('http://example.org') as response:
            print("Status:", response.status)
            print("Content-type:", response.headers['content-type'])
            html = await response.text()
            print("Body:", html[:15], "...")

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

My result:
![image](https://user-images.githubusercontent.com/17294071/97650476-b63f0f00-1a94-11eb-9889-693b7e414f6a.png)

2020-10-30 05:44 UTC, MingcongBai requested changes

2020-10-30 05:44 UTC, MingcongBai commented on extra-python/aiohttp/autobuild/defines
>  ABTYPE=python
Is this package `noarch` or not?

2020-10-30 05:44 UTC, MingcongBai commented on extra-python/yarl/autobuild/defines
>  ABTYPE=python
Again, is this package `noarch` or not?

2020-10-30 05:44 UTC, MingcongBai commented on extra-python/yarl/autobuild/prepare
> +sed 's| .install-cython ||g' -i Makefile
Please use absolute path here.

2020-10-30 05:44 UTC, MingcongBai commented on extra-python/aiohttp/autobuild/prepare
> +sed 's| .install-cython ||g' -i Makefile
Please use absolute path here.

2020-10-30 06:05 UTC, MingcongBai approved these changes

2020-10-30 06:55 UTC, MingcongBai commented
Test failure all architectures, using your sample code above. Log is something like the following on all of them...

```
root@arm64-11005b [ ~ ] # python3 test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import aiohttp
  File "/usr/lib/python3.8/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/lib/python3.8/site-packages/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/usr/lib/python3.8/site-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/lib/python3.8/site-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/lib/python3.8/site-packages/aiohttp/helpers.py", line 48, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'
```

2020-10-30 16:58 UTC, cthbleachbit commented
`typing_extensions`: See <https://pypi.org/project/typing-extensions/>

2020-10-30 17:00 UTC, cthbleachbit commented
It seems like aiohttp is polluting the modules namespace. `http.server` is really supposed to be a built-in module, but apparently something in aiohttp masked the one built-in and cause python to use the aiohttp one instead (incorrectly).

With aiohttp:
```
>>> import http.server
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/aiohttp/http.py", line 1, in <module>
    import http.server
ModuleNotFoundError: No module named 'http.server'; 'http' is not a package
```

Without aiohtto:
```
>>> import http.server
>>> print(http.server.__file__)
/usr/lib/python3.8/http/server.py
>>> 
```

2020-10-30 18:40 UTC, cthbleachbit commented
PR has been changed to reflect architecture requirements of cpython enabled packages.

2020-10-30 18:41 UTC, cthbleachbit commented
@MingcongBai Please test again.

2020-10-30 18:44 UTC, cthbleachbit commented
Confirmed working on amd64

```
cth451@cth-desktop-dorm [ ~ ] $ python3
Python 3.8.6 (default, Oct 21 2020, 14:11:15) 
[GCC 9.3.1 20200616 (AOSC OS, Core)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aiohttp
>>> import asyncio
>>> 
>>> async def main():
...     async with aiohttp.ClientSession() as session:
...         async with session.get('http://example.org') as response:
...             print("Status:", response.status)
...             print("Content-type:", response.headers['content-type'])
...             html = await response.text()
...             print("Body:", html[:15], "...")
... 
>>> loop = asyncio.get_event_loop()
>>> loop.run_until_complete(main())
Status: 200
Content-type: text/html; charset=UTF-8
Body: <!doctype html> ...
>>> 
```

2020-10-31 05:02 UTC, MingcongBai approved these changes

2020-11-02 07:12 UTC, OriginCode commented
LGTM on amd64
![image](https://user-images.githubusercontent.com/17294071/97839739-bdc51900-1d1d-11eb-9845-2fa589d0f7e3.png)

2020-11-03 01:46 UTC, OriginCode commented
On Loongson 3
![image](https://user-images.githubusercontent.com/17294071/97937245-0c73c100-1db9-11eb-985f-39b7ad8ec9d6.png)

On AArch64
![Capture d’écran de 2020-11-03 09-41-05](https://user-images.githubusercontent.com/17294071/97937137-c1f24480-1db8-11eb-9b8b-03985b575801.png)

On ppc64el
![Capture d’écran de 2020-11-03 09-45-57](https://user-images.githubusercontent.com/17294071/97937344-63799600-1db9-11eb-8ca3-c05997581a1e.png)

2020-11-03 02:01 UTC, merged