z3: new, 4.8.9
AOSC-Dev/aosc-os-abbs pull request #2471
Opened 2020-11-03 03:23 UTC by cthbleachbit

Topic Description
-----------------

This PR introduces a new package: Z3, an efficient constraint solver and theorem prover utility and its python bindings.

Package(s) Affected
-------------------

`z3` 4.8.9

Architectural Progress
----------------------

- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2020-11-03 03:23 UTC, cthbleachbit commented
Testing Procedures
--------------------------

For the main program:

```
cth451@cth-desktop-dorm [ ~ ] $ cat /tmp/test.smt 
(declare-fun x () Int)
(declare-fun y () Int)
(declare-fun z () Int)
(assert (>= (* 2 x) (+ y z)))
(declare-fun f (Int) Int)
(declare-fun g (Int Int) Int)
(assert (< (f x) (g x x)))
(assert (> (f y) (g x x)))
(check-sat)
(get-model)
(push)
(assert (= x y))
(check-sat)
(pop)
(exit)
cth451@cth-desktop-dorm [ ~ ] $ z3 /tmp/test.smt 
sat
(model 
  (define-fun y () Int
    3)
  (define-fun x () Int
    2)
  (define-fun z () Int
    1)
  (define-fun g ((x!0 Int) (x!1 Int)) Int
    0)
  (define-fun f ((x!0 Int)) Int
    (ite (= x!0 3) 1
      (- 1)))
)
unsat
```

For python bindings:
```
cth451@cth-desktop-dorm [ ~ ] $ python3
Python 3.8.6 (default, Oct 21 2020, 14:11:15) 
[GCC 9.3.1 20200616 (AOSC OS, Core)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from z3 import *
>>> x = Int('x')
>>> y = Int('y')
>>> z = Int('z')
>>> f = Function('f', IntSort(), IntSort())
>>> g = Function('g', IntSort(), IntSort(), IntSort())
>>> s.add(2 * x >= y + z)
>>> s.add(f(x) < g(x,x))
>>> s.add(f(y) > g(x,x))
>>> s.check()
sat
>>> s.model()
[y = 3,
 x = 2,
 z = 1,
 g = [else -> 0],
 f = [3 -> 1, else -> -1]]
>>>
```

2020-11-03 03:25 UTC, MingcongBai requested changes

2020-11-03 03:25 UTC, MingcongBai commented on extra-scientific/z3/autobuild/beyond
> +cp -vr ${PKGDIR}/usr/lib/python3.* ${PKGDIR}/usr/lib/python2.7
Dot `abinfo` throughout custom scripts - this is required by the [Styling Manual's Scripting section](https://wiki.aosc.io/developer/packaging/package-styling-manual/#scripting).

2020-11-03 03:25 UTC, MingcongBai commented on extra-scientific/z3/autobuild/beyond
> +python2 -m compileall "$PKGDIR"/usr/lib/python2.*/site-packages/z3
Use `$ABPY2VER` and `$ABPY3VER` here.

2020-11-03 03:25 UTC, MingcongBai commented on extra-scientific/z3/autobuild/defines
> +ABTYPE=cmake
Does `cmakeninja` not work?

2020-11-03 03:25 UTC, MingcongBai commented on extra-scientific/z3/spec
> +SRCS="tarball::https://github.com/Z3Prover/z3/archive/z3-${VER}.tar.gz"
`tbl`, not `tarball`.

2020-11-03 03:42 UTC, MingcongBai approved these changes

2020-11-05 06:40 UTC, MingcongBai requested changes

2020-11-05 06:40 UTC, MingcongBai commented on extra-scientific/z3/autobuild/beyond
> +cp -vr ${PKGDIR}/usr/lib/python${ABPY3VER} ${PKGDIR}/usr/lib/python${ABPY2VER}
Another issue, `$PKGDIR` should be quoted.

2020-11-05 06:41 UTC, MingcongBai commented
Another issue is that some CMake options are invalid, specially the part about enabling Python bindings.

```
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_PYTHON_BINDINGS
    LIB_INSTALL_DIR
    SYSCONF_INSTALL_DIR
```

2020-11-07 03:02 UTC, Cyanoxygen commented
### Testing in `arm64`
- native z3

![image](https://user-images.githubusercontent.com/29174191/98430476-89b87200-20e8-11eb-9758-fa392039173a.png)

- python3 binding
![image](https://user-images.githubusercontent.com/29174191/98430504-bf5d5b00-20e8-11eb-9829-63c753c08371.png)

2020-11-08 07:12 UTC, MingcongBai commented
The newest scripts doesn't seem to produce a working build.

```
-- Z3_COMPONENT_EXTRA_INCLUDE_DIRS: /var/cache/acbs/build/acbs.tychw057/z3-z3-4.8.9/build-py2/src;/var/cache/acbs/build/acbs.tychw057/z3-z3-4.8.9/src
-- Z3_DEPENDENT_EXTRA_CXX_LINK_FLAGS: 
-- CMAKE_INSTALL_LIBDIR: "lib              -DZ3_LINK_TIME_OPTIMIZATION=ON              -DZ3_BUILD_PYTHON_BINDINGS=ON              -DPYTHON_EXECUTABLE=/usr/bin/python2"
-- CMAKE_INSTALL_BINDIR: "bin"
-- CMAKE_INSTALL_INCLUDEDIR: "include"
-- CMAKE_INSTALL_PKGCONFIGDIR: "lib              -DZ3_LINK_TIME_OPTIMIZATION=ON              -DZ3_BUILD_PYTHON_BINDINGS=ON              -DPYTHON_EXECUTABLE=/usr/bin/python2/pkgconfig"
-- CMAKE_INSTALL_Z3_CMAKE_PACKAGE_DIR: "lib              -DZ3_LINK_TIME_OPTIMIZATION=ON              -DZ3_BUILD_PYTHON_BINDINGS=ON              -DPYTHON_EXECUTABLE=/usr/bin/python2/cmake/z3"
```

And finally...

```
cp: cannot stat '/var/cache/acbs/build/acbs.tychw057/z3-z3-4.8.9/build-py2/inst/usr/lib/python2.7': No such file or directory
```

2020-11-10 21:16 UTC, MingcongBai approved these changes

2020-11-10 21:16 UTC, merged