qliveplayer new
AOSC-Dev/aosc-os-abbs pull request #2488
Opened 2020-11-07 04:45 UTC by fearyncess

Topic Description
-----------------
Introduce the package "qliveplayer", and the needed dependencies.

Package(s) Affected
-------------------
`qliveplayer`, `ykdl`, `m3u8`, `pyiso8601`

Security Update?
No

Build Order
-----------
`pyiso8601` -> `m3u8` -> `ykdl` -> `qliveplayer`

Architectural Progress
----------------------
- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------
- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------
- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------
Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2020-11-07 12:17 UTC, fearyncess commented
![图片](https://user-images.githubusercontent.com/53393166/98440856-3836d400-2136-11eb-847c-1aff77a3d178.png)
it can works well in AMD64

2020-11-08 06:15 UTC, MingcongBai requested changes

2020-11-08 06:15 UTC, MingcongBai commented on extra-js/quickjs/autobuild/prepare
> +cd ${SRCDIR}
Quote your path.

2020-11-08 06:15 UTC, MingcongBai commented on extra-js/quickjs/autobuild/prepare
> +sed -i "s#prefix=/usr/local#prefix=/usr#g" Makefile
Use absolute path for your sed operations.

2020-11-08 06:15 UTC, MingcongBai commented on extra-js/quickjs/spec
> +SRCS="https://bellard.org/quickjs/quickjs-${VER: -8:4}-${VER: -4:2}-${VER: -2}.tar.xz"
Why a space behind `:`?

2020-11-08 06:15 UTC, MingcongBai commented on extra-multimedia/streamlink/autobuild/prepare
> +export STREAMLINK_USE_PYCOUNTRY=y
Add an `abinfo` to denote what is done here.

2020-11-08 06:18 UTC, MingcongBai requested changes

2020-11-08 06:18 UTC, MingcongBai commented on extra-js/quickjs/spec
> +SRCS="https://bellard.org/quickjs/quickjs-${VER: -8:4}-${VER: -4:2}-${VER: -2}.tar.xz"
You should be using `2020.09.06` as version number here, since you're trying to get `2020-09-06`. You can achieve this by using `${VER//./-}`.

2020-11-08 06:49 UTC, MingcongBai requested changes

2020-11-08 06:49 UTC, MingcongBai commented on extra-js/quickjs/autobuild/defines
> +PKGDES="A small and embeddable Javascript engine"
JavaScript *

2020-11-08 06:49 UTC, MingcongBai commented on extra-multimedia/streamlink/autobuild/prepare
> +abinfo "Make streamlink to use pycountry for the localization"
Drop the "to."

2020-11-08 06:49 UTC, MingcongBai commented on extra-python/pyiso8601/spec
> +
Trailing line here.

2020-11-08 06:57 UTC, MingcongBai approved these changes

2020-11-08 07:09 UTC, MingcongBai commented
Working on POWER.

![Uploading 图片.png…]()

2020-11-08 07:12 UTC, MingcongBai commented
Working on POWER. This is such crapware, it saddens me to merge this.

![Screenshot_20201107_231137](https://user-images.githubusercontent.com/5006263/98459317-a7202700-214e-11eb-9762-ab9aff50188e.png)

2020-11-08 07:12 UTC, merged