osu-lazer: update to 2020.1031.0
AOSC-Dev/aosc-os-abbs pull request #2493
Opened 2020-11-07 11:22 UTC by OriginCode

Topic Description
-----------------

Update `osu-lazer` to 2020.1031.0

Package(s) Affected
-------------------

`osu-lazer`

Security Update?
----------------

No

Architectural Progress
----------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2020-11-08 00:58 UTC, eatradish requested changes
Please use `SRCS` and `CHKSUMS`

2020-11-08 11:18 UTC, eatradish approved these changes

2020-11-09 03:56 UTC, MingcongBai approved these changes

2020-11-09 03:56 UTC, MingcongBai commented on extra-games/osu-lazer/spec
>  SRCTBL="https://github.com/ppy/osu/archive/$VER.tar.gz"
Please use [new ACBS spec format](https://wiki.aosc.io/developer/packaging/acbs/spec-format/)

2020-11-09 05:08 UTC, OriginCode commented
Works fine on amd64:
![image](https://user-images.githubusercontent.com/17294071/98502271-8e1d9000-228c-11eb-9db9-c1368bd5a720.png)

2020-11-09 20:21 UTC, cthbleachbit approved these changes
LGTM.

2020-11-09 23:42 UTC, merged