deno: update to 1.5.2
AOSC-Dev/aosc-os-abbs pull request #2505
Opened 2020-11-09 06:41 UTC by eatradish

Topic Description
-----------------

deno: update to 1.5.2

Package(s) Affected
-------------------

deno 1.5.2

Security Update?
----------------

No

Architectural Progress
----------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

2020-11-09 06:46 UTC, MingcongBai requested changes

2020-11-09 06:46 UTC, MingcongBai commented on extra-js/deno/autobuild/prepare
> +export GN_ARGS="no_inline_line_tables=false use_lld=false is_clang=false \
`abinfo` please.

2020-11-09 07:01 UTC, eatradish commented
![photo_2020-11-09_14-57-27](https://user-images.githubusercontent.com/19554922/98509623-7c43e900-229c-11eb-998f-1c1f8104b267.jpg)

emmm

2020-11-10 10:07 UTC, MingcongBai commented
@liushuyu What do you say about this?

2020-11-26 00:27 UTC, liushuyu commented
Please update to `deno` 1.5.3 and remove the patches.

2020-11-28 03:38 UTC, MingcongBai commented
@eatradish Please update. Closing.

2020-11-28 03:38 UTC, closed without merging