ffmpeg: enable libaom
AOSC-Dev/aosc-os-abbs pull request #2538
Opened 2020-11-19 10:35 UTC by eatradish

Topic Description
-----------------

Ffmpeg: enable libaom

Package(s) Affected
-------------------

aom 2.0.0
Ffmpeg 4.2.4-4

Security Update?
----------------

No

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2020-11-19 10:44 UTC, eatradish commented
Before: 

```
saki@Magputer [ ~ ] ! mpv 鏗鏘集：情騙.mp4
 (+) Video --vid=1 (*) (av1 1280x720 25.001fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
Failed to initialize a decoder for codec 'av1'.
Video: no video
```

After:

![image](https://user-images.githubusercontent.com/19554922/99655868-2b4fa400-2a97-11eb-9b46-35e4f9ed56ac.png)

LGTM on AMD64

2020-11-21 18:37 UTC, MingcongBai commented
What is up with the +32 builds?

2020-11-21 18:38 UTC, MingcongBai requested changes

2020-11-21 18:38 UTC, MingcongBai commented on extra-libs/aom/autobuild/build
> +mkdir -p "$SRCDIR"../aom_build
You lost a `/`.

2020-11-21 18:38 UTC, MingcongBai commented on extra-libs/aom/autobuild/build
> +abinfo "Create build directory..."
I don't see why you wouldn't be able to use `ABTYPE=cmakeninja`.

2020-11-21 18:39 UTC, MingcongBai commented
Honestly you can leave the +32 package as it is, unless some other applications (Steam, for instance) needs it.

If you choose to do so, remove the `optenv32` entry, address the two issues noted above, and you will be good to merge.

2020-11-21 19:48 UTC, eatradish commented
> Honestly you can leave the +32 package as it is, unless some other applications (Steam, for instance) needs it.
> 
> If you choose to do so, remove the `optenv32` entry, address the two issues noted above, and you will be good to merge.

Ok. dropped.

2020-11-23 06:20 UTC, MingcongBai approved these changes

2020-11-23 06:42 UTC, merged