thunderbird: update to 78.5.0
AOSC-Dev/aosc-os-abbs pull request #2539
Opened 2020-11-19 16:56 UTC by eatradish

Topic Description
-----------------

thunderbird: update to 78.5.0

Package(s) Affected
-------------------

thunderbird 78.5.0

Security Update?
----------------

No

Architectural Progress
----------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2020-11-19 17:22 UTC, eatradish commented
![image](https://user-images.githubusercontent.com/19554922/99701008-dfb8ec80-2ace-11eb-85d6-46688b60a2ee.png)

LGTM on AMD64

2020-11-19 17:33 UTC, eatradish commented
FTBFS on Loongson3:

![image](https://user-images.githubusercontent.com/19554922/99702104-5efaf000-2ad0-11eb-80ab-4226b58f20e4.png)

Log: https://fars.ee/1bAn

2020-11-19 18:44 UTC, MingcongBai commented
@eatradish Please try rebuilding with ld.bfd (remove gold linker specification for loongson3).

2020-11-20 05:20 UTC, eatradish commented
Switch to bfd linker, In Loongson3:

![image](https://user-images.githubusercontent.com/19554922/99762317-322bf480-2b33-11eb-97d1-c93d32f6660f.png)

2020-11-20 05:21 UTC, MingcongBai commented
@eatradish You might have to disable JIT - reference extra-libs/js-78 for appropriate options to do so.

2020-11-21 18:40 UTC, MingcongBai commented
Dropping `loongson3` from build list, since #2530 is not yet merged.

2020-11-21 18:41 UTC, MingcongBai commented
@eatradish In the future, please make sure that you read the changelogs/release notes carefully. Thunderbird 78.5.0 *is* a security update, addressing multiple CVEs.

cc @l2dy

2020-11-21 18:42 UTC, MingcongBai requested changes

2020-11-21 18:42 UTC, MingcongBai commented on extra-web/thunderbird/autobuild/mozconfig
> +ac_add_options --enable-linker=bfd
This should not be applied across the board. This is probably only needed with `arm64`?

2020-11-25 03:51 UTC, OriginCode commented
LGTM super amd64:
![image](https://user-images.githubusercontent.com/17294071/100181146-99232200-2f14-11eb-9315-8fe29098b4e7.png)

2020-11-25 06:07 UTC, MingcongBai approved these changes

2020-11-25 06:07 UTC, MingcongBai commented on extra-web/thunderbird/autobuild/mozconfig
> +ac_add_options --enable-linker=bfd
Ping on this change.

2020-11-25 07:16 UTC, merged