wine: update to 5.22
AOSC-Dev/aosc-os-abbs pull request #2546
Opened 2020-11-21 14:45 UTC by eatradish

Topic Description
-----------------

wine: update to 5.22

- Use SRCS to fetch wine-staging patches

Package(s) Affected
-------------------

wine 5.22

Security Update?
----------------

No

Architectural Progress
----------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2020-11-21 18:45 UTC, MingcongBai approved these changes

2020-11-21 18:46 UTC, MingcongBai requested changes

2020-11-21 18:46 UTC, MingcongBai commented on extra-emulation/wine/autobuild/prepare
> +./patchinstall.sh DESTDIR="$SRCDIR" --all
Please use absolute path (`"$SRCDIR"/patchinstall.sh`) here.

2020-11-21 19:39 UTC, eatradish commented on extra-emulation/wine/autobuild/prepare
> +./patchinstall.sh DESTDIR="$SRCDIR" --all
Done

2020-11-22 07:14 UTC, MingcongBai requested changes

2020-11-22 07:14 UTC, MingcongBai commented on extra-emulation/wine/autobuild/prepare
> +ln -s "$SRCDIR" wine
Verbose and non-absolute path detected...

2020-11-22 07:34 UTC, MingcongBai approved these changes

2020-11-22 07:36 UTC, eatradish commented
![Uploading image.png…]()

LGTM

2020-11-22 07:38 UTC, merged