fcitx5-material-color: update to 20201022
AOSC-Dev/aosc-os-abbs pull request #2549
Opened 2020-11-22 09:42 UTC by eatradish

Topic Description
-----------------

fcitx5-material-color: update to 20201022

Package(s) Affected
-------------------

fcitx5-material-color 20201022

Security Update?
----------------

No

Architectural Progress
----------------------

- [ ] Architecture-independent `noarch` 

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] Architecture-independent `noarch`

2020-11-23 06:21 UTC, MingcongBai requested changes

2020-11-23 06:21 UTC, MingcongBai commented on extra-i18n/fcitx5-material-color/autobuild/build
> +for _variant in blue brown deepPurple indigo pink red teal black; do
It might be better to use a script to generate a list of colours.

2020-11-23 06:21 UTC, MingcongBai commented on extra-i18n/fcitx5-material-color/autobuild/build
>      install -Dm644 panel-$_variant.png "$PKGDIR"/usr/share/fcitx5/themes/$_variant_name/panel.png
Missing verbosity (and possibly in other places in this script).

2020-11-25 07:42 UTC, eatradish commented
Upstrean commit new version, closing...

2020-11-25 07:42 UTC, closed without merging