mpv: update to 0.33.0
AOSC-Dev/aosc-os-abbs pull request #2552
Opened 2020-11-23 07:23 UTC by eatradish

- Drop libsmbclient, because upstream dropped. (why?)
- Disable build date

Topic Description
-----------------

mpv: update to 0.33.0

- Drop libsmbclient, because upstream dropped. (why?)
- Disable build date

Package(s) Affected
-------------------

No

Security Update?
----------------

No

Architectural Progress
----------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2020-11-23 07:59 UTC, MingcongBai commented
@eatradish No need to mark "DO NOT MERGE" in title. Convert this pull request to a "draft" and note your reasoning below.

2020-11-25 06:28 UTC, MingcongBai requested changes

2020-11-25 06:28 UTC, MingcongBai commented on extra-multimedia/mpv/autobuild/build
> +mkdir -p "$PKGDIR"/etc/bash_completion.d
Verbosity here.

2020-11-25 06:28 UTC, MingcongBai commented on extra-multimedia/mpv/autobuild/build
> +cp -av mpv "$PKGDIR"/etc/bash_completion.d/
Absolute path here please.

2020-11-25 06:37 UTC, MingcongBai requested changes

2020-11-25 06:37 UTC, MingcongBai commented on extra-multimedia/mpv/autobuild/build
>  ./waf build
More absolute path here.

2020-11-25 06:44 UTC, MingcongBai approved these changes

2020-11-25 11:21 UTC, OriginCode commented
Not LGTM, ERR: 
mpv: symbol lookup error: mpv: undefined symbol: archive_read_support_format_rar5

![image](https://user-images.githubusercontent.com/17294071/100221190-4e74ca80-2f53-11eb-9605-34b76c2dda91.png)

2020-11-25 19:00 UTC, eatradish commented
> Not LGTM, ERR:
> `mpv: symbol lookup error: mpv: undefined symbol: archive_read_support_format_rar5`
> 
> ![image](https://user-images.githubusercontent.com/17294071/100221190-4e74ca80-2f53-11eb-9605-34b76c2dda91.png)

@OriginCode Try again now?

2020-11-25 19:02 UTC, eatradish commented
![image](https://user-images.githubusercontent.com/19554922/100271000-bf3bd700-2f93-11eb-966b-a1f45facc76f.png)

LGTM on AMD64

2020-11-25 20:40 UTC, MingcongBai commented
LGTM on POWER.

![图片](https://user-images.githubusercontent.com/5006263/100279474-75afa580-2f1b-11eb-9ca2-f30492f40797.png)

2020-11-25 23:36 UTC, OriginCode commented
Works but with err (amd64):
![image](https://user-images.githubusercontent.com/17294071/100291900-fde48800-2fb9-11eb-936d-42b6c239cca3.png)

2020-11-26 08:22 UTC, MingcongBai commented
> Works but with err (amd64):
> ![image](https://user-images.githubusercontent.com/17294071/100291900-fde48800-2fb9-11eb-936d-42b6c239cca3.png)

This is probably an NVIDIA issue.

2020-11-26 08:24 UTC, merged