Update dotnet-core 3.1 to 3.1.10
AOSC-Dev/aosc-os-abbs pull request #2576
Opened 2020-12-05 10:15 UTC by liushuyu

Topic Description
-----------------

Update `dotnet` 3.1 series to 3.1.10

Package(s) Affected
-------------------

- extra-libs/dotnet-host
- extra-libs/dotnet-host-fxr
- extra-libs/dotnet-runtime-3.1
- extra-devel/aspnetcore-runtime-3.1
- extra-devel/dotnet-sdk-3.1.4xx
- extra-devel/dotnet-sdk-3.1.1xx
- extra-devel/dotnet-sdk-3.1

Security Update?
----------------

Yes, `#PENDING`

Build Order
-----------

```
extra-libs/dotnet-host
extra-libs/dotnet-host-fxr
extra-libs/dotnet-runtime-3.1
extra-devel/aspnetcore-runtime-3.1
extra-devel/dotnet-sdk-3.1.4xx
extra-devel/dotnet-sdk-3.1.1xx
extra-devel/dotnet-sdk-3.1
```

Architectural Progress
----------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------

N/A

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

N/A

2020-12-05 10:17 UTC, MingcongBai requested changes

2020-12-05 10:17 UTC, MingcongBai commented on extra-libs/dotnet-host/autobuild/build
> +ln -sv /usr/lib/dotnet/dotnet "$PKGDIR"/usr/bin/dotnet
It's probably more reasonable to use a relative symlink target here, i.e. `../lib/dotnet/dotnet`.

2020-12-05 10:17 UTC, MingcongBai commented on extra-libs/dotnet-host/autobuild/build
>  # cp dotnet.1.gz "$PKGDIR"/usr/share/man/man1
Drop this line if not needed.

2020-12-10 22:27 UTC, MingcongBai commented
@liushuyu Any updates?

2021-01-21 23:33 UTC, liushuyu commented
Superseded by #2717

2021-01-21 23:33 UTC, closed without merging