cinnamon : update to 4.8.0
AOSC-Dev/aosc-os-abbs pull request #2586
Opened 2020-12-06 14:50 UTC by Cyanoxygen

Topic Description
-----------------

Update the Cinnamon desktop environment to 4.8.0. ~~And, Core 8 is out.~~

Package(s) Affected
-------------------

`xapps` - 2.0.0
`groups/cinnamon` - 4.8.0

Security Update?
----------------

No

Build Order
-----------
 
1. `xapps`
2. `groups/cinnamon`

Architectural Progress
----------------------

- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2020-12-06 14:55 UTC, Cyanoxygen commented
## Testing
After a few hours of [debugging](https://github.com/linuxmint/cinnamon/issues/9738), the new desktop finally runs and smoothly.

Here's a screenshot showing Cinnamon 4.8.0 and nemo running in my laptop:

![image](https://user-images.githubusercontent.com/29174191/101283528-e9a05680-3815-11eb-8336-29a92fd14ca1.png)

## Conclusion

Waiting for the results from other platforms.

2020-12-07 05:45 UTC, MingcongBai requested changes

2020-12-07 05:45 UTC, MingcongBai commented on extra-cinnamon/cinnamon/autobuild/patches/0002-default-theme.patch
> +
What's with all the trailing blank lines?

2020-12-07 05:45 UTC, MingcongBai commented on extra-cinnamon/cinnamon-menus/spec
> +
Trailing blank line here.

2020-12-07 05:45 UTC, MingcongBai commented on extra-x11/xapps/spec
> +
Trailing blank line here.

2020-12-07 05:45 UTC, MingcongBai commented on extra-cinnamon/nemo/spec
>  SUBDIR="nemo-$VER"
I think you can drop all the `SUBDIR=` here. This is a relic from a broken ACBS revision.

2020-12-07 12:59 UTC, Cyanoxygen commented
Converting to draft as there are some possible bugs on upstream side.

2020-12-07 19:45 UTC, MingcongBai commented
@Cyanoxygen Upstream report: https://github.com/linuxmint/nemo/issues/2579

2020-12-10 02:52 UTC, Cyanoxygen commented
Reopen as a critical bug was fixed in nemo 4.8.2.
Rebuild and retest required.

2020-12-10 06:52 UTC, Cyanoxygen commented
## Testingh

### Platform
- AOSC OS: 8.0
- Arch: `arm64`
- Platform: Raspberry Pi 4
- Xorg: xrdp

Here's a screenshot shwoing Nemo and Cinnamon running on my Raspberry Pi 4.
![image](https://user-images.githubusercontent.com/29174191/101731692-f7e0c200-3af6-11eb-9a30-ea6dcdbaaffe.png)

2020-12-10 07:15 UTC, MingcongBai approved these changes

2020-12-10 10:59 UTC, Cyanoxygen commented
## Testing
### Platform
- AOSC OS: 8.0
- Arch: amd64
- Xorg: X11

Here's a screenshot showing Cinnamon 4..8.2 running on my Laptop:
![image](https://user-images.githubusercontent.com/29174191/101762923-02ac4e80-3b19-11eb-9a2b-2a7f8fe7a307.png)

## Merging eligibility 
Yes

2020-12-11 02:49 UTC, Cyanoxygen commented
Sucessfully built on all necessary platforms.

## Merging eligibility
Yes

2020-12-11 02:49 UTC, merged

2020-12-11 21:37 UTC, MingcongBai commented
Package uploads pending. @Cyanoxygen