[WIP] Perl dependency rework
AOSC-Dev/aosc-os-abbs pull request #2638
Opened 2020-12-27 09:31 UTC by cthbleachbit

Topic Description
-----------------

This PR attempts to rework dependency mess in perl packages... Notably missing dependencies of `perl-text-wrapi18n`, and `perl-pod-parser` for `po4a`. However po4a is currently missing unknown symbol `PerlIO::F_UTF8`.

Package(s) Affected
-------------------

##### Group 0:

* ELF: `perl-unicode-linebreak` 2019.001
* ELF: `perl-mime-charset` 1.012.2

##### Group 1:

* noarch: `perl-text-wrapi18n` 0.06

##### Group 2:

* ELF: `perl-pod-parser` 1.63

##### Failing group 3:

* noarch: `po4a` 0.62

Build Order by groups
-----------

{(0 -> 1), 2} -> Group 3

Architectural Progress
----------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
- [ ] Architecture-independent `noarch`

Secondary Architectural Progress
--------------------------------

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
- [ ] Architecture-independent `noarch`

Post-Merge Secondary Architectural Progress
-------------------------------------------

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2020-12-27 09:34 UTC, cthbleachbit commented
At this point `po4a` cannot parse `pod` formats at all. This blocks building any packages that generate documentation with `po4a`.

2021-01-16 04:29 UTC, MingcongBai requested changes

2021-01-16 04:29 UTC, MingcongBai commented on extra-i18n/po4a/autobuild/build
>  perl Build.PL create_packlist=0
Use absolute path here.

2021-01-16 04:29 UTC, MingcongBai commented on extra-i18n/po4a/autobuild/build
The build script ends with `perl Build`? Also, a trailing white line here.

2021-01-16 05:26 UTC, MingcongBai approved these changes

2021-01-16 05:29 UTC, merged