xss-lock: new, 0.3.0+git20140302
AOSC-Dev/aosc-os-abbs pull request #2655
Opened 2020-12-31 14:20 UTC by OriginCode

Topic Description
-----------------

Add package xss-lock.
Add PKGDEP xss-lock to i3 and i3-gaps

Package(s) Affected
-------------------

`xss-lock`
`i3`
`i3-gaps`

Security Update?
----------------

No

Architectural Progress
----------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-01-01 03:50 UTC, szclsya commented
i3-gaps looks good on `AMD64`.

2021-01-01 03:51 UTC, szclsya approved these changes

2021-01-01 04:55 UTC, OriginCode commented
LGTM on amd64:
![image](https://user-images.githubusercontent.com/17294071/103433677-9660ce80-4c30-11eb-94bf-aa6120aadb9e.png)

2021-01-03 03:49 UTC, MingcongBai requested changes

2021-01-03 03:49 UTC, MingcongBai commented on extra-utils/xss-lock/autobuild/defines
> +PKGDES="A tool helps use external locker as X screen saver"
Please rephrase this (awkward sentence, misspelled XScreenSaver). I'd suggest:

"A tool for using external lockers as XScreenSaver replacements"

2021-01-03 04:02 UTC, MingcongBai approved these changes

2021-01-03 04:03 UTC, merged