wmctrl: new, 1.07
AOSC-Dev/aosc-os-abbs pull request #2677
Opened 2021-01-07 07:15 UTC by OriginCode

Topic Description
-----------------

Add `wmctrl` package

Package(s) Affected
-------------------

wmctrl

Architectural Progress
----------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-01-07 07:30 UTC, OriginCode commented
LGTM on amd64:
![image](https://user-images.githubusercontent.com/17294071/103864217-2e612b00-50fd-11eb-9823-dc13ec0e6b45.png)

2021-01-07 20:24 UTC, MingcongBai requested changes

2021-01-07 20:24 UTC, MingcongBai commented on extra-wm/wmctrl/autobuild/defines
> +PKGDES="A command line tool to interact with an EWMH/NetWM compatible X Window Manager"
"A command line tool to interact with EWMH/NetWM-compatible X window managers"

2021-01-08 00:47 UTC, MingcongBai approved these changes

2021-01-08 11:40 UTC, merged