ss-tproxy: new, 4.6.1
AOSC-Dev/aosc-os-abbs pull request #2716
Opened 2021-01-21 11:17 UTC by fearyncess

Topic Description
-----------------
Introduce `ss-tproxy`. 

Package(s) Affected
-------------------
- `ss-tproxy`
- `chinadns-ng`
- `ipt2socks`

Security Update?
----------------
No 

Build Order
-----------
- `{ipt2socks, chinadns-ng} -> `ss-tproxy`

Architectural Progress
----------------------
- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------
Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------
- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-01-24 11:01 UTC, fearyncess commented
![图片](https://user-images.githubusercontent.com/53393166/105628193-75c61600-5e76-11eb-8491-9fd0b3eef594.png)
`ss-tproxy` and `chinadns-ng` LGTM

2021-01-30 05:23 UTC, MingcongBai requested changes

2021-01-30 05:23 UTC, MingcongBai commented on extra-network/ss-tproxy/autobuild/build
> +install -Dm755  "${SRCDIR}"/ss-tproxy          "${PKGDIR}"/usr/bin/ss-tproxy
Verbosity is missing throughout.

2021-01-30 05:51 UTC, MingcongBai approved these changes

2021-01-30 05:51 UTC, merged