thin-provisioning-tools: new, 0.9.0
AOSC-Dev/aosc-os-abbs pull request #2824
Opened 2021-02-28 11:37 UTC by RedL0tus

Topic Description
-----------------

Introduce thin-provisioning-tools, which is required for thin-provisioning-related functionalities of LVM2.

Package(s) Affected
-------------------

thin-provisioning-tools: new, 0.9.0

Security Update?
----------------

No

Architectural Progress
----------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-02-28 11:41 UTC, RedL0tus commented
@cthbleachbit Kould you pwease review and test dis senpai? UwU

2021-03-02 03:29 UTC, MingcongBai requested changes

2021-03-02 03:29 UTC, MingcongBai commented on extra-admin/thin-provisioning-tools/autobuild/build
> +autoconf
Use more `abinfo` throughout`, and add verbosity.

2021-03-02 03:29 UTC, MingcongBai commented on extra-admin/thin-provisioning-tools/autobuild/build
> +./configure ${AUTOTOOLS_DEF} ${AUTOTOOLS_AFTER}
Use absolute path here.

2021-03-02 03:29 UTC, MingcongBai commented on extra-admin/thin-provisioning-tools/autobuild/build
> +
So... Why did you not use an `ABTYPE`?

2021-03-13 09:09 UTC, MingcongBai approved these changes

2021-03-13 09:52 UTC, merged