Mozilla Survey on 20210226
AOSC-Dev/aosc-os-abbs pull request #2828
Opened 2021-03-02 06:04 UTC by MingcongBai

Topic Description
-----------------

Survey all Mozilla libraries, runtime, and Web applications. Drop unused MozJS runtime.

Package(s) Affected
-------------------

New Packages

- `cbindgen` v0.17.0
- `erlang-22` v22.3.4.11

Updated Packages

- `0ad` v0.2.24b
- `couchdb` v3.1.1
- `firefox` v86.0
- `js-78` v78.8.0
- `nss` v3.62
- `rebar` v3.14.4
- `thunderbird` v78.8.0

Rebuilt Packages

- `cjs` v4.8.1-1
- `erlang` v23.1-1
- `js` v1.8.5-7
- `js-68` v68.12.0-4

Dropped Packages

- `coin`, lack of maintenance, also unneeded.
- `js-24`, `js-38`, `js-52`, `js-60`, no longer needed.

Security Update?
----------------

Yes.

- Firefox 86.0, [MSFA2021-07](https://www.mozilla.org/en-US/security/advisories/mfsa2021-07/).
- Thunderbird 78.8.0, [MSFA2021-09](https://www.mozilla.org/en-US/security/advisories/mfsa2021-09/).
- MozJS 78.8.0 [MSFA2021-08](https://www.mozilla.org/en-US/security/advisories/mfsa2021-09/).

Build Order
-----------

```
js erlang erlang-22 rebar js-68 couchdb js-78 cjs 0ad nss cbindgen firefox thunderbird
```

Architectural Progress
----------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-03-02 06:09 UTC, liushuyu approved these changes

2021-03-02 23:49 UTC, OriginCode requested changes

2021-03-02 23:49 UTC, OriginCode commented on extra-games/0ad/autobuild/build
> +install -Dm755 "$SRCDIR"/binaries/system/*.so \
Need verbosity.

2021-03-03 08:04 UTC, OriginCode approved these changes

2021-03-07 10:24 UTC, szclsya commented
firefox 86.0 LGTM on AMD64.

2021-03-07 10:33 UTC, OriginCode commented
firefox and thunderbird LGTM on AMD64.

2021-03-07 23:02 UTC, MingcongBai commented
Firefox and Thunderbird FTBFS on Loongson 3. Skipping now in interest to ship security update. cc @FlyGoat

2021-03-07 23:02 UTC, merged

2021-03-07 23:03 UTC, MingcongBai commented
Firefox 86 also comes with stability improvement for POWER, tabs no longer crash when attempting to play videos.

2021-03-07 23:03 UTC, MingcongBai commented
@l2dy Please assign an AOSA.

2021-03-21 13:28 UTC, l2dy commented
Use AOSA-2021-0007.