systemd-boot-friend: update to 0.2.2
AOSC-Dev/aosc-os-abbs pull request #2847
Opened 2021-03-06 14:07 UTC by szclsya

Topic Description
-----------------
Make systemd-boot-friend great!

After this upgrade, systemd-boot-friend will be triggered by dracut's trigger script, which ensures the correct run order.

Also, systemd-boot-friend should install the kernels from oldest to latest now.

Package(s) Affected
-------------------
+ systemd-boot-friend
+ dracut

Security Update?
----------------
No

Architectural Progress
----------------------
- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------
- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------
- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------
- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-03-06 20:58 UTC, MingcongBai requested changes

2021-03-06 20:58 UTC, MingcongBai commented on extra-kernel/dracut/autobuild/overrides/usr/bin/update-initramfs
> +    if [[ -x /usr/bin/grub-mkconfig && $(stat -c %i /) == 2 ]]; then
Could you help me by dropping the `stat` condition check here?

2021-03-07 06:08 UTC, MingcongBai approved these changes

2021-03-07 10:32 UTC, OriginCode approved these changes

2021-03-20 05:31 UTC, merged