kodi: update to 19.0
AOSC-Dev/aosc-os-abbs pull request #2850
Opened 2021-03-07 09:20 UTC by eatradish

Topic Description
-----------------

kodi: update to 19.0

Package(s) Affected
-------------------

kodi: 19.0
waylandpp: 0.2.8

Security Update?
----------------

Architectural Progress
----------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-03-07 16:20 UTC, eatradish commented
LGTM on AMD64

![Screenshot_20210308_001927](https://user-images.githubusercontent.com/19554922/110246798-09c1ec00-7fa4-11eb-9a94-5c626b128590.png)

2021-03-07 18:41 UTC, RedL0tus commented
@eatradish 好活当赏

2021-03-08 15:24 UTC, eatradish commented
![Screenshot_20210308_232331](https://user-images.githubusercontent.com/19554922/110341556-69cc9700-8065-11eb-9319-e77b949cc8d9.png)

iptvsimple LGTM

2021-03-09 16:01 UTC, eatradish commented
LGTM on ARM64

2021-03-10 10:04 UTC, MingcongBai requested changes

2021-03-10 10:04 UTC, MingcongBai commented on extra-libs/libudfread/autobuild/defines
> +PKGSEC="libs"
No dependency whatsoever?

2021-03-10 10:04 UTC, MingcongBai commented on extra-libs/waylandpp/autobuild/defines
> +BUILDDEP="cmake"
This is unnecessary.

2021-03-10 10:04 UTC, MingcongBai commented on extra-libs/waylandpp/spec
> +
Extra line here.

2021-03-13 21:26 UTC, MingcongBai approved these changes

2021-03-16 00:31 UTC, merged