msr-tools: new, 20170320
AOSC-Dev/aosc-os-abbs pull request #2875
Opened 2021-03-18 11:18 UTC by RedL0tus

Topic Description
-----------------

Introduce msr-tools by Intel for accessing model-specific registers(MSRs).

Intel changed its build system to autotools without making a new release, so the latest git commit is used here.

Package(s) Affected
-------------------

msr-tools: new, 20170320

Security Update?
----------------

No

Architectural Progress
----------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-03-18 18:50 UTC, MingcongBai requested changes

2021-03-18 18:50 UTC, MingcongBai commented on extra-utils/msr-tools/autobuild/prepare
> +rm -v ${SRCDIR}/autogen.sh
Why...? Also quote your variable.

2021-03-19 01:59 UTC, MingcongBai approved these changes

2021-03-19 02:01 UTC, RedL0tus commented on extra-utils/msr-tools/autobuild/prepare
> +rm -v ${SRCDIR}/autogen.sh
[`autogen.sh`](https://github.com/intel/msr-tools/blob/master/autogen.sh) provided by the upstream called the generated `configure` script on its own, this causes autobuild/ACBS to be confused.

2021-03-19 02:08 UTC, merged