shadowsocks-rust: update to 1.10.1
AOSC-Dev/aosc-os-abbs pull request #2909
Opened 2021-03-27 09:38 UTC by eatradish

Topic Description
-----------------

shadowsocks-rust: update to 1.10.1

- Enable local-http-native-tls in loongson3 and ppc64el to fix build
- Use rust nightly to build on loongson3 and ppc64el to fix build

Package(s) Affected
-------------------

shadowsocks-rust: 1.10.1

Security Update?
----------------

No

Architectural Progress
----------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-03-27 09:42 UTC, MingcongBai requested changes

2021-03-27 09:42 UTC, MingcongBai commented on extra-network/shadowsocks-rust/autobuild/loongson3/prepare
> +export PATH=$HOME/.cargo/bin:$PATH
Quote your variable.

2021-03-27 09:42 UTC, MingcongBai commented on extra-network/shadowsocks-rust/autobuild/loongson3/prepare
> +source $HOME/.cargo/env
Ditto.

2021-03-27 09:42 UTC, MingcongBai commented on extra-network/shadowsocks-rust/autobuild/defines
> +NOLTO__PPC64EL=1
Why?

2021-03-27 09:42 UTC, MingcongBai commented on extra-network/shadowsocks-rust/autobuild/ppc64el/prepare
> +export PATH=$HOME/.cargo/bin:$PATH
Okay. You could have not used architectural sub-directories here (especially not by making a copy for each architecture - come on...!), I'd suggest that you use a big `if` branch instead.

2021-03-27 10:11 UTC, MingcongBai requested changes

2021-03-27 10:11 UTC, MingcongBai commented on extra-network/shadowsocks-rust/autobuild/defines
> +# Since ring does not support ppc64el and loongson3 architecture, use local-http-native-tls to avoid this dependency
Architectures *

2021-03-27 10:11 UTC, MingcongBai commented on extra-network/shadowsocks-rust/autobuild/prepare
> +source $HOME/.cargo/env
Quote your variable.

2021-03-28 00:49 UTC, eatradish commented
All LGTM

2021-03-28 00:49 UTC, MingcongBai approved these changes

2021-03-28 00:50 UTC, merged