rime-cantonese: update to 20210325
AOSC-Dev/aosc-os-abbs pull request #2913
Opened 2021-03-28 03:54 UTC by eatradish

Topic Description
-----------------

rime-cantonese: update to 20210325

Package(s) Affected
-------------------

rime-cantonese: 20210325

Security Update?
----------------

No

Architectural Progress
----------------------

 - [ ] Architecture-independent `noarch` 

Post-Merge Architectural Progress
---------------------------------

- [ ] Architecture-independent `noarch`

2021-03-28 09:52 UTC, MingcongBai approved these changes

2021-03-28 09:52 UTC, MingcongBai requested changes

2021-03-28 09:52 UTC, MingcongBai commented on extra-i18n/rime-cantonese/spec
> +VER=20210325
Use 0+git20210325 here.

2021-03-29 08:31 UTC, liushuyu approved these changes

2021-03-29 22:36 UTC, MingcongBai approved these changes

2021-03-30 03:12 UTC, merged