yubikey-manager-qt: update to 1.2.1
AOSC-Dev/aosc-os-abbs pull request #2974
Opened 2021-04-12 03:56 UTC by fearyncess

Topic Description
-----------------
Update `yubikey-manager-qt` to 1.2.1

Package(s) Affected
-------------------
* `fido2`
* `libfido2`
* `libcbor`
* `yubikey-manager`
* `yubikey-manager-qt`

Security Update?
----------------
No

Build Order
-----------
* `libcbor` -> `libfido2` -> `fido2` ->  `yubikey-manager` -> `yubikey-manager-qt`

Architectural Progress
----------------------
- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------
Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------
- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------
Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-04-12 03:57 UTC, fearyncess commented
![image](https://user-images.githubusercontent.com/53393166/114338694-2c888700-9b86-11eb-9677-177b1dc634a8.png)
LGTM on my machine with my *Yubikey FIDO 2*.
Maybe need a test with other yubikey hardware tokens.

2021-04-12 04:19 UTC, MingcongBai requested changes

2021-04-12 04:19 UTC, MingcongBai commented on extra-libs/libcbor/spec
> +
Trailing blank line here.

2021-04-12 04:19 UTC, MingcongBai commented on extra-libs/libfido2/autobuild/defines
> +CMAKE_AFTER="-Wno-dev"
Why is this necessary?

2021-04-12 04:19 UTC, MingcongBai commented on extra-libs/libfido2/autobuild/defines
> +PKGDES="A library which providing functionality for FIDO 2.0 over USB communications."
No period point in PKGDES, please.

2021-04-12 04:19 UTC, MingcongBai commented on extra-libs/libfido2/autobuild/defines
> +PKGDES="A library which providing functionality for FIDO 2.0 over USB communications."
I'd suggest changing this to "A library  which provides FIDO 2.0 functionality over USB"

2021-04-12 04:19 UTC, MingcongBai commented on extra-libs/libcbor/autobuild/defines
> +PKGDES="A CBOR protocol implementation for C"
"A C implementation for the CBOR protocol"

2021-04-20 19:20 UTC, MingcongBai requested changes

2021-04-20 19:20 UTC, MingcongBai commented on extra-libs/libfido2/autobuild/defines
> +PKGDES="A library which provides FIDO2 functionality over USB."
Remove period point here.

2021-04-20 19:20 UTC, MingcongBai commented on extra-libs/libcbor/autobuild/defines
> +PKGDES="A C implementation for CBOR protocol"
of the CBOR protocol *

2021-04-20 19:25 UTC, MingcongBai approved these changes

2021-04-24 09:40 UTC, cthbleachbit commented
There is no `.desktop` file for `ykman-qt5`? I was expecting one for a graphical application.

2021-04-28 14:53 UTC, fearyncess commented
> There is no `.desktop` file for `ykman-qt5`? I was expecting one for a graphical application.
It has been added in `053624d`.

2021-04-28 14:53 UTC, merged