samba: update to 4.14.2
AOSC-Dev/aosc-os-abbs pull request #2992
Opened 2021-04-15 08:36 UTC by eatradish

Topic Description
-----------------

Update samba to 4.14.2

Package(s) Affected
-------------------

talloc: 2.3.2
liburing: 2.0
`perl-parse-yapp-driver:` 1.2.0
ldb: 2.3.0
samba: 4.14.2
ffmpeg: 4.2.4-6

Security Update?
----------------

No

Build Order
-----------

liburing ldb perl-parse-yapp-driver talloc samba ffmpeg

Architectural Progress
----------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-04-15 08:51 UTC, MingcongBai requested changes

2021-04-15 08:51 UTC, MingcongBai commented on extra-libs/liburing/autobuild/build
> +abinfo "Configuring..."
So... Why did you not use `ABTYPE=autotools`?

2021-04-15 08:51 UTC, MingcongBai commented on extra-libs/liburing/spec
> +
Trailing blank line here.

2021-04-15 08:51 UTC, MingcongBai commented on extra-libs/liburing/autobuild/defines
> +PKGDES="Linux-native io_uring I/O access library"
A Kernel async I/O access library for Linux

(Stop copying from Arch Linux...)

2021-04-15 08:51 UTC, MingcongBai commented on extra-perl/perl-parse-yapp-driver/autobuild/defines
> +PKGNAME="perl-parse-yapp-driver"
Source name is `perl-parse-yapp`.

2021-04-15 08:51 UTC, MingcongBai commented on extra-perl/perl-parse-yapp-driver/autobuild/defines
> +PKGDES="Perl/CPAN Module Parse::Yapp : Generates OO LALR parser modules"
Perl extension for generating and using LALR parsers

(Again, stop, copying, from, Arch Linux! Their package descriptions are inconsistent at best, and why not just reference the upstream?)

2021-04-15 09:08 UTC, MingcongBai requested changes

2021-04-15 09:08 UTC, MingcongBai commented on extra-libs/liburing/autobuild/build
> +./configure --prefix='/usr' \
Absolute path here.

2021-04-15 09:08 UTC, MingcongBai commented on extra-network/samba/autobuild/build
>  ./configure --enable-fhs \
Absolute path here.

2021-04-15 09:15 UTC, MingcongBai approved these changes

2021-04-15 10:24 UTC, eatradish commented
sssd FTBFS on ARM64: http://fars.ee/3hSm

2021-04-15 11:11 UTC, eatradish commented
![Screenshot_20210415_190721](https://user-images.githubusercontent.com/19554922/114860238-52c85400-9e1e-11eb-8f32-827eee774eb8.png)

LGTM on ARM64

2021-04-15 18:45 UTC, MingcongBai commented
> sssd FTBFS on ARM64: http://fars.ee/3hSm

```
/usr/bin/ld: cannot find -lsss_util
```

Please make sure `sssd` was specified as a run-time dependency, and that it was built successfully.

2021-04-16 00:34 UTC, MingcongBai requested changes

2021-04-16 00:34 UTC, MingcongBai commented on extra-database/ldb/autobuild/defines
> +PKGBREAK="sssd<=2.4.0"
This package should also break samba.

2021-04-20 19:42 UTC, MingcongBai approved these changes

2021-04-20 20:01 UTC, merged