bitwarden-cli: new, 1.15.1
AOSC-Dev/aosc-os-abbs pull request #3005
Opened 2021-04-20 19:19 UTC by eatradish

Topic Description
-----------------

bitwarden-cli: new, 1.15.1

- 0001-bitwarden-fix-webpack-bundling.patch (by @liushuyu)

Package(s) Affected
-------------------

Security Update?
----------------

No

Architectural Progress
----------------------

 - [ ] Architecture-independent `noarch` 
 - [ ] 
----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

 - [ ] Architecture-independent `noarch`

2021-04-20 19:21 UTC, MingcongBai requested changes

2021-04-20 19:21 UTC, MingcongBai commented on extra-js/bitwarden-cli/spec
> +      tbl::https://github.com/bitwarden/jslib/archive/${JSLIBCOMMIT}.tar.gz"
You should use a Git source here instead, saving an extra variable that could be easily ignored.

2021-04-20 21:05 UTC, MingcongBai approved these changes

2021-04-21 01:48 UTC, liushuyu commented on extra-js/bitwarden-cli/spec
> +      git::rename=jslib;commit=f80e89465ffc004705d2941301c0ffb6bfd71d1a::https://github.com/bitwarden/jslib"
Or you can just and avoid specifying submodules separately...

```suggestion
SRCS="git::commit=tags/$VER::https://github.com/bitwarden/cli"
```

2021-04-21 04:37 UTC, merged