opencc: fix pkg-config libdir path
AOSC-Dev/aosc-os-abbs pull request #3123
Opened 2021-05-29 18:15 UTC by eatradish

Topic Description
-----------------

opencc: fix pkg-config libdir path

Package(s) Affected
-------------------

opencc: 1.1.1-2

Security Update?
----------------

No

Architectural Progress
----------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-05-29 18:16 UTC, eatradish commented
```
saki@Mag230 [ autobuild3@master ] $ grep -nr "LIB_INSTALL_DIR"
etc/autobuild/ab3_defcfg.sh:124:        -DLIB_INSTALL_DIR=lib
```

Is this normal?

2021-05-30 04:05 UTC, cthbleachbit requested changes

2021-05-30 04:05 UTC, cthbleachbit commented on extra-i18n/opencc/autobuild/defines
> +             -DLIB_INSTALL_DIR=/usr/lib \
I'd recommend that you add a comment indicating that this `LIB_INSTALL_DIR` is required so that the `.pc` file has correct `libdir`.

2021-05-30 04:06 UTC, cthbleachbit commented on extra-i18n/opencc/autobuild/defines
> +             -DLIB_INSTALL_DIR=/usr/lib \
Especially when `LIB_INSTALL_DIR` is relative to  `CMAKE_INSTALL_PREFIX` for most projects and in the CMake official guidelines.

2021-06-03 06:51 UTC, MingcongBai approved these changes

2021-06-03 06:55 UTC, cthbleachbit approved these changes

2021-06-03 08:14 UTC, merged