openjdk: feature update to 17
AOSC-Dev/aosc-os-abbs pull request #3173
Opened 2021-06-13 09:55 UTC by liushuyu

Topic Description
-----------------

openjdk: feature update to 17

Package(s) Affected
-------------------

```
openjdk
openjfx
```

Security Update?
----------------

No

Architectural Progress
----------------------

- [X] AMD64 `amd64`   
- [X] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-09-05 21:57 UTC, liushuyu commented
TODO: OpenJDK 11 is still required and will be reinstated on this branch.

2021-09-16 01:42 UTC, liushuyu commented
Ready for review.

The following items are still not done and they may as well be addressed in a later topic:

- Check for all incompatible reverse-dependencies (Currently, only some of them are checked and marked)
- Cherry-pick some patches from https://github.com/JetBrains/JetBrainsRuntime to JDK 11 to fix certain crashes

2021-09-16 07:42 UTC, MingcongBai requested changes

2021-09-16 07:42 UTC, MingcongBai commented on extra-java/openjdk-11/autobuild/beyond
> +printf 'update-alternatives --install /usr/bin/java java /usr/lib/java-11/bin/java 50' >> "$SRCDIR/autobuild/postinst"
abinfo missing throughout.

2021-09-16 07:42 UTC, MingcongBai commented on extra-java/openjdk-11/autobuild/build
> +UPDATE=${PKGVER:2:-3}
Code style non-compliant.

2021-09-16 07:42 UTC, MingcongBai commented on extra-java/openjdk-11/autobuild/conffiles
> +/etc/openjdk/ppc/jvm.cfg
This probably could be generated.

2021-09-16 07:42 UTC, MingcongBai commented on extra-java/openjdk-11/autobuild/patches/debian-hotspot-mips-align.diff
> +Index: b/src/hotspot/cpu/zero/cppInterpreter_zero.cpp
Patch file name non-compliant.

2021-09-16 07:46 UTC, liushuyu commented on extra-java/openjdk-11/autobuild/conffiles
> +/etc/openjdk/ppc/jvm.cfg
This only applies to ppc

2021-09-16 07:47 UTC, MingcongBai requested changes

2021-09-16 07:47 UTC, MingcongBai commented on extra-java/openjdk-11/autobuild/prepare
> +export EXTRA_CFLAGS="${CPPFLAGS} ${CFLAGS} -Wno-error"
abinfo missing throughout.

2021-09-16 07:47 UTC, MingcongBai commented on extra-java/openjdk/autobuild/build
>  install -d -m 755 "$SRCDIR"/image
Verbosity here.

2021-09-16 07:47 UTC, MingcongBai commented on extra-java/openjdk/autobuild/build
>  sh configure \
Absolute path here.

2021-09-16 07:47 UTC, MingcongBai commented on extra-java/openjdk/autobuild/build
> +make product-images docs
abinfo missing,

2021-09-16 07:47 UTC, MingcongBai commented on extra-java/openjdk/autobuild/build
>  mkdir -p "$PKGDIR"/usr/lib/java
Verbosity here, and below.

2021-09-16 07:47 UTC, MingcongBai commented on extra-java/openjdk/autobuild/patches/debian-hotspot-mips-align.diff
> -Index: b/src/hotspot/cpu/zero/cppInterpreter_zero.cpp
Patch file name non-compliant.

2021-09-16 07:47 UTC, MingcongBai commented on extra-java/openjdk/autobuild/prepare
> +export EXTRA_CFLAGS="${CPPFLAGS} ${CFLAGS/-fexceptions/}"
abinfo missing throughout.

2021-09-16 07:47 UTC, MingcongBai commented on extra-java/openjdk/spec
> +CHKSUMS="sha256::8971e4c3555fffae60bd58a5fb403e51a1e0dda14645c6214b81ceff954dd411"
Missing CHKUPDATE.

2021-09-16 07:47 UTC, MingcongBai commented on extra-java/openjdk/autobuild/build
> -    config_zero="--with-jvm-variants=zero --enable-precompiled-headers"
abinfo missing.

2021-09-16 07:47 UTC, MingcongBai commented on extra-java/openjdk/autobuild/build
> +    EXTRA_FEATURES+=",shenandoahgc"
abinfo missing.

2021-09-16 07:47 UTC, MingcongBai commented on extra-java/openjdk-11/autobuild/beyond
> +printf 'update-alternatives --install /usr/bin/java java /usr/lib/java-11/bin/java 50' >> "$SRCDIR/autobuild/postinst"
Also verbosity missing throughout.

2021-09-16 07:47 UTC, MingcongBai commented on extra-java/openjfx-11/autobuild/build
> +export CXXFLAGS="${CXXFLAGS} -Wno-expansion-to-defined -fPIC "
abinfo and verbosity missing throughout.

2021-09-16 07:47 UTC, MingcongBai commented on extra-java/openjfx-11/autobuild/gradle.properties
> +
Trailing blank line.

2021-09-16 07:47 UTC, MingcongBai commented on extra-java/openjfx-11/autobuild/patches/0002-remove-arch-restriction.patch
> +
Tailing blank lines?

2021-09-16 07:47 UTC, MingcongBai commented on extra-java/openjfx-11/autobuild/patches/0004-fix-deprecation-error.patch
> +
Trailing blank line?

2021-09-16 07:47 UTC, MingcongBai commented on extra-java/openjfx-11/autobuild/prepare
> +if [[ "${CROSS:-$ARCH}" = "amd64" ]]; then
Could just use !=.

2021-09-16 07:47 UTC, MingcongBai commented on extra-java/openjfx/spec
> +CHKSUMS="sha256::624bb375419a1c9deabd550cc82fababe9cf0bd1d5f366290cb56310dc99ef54"
CHKUPDATE missing.

2021-09-16 17:02 UTC, MingcongBai requested changes

2021-09-16 17:02 UTC, MingcongBai commented on extra-java/openjdk-11/autobuild/beyond
> +printf 'update-alternatives --install /usr/bin/java java /usr/lib/java-11/bin/java 50' >> "$SRCDIR/autobuild/postinst"
Issue not addressed.

2021-09-16 17:02 UTC, MingcongBai commented on extra-java/openjdk-11/autobuild/beyond
> +printf 'update-alternatives --install /usr/bin/java java /usr/lib/java-11/bin/java 50' >> "$SRCDIR/autobuild/postinst"
Issue not addressed.

2021-09-16 17:02 UTC, MingcongBai commented on extra-java/openjdk-11/autobuild/build
> +UPDATE=${PKGVER:2:-3}
abinfo still missing.

2021-09-16 17:02 UTC, MingcongBai commented on extra-java/openjdk-11/autobuild/prepare
> +export EXTRA_CFLAGS="${CPPFLAGS} ${CFLAGS} -Wno-error"
Issue not resolved.

2021-09-16 17:02 UTC, MingcongBai commented on extra-java/openjdk/autobuild/build
> -    config_zero="--with-jvm-variants=zero --enable-precompiled-headers"
Issue not resolved, please add abinfo also for branched routines.

2021-09-16 17:02 UTC, MingcongBai commented on extra-java/openjdk/autobuild/build
> +    EXTRA_FEATURES+=",shenandoahgc"
Ditto above.

2021-09-16 17:02 UTC, MingcongBai commented on extra-java/openjfx-11/autobuild/build
> +export CXXFLAGS="${CXXFLAGS} -Wno-expansion-to-defined -fPIC "
Issue not resolved.

2022-03-21 03:23 UTC, MingcongBai approved these changes

2022-03-21 03:29 UTC, merged