curl: update to 7.78.0
AOSC-Dev/aosc-os-abbs pull request #3293
Opened 2021-07-22 06:59 UTC by OriginCode

Topic Description
-----------------

Update curl to 7.78.0

Package(s) Affected
-------------------

curl

Security Update?
----------------

Yes - Issue Number: #3292 

Architectural Progress
----------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-07-22 07:04 UTC, MingcongBai approved these changes

2021-07-22 11:50 UTC, KexyBiscuit requested changes

2021-07-22 11:50 UTC, KexyBiscuit commented on extra-optenv32/curl+32/autobuild/defines
> +PKGDEP="ca-certs openssl krb5+32 libssh2+32 openssl+32 zlib+32"
```suggestion
PKGDEP="ca-certs krb5+32 libssh2+32 openssl+32 zlib+32"
```

2021-07-22 11:50 UTC, KexyBiscuit requested changes

2021-07-22 11:50 UTC, KexyBiscuit commented on extra-optenv32/curl+32/autobuild/defines
>  PKGDES="An URL retrieval utility and library (optenv32, libraries only)"
```suggestion
PKGDES="A URL retrieval utility and library (optenv32, libraries only)"
```

2021-07-22 11:54 UTC, KexyBiscuit approved these changes

2021-07-24 14:31 UTC, OriginCode commented
LGTM on amd64:
![image](https://user-images.githubusercontent.com/17294071/126871702-0a26221d-67ad-42ed-871f-1c6b97312018.png)

2021-07-30 01:28 UTC, merged