Move dbus system / session configurations from /etc/dbus-1 to /usr/share/dbus-1
AOSC-Dev/aosc-os-abbs pull request #3360
Opened 2021-08-18 23:12 UTC by cthbleachbit

Topic Description
-----------------

This PR moves package-provided dbus configurations misplaced under `/etc/dbus-1` to `/usr/share/dbus-1`. Following packages are updated due to changes in other packages (e.g. python3) or otherwise fail to build:

* networkmanager-l2tp
* xpra
* xbar

Package(s) Affected
-------------------

* `accountsservice`
* `avahi`
* `blueman`
* `bluez`
* `bluez-alsa`
* `cdemu-daemon`
* `cmst`
* `cups`
* `cups-pk-helper`
* `dm-shared-dbus-config`
* `flatpak`
* `gconf`
* `gdm`
* `geoclue2`
* `gnome-applets`
* `hplip`
* `iio-sensor-proxy`
* `libma`
* `lvm2`
* `modemmanager`
* `networkmanager-l2tp`
* `networkmanager-openconnnect`
* `ofono`
* `packagekit`
* `sddm`
* `sssd`
* `system-config-printer`
* `tdelibs`
* `tdenetworkmanager`
* `thermald`
* `udisks`
* `urfkill`
* `wpa-supplicant`
* `xpra`
* `zbar`

Build Order
-----------

This survey does not involves library dependency chains and do not need to be built in a specific order. You may build in lexicographical order.

Architectural Progress
----------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-08-18 23:13 UTC, cthbleachbit commented
Build and tests pending.

2021-08-18 23:14 UTC, MingcongBai requested changes

2021-08-18 23:14 UTC, MingcongBai commented on extra-admin/accountsservice/autobuild/beyond
> +mkdir -p "${PKGDIR}/usr/share/dbus-1/system.d/"
Verbosity here, and for the rest of mkdir's below.

2021-08-21 06:42 UTC, MingcongBai approved these changes

2021-08-23 05:16 UTC, merged

2021-08-23 05:19 UTC, cthbleachbit commented
Quick note to non-amd64 arch: `thermald` is amd64 only