arping: fix PKGSEC
AOSC-Dev/aosc-os-abbs pull request #3400
Opened 2021-08-30 08:49 UTC by xyq1113723547

Topic Description
-----------------
arping: fix PKGSEC

Package(s) Affected
-------------------

Security Update?
----------------

No

Architectural Progress
----------------------

- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-08-31 07:40 UTC, MingcongBai commented on extra-network/arping/autobuild/defines
> +PKGSEC=net
You should bump REL for this change.

2021-08-31 07:41 UTC, MingcongBai requested changes
Bump REL for PKGSEC change.

2021-09-03 21:09 UTC, liushuyu approved these changes

2021-09-06 05:19 UTC, MingcongBai approved these changes

2021-10-03 08:24 UTC, KexyBiscuit commented
/build arping

2021-10-06 04:15 UTC, merged