gitui: new, 0.17.1
AOSC-Dev/aosc-os-abbs pull request #3460
Opened 2021-09-16 03:25 UTC by WhiredPlanck

Topic Description
-----------------

Introduce `gitui`, a blazing fast terminal ui for git written in Rust (as they say).

Package(s) Affected
-------------------

`gitui`

Security Update?
----------------

No

Architectural Progress
----------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-09-16 03:37 UTC, WhiredPlanck commented
LGTM on amd64

![image](https://user-images.githubusercontent.com/47623588/133545342-a377ae5d-81aa-49da-96fc-49ad974b479f.png)

2021-09-16 07:30 UTC, MingcongBai requested changes

2021-09-16 07:30 UTC, MingcongBai commented on extra-utils/gitui/autobuild/defines
> +PKGDES="Terminal UI for git written in rust"
Git, also no need to mention "written in rust."

2021-09-16 16:56 UTC, MingcongBai approved these changes

2021-10-05 16:35 UTC, MingcongBai requested changes

2021-10-05 16:35 UTC, MingcongBai commented on extra-electronics/fritzing/autobuild/defines
> +QTPROJ_AFTER="DEFINES=QUAZIP_INSTALLED CONFIG+=force_debug_info"
Just a suggestion, break up long lines with `\`.

2021-10-05 16:35 UTC, MingcongBai commented on extra-libs/libgit2/autobuild/defines
> -PKGBREAK="exa<=0.8.0-1 fritzing<=0.9.3b-2 geany-plugins<=1.34 \
Why did you drop all the PKGBREAKs?

2021-10-05 16:35 UTC, MingcongBai commented on extra-productivity/calligra/autobuild/patches/0228-Update-Cmake-and-deps-Fix-Freetype-and-FontConfig-Linkage.patch
> +From 62f510702ef9c34ac50f8d8601a4290ab558464c Mon Sep 17 00:00:00 2001
Rename your patch to reflect on the sequence, 0228 makes no sense here.

2021-10-05 16:35 UTC, MingcongBai commented on extra-utils/gitui/autobuild/defines
> +PKGDES="Terminal UI for Git"
Don't abbreviate UI.

2021-10-06 00:03 UTC, WhiredPlanck commented on extra-libs/libgit2/autobuild/defines
> -PKGBREAK="exa<=0.8.0-1 fritzing<=0.9.3b-2 geany-plugins<=1.34 \
I wrote it above the CMAKE_AFTER.

2021-10-06 02:32 UTC, KexyBiscuit reviewed
LGTM overall except existing comments.

2021-10-06 09:25 UTC, MingcongBai approved these changes

2021-10-06 09:26 UTC, KexyBiscuit commented
/build gitui

2021-10-06 11:02 UTC, merged