deno: update to 1.14.2
AOSC-Dev/aosc-os-abbs pull request #3482
Opened 2021-09-30 08:15 UTC by eatradish

Topic Description
-----------------

deno: update to 1.14.2

Package(s) Affected
-------------------

deno: 1.14.2

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-09-30 08:16 UTC, eatradish commented
LGTM on AMD64:

![image](https://user-images.githubusercontent.com/19554922/135414426-5587deaf-17a3-405b-8a22-af99e6e23f94.png)

2021-09-30 10:20 UTC, eatradish commented
LGTM on ARM64:

![image](https://user-images.githubusercontent.com/19554922/135437817-35a94091-0b13-47c8-b111-90431d76f232.png)

2021-09-30 17:27 UTC, MingcongBai approved these changes

2021-09-30 17:27 UTC, MingcongBai requested changes
Wait, why is openimagedenoise included here?

2021-10-01 08:55 UTC, MingcongBai approved these changes

2021-10-01 08:58 UTC, merged