Support building all modified packages
AOSC-Dev/aosc-os-abbs pull request #3520
Opened 2021-10-03 12:46 UTC by KexyBiscuit

The workflow can now check for modified spec files and build the packages.

2021-10-03 13:07 UTC, outloudvi commented
I think the workflow might be too long for now. Would it be possible for us to make it a seperate action and possibly reduce the overall complexity in this yml file?

2021-10-03 13:07 UTC, KexyBiscuit commented
@outloudvi Will do this the next time, just a bit sleepy today.

2021-10-03 13:11 UTC, outloudvi commented
> @outloudvi Will do this the next time, just a bit sleepy today.

Cool! Looking forward to that.

"*Take care of yourself, and be well*" -Chubbyemu

2021-10-03 13:41 UTC, WhiredPlanck commented
Super cool!

2021-10-04 03:04 UTC, KexyBiscuit commented
Demo available at https://github.com/BiscuitTin/aosc-os-abbs/actions/runs/1300526278.

2021-10-04 03:37 UTC, outloudvi commented
Seems great! Some non-procedural points IMO:

* Seperate the artifacts of each package
    * Probably by appending the name of the package to `name` for `actions/upload-artifact@v2`?
* Add some styles to the output message
    * Currently [the messages](https://github.com/BiscuitTin/aosc-os-abbs/pull/1#issuecomment-932945926) seem to be a bit hard to read
    * Probably add some bolds or emojis?

2021-10-04 03:38 UTC, KexyBiscuit commented
Whoa, forgot to modify the upload step, thanks!

2021-10-04 04:24 UTC, KexyBiscuit commented
Problems solved; the message looks nice now!
https://github.com/BiscuitTin/aosc-os-abbs/pull/1#issuecomment-933129684

2021-10-04 05:06 UTC, MingcongBai requested changes

2021-10-04 05:06 UTC, MingcongBai commented on .github/workflows/README.md
> +  - GitHub-hosted runners currently provide no TTY device[^1], any build rely on this will fail.
any build that relies *

2021-10-04 05:07 UTC, KexyBiscuit commented on .github/workflows/README.md
> +  - GitHub-hosted runners currently provide no TTY device[^1], any build rely on this will fail.
```suggestion
  - GitHub-hosted runners currently provide no TTY device[^1], any build that relies on this will fail.
```

2021-10-04 05:08 UTC, MingcongBai approved these changes

2021-10-04 05:08 UTC, merged