kate: rebuild for new version libgit2
AOSC-Dev/aosc-os-abbs pull request #3535
Opened 2021-10-06 11:51 UTC by WhiredPlanck

Topic Description
-----------------

As `kate` and `kwrite` is actually depend on `libgit2` directly, now they need to rebuild.

Package(s) Affected
-------------------

`kate` and `kwrite`

Security Update?
----------------

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-10-06 18:02 UTC, KexyBiscuit requested changes
Please add `libgit2` to dependencies list.

2021-10-06 20:17 UTC, MingcongBai requested changes
You should also mark `kate` and `kwrite` in `libgit2`'s PKGBREAK.

2021-10-07 01:15 UTC, WhiredPlanck commented
@KexyBiscuit @MingcongBai Roger. Just need to take a moment.

2021-10-07 02:29 UTC, KexyBiscuit commented
/build kate

2021-10-07 22:36 UTC, MingcongBai requested changes

2021-10-07 22:36 UTC, MingcongBai commented on extra-libs/libgit2/autobuild/defines
> +          libgit2-glib<=0.28.0.1-1 pygit2<=1.0.3-1"
You'd need to bump REL for libgit2.

2021-10-08 00:07 UTC, WhiredPlanck commented on extra-libs/libgit2/autobuild/defines
> +          libgit2-glib<=0.28.0.1-1 pygit2<=1.0.3-1"
Ok ~

2021-10-10 00:03 UTC, WhiredPlanck commented
@MingcongBai I built `kwrite` after building `libgit2` v1.3.0, but `kwrtie` still links to `libgit2.so.28` instead of  `libgit2.so.1.3.0`. Totally have no idea ......

2021-10-10 01:31 UTC, MingcongBai commented
@WhiredPlanck Could you make sure you updated your Git tree such that libgit2 has a bumper REL? If the version of libgit2 built matches the one on the repository, Ciel will not update it before the next package build.

2021-10-10 03:20 UTC, WhiredPlanck commented
@JeffBai Sorry, I made a big mistake.  `kwrite` and `kate` just depend on `ktexteditor`, which is actually depend on `libgit2`. I put `ktexteditor` in front of `libgit2` to build accidentally. Anyway, this is not necessary any more... I'll close it with this comment.

2021-10-10 03:20 UTC, closed without merging