premake: new, 5.0~a16
AOSC-Dev/aosc-os-abbs pull request #3536
Opened 2021-10-06 20:01 UTC by xyq1113723547

Topic Description
-----------------
premake: new, 5.0 alpha 16

Package(s) Affected
-------------------

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-10-06 20:14 UTC, KexyBiscuit requested changes

2021-10-06 20:14 UTC, KexyBiscuit commented on extra-utils/premake/autobuild/build
> +make STRIP="ture" config=release
`ture`?

2021-10-06 20:14 UTC, KexyBiscuit commented on extra-utils/premake/autobuild/build
> +abinfo "Installing premake and LISENSE"
`LISENSE`?

2021-10-06 20:14 UTC, KexyBiscuit commented on extra-utils/premake/autobuild/build
> +install -Dm755 "bin/release/premake5" "${PKGDIR}/usr/bin/premake5"
Use verbose. `-v`

2021-10-06 20:14 UTC, KexyBiscuit commented on extra-utils/premake/autobuild/build
> +cd "build/gmake2.unix"
Absolute path everywhere, like `cd "$SRCDIR"`

2021-10-06 20:14 UTC, KexyBiscuit commented on extra-utils/premake/autobuild/defines
> +PKGDEP="glibc"
No need to list `glibc` here.

2021-10-06 20:16 UTC, MingcongBai requested changes

2021-10-06 20:16 UTC, MingcongBai commented on extra-utils/premake/autobuild/build
> +cd "build/gmake2.unix"
Also, use parenthetical expression.

```bash
(
    cd "$SRCDIR"/build/gmake2.unix
    ...
)

2021-10-06 20:16 UTC, MingcongBai commented on extra-utils/premake/autobuild/build
> +install -Dm644 LICENSE.txt "$PKGDIR/usr/share/licenses/$PKGNAME/LICENSE"
Verbosity here, also absolute path, as with everywhere else.

2021-10-06 20:16 UTC, MingcongBai commented on extra-utils/premake/autobuild/build
> +install -Dm755 "bin/release/premake5" "${PKGDIR}/usr/bin/premake5"
Absolute path.

2021-10-06 20:16 UTC, MingcongBai commented on extra-utils/premake/spec
> +VER=5.0~a16
Use 5.0.0~alpha16, and `${VER/\~/-}` in `SRCS`.

2021-10-06 20:18 UTC, MingcongBai requested changes

2021-10-06 20:18 UTC, MingcongBai commented on extra-utils/premake/autobuild/build
> +cd "$PKGDIR/build/gmake2.unix"
Make sure you understand what `$PKGDIR` and `$SRCDIR` are respetively.

2021-10-06 20:18 UTC, MingcongBai commented on extra-utils/premake/autobuild/build
> +cd ../..
Please just use parenthetical expression instead, cd-ing back is a waste of keyboard.

2021-10-06 20:23 UTC, MingcongBai requested changes

2021-10-06 20:23 UTC, MingcongBai commented on extra-utils/premake/autobuild/build
> +install -v -Dm755 "bin/release/premake5" "${PKGDIR}/usr/bin/premake5"
Use absolute path here.

2021-10-06 20:23 UTC, MingcongBai commented on extra-utils/premake/autobuild/build
> +install -v -Dm644 LICENSE.txt "$PKGDIR/usr/share/licenses/$PKGNAME/LICENSE"
Use absolute path here.

2021-10-06 20:25 UTC, KexyBiscuit submitted a review, later dismissed

2021-10-06 20:25 UTC, KexyBiscuit commented on extra-utils/premake/autobuild/build
> +install -v -Dm755 "bin/release/premake5" "${PKGDIR}/usr/bin/premake5"
Merge the options.
```suggestion
install -Dvm755 "bin/release/premake5" "${PKGDIR}/usr/bin/premake5"
```

2021-10-06 20:25 UTC, KexyBiscuit commented on extra-utils/premake/autobuild/build
> +install -v -Dm644 LICENSE.txt "$PKGDIR/usr/share/licenses/$PKGNAME/LICENSE"
```suggestion
install -Dvm644 LICENSE.txt "$PKGDIR/usr/share/licenses/$PKGNAME/LICENSE"
```

2021-10-06 20:25 UTC, KexyBiscuit commented on extra-utils/premake/autobuild/build
> +install -v -Dm755 "bin/release/premake5" "${PKGDIR}/usr/bin/premake5"
Use absolute path everywhere.
```suggestion
install -v -Dm755 "$SRCDIR/bin/release/premake5" "${PKGDIR}/usr/bin/premake5"
```

2021-10-06 20:25 UTC, KexyBiscuit commented on extra-utils/premake/autobuild/build
> +install -v -Dm644 LICENSE.txt "$PKGDIR/usr/share/licenses/$PKGNAME/LICENSE"
```suggestion
install -v -Dm644 "$SRCDIR"/LICENSE.txt "$PKGDIR/usr/share/licenses/$PKGNAME/LICENSE"
```

2021-10-06 20:41 UTC, KexyBiscuit commented
/build premake

2021-10-07 22:35 UTC, MingcongBai requested changes

2021-10-07 22:35 UTC, MingcongBai commented on extra-utils/premake/autobuild/build
> +  cd "${SRCDIR}"
This is not necessary, Autobuild3 runs the build scripts in "$SRCDIR".

2021-10-08 20:28 UTC, MingcongBai requested changes

2021-10-08 20:28 UTC, MingcongBai commented on extra-utils/premake/autobuild/build
> +(
Why is this even necessary here?

2021-10-09 08:28 UTC, xyq1113723547 commented on extra-utils/premake/autobuild/build
> +(
Isolating build and install set of commands is beneficial.
If there are errors in make stage, this info will not print out, which suggests errors are in pre-install stage.

2021-10-09 10:59 UTC, KexyBiscuit commented
/build premake

2021-11-03 16:04 UTC, WhiredPlanck requested changes, later dismissed

2021-11-03 16:04 UTC, WhiredPlanck commented on extra-utils/premake/autobuild/defines
> +ABSPLITDBG=0
Please split debug info as much as possible, or explain why it's impossible to be done with a comment. See [`ABSPLITDBG` section](https://wiki.aosc.io/developer/packaging/autobuild3-manual/#:~:text=1%20or%20%E2%80%9Con%E2%80%9D\).-,absplitdbg,-expects%20a%20binary) below [Autobuild3 Manual - Clang specific configurations](https://wiki.aosc.io/developer/packaging/autobuild3-manual/#clang-specific-configurations).

2021-11-06 05:15 UTC, WhiredPlanck commented
LGTM on AMD64

![图片](https://user-images.githubusercontent.com/47623588/140598872-7c3a2db0-08d4-4c8b-b1cb-d3a3ea845409.png)

2021-11-06 06:05 UTC, WhiredPlanck commented
> LGTM on AMD64
> 
> ![图片](https://user-images.githubusercontent.com/47623588/140598872-7c3a2db0-08d4-4c8b-b1cb-d3a3ea845409.png)

This test process and results are still valid, only the version number has changed.

2021-11-06 06:13 UTC, MingcongBai approved these changes

2021-11-06 06:17 UTC, merged