[ci] openssh: security update to 8.8p1
AOSC-Dev/aosc-os-abbs pull request #3547
Opened 2021-10-09 12:21 UTC by KexyBiscuit

Topic Description
-----------------

- Patch `ssh_config` to support drop-ins. This enables packaging of Buildbots.
- Lint scripts.

Package(s) Affected
-------------------

`openssh`

Security Update?
----------------

Yes

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

2021-10-10 14:18 UTC, MingcongBai requested changes

2021-10-10 14:18 UTC, MingcongBai commented on extra-network/openssh/autobuild/beyond
> +install -Dvm755 contrib/ssh-copy-id "$PKGDIR"/usr/bin/ssh-copy-id
Use absolute path.

2021-10-10 14:18 UTC, MingcongBai commented on extra-network/openssh/autobuild/beyond
> +abinfo "Patching ssh_config ..."
Be specific about what you did here.

2021-10-10 14:18 UTC, MingcongBai commented on extra-network/openssh/autobuild/beyond
> +abinfo "Patching sshd_config ..."
Ditto above.

2021-10-10 14:31 UTC, MingcongBai approved these changes

2021-10-17 11:55 UTC, KexyBiscuit commented
Smoke test passed.

2021-10-17 11:55 UTC, merged