landrop: new, 0.4.0
AOSC-Dev/aosc-os-abbs pull request #3558
Opened 2021-10-12 12:10 UTC by WhiredPlanck

Topic Description
-----------------

Introduce `landrop`, a tool allows you to drop files to the devices on your LAN.

Package(s) Affected
-------------------

`landrop`

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-10-12 12:10 UTC, WhiredPlanck commented
/build landrop

2021-10-12 12:16 UTC, KexyBiscuit commented on extra-network/landrop/spec
> +SRCS="tbl::https://github.com/LANDrop/LANDrop/archive/v{VER}.tar.gz"
```suggestion
SRCS="tbl::https://github.com/LANDrop/LANDrop/archive/v$VER.tar.gz"
```

2021-10-12 14:55 UTC, WhiredPlanck commented
LGTM on AMD64

![image](https://user-images.githubusercontent.com/47623588/136979941-f944d1ea-4ec0-4ef1-9679-1d03a383567c.png)

2021-10-12 15:09 UTC, WhiredPlanck commented
/build landrop

2021-10-12 15:47 UTC, WhiredPlanck commented
**Note**: If you would like to test this topic, you could install the mobile app from https://landrop.app to your device, and install the package(s) from this topic, then follow the app's instructions.

2021-10-12 15:49 UTC, MingcongBai requested changes

2021-10-12 15:49 UTC, MingcongBai commented on extra-network/landrop/autobuild/defines
> +QTPROJ_AFTER="CONFIG+=force_debug_info"
Let's add this to Autobuild3, and include the Autobuild3 update in this topic.

2021-10-15 15:59 UTC, WhiredPlanck commented on extra-network/landrop/autobuild/defines
> +QTPROJ_AFTER="CONFIG+=force_debug_info"
Great, I will handle it.

2021-10-16 03:04 UTC, WhiredPlanck commented on extra-network/landrop/autobuild/defines
> +QTPROJ_AFTER="CONFIG+=force_debug_info"
P.S. It seems that `qmake PREFIX=/path/to/custom/dir` didn't take effect in this case. I have no idea with it yet.

2021-10-16 08:20 UTC, MingcongBai approved these changes

2021-10-16 08:41 UTC, WhiredPlanck commented
Add some test result of 83f4c05 :

Parameter `CONFIG+=force_debug_info` is necessary especially when `.pro` file explicitly specifies the build type as `release` or `debug_and_release` to make sure that Autobuild3 can build up a debug package.

For example, building `fritzing`, which a package specifies the build type as `debug_and_release`, without the parameter above will fail. Add `CONFIG+=force_debug_info` to `etc/autobuild/ab3_defcfg` can help to handle it.

![image](https://user-images.githubusercontent.com/47623588/137580828-690ba43f-5240-4f81-b9a8-3685a728719d.png)

2021-10-16 08:53 UTC, merged