libcdio 2.1.0 Survey and kodi-pvr-iptvsimple update to 19.0.0
AOSC-Dev/aosc-os-abbs pull request #3574
Opened 2021-10-16 09:05 UTC by eatradish

Topic Description
-----------------

libcdio update to 2.1.0 and update/rebuild for libcdio

Package(s) Affected
-------------------
groups/libcdio-rebuilds
groups/xine-lib-rebuilds
kodi-pvr-iptvsimple: 19.0.0
whipper: 10.0.0-1

Security Update?
----------------

No

Build Order
-----------

libcdio groups/libcdio-rebuilds groups/xine-lib-rebuilds kodi-pvr-iptvsimple whipper

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-10-16 11:25 UTC, KexyBiscuit commented on extra-multimedia/kodi/autobuild/beyond
> +pushd ${SRCDIR}/abbuild
Use parentheses instead of `pushd`/`popd`/`cd`.

2021-10-16 11:26 UTC, KexyBiscuit requested changes
One change requested.

2021-10-16 11:41 UTC, KexyBiscuit commented on extra-multimedia/kodi/autobuild/beyond
> +cd "$SRCDIR"/abbuild
Use parentheses instead of `pushd`/`popd`/`cd`.

2021-10-16 11:41 UTC, KexyBiscuit requested changes
One change requested.

2021-12-16 03:57 UTC, cthbleachbit approved these changes

2021-12-16 04:00 UTC, KexyBiscuit approved these changes
LGTM.

2021-12-18 10:06 UTC, merged