[ci] squashfs-tools: update to 4.5
AOSC-Dev/aosc-os-abbs pull request #3585
Opened 2021-10-18 05:09 UTC by KexyBiscuit

Topic Description
-----------------

squashfs-tools: update to 4.5

- Lint build scripts and texts.

Package(s) Affected
-------------------

`squashfs-tools`

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

2021-10-18 05:19 UTC, MingcongBai requested changes

2021-10-18 05:19 UTC, MingcongBai commented on extra-admin/squashfs-tools/autobuild/build
> -    -t "$PKGDIR"/usr/bin/
What, why?

2021-10-18 05:19 UTC, MingcongBai commented on extra-admin/squashfs-tools/autobuild/defines
> +PKGDES="Tools for Squashfs, a compressed read-only filesystem for Linux"
SquashFS *

2021-10-18 05:25 UTC, KexyBiscuit commented on extra-admin/squashfs-tools/autobuild/defines
> +PKGDES="Tools for Squashfs, a compressed read-only filesystem for Linux"
```suggestion
PKGDES="Tools for SquashFS, a compressed read-only filesystem for Linux"
```

2021-10-18 09:34 UTC, KexyBiscuit commented
Ubuntu names the patches with CVE numbers, which looks better.
https://git.launchpad.net/ubuntu/+source/squashfs-tools/tree/debian/patches

2021-10-18 20:27 UTC, MingcongBai approved these changes

2021-10-19 08:07 UTC, KexyBiscuit commented
Smoke test passed on Loongson 3.

2021-10-19 08:07 UTC, merged