Nvidia Drivers 470.74, Cuda 11.4.2+470.57.02
AOSC-Dev/aosc-os-abbs pull request #3609
Opened 2021-10-21 06:47 UTC by cthbleachbit

Topic Description
-----------------

This PR updates nvidia drivers to 470.74, the latest stable release and cuda to 11.4.2+470.57.02. Cuda 11.5 was excluded from this survey as it requires 490.X unstable drivers. Rework of pycuda and bindings for 11.5 will be addressed in a separate topic when driver version 490.x enters stable channel.

Issues on arm64
-------------------

Nvidia has been providing drivers for SBSA arm64 for quite a while now. This PR also populates build scripts for arm64.

At the current stage nvidia kernel modules will not compile on mainline 5.14.x due to kernel symbol `MT_DEVICE_GRE` in arm64 memory management [removed in 5.14](https://patchwork.kernel.org/project/linux-arm-kernel/patch/20210506095034.15246-2-will@kernel.org/).

Due to the lack of dogfooding capacity with an nvidia card on an SBSA compliant arm64 device and dkms failures, `arm64` will still be considered `FAIL_ARCH` until nvidia fixes this in a later version, or anyone in AOSC finds a chance to do a smoke test with such hardware configuration.

Package(s) Affected
-------------------

* `egl-wayland`: 1.1.7
* `nvidia`, `nvidia+32`: 470.74
* `cuda`: 11.4.2+470.57.02

Build Order
-----------

`egl-wayland` -> `nvidia` -> `nvidia+32` -> `cuda`

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [x] AMD64 `amd64`

2021-10-21 06:54 UTC, cthbleachbit commented
/build nvidia

2021-10-21 07:07 UTC, cthbleachbit commented
![2021-10-21 02-06-40 的屏幕截图](https://user-images.githubusercontent.com/3353318/138228397-a492a1fb-d822-4581-b2f5-7b005d7c83fc.png)
![2021-10-21 02-01-36 的屏幕截图](https://user-images.githubusercontent.com/3353318/138228402-a08c1d59-aa3d-4cbe-a3e5-1b0eb8b81a38.png)

I guess it works.

2021-10-21 07:09 UTC, KexyBiscuit commented on extra-x11/nvidia/autobuild/arm64/build
> +cd "$SRCDIR"
Please use paratheses instead of `cd` in and out directories.

2021-10-21 07:11 UTC, KexyBiscuit commented on extra-x11/nvidia/autobuild/arm64/build
> +create_links() {
Why split this function out while it's only used once?

2021-10-21 07:11 UTC, KexyBiscuit requested changes
Changes requested in build script.

2021-10-21 16:16 UTC, MingcongBai commented on extra-x11/nvidia/autobuild/arm64/build
> +cd "$SRCDIR"
> Please use paratheses instead of `cd` in and out directories.

I'd treat this as a suggestion. Marking as resolved.

2021-10-21 16:16 UTC, MingcongBai commented on extra-x11/nvidia/autobuild/arm64/build
> +create_links() {
> Why split this function out while it's only used once?

Arch Linux PKGBUILD-ism. Not a problem (against our own Styling Manual), but a worthy note.

2021-10-21 16:16 UTC, MingcongBai submitted a review, later dismissed

2021-10-23 19:42 UTC, KexyBiscuit submitted a review, later dismissed
Great job!

2021-10-25 01:01 UTC, MingcongBai approved these changes

2021-10-25 04:31 UTC, merged