meowdict: update to 0.10.0; cargo-audit: update to 0.15.2
AOSC-Dev/aosc-os-abbs pull request #3610
Opened 2021-10-21 11:07 UTC by eatradish

Topic Description
-----------------

meowdict: update to 0.10.0
cargo-audit: update to 0.15.2

Package(s) Affected
-------------------

cargo-audit: 0.15.2
meowdict: 0.10.0

Security Update?
----------------

No

Build Order
-----------

cargo-audit meowdict

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-10-21 16:14 UTC, MingcongBai requested changes

2021-10-21 16:14 UTC, MingcongBai commented on extra-rust/cargo-audit/autobuild/defines
> +# It is not necessary to check the audit itself to construct a new version of cargo-audit
construct => build

2021-10-21 16:18 UTC, MingcongBai submitted a review, later dismissed

2021-10-21 17:08 UTC, eatradish commented
/build

2021-10-21 17:31 UTC, eatradish commented
/build cargo-audit meowdict

2021-10-22 06:02 UTC, liushuyu approved these changes

2021-10-22 06:02 UTC, merged