Introduce Tectonic 0.8.0 and Basic Tex Editor Update
AOSC-Dev/aosc-os-abbs pull request #3615
Opened 2021-10-23 11:22 UTC by WhiredPlanck

Topic Description
-----------------

Introduce `tectonic`, a complete and self-contained Tex/LaTeX engine; and update some Tex editor packages by the way.

Package(s) Affected
-------------------

- `tectonic`
- `texworks`
- `texstudio`
- `texmaker`
- `qtsingleapplication`

Security Update?
----------------

No

Build Order
-----------

`qtsingleapplication` then `texstudio`

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-10-23 13:42 UTC, WhiredPlanck commented
LGTM on AMD64 (tectonic, works with TeXWorks)
(build command: `tectonic -X compile $filename`)

![图片](https://user-images.githubusercontent.com/47623588/138558888-0a385797-dd6a-44a1-8a3d-d6dad04e81c2.png)

2021-10-23 17:16 UTC, WhiredPlanck commented
LGTM on AMD64 (`texworks`)

![图片](https://user-images.githubusercontent.com/47623588/138565686-904e0e6e-9461-44e7-a9db-425fad266711.png)

2021-10-24 02:46 UTC, WhiredPlanck commented
LGTM on AMD64 (`texstudio`, using `tectonic` to compile)

![图片](https://user-images.githubusercontent.com/47623588/138578183-5ee5702c-7b5e-4ae2-a4e5-9d27e4157583.png)

2021-10-24 04:23 UTC, WhiredPlanck commented
LGTM on AMD64 (`texmaker`, using tectonic to compile, without `texlive`)

![图片](https://user-images.githubusercontent.com/47623588/138580663-3ba7b3a8-da66-48de-85fc-0593ae8fcd6c.png)

2021-10-25 03:01 UTC, WhiredPlanck commented
@MingcongBai This Pull Request is ready for review.

2021-10-25 09:03 UTC, MingcongBai requested changes

2021-10-25 09:03 UTC, MingcongBai commented on extra-libs/qtsingleapplication/autobuild/build
>  /usr/bin/qmake-qt5
Please lint this script to comply with our Styling Manual.

2021-10-25 09:03 UTC, MingcongBai commented on extra-tex/tectonic/autobuild/defines
> +PKGDES="A TeX/LaTeX engine"
Not a very helpful description, what else can you tell me about Tectonic?

2021-10-25 09:03 UTC, MingcongBai commented on extra-tex/tectonic/autobuild/defines
> +BUILDDEP="rustc llvm pkg-config"
Leave `pkg-config` out, this is not needed with BuildKit.

2021-10-25 13:43 UTC, WhiredPlanck commented on extra-tex/tectonic/autobuild/defines
> +BUILDDEP="rustc llvm pkg-config"
Get it, I'll fix this soon.

2021-10-25 13:50 UTC, WhiredPlanck commented on extra-tex/tectonic/autobuild/defines
> +PKGDES="A TeX/LaTeX engine"
The upstream says it's `A modernized, complete, self-contained TeX/LaTeX engine`, I think `modernized`, `complete` and `self-contained` are may not very objective, so I removed them. I may need some suggestions from other people because of my poor English. :smiling_face_with_tear:

2021-10-25 13:50 UTC, WhiredPlanck commented on extra-libs/qtsingleapplication/autobuild/build
>  /usr/bin/qmake-qt5
Get it, I'll fix it soon.

2021-10-30 00:24 UTC, WhiredPlanck commented
`texstudio` can not be built on longsoon3 yet.

2021-11-01 09:46 UTC, WhiredPlanck commented
/build

2021-11-01 10:49 UTC, WhiredPlanck commented
> ❌ Building `texstudio` ends with status **failure**

texstudio needs qtsingleapplication to be built first, so don't mind this.

2021-11-05 04:23 UTC, MingcongBai approved these changes

2021-11-05 12:45 UTC, merged