tailscale: new, 1.16.2
AOSC-Dev/aosc-os-abbs pull request #3620
Opened 2021-10-25 05:00 UTC by RedL0tus

Topic Description
-----------------

Introduction of Tailscale, a mesh VPN service based on the WireGuard protocol.

Package(s) Affected
-------------------

tailscale: new, 1.16.2

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-10-25 09:00 UTC, MingcongBai requested changes

2021-10-25 09:00 UTC, MingcongBai commented on extra-network/tailscale/autobuild/build
> +cd "${SRCDIR}"
This ain't no PKGBUILD, cowboy.

2021-10-25 09:00 UTC, MingcongBai commented on extra-network/tailscale/autobuild/build
> +install -Dvm755 tailscale tailscaled -t "${PKGDIR}/usr/bin"
Absolute path here.

2021-10-28 00:46 UTC, MingcongBai approved these changes

2021-10-28 00:46 UTC, MingcongBai requested changes
Waiting for tests results.

2021-10-28 02:24 UTC, RedL0tus commented
> Waiting for tests results.

![AArch64](https://user-images.githubusercontent.com/16459559/139175170-8107b193-5c77-4b3b-9f31-8b1504cab4b0.png)

![AMD64](https://user-images.githubusercontent.com/16459559/139175188-7bb22f72-ae1f-4638-a7bf-e76600b38803.png)

It werks senpai ! 🚀🚀🚀 @MingcongBai

2021-10-28 02:24 UTC, MingcongBai submitted a review, later dismissed

2021-10-28 02:24 UTC, MingcongBai commented
Fine, kid. Now get outta here.

2021-11-05 00:38 UTC, WhiredPlanck approved these changes

2021-11-05 03:48 UTC, RedL0tus commented
![1.16.2](https://user-images.githubusercontent.com/16459559/140455045-5e6ae9c2-3bcb-409e-8c81-7d97313e7487.png)

1.16.2 also werks senpai tachi!  🚀🚀🚀

2021-11-05 04:47 UTC, merged