nvidia: manually create symlink for libglxserver_nvidia.so
AOSC-Dev/aosc-os-abbs pull request #3632
Opened 2021-10-29 07:12 UTC by cthbleachbit

Topic Description
-----------------

This PR fixed an issue introduced in nvidia 470.74 where `/usr/lib/nvidia/xorg/libglxserver_nvidia.so.470.74` is not correctly symlinked. X server will error out during start up due to `libglxserver_nvidia.so` not found.

Package(s) Affected
-------------------

* nvidia: 470.74-1

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`

2021-10-29 07:15 UTC, MingcongBai requested changes

2021-10-29 07:15 UTC, MingcongBai commented on extra-x11/nvidia/autobuild/build
> +        [[ -e "${_soname}" ]] || ln -sf $(basename "${_lib}") "${_soname}"
Add verbosity here.

2021-10-31 04:25 UTC, cthbleachbit commented
Tested to work now.

2021-10-31 04:25 UTC, MingcongBai approved these changes

2021-10-31 06:34 UTC, merged