systemd-boot-friend: update to 0.10.3
AOSC-Dev/aosc-os-abbs pull request #3634
Opened 2021-10-29 15:23 UTC by OriginCode

Topic Description
-----------------

Update systemd-boot-friend.

Package(s) Affected
-------------------

systemd-boot-friend

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

2021-10-30 17:12 UTC, WhiredPlanck requested changes

2021-10-30 17:12 UTC, WhiredPlanck commented on extra-admin/systemd-boot-friend/autobuild/beyond
> +PREFIX="$PKGDIR/usr/" ./install-assets.sh
May `"$SRCDIR"/install-assets.sh` here?

2021-10-31 07:15 UTC, MingcongBai commented on extra-admin/systemd-boot-friend/autobuild/beyond
> +PREFIX="$PKGDIR/usr/" ./install-assets.sh
@WhiredPlanck is right.

2021-10-31 07:36 UTC, OriginCode commented on extra-admin/systemd-boot-friend/autobuild/beyond
> +PREFIX="$PKGDIR/usr/" ./install-assets.sh
@MingcongBai BTW copied from ciel XD

2021-11-03 05:52 UTC, OriginCode commented
New version released! XD

2021-11-03 05:52 UTC, closed without merging