virtualbox: security update to 6.1.28; #3664
AOSC-Dev/aosc-os-abbs pull request #3665
Opened 2021-11-19 14:04 UTC by WhiredPlanck

Topic Description
-----------------

Security update `virtualbox` to 6.1.28

Package(s) Affected
-------------------

`virtualbox`

Security Update?
----------------

Yes - Issue Number: #3664 

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
    

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`

2021-11-24 08:31 UTC, WhiredPlanck commented
LGTM on AMD64

![图片](https://user-images.githubusercontent.com/47623588/143202032-bfa6a18b-113f-4c5a-b6a3-16111c508fae.png)

2021-11-24 08:38 UTC, MingcongBai requested changes

2021-11-24 08:38 UTC, MingcongBai commented on extra-emulation/virtualbox/01-host/build
> -./configure \
Missing abinfo.

2021-11-24 08:38 UTC, MingcongBai commented on extra-emulation/virtualbox/01-host/build
> +source "$SRCDIR"/env.sh
Missing abinfo.

2021-11-24 08:38 UTC, MingcongBai commented on extra-emulation/virtualbox/01-host/build
> +abinfo "Forward port DKMS"
What?

2021-11-24 08:38 UTC, MingcongBai commented on extra-emulation/virtualbox/01-host/build
> +chmod -v +x "$PKGDIR"/usr/src/vboxhost-$PKGVER/do_dkms
Missing abinfo.

2021-11-24 08:38 UTC, MingcongBai commented on extra-emulation/virtualbox/02-guest/build
> -source ./env.sh
Missing abinfo throughout.

2021-11-24 08:50 UTC, WhiredPlanck commented
And ... (remind myself):
- Don’t use abbreviations for topic names.
- One should modify `postinst`, `prerm` etc. via `sed` command in prepare to use the value of a variable (like `$PKGVER`).

2021-11-25 11:39 UTC, MingcongBai approved these changes, later dismissed

2021-11-25 12:21 UTC, MingcongBai approved these changes

2021-11-25 12:26 UTC, merged