Linux Kernel 5.15
AOSC-Dev/aosc-os-abbs pull request #3669
Opened 2021-11-23 09:11 UTC by cthbleachbit

Topic Description
-----------------

This PR updates main linux kenel to 5.15.4 and various other supporting packages. Here is a summary of changes for the primary architectures:

#### amd64:

- DAMON: Data Access Monitoring framework
- I2C/GPIO over VirtIO
- AMD PTDMA engine
- NTFS3 support from paragon
- AESNI/SSE accelerated SM4 cryptography routines

#### arm64:

- DAMON: Data Access Monitoring framework
- I2C/GPIO over VirtIO
- NTFS3 support from paragon
- HyperV guest modules: PCIe, balloning, input, storage, blah blah
- Apple M1 DART IOMMU support

For detailed changes, see [this spreadsheet](https://docs.google.com/spreadsheets/d/1-ohaMnTXqQXBrtbV7v4G0YWu_mzw80zTGRgeDJfYblY/edit?usp=sharing).

Curently waiting on packages in #3531 as some of the utilities require python.

Package(s) Affected
-------------------

* pahole 1.22
* linux-kernel, kernel-tools, linux+kernel 5.15.4
* util-linux: 2.37.2
* libbpf 0.5.0
* bcc 0.22.0

Build Order
-----------

pahole linux-kernel kernel-tools linux+kernel util-linux libbpf bcc

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Unconfigured yet.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-11-29 03:28 UTC, KexyBiscuit commented on extra-kernel/libbpf/autobuild/build
> +install -Dm644 "${SRCDIR}"/README.md -t "${PKGDIR}/usr/share/doc/libbpf"
```suggestion
install -Dvm644 "${SRCDIR}"/README.md -t "${PKGDIR}/usr/share/doc/libbpf"
```

2021-11-29 03:28 UTC, KexyBiscuit commented on extra-kernel/linux+kernel/spec
> +SRCS="tbl::https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-${VER/.0/}.tar.xz"
But why?

2021-11-29 03:28 UTC, KexyBiscuit requested changes
LGTM overall, a few changes.

2021-11-30 07:00 UTC, cthbleachbit commented on extra-kernel/linux+kernel/spec
> +SRCS="tbl::https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-${VER/.0/}.tar.xz"
My bad. I replaced the spec file from other concrete packages.

2021-12-01 07:26 UTC, KexyBiscuit reviewed
LGTM, waiting for test results.

2021-12-04 20:35 UTC, cthbleachbit commented
Dogfooding uptime 3 days. I suppose this is good enough for stable.

2021-12-04 20:35 UTC, KexyBiscuit approved these changes

2021-12-05 02:03 UTC, merged