starship: new, 1.0.0
AOSC-Dev/aosc-os-abbs pull request #3674
Opened 2021-11-24 10:11 UTC by CoelacanthusHex

Topic Description
-----------------

Introduce `starship`, a customizable prompt for shell written by Rust.

Package(s) Affected
-------------------

`starship`

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-11-24 11:10 UTC, CoelacanthusHex commented
LGTM on AMD64, bash, zsh and fish works well
![图片](https://user-images.githubusercontent.com/43064781/143227668-3af6bb72-ab27-4bfe-ab80-88889dfd9e8a.png)

2021-11-25 00:39 UTC, WhiredPlanck requested changes

2021-11-25 00:39 UTC, WhiredPlanck commented on extra-utils/starship/autobuild/beyond
> +    mkdir -p $(dirname ${completion_files[$sh]})
Add verbosity here please.

2021-11-25 00:39 UTC, WhiredPlanck commented on extra-utils/starship/autobuild/defines
> +PKGDES="A customizable prompt for shell."
It would be better to remove the period.

2021-11-25 00:40 UTC, liushuyu commented on extra-utils/starship/autobuild/beyond
> +    mkdir -p $(dirname ${completion_files[$sh]})
```suggestion
    mkdir -p "$(dirname ${completion_files[$sh]})"
```

Prevent potential globbing.

2021-11-25 00:40 UTC, liushuyu commented on extra-utils/starship/autobuild/defines
> +ABSPLITDBG=0
```suggestion

ABTYPE=rust
USECLANG=1
ABSPLITDBG=0
```

Usually we use a blank line to separate metadata definitions and compilation definitions.

2021-11-25 00:40 UTC, liushuyu commented on extra-utils/starship/autobuild/defines
> +PKGDES="A customizable prompt for shell."
```suggestion
PKGDES="A customizable shell prompt"
```

Remove period. Also, rephrase the sentence if needed, you don't have to follow what the upstream says.

2021-11-25 11:00 UTC, MingcongBai approved these changes

2021-11-25 11:24 UTC, WhiredPlanck approved these changes

2021-11-25 11:25 UTC, merged