Opencv 4.5.4 Survey
AOSC-Dev/aosc-os-abbs pull request #3684
Opened 2021-12-01 08:26 UTC by WhiredPlanck

Topic Description
-----------------

Update `opencv` to 4.5.4

Package(s) Affected
-------------------

```
opencv
vtk
gl2ps
liblas
```

Security Update?
----------------

No

Build Order
-----------

To bee filled soon.

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-12-18 14:30 UTC, WhiredPlanck commented
OpenCV LGTM (AMD64)
![图片](https://user-images.githubusercontent.com/47623588/146644556-3617216c-34b2-4b99-af94-0ac7b7806d13.png)

2021-12-19 01:59 UTC, liushuyu requested changes

2021-12-19 01:59 UTC, liushuyu commented on extra-libs/spdlog/autobuild/defines
> +PKGDES="A header-only/compiled C++ logging library dedicated to high performance"
```suggestion
PKGDES="A header-only/compiled C++ logging library"
```

2021-12-19 01:59 UTC, liushuyu commented on extra-scientific/vtk/autobuild/prepare
> +sed -e "s|8.1.0|8.0.1|" -i "$SRCDIR"/ThirdParty/fmt/CMakeLists.txt
Seems like a very fragile substitution, I would suggest generating a patch. That way, if the upstream package updates, the next maintainer would notice the issue.

2021-12-20 04:18 UTC, liushuyu approved these changes

2021-12-21 00:12 UTC, merged