Jellyfin: new, 10.7.7
AOSC-Dev/aosc-os-abbs pull request #3695
Opened 2021-12-07 17:17 UTC by eatradish

Topic Description
-----------------

Jellyfin: new, 10.7.7

Package(s) Affected
-------------------

Jellyfin: 10.7.7

Security Update?
----------------

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

2021-12-07 18:17 UTC, eatradish commented
LGTM on AMD64:

![Screenshot_20211208_021656](https://user-images.githubusercontent.com/19554922/145084341-e68e959e-68f4-40d7-bb13-49b2b2514192.png)

![Screenshot_20211208_021618](https://user-images.githubusercontent.com/19554922/145084380-fedc87d5-7392-4bef-8634-7b0e338c4b9b.png)

![Screenshot_20211208_021530](https://user-images.githubusercontent.com/19554922/145084398-a8f11e36-80af-4349-83be-d91e090a9436.png)

2021-12-07 18:32 UTC, eatradish commented
Systemd service also LGTM

2021-12-13 10:18 UTC, KexyBiscuit commented on extra-devel/aspnetcore-runtime-6.0/spec
> +CHKSUM="sha256::07dd14194e37c839a9580a212f9fd47131d443058f399177c3747b56fad35948"
Why adding these checksums?

2021-12-13 21:46 UTC, MingcongBai requested changes

2021-12-13 21:46 UTC, MingcongBai commented on extra-devel/aspnetcore-runtime-6.0/spec
> +CHKSUM="sha256::07dd14194e37c839a9580a212f9fd47131d443058f399177c3747b56fad35948"
Ditto.

2021-12-14 03:51 UTC, MingcongBai approved these changes

2021-12-14 03:52 UTC, merged