zerotier-one: update to 1.8.4 and fix format
AOSC-Dev/aosc-os-abbs pull request #3710
Opened 2021-12-21 05:32 UTC by Nyovelt

Topic Description
-----------------

zerotier-one: update to 1.8.4 and fix format

Package(s) Affected
-------------------

Security Update?
----------------

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2022-01-02 02:09 UTC, RedL0tus requested changes, later dismissed

2022-01-02 02:09 UTC, RedL0tus commented on extra-network/zerotier-one/spec
>  CHKUPDATE="anitya::id=17578"
Missing new line at end of file. Otherwise LGTM.

2022-01-02 14:33 UTC, WhiredPlanck submitted a review, later dismissed

2022-01-02 14:33 UTC, WhiredPlanck commented on extra-network/zerotier-one/spec
>  CHKUPDATE="anitya::id=17578"
Missing new line, otherwise LGTM too.

2022-01-02 14:33 UTC, WhiredPlanck commented
@Nyovelt ping?

2022-01-04 11:00 UTC, Nyovelt commented on extra-network/zerotier-one/spec
>  CHKUPDATE="anitya::id=17578"
Fixed

2022-01-05 17:38 UTC, MingcongBai approved these changes

2022-01-06 02:35 UTC, merged