keepassxc: update to  2.6.6
AOSC-Dev/aosc-os-abbs pull request #3727
Opened 2021-12-30 19:32 UTC by WhiredPlanck

Topic Description
-----------------

Update `keepassxc` to 2.6.6

Package(s) Affected
-------------------

`keepassxc`

Security Update?
----------------

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-12-31 01:43 UTC, MingcongBai requested changes

2021-12-31 01:43 UTC, MingcongBai commented on extra-security/keepassxc/autobuild/patches/0001-Fedora-fixes-GNOME-quirks-on-Wayland-sessions.patch
> +--- keepassxc-2.6.6-orig/src/main.cpp	2021-06-14 18:11:55.987803422 -0400
fixes => fix. I know they referenced it as such in their [spec file](https://src.fedoraproject.org/rpms/keepassxc/blob/rawhide/f/keepassxc.spec#_11) but let's not.

2022-01-01 08:29 UTC, MingcongBai approved these changes

2022-01-01 10:19 UTC, WhiredPlanck commented
LGTM on AMD64

![图片](https://user-images.githubusercontent.com/47623588/147848460-90eb161e-faad-493f-a390-023f550c7c68.png)

2022-01-01 10:19 UTC, merged