Web Survey on 20211231
AOSC-Dev/aosc-os-abbs pull request #3728
Opened 2021-12-31 01:34 UTC by MingcongBai

Topic Description
-----------------

Survey for updates in the `base-web` and `extra-web` categories.

Package(s) Affected
-------------------

- `curl+32` v7.80.0
- `hugo` v0.91.2
- `nginx` v1.21.5
- `qownnotes` v21.12.8
- `seamonkey` v2.53.10.2
- `telegram-desktop` v3.4.0

Security Update?
----------------

*Investigating*

Build Order
-----------

```
extra-optenv32/curl+32
extra-web/hugo
extra-web/nginx
extra-web/qownnotes
extra-web/seamonkey
extra-web/telegram-desktop
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
- [ ] 32-bit Optional Environment `optenv32`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
- [ ] 32-bit Optional Environment `optenv32`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2021-12-31 08:51 UTC, WhiredPlanck requested changes

2021-12-31 08:51 UTC, WhiredPlanck commented on extra-web/telegram-desktop/spec
>  SUBDIR=tdesktop-$VER-full
Shall we quote the path here ...?

2021-12-31 08:56 UTC, MingcongBai commented on extra-web/telegram-desktop/spec
>  SUBDIR=tdesktop-$VER-full
Yes.

2021-12-31 08:57 UTC, MingcongBai commented on extra-web/telegram-desktop/spec
>  SUBDIR=tdesktop-$VER-full
Addressed. Resolving.

2021-12-31 09:01 UTC, WhiredPlanck commented
Telegram LGTM on AMD64

2021-12-31 09:03 UTC, MingcongBai commented
![image](https://user-images.githubusercontent.com/5006263/147813984-cb9712f2-6988-4e9d-b302-9aa0f1c10e8c.png)

QOwnNotes requires intervention, we should opt-out by default.

2021-12-31 09:04 UTC, MingcongBai commented
Other packages LGTM.

2022-01-01 16:19 UTC, WhiredPlanck commented
QOwnNotes LGTM on AMD64
App metrics and heartbeat are disable by default.
All architecture test builds done.

![图片](https://user-images.githubusercontent.com/47623588/147854815-c7770bf0-4b13-4ef9-b5b5-ffa9d3a9d307.png)
![图片](https://user-images.githubusercontent.com/47623588/147854882-8fcbe741-f15e-4d26-b2fc-35a4bec4118a.png)
![图片](https://user-images.githubusercontent.com/47623588/147854960-224defbf-d198-47ae-b045-b0af07a110ae.png)

2022-01-02 08:33 UTC, cthbleachbit approved these changes

2022-01-02 08:37 UTC, WhiredPlanck approved these changes

2022-01-02 08:46 UTC, merged