helix: new, 0.6.0
AOSC-Dev/aosc-os-abbs pull request #3737
Opened 2022-01-05 16:53 UTC by WhiredPlanck

Topic Description
-----------------

Introduce `helix`, a [post-modern](https://helix-editor.com/#:~:text=FAQ-,Post%2Dmodern%3F!,-It%27s%20a%20joke) modal text editor.

Package(s) Affected
-------------------

`helix`

Security Update?
----------------

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2022-01-05 16:54 UTC, WhiredPlanck commented
LGTM on AMD64

![图片](https://user-images.githubusercontent.com/47623588/148256937-da7198de-e385-4f02-83a8-14f5e6e09d7b.png)

2022-01-05 17:37 UTC, MingcongBai requested changes

2022-01-05 17:37 UTC, MingcongBai commented on extra-editors/helix/autobuild/alternative
> +
Trailing blank line.

2022-01-05 17:37 UTC, MingcongBai commented on extra-editors/helix/autobuild/beyond
> +
Trailing blank line.

2022-01-05 17:37 UTC, MingcongBai commented on extra-editors/helix/autobuild/defines
> +
Trailing blank line.

2022-01-05 17:37 UTC, MingcongBai commented on extra-editors/helix/autobuild/defines
> +PKGDES="A post-modern modal text editor"
What does that even mean, it's certainly not helping me decide.

2022-01-05 17:37 UTC, MingcongBai commented on extra-editors/helix/autobuild/patches/0001-remove-pre-define-LTO-settings.patch
> +diff -aur helix-0.6.0/Cargo.toml helix-0.6.0.aosc/Cargo.toml
pre-defined *

2022-01-05 17:37 UTC, MingcongBai commented on extra-editors/helix/spec
> +
Trailing blank line.

2022-01-06 06:22 UTC, MingcongBai approved these changes

2022-01-06 07:43 UTC, merged