Qt 6 Survey 20210113
AOSC-Dev/aosc-os-abbs pull request #3760
Opened 2022-01-20 06:53 UTC by WhiredPlanck

Topic Description
-----------------

Introduce Qt version 6.

Package(s) Affected
-------------------
```
qt-6
```

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2022-01-21 09:23 UTC, MingcongBai requested changes

2022-01-21 09:23 UTC, MingcongBai commented on extra-libs/libb2/autobuild/defines
> +PKGDES="A C library providing BLAKE2b, BLAKE2s, BLAKE2bp, BLAKE2sp hash functions"
..., and BLAKE2sp *

2022-01-21 09:23 UTC, MingcongBai commented on extra-libs/qt-6/autobuild/defines
> +             -DINSTALL_DOCDIR=share/doc/qt6 \
Should be `share/doc/qt-6`. This was a mistake we made in Qt 5, and wouldn't be easily fixed unless we run a survey for all the packages containing `/usr/share/doc/qt5`.

2022-01-21 09:23 UTC, MingcongBai commented on extra-libs/qt-6/autobuild/defines
> +             -DINSTALL_EXAMPLESDIR=share/doc/qt6/examples \
Ditto above.

2022-01-21 09:23 UTC, MingcongBai commented on extra-libs/qt-6/autobuild/defines
> +             -DQT_FEATURE_sse3=ON"
Our AMD64 port uses the SSE2 baseline.

2022-01-23 13:02 UTC, closed without merging

2022-01-23 13:18 UTC, WhiredPlanck commented
There is a fatal typo that wrong date is used in the branch name, so I closed this and will open another PR.