stellarium: update to 0.21.3
AOSC-Dev/aosc-os-abbs pull request #3861
Opened 2022-03-05 06:17 UTC by WhiredPlanck

Topic Description
-----------------

Update `stellarium` to 0.21.3.
Because Mesa versions from v21.3.0 to v21.3.4 have an [flickering issue](https://gitlab.freedesktop.org/mesa/mesa/-/issues/5731), which leads to Stellarium's flickering issue, so update it to the latest v21.3.7 at the same time.
In addition, this PR may update or rebuild `gpsd` for lack of RISCV64 packages and dropping Python 2.

Package(s) Affected
-------------------

- `mesa` v21.3.7
- `stellarium` v0.21.3
- `gpsd` v(to be filled)

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2022-03-09 11:17 UTC, WhiredPlanck commented
LGTM on AMD64

![图片](https://user-images.githubusercontent.com/47623588/157431274-07aa29ce-a0c4-4602-8571-0b7ca0ab37b7.png)

2022-03-16 08:53 UTC, MingcongBai requested changes

2022-03-16 08:53 UTC, MingcongBai commented on extra-libs/mesa/autobuild/defines
> +NOLTO__LOONGSON3=1
What?

2022-03-17 04:57 UTC, WhiredPlanck commented
@MingcongBai All architectures test builds done without any issue.

2022-03-23 05:54 UTC, MingcongBai approved these changes

2022-03-23 14:04 UTC, merged