hpl: new, 2.3
AOSC-Dev/aosc-os-abbs pull request #3862
Opened 2022-03-06 10:49 UTC by Icenowy

Topic Description
-----------------

Introduce HPL, a High-performeance Linpack implementation.

Package(s) Affected
-------------------

- `hpl` (new, 2.3)

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2022-03-09 01:59 UTC, WhiredPlanck requested changes, later dismissed

2022-03-09 01:59 UTC, WhiredPlanck commented on extra-benchmarks/hpl/autobuild/beyond
> +cp "$SRCDIR"/testing/ptest/HPL.dat "$PKGDIR"/usr/share/doc/hpl/
Add verbosity to two operations.

2023-02-27 05:39 UTC, MingcongBai commented
<img width="640" alt="图片" src="https://user-images.githubusercontent.com/5006263/221483281-a8db272f-4cb0-419a-a87b-01f3e577d2fb.png">

LGTM on amd64.

2023-02-27 05:40 UTC, eatradish approved these changes

2023-02-27 05:41 UTC, merged