throttled: new, 0.9.2
AOSC-Dev/aosc-os-abbs pull request #3868
Opened 2022-03-13 09:02 UTC by CamberLoid

Topic Description
-----------------

Add package `throttled` in response to [pakreq 1008](https://pakreq.aosc.io/detail/1008)

Package(s) Affected
-------------------

`throttled` v0.9.2

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] noarch `noarch`

    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2022-03-13 14:33 UTC, WhiredPlanck requested changes
Hi, @CamberLoid. Welcome to AOSC Community! And thanks your first pull request here ~ 

I've made several reviews according our [Package Styling Manual](https://wiki.aosc.io/developer/packaging/package-styling-manual/). This can help us to make more better packages.

2022-03-13 14:33 UTC, WhiredPlanck commented on extra-admin/throttled/autobuild/build
> +mkdir "$PKGDIR"/usr/lib/python"$ABPY3VER"/site-package/throttled -p
Every command needs to add verbosity if possible. For this case:

```suggestion
mkdir -pv "$PKGDIR"/usr/lib/python"$ABPY3VER"/site-package/throttled
```
...

2022-03-13 14:33 UTC, WhiredPlanck commented on extra-admin/throttled/autobuild/build
> +install -Dvm644 "$SRCDIR"/systemd/lenovo_fix.service "$PKGDIR"/usr/lib/systemd/system/throttled.service
And for this case, you added verbosity, very good. But it's recommended that if the character numbers of a line is bigger than 80, insert a `\` into a proper place:

```suggestion
install -Dvm644 "$SRCDIR"/systemd/lenovo_fix.service \
    "$PKGDIR"/usr/lib/systemd/system/throttled.service
```

just like what you did at line 3, 4 and 5, 6.

2022-03-13 14:33 UTC, WhiredPlanck commented on extra-admin/throttled/autobuild/build
> +abinfo "All done"
`abinfo`  at this line is unnecessary. 

Always add a blank line at the end of each file.

2022-03-13 14:33 UTC, WhiredPlanck commented on extra-admin/throttled/spec
> +# REL=0
If a variable is unused, just remove it.

2022-03-13 14:33 UTC, WhiredPlanck commented on extra-admin/throttled/autobuild/prepare
> +sed -i "s|ExecStart=.*|ExecStart=/bin/python3 /usr/lib/python$ABPY3VER/site-package/throttled.py|" "$SRCDIR"/systemd/lenovo_fix.service
For `sed` actions, we need to write them like this, which may be more clear to see what happened:

```suggestion
sed -e "s|ExecStart=.*|ExecStart=/bin/python3 /usr/lib/python$ABPY3VER/site-package/throttled.py|" \
    -i "$SRCDIR"/systemd/lenovo_fix.service
```

And here wouldn't it be more appropriate to create a symlink at `/usr/bin` to site-package path?

2022-03-13 14:33 UTC, WhiredPlanck commented on extra-admin/throttled/autobuild/defines
> +ABHOST=noarch
Add a blank line at the end.

2022-03-13 14:33 UTC, WhiredPlanck commented on extra-admin/throttled/autobuild/build
> +ln -s throttled.conf "$PKGDIR"/etc/lenovo_fix.conf
Add verbosity: `ln -sv` ...

2022-03-13 14:33 UTC, WhiredPlanck commented on extra-admin/throttled/autobuild/prepare
> +mv lenovo_fix.py throttled.py
Add verbosity: `mv -v` ...

2022-03-13 14:33 UTC, WhiredPlanck commented on extra-admin/throttled/spec
> +CHKSUMS="sha256::01beb3e17303b11d86aeadc74d85d0ee2d50375998137dcdb5e464de4fdc4e07"
Here we need to add a variable called `CHKUPDATE`, which can help us to check if the new version of application is available. You could see [here](https://github.com/AOSC-Dev/aosc-findupdate/blob/master/docs/config.zh-CN.md) for more information.

2022-03-13 16:46 UTC, CamberLoid commented
Thanks for mentoring.
Suggestion applied.

2022-03-14 01:45 UTC, WhiredPlanck commented
/build throttled

2022-03-14 03:03 UTC, CamberLoid commented
duplicated.
closing now

2022-03-14 03:03 UTC, closed without merging