AOSC OS Core 9.1.1
AOSC-Dev/aosc-os-abbs pull request #3903
Opened 2022-04-06 09:14 UTC by CamberLoid

Topic Description
-----------------

This topic updates AOSC OS Core to 9.1.1, containing a security update of zlib 1.2.12.

Package(s) Affected
-------------------

`zlib` 1.2.11-5 -> 1.2.12
`aosc-aaa` 9.1.0 -> 9.1.1

Security Update?
----------------

Yes #3896 / https://github.com/advisories/GHSA-jc36-42cf-vqwj

Build Order
-----------

```
core-libs/zlib
core-misc/aosc-aaa
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2022-04-08 09:26 UTC, MingcongBai approved these changes

2022-04-08 09:27 UTC, MingcongBai requested changes
Zlib update results in non-fatal errors:

```
flatpak: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libsoup-2.4.so.1)
flatpak: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libxml2.so.2)
flatpak: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libxml2.so.2)
flatpak: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libgio-2.0.so.0)
```

2022-04-09 07:29 UTC, CamberLoid commented
https://github.com/AOSC-Dev/aosc-os-abbs/pull/3903/commits/e681d4e5909579ed6e9c7ef518b13154538a4aab should fix https://github.com/AOSC-Dev/aosc-os-abbs/pull/3903#pullrequestreview-936176582

Discarding label `help-wanted` and preparing for testing.

2022-04-09 08:47 UTC, MingcongBai commented
> [e681d4e](https://github.com/AOSC-Dev/aosc-os-abbs/commit/e681d4e5909579ed6e9c7ef518b13154538a4aab) should fix [#3903 (review)](https://github.com/AOSC-Dev/aosc-os-abbs/pull/3903#pullrequestreview-936176582)
> 
> Discarding label `help-wanted` and preparing for testing.

Confirmed.

2022-04-09 08:49 UTC, MingcongBai requested changes

2022-04-09 08:49 UTC, MingcongBai commented on core-libs/zlib/autobuild/build
>  ./configure --prefix=/usr
Try using ABTYPE, would dropping autobuild/build produce a working build?

2022-04-09 09:34 UTC, MingcongBai approved these changes

2022-04-09 12:17 UTC, CamberLoid commented
Merging Core 9.1.1 to stable

2022-04-09 12:17 UTC, merged

2022-04-09 12:32 UTC, CamberLoid commented
Note: Packages of `riscv64` and `ppcel64` are built in qemu user-mode emulated containers.

2022-04-09 12:32 UTC, CamberLoid commented
All packages are pushed to stable.