dub: rebuild for liblphobos
AOSC-Dev/aosc-os-abbs pull request #3912
Opened 2022-04-09 09:30 UTC by eatradish

Topic Description
-----------------

dub: rebuild for liblphobos

Package(s) Affected
-------------------

dub

Security Update?
----------------

NO

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2022-04-09 09:35 UTC, MingcongBai approved these changes

2022-04-09 09:35 UTC, MingcongBai requested changes

2022-04-09 09:35 UTC, MingcongBai commented on extra-dlang/dub/autobuild/defines
> +PKGDEP="curl ldc liblphobos"
Why? `ldc` already depends on `liblphobos`.

2022-04-13 09:42 UTC, MingcongBai approved these changes

2022-06-16 03:11 UTC, liushuyu commented
Superseded by 0de8a4b9fa6

2022-06-16 03:11 UTC, closed without merging