Go 1.18 Survey
AOSC-Dev/aosc-os-abbs pull request #3923
Opened 2022-04-12 02:43 UTC by CamberLoid

Topic Description
-----------------

This topic will update `go` to 1.18. Check updates and rebuild all packages of `groups/go-rebuilds`.

Package(s) Affected
-------------------

`go`
`groups/go-rebuilds`
`extra-base/golang-base`

Security Update?
----------------

No. 

Build Order
-----------

`go` ->
`golang-base` -> 
`groups/go-rebuilds`

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2022-04-21 07:29 UTC, CamberLoid commented
Upstream has released newer go compiler 1.18.1 . Previously updated packages will be rebuilt.

2022-05-07 13:50 UTC, CamberLoid commented
`popub` is tested and perform well on `riscv64`.
Despite there is no major behavior change between two commit of upstream, this package may require further tests due to the change of compiler from gccgo to google-go

2022-05-07 14:14 UTC, CamberLoid commented
Test checklist for `frp`
- [x] amd64 | Log: http://fars.ee/CjeV
- [ ] arm64
- [ ] loongson3
- [ ] ppc64el
- [ ] riscv64

2022-05-07 16:04 UTC, CamberLoid commented
Test checklist for hugo
- [ ] amd64
- [ ] arm64
- [ ] ppc64el
- [ ] loongson3
- [ ] riscv64

2022-05-08 09:04 UTC, CamberLoid commented
Test checklist for packages, so far
1. Core component
- [x] The compiler itself `go` | As long as there is no building error for other packages, considering this is tested
2. Packages updated
- [x] `frp` https://github.com/AOSC-Dev/aosc-os-abbs/pull/3923#issuecomment-1120217271
- [ ] `hugo` https://github.com/AOSC-Dev/aosc-os-abbs/pull/3923#issuecomment-1120233524
- [ ] `clash`
- [ ] `popub`
- [ ] `git-lfs`
- [ ] `gh`/`github-cli`
- [ ] `go-md2man`

2022-05-09 03:10 UTC, CamberLoid commented
Test checklist for `gotop` | Pass if normally executed.
- [ ] amd64
- [ ] arm64
- [ ] loongson3
- [ ] ppc64el
- [ ] riscv64

2022-05-09 07:52 UTC, CamberLoid commented
Patches in commit [0a71c63](https://github.com/AOSC-Dev/aosc-os-abbs/pull/3923/commits/0a71c63df0b405818070e4615b0b306270c64108) and [ca7dfe9](https://github.com/AOSC-Dev/aosc-os-abbs/pull/3923/commits/ca7dfe94787a551e26e3c454e530ea9da0dc543b) have been formed to a pull request and submitted to upstream. This patch will solve a FTBFS issue on riscv64 platform.

Reference: https://github.com/xxxserxxx/gotop/pull/218

2022-05-09 13:48 UTC, CamberLoid commented
Tests for clash(FOSS) are skipped because a checking dependency `docker` is missing, which is required by upstream-shipped test suite.

2022-05-10 03:07 UTC, CamberLoid commented
Test for `hub` will be performed by adding these lines to `autobuild/beyond`. Check if no error reports.
```bash
abinfo "Checking ..."
pushd "$SRCDIR"/src/github.com/github/hub
    make test || abwarn "Test failed ..."
popd
```
- [ ] amd64
- [ ] arm64
- [ ] loongson3
- [ ] ppc64el
- [ ] riscv64

2022-05-10 05:34 UTC, CamberLoid commented
Tests for `gh` will be performed using integrated check by adding the following lines to `autobuild/beyond` (will be restored). Check if build succeeds with no error.
```bash
abinfo "Checking ..."
(make test || abwarn "Test failed.") && abinfo "Test passed."
```
- [ ] amd64
- [ ] arm64
- [ ] loongson3
- [ ] ppc64el
- [ ] riscv64

2022-05-11 03:11 UTC, CamberLoid commented
Unit tests for `flatbuffers` are skipped as built-in tests are broken (also reported by archlinux).

2022-05-11 06:28 UTC, CamberLoid commented
`flatbuffers` does not requires `go` and `openjdk` to build. Will be dropped out of `groups/go-rebuilds` by the end of survey.

2022-05-11 15:34 UTC, MingcongBai requested changes

2022-05-11 15:34 UTC, MingcongBai commented on extra-shells/elvish/autobuild/postinst
> +grep -Fqx '/usr/bin/elvish' /etc/shells || \
Try and add some indents after line breaks to denote a chain of commands.

```
grep -Fqx '/bin/elvish' /etc/shells || \
    grep -Fqx '/usr/bin/elvish' /etc/shells || \
    echo '/usr/bin/elvish' >> /etc/shells
```

No need to tell user about /etc/shells update.

2022-05-11 15:34 UTC, MingcongBai commented on extra-shells/elvish/autobuild/postrm
> +# https://github.com/archlinux/svntogit-community/blob/packages/elvish/trunk/elvish.install
Use a specific commit snapshot for your reference.

2022-05-11 15:34 UTC, MingcongBai commented on extra-shells/elvish/autobuild/postrm
> +    echo "Attempting to purge elvish from /etc/shells ..."
Again, no need to add outputs like this. We might address this in a shell survey for consistency.

2022-05-11 15:34 UTC, MingcongBai commented on extra-shells/elvish/autobuild/prepare
> +abinfo "Setting GOFLAGS ..."
Be a bit more specific about what GOFLAGS you've set here, and move the all-arch export line directly after this line.

2022-05-11 15:34 UTC, MingcongBai commented on extra-shells/elvish/autobuild/build
> +# The following command is partitially adopted from Arch Linux's PKGBUILD
"Adapt" *, and also by adapting a script, whether it's partial or not is less relevant. Minor note, but do fix your word choice.

2022-05-11 15:34 UTC, MingcongBai commented on extra-shells/elvish/autobuild/build
> +export GOPATH="$SRCDIR/abgopath"
Missing abinfo.

2022-05-11 15:34 UTC, MingcongBai commented on extra-shells/elvish/autobuild/build
> +mkdir -vp "$PKGDIR"/usr/share/doc/elvish/website
Why "website"? You could consider renaming the README.md above to ELVISH.md.

2022-05-13 03:36 UTC, CamberLoid commented
Test build for arm64 is successfully performed

2022-05-17 09:15 UTC, CamberLoid commented
Tests for `gogs` is successfully performed on the following platforms: `gogs web` + `lynx localhost:3000`
- [x] `amd64`
![image](https://user-images.githubusercontent.com/22998116/168776048-75377410-d313-4e84-9f25-af7054db9914.png)
- [ ] `arm64`
- [ ] `loongson3`
- [ ] `ppc64el`
- [ ] `riscv64`

2022-06-03 04:58 UTC, OriginCode commented
![image](https://user-images.githubusercontent.com/17294071/171789107-219c8951-ff97-47c6-ad9f-b35edabdd66d.png)

2022-06-07 02:20 UTC, CamberLoid commented
From this point, test will be performed via a patched version of autobuild3.

See also: 
- https://github.com/AOSC-Dev/autobuild3/pull/128

2022-06-07 04:08 UTC, CamberLoid commented
Test checklist for `elvish`: 
- [x] `amd64`
![image](https://user-images.githubusercontent.com/22998116/172293607-72bbf956-e56f-4bf6-b658-dc785bbe2d02.png)
- [] `arm64`
- [] `loongson3`
- [] `riscv64`

Script: https://github.com/AOSC-Dev/aosc-os-abbs/commit/c69c4222f3ab7d0cec23c4cc59cae7ec0a40cdfb

2022-06-07 06:13 UTC, CamberLoid commented
Test checklist for `direnv`: 
- [x] `amd64` | Test exited with acceptable known failure
![image](https://user-images.githubusercontent.com/22998116/172308497-f61c51a5-1f8f-47c4-b5f9-a1b7dcfcdebb.png)
- [] `arm64`
- [] `loongson3`
- [] `riscv64`

Script: https://github.com/AOSC-Dev/aosc-os-abbs/commit/35e457be4a8f25db5ee7f3182d922b611a13e49e

2022-06-07 06:43 UTC, CamberLoid commented
Test checklist for `git-lfs`:
- [ ] `amd64` no major failure
![image](https://user-images.githubusercontent.com/22998116/172313393-bf25211d-536c-4c4f-abdf-c2a430b1c19f.png)
- [ ] `arm64`
- [ ] `loongson3`
- [ ] `riscv64`

2022-06-07 11:02 UTC, CamberLoid commented
Unit test for rclone is skipped as it requires rclone to be built without LTO, which violates out package building principles.

2022-06-07 11:41 UTC, CamberLoid commented
pcstat: LGTM on amd64
![image](https://user-images.githubusercontent.com/22998116/172370594-135fdb1a-b2dd-49c0-8180-4e7940edf1fc.png)

2022-06-07 12:06 UTC, CamberLoid commented
v2ray: test checklist
- [x] `amd64` with a minor failure on TestTCPLocalNameServer
- [ ] `arm64`
- [ ] `loongson3`
- [ ] `riscv64`

2022-06-07 12:17 UTC, CamberLoid commented
xray:
- [ ] `amd64` minor failure as geoip is not available, consider passed\
![image](https://user-images.githubusercontent.com/22998116/172376817-d155d81a-2738-42d0-986d-bcaf80fc2e45.png)
- [ ] `arm64`
- [ ] `loongson3`
- [ ] `riscv64`

2022-06-07 12:32 UTC, CamberLoid commented
ccat:
- [x] `amd64`: seems good to me, at least it works
![image](https://user-images.githubusercontent.com/22998116/172379390-4f235758-8ce3-443b-81f6-6d3f8e901b5f.png)
- [ ] `arm64`
- [ ] `loongson3`
- [ ] `riscv64`

2022-06-07 12:48 UTC, CamberLoid commented
syncthing: 
- [x] `amd64`
![image](https://user-images.githubusercontent.com/22998116/172382587-b7a34cac-49db-4e14-860d-1fd118ad3933.png)
- [ ] `arm64`
- [ ] `loongson3`
- [ ] `riscv64`

2022-06-07 12:59 UTC, CamberLoid commented
fzf:
- [x] `amd64`
![image](https://user-images.githubusercontent.com/22998116/172385300-27e221ea-a247-44a3-863d-cb56079613f9.png)
- [ ] `arm64`
- [ ] `loongson3`
- [ ] `riscv64`

2022-06-07 13:06 UTC, CamberLoid commented
pup: with an expected difference since https://github.com/ericchiang/pup/commit/6d1318bfa484b60309fe7a13e036093c179f15d6
- [x] `amd64`
![image](https://user-images.githubusercontent.com/22998116/172387163-2eb37fe5-9edc-4c55-b7c7-ed3cacb9f341.png)
- [x] `arm64`
![image](https://user-images.githubusercontent.com/22998116/172558596-f7cbb7e4-565a-4d40-9c4a-4cc85733a2e5.png)
- [ ] `loongson3`
- [ ] `riscv64`

2022-06-07 13:18 UTC, CamberLoid commented
restic: unit test failed as fusermount failed inside container. May need further test on non-container environment.
![image](https://user-images.githubusercontent.com/22998116/172389750-9789588d-7d9e-4864-a030-8edbda5b0247.png)
- [ ] `amd64`
- [ ] `arm64`
- [ ] `loongson3`
- [ ] `riscv64`

2022-07-06 04:24 UTC, CamberLoid commented
Test for restic will be skipped and placed to next survey.
Marking this PR as ready for review

2022-07-06 04:32 UTC, MingcongBai submitted a review, later dismissed

2022-07-06 04:35 UTC, MingcongBai approved these changes, later dismissed

2022-07-06 04:49 UTC, MingcongBai approved these changes, later dismissed

2022-07-07 16:07 UTC, MingcongBai approved these changes

2022-07-08 00:36 UTC, merged