qemu: adopt ppc64le binfmt support
AOSC-Dev/aosc-os-abbs pull request #3924
Opened 2022-04-12 05:13 UTC by CamberLoid

Topic Description
-----------------

The topic will adopt ppc64el binfmt support from qemu by introducing new configuration file.

Package(s) Affected
-------------------

`qemu` - `qemu-ppc*-static`

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2022-04-12 06:10 UTC, CamberLoid commented
Test complete on amd64.

2022-04-13 05:20 UTC, MingcongBai approved these changes, later dismissed

2022-04-14 06:57 UTC, CamberLoid commented
Can confirm qemu-static-ppc* for ppc64le does not contain any binfmt,d file.

2022-04-15 07:04 UTC, MingcongBai requested changes

2022-04-15 07:04 UTC, MingcongBai commented on extra-emulation/qemu/21-static-ppc64le/overrides/etc/binfmt.d/qemu-ppc64le.conf
> +:qemu-ppc64le:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x15\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\x00:/usr/bin/qemu-ppc64le-static:
Missing newline. Try and use Linux editors.

2022-04-15 07:19 UTC, MingcongBai approved these changes

2022-04-15 08:50 UTC, merged