deadbeef: update to 1.9.1
AOSC-Dev/aosc-os-abbs pull request #3969
Opened 2022-05-17 13:11 UTC by WhiredPlanck

Topic Description
-----------------

This PR is to update `deadbeef` to 1.9.1, and introduce its new dependency `libdispatch`, which will replace old and orphaned `libblocksruntime` and `libdispatch-objc2`.

Package(s) Affected
-------------------

- `deadbeef` v1.9.1 (update)
- `libdispatch` v5.6.1 (new)
- `libblocksruntime` v0.4.1-2 (drop, replaced by `libdispatch`)
- `libdispatch-objc2` v20140226-3 (drop, replaced by `libdispatch`)

Security Update?
----------------

No

Build Order
-----------

`libdispatch` then `deadbeef`.

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2022-05-17 13:15 UTC, WhiredPlanck commented
LGTM on AMD64
![图片](https://user-images.githubusercontent.com/47623588/168819442-efb0c58e-f537-4bd4-b0f0-53603322e7b1.png)

Test built packages are available in topic repo except RISC-V architecture (I cannot connect to build machine now).

2022-05-17 14:11 UTC, WhiredPlanck commented
/build

2022-05-18 02:54 UTC, WhiredPlanck commented
/build deadbeef

2022-05-18 06:30 UTC, MingcongBai requested changes

2022-05-18 06:30 UTC, MingcongBai commented on extra-libs/libdispatch/autobuild/defines
> +PKGBREAK="libblocksruntime>=0.4.1-2 libdispatch-objc2>=20140226-3"
Should be `<=`.

2022-05-18 06:30 UTC, MingcongBai commented on extra-libs/libdispatch/autobuild/defines
> +PKGDES="A library provides support for concurrency on multicore hardware"
Support library for concurrent code execution on multi-core hardware.

Adopted from [upstream homepage](https://apple.github.io/swift-corelibs-libdispatch/).

2022-05-19 06:12 UTC, MingcongBai approved these changes

2022-05-19 11:14 UTC, merged