openixcard: new, 1.0.1
AOSC-Dev/aosc-os-abbs pull request #3984
Opened 2022-05-23 18:26 UTC by CamberLoid

Topic Description
-----------------

The topic will introduce a new package `openixcard`, which is helpful for developing BSP for sunxi target.

Package(s) Affected
-------------------

`openixcard`: 1.0.1

Security Update?
----------------

No.

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2022-05-23 18:37 UTC, CamberLoid commented
LGTM on AMD64. May not test on other platform.
(Wrong image error corrected)
![image](https://user-images.githubusercontent.com/22998116/169885594-dfccb6b4-a5e9-403e-883d-0f2b315b1eac.png)
![image](https://user-images.githubusercontent.com/22998116/169887126-98985f1c-665b-4b14-9e4f-4f20e4f90256.png)

2022-05-23 18:56 UTC, CamberLoid commented
For the record: patch is related to https://github.com/YuzukiTsuru/OpenixCard/issues/3

2022-05-24 08:28 UTC, MingcongBai commented
> For the record: patch is related to [YuzukiTsuru/OpenixCard#3](https://github.com/YuzukiTsuru/OpenixCard/issues/3)

You should include this in your commit msg, as a "Ref: " line.

2022-05-24 08:41 UTC, MingcongBai requested changes

2022-05-24 08:41 UTC, MingcongBai commented on extra-devel/openixcard/autobuild/defines
> +BUILDDEP="cmake"
You won't need to define this. Our guideline specifies that there is no need to specify software shipped with BuildKit as BUILDDEP.

2022-05-24 08:41 UTC, MingcongBai commented on extra-devel/openixcard/autobuild/defines
> +ABTYPE=cmake
Would `cmakeninja` not work?

2022-05-24 08:41 UTC, MingcongBai commented on extra-devel/openixcard/autobuild/beyond
> +chmod +x "$PKGDIR"/usr/libexec/openixcard/genimage
Missing verbosity.

2022-05-24 08:41 UTC, MingcongBai commented on extra-devel/openixcard/autobuild/prepare
> +pushd lib/argparse
Use absolute path here.

2022-05-24 08:41 UTC, MingcongBai commented on extra-devel/openixcard/autobuild/defines
> +PKGDES="Open Source Implementation of Allwinner/sunxi's Image Manipulation Tool PhoenixCard"
"Open source implementation of PhoenixCard - Allwinner's image manipulation tool"

Reader attention theory: keep the key information/detail towards the middle of the sentence.

Also, there's no need to capitalise all first letters for all words in a sentence.

2022-05-31 04:43 UTC, MingcongBai approved these changes

2022-05-31 05:21 UTC, merged