systemd-usb-gadget: new, newest git
AOSC-Dev/aosc-os-abbs pull request #4008
Opened 2022-05-31 08:42 UTC by Icenowy

Topic Description
-----------------

Add systemd-usb-gadget package to AOSC OS, which is a systemd unit that controls USB gadget via configfs.

Package(s) Affected
-------------------

- `systemd-usb-gadget` 

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] Architecture-independent `noarch`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] Architecture-independent `noarch`

2022-06-02 18:52 UTC, MingcongBai requested changes

2022-06-02 18:52 UTC, MingcongBai commented on extra-admin/systemd-usb-gadget/autobuild/build
> +sed -i 's@/sbin@/usr/libexec@g' usb-gadget@.service
Missing absolute path.

2022-06-30 05:25 UTC, Icenowy commented
Re-request reviewing.

2022-06-30 05:45 UTC, MingcongBai approved these changes, later dismissed

2023-02-27 06:06 UTC, MingcongBai approved these changes

2023-02-27 06:08 UTC, merged