openscad: new, 2021.01+git20220514
AOSC-Dev/aosc-os-abbs pull request #4012
Opened 2022-06-01 03:13 UTC by RedL0tus

Topic Description
-----------------

Introduce OpenSCAD and its dependencies.

Package(s) Affected
-------------------

`opencsg`: new, 1.5.1
`automatic-components-toolkit`: new, 1.6.0
`lib3mf`: new, 2.2.0
`openscad`: new, 2021.01+git20220514

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2022-06-02 19:00 UTC, MingcongBai commented
Awaiting test results.

2022-06-17 05:17 UTC, RedL0tus commented
![image](https://user-images.githubusercontent.com/16459559/174230132-04a00482-57cb-4df3-9d03-a0a112e6f67d.png)
x86

![image](https://user-images.githubusercontent.com/16459559/174230055-5ee5f8ed-47f1-4db1-9fe5-548a73bc150e.png)
AArch64

2022-06-17 22:21 UTC, MingcongBai requested changes

2022-06-17 22:21 UTC, MingcongBai commented on extra-libs/lib3mf/autobuild/defines
> +ABTYPE=cmake
Why is it not using Ninja?

2022-11-07 13:11 UTC, RedL0tus commented
![image](https://user-images.githubusercontent.com/16459559/200318799-0f50eae0-357d-41ce-bc26-edfc8c7f29c9.png)
Works on AMD64

2022-11-11 07:27 UTC, Icenowy commented
![图片](https://user-images.githubusercontent.com/1916518/201288667-140ca3ad-f702-48a4-bac2-5c203db355e8.png)

Works on ARM64 (Phytium D2000).

2022-11-11 17:36 UTC, MingcongBai approved these changes

2023-01-04 07:25 UTC, merged