btop: new, 1.2.7
AOSC-Dev/aosc-os-abbs pull request #4021
Opened 2022-06-05 11:24 UTC by WhiredPlanck

Topic Description
-----------------

Introduce `btop`, a monitor of system resources written in C++.

Package(s) Affected
-------------------

`btop` v1.2.7

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
~~- [ ] PowerPC 64-bit (Little Endian) `ppc64el`~~
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
~~- [ ] PowerPC 64-bit (Little Endian) `ppc64el`~~
- [ ] RISC-V 64-bit `riscv64`

2022-06-05 11:32 UTC, WhiredPlanck commented
/build

2022-06-05 11:38 UTC, WhiredPlanck commented
LGTM on AMD64
![图片](https://user-images.githubusercontent.com/47623588/172048620-728672c6-d6a9-4ecd-ab76-8005c2016a47.png)

2022-06-14 16:56 UTC, MingcongBai requested changes

2022-06-14 16:56 UTC, MingcongBai commented on extra-utils/btop/autobuild/defines
> +PKGDES="A monitor of system resources"
A terminal system resource and status monitor

2022-06-15 00:20 UTC, MingcongBai approved these changes

2022-06-15 00:39 UTC, merged