openixcard: update to 1.1.0
AOSC-Dev/aosc-os-abbs pull request #4028
Opened 2022-06-14 08:22 UTC by CamberLoid

Topic Description
-----------------

This topic will upgrade `openixcard` to version 1.1.0

Changelog:

- Switch ABTYPE to `cmake` due to incompability of ninja with `${SRCDIR}/src/GenIMG/CmakeLists.txt` (May patch that file and use `cmakeninja` again);
  - Log: `ninja: error: 'thirdparty/genimage-src/libgenimage.a', needed by 'dist/OpenixCard', missing and no known rule to make it`
  - May not purpose a issue/PR to upstream, as upstream's document uses plain cmake to build.
- Fix wrong executable destination;
- Drop patches and previous `prepare` as upstream fixed it;
  - Also dropped `beyond`, as there is no more `genimage`

Package(s) Affected
-------------------

`openixcard` 1.1.0

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] RISC-V 64-bit `riscv64`

2022-06-15 00:18 UTC, MingcongBai commented
Awaiting test results.

2022-06-15 00:19 UTC, MingcongBai requested changes

2022-06-15 00:19 UTC, MingcongBai commented on extra-devel/openixcard/autobuild/prepare
> +cat "$SRCDIR"/CMakeLists.txt | sed 's/opt\/openixcard\/bin/bin/g' > "$SRCDIR"/CMakeLists.txt
Please use sed's -i parameter.

```
sed -e 's|/opt/openixcard/bin|/usr/bin|g' \
    -i "$SRCDIR"/CMakeLists.txt
```

2022-08-12 09:21 UTC, CamberLoid commented
Upstream released new version. The topic will be closed.

2022-08-12 09:21 UTC, closed without merging