i3 survey 20220710
AOSC-Dev/aosc-os-abbs pull request #4061
Opened 2022-07-11 03:15 UTC by OriginCode

Topic Description
-----------------

Update i3wm packages along with `picom` and `rofi` utilities

Package(s) Affected
-------------------

- `i3` 4.20.1
- `i3lock` 2.14.1
- `i3status` 2.14
- `i3-gaps` 4.20.1
- `picom` 9.1
- `rofi` 1.7.3
- `i3ipc-python` 2.2.0

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

`i3ipc-python`
- [ ] Architecture-independent `noarch`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

`i3ipc-python`
- [ ] Architecture-independent `noarch`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2022-07-11 05:16 UTC, OriginCode commented
LGTM on amd64:
![圖片](https://user-images.githubusercontent.com/17294071/178901102-3bc0cdce-356f-4e63-acc3-0fe0125dbe1e.png)

2022-07-14 04:50 UTC, WhiredPlanck requested changes

2022-07-14 04:50 UTC, WhiredPlanck commented on extra-utils/dunst/autobuild/build
> +install -Dvm755 dunstify "$PKGDIR"/usr/bin/dunstify
Need a absolute path here.

2022-07-14 04:52 UTC, MingcongBai approved these changes

2022-07-14 04:53 UTC, WhiredPlanck approved these changes

2022-07-14 04:54 UTC, merged