chisel: new, 1.7.7
AOSC-Dev/aosc-os-abbs pull request #4167
Opened 2022-08-29 23:08 UTC by Nyovelt

Topic Description
-----------------

Trying to introduce chisel, A fast TCP/UDP tunnel over HTTP.

Package(s) Affected
-------------------

No

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2022-08-29 23:14 UTC, Nyovelt commented
![testresult](https://user-images.githubusercontent.com/18253926/187314690-e4d78ecc-f4b8-4bdc-b002-0f99ce532d77.png)

2022-08-29 23:21 UTC, MingcongBai requested changes

2022-08-29 23:21 UTC, MingcongBai commented on extra-network/chisel/autobuild/build
> +if [[ "${CROSS:-$ARCH}" != "loongson3" ]]; then
Please use `if ! ab_match_arch loongson3; then` clause and add a comment explaining why.

2022-08-29 23:21 UTC, MingcongBai commented on extra-network/chisel/autobuild/defines
> +PKGDES="A fast TCP/UDP tunnel over HTTP "
Remove "fast."

2022-08-30 05:13 UTC, MingcongBai approved these changes

2022-08-30 05:27 UTC, merged