telegram-desktop: update to 4.2.0
AOSC-Dev/aosc-os-abbs pull request #4215
Opened 2022-09-21 01:46 UTC by RedL0tus

Topic Description
-----------------

Update `telegram-desktop` to v4.2.0

Package(s) Affected
-------------------

telegram-desktop: update to 4.2.0

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2022-09-21 04:32 UTC, Nyovelt requested changes
I met `Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt5::Core" does
not agree with the value of QT_MAJOR_VERSION already determined
for "Telegram".`  as I built it on my device.

The full log file is at [the attachment here.](https://pastebin.aosc.io/paste/381mdZIYAqt1J07AwcNE~A)

2022-09-23 21:24 UTC, OriginCode commented
LGTM on amd64:
![圖片](https://user-images.githubusercontent.com/17294071/192058644-6bc42029-5a2c-4ee8-b380-e711a3838248.png)

2022-09-23 21:26 UTC, OriginCode approved these changes

2022-10-10 17:14 UTC, MingcongBai commented
> I met `Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt5::Core" does not agree with the value of QT_MAJOR_VERSION already determined for "Telegram".` as I built it on my device.
> 
> The full log file is at [the attachment here.](https://pastebin.aosc.io/paste/381mdZIYAqt1J07AwcNE~A)

This issue should be fixed now.

2022-10-10 17:14 UTC, MingcongBai approved these changes

2022-11-07 09:02 UTC, closed without merging