hardinfo 0.5.1 rework 20220
AOSC-Dev/aosc-os-abbs pull request #4219
Opened 2022-09-24 11:06 UTC by CamberLoid

Topic Description
-----------------

* Latest commit on upstream source tree has made multiple changes comparing to our version, including supports for various architectures, bugfixes, and adaption to modern envrionments. The package will now use snapshot of latest commit from master branch from Github instead of debian's source code.
* The package should use ABTYPE=CMAKENINJA from this commit.

Package(s) Affected
-------------------

hardinfo

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] RISC-V 64-bit `riscv64`

2022-09-27 04:36 UTC, Nyovelt reviewed
Built and worked success on my amd64 devices

2022-09-29 02:21 UTC, Nyovelt submitted a review, later dismissed

2022-10-09 08:17 UTC, MingcongBai requested changes

2022-10-09 08:17 UTC, MingcongBai commented on extra-libs/concurrencykit/autobuild/defines
> +PKGDES="Concurrency Kit C Library, with related algorithms and data structures"
C library to aid concurrent application development

2022-10-09 08:17 UTC, MingcongBai commented on extra-utils/sysbench/autobuild/defines
> +PKGDES="Scriptable database and system performance benchmark, based on LuaJIT"
Scriptable database and system performance benchmark

2022-10-09 14:58 UTC, MingcongBai approved these changes

2022-10-09 15:32 UTC, merged

2024-08-16 23:10 UTC, hwspeedy commented
Hi AOSC,

We have released new version of hardinfo as community edition hardinfo2.

Please revert to debian source code for hardinfo2 or make an updated package from community edition.

github source: https://github.com/hardinfo2/hardinfo2
webpage: https://hardinfo2.org