Server survey 20220929
AOSC-Dev/aosc-os-abbs pull request #4222
Opened 2022-09-29 08:44 UTC by Cyanoxygen

Topic Description
-----------------

This topic updates MariaDB, nginx and httpd to their latest version, and makes some modifications on various things, e.g. default configurations, etc.

Related: Issue #4043.

Package(s) Affected
-------------------

- `nginx`
- `httpd`
- `mariadb`

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
- [ ] 
**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2022-10-01 00:02 UTC, MingcongBai requested changes

2022-10-01 00:02 UTC, MingcongBai commented on extra-database/mariadb/autobuild/defines
> +             -DMYSQL_DATADIR=/var/db/mysql \
We might consider turning this into a QA standard.

2022-10-01 00:02 UTC, MingcongBai commented on extra-database/mariadb/autobuild/overrides/etc/mysql/my.cnf
> +# Server only configuration
Server configuration *

2022-10-01 00:02 UTC, MingcongBai commented on extra-database/mariadb/autobuild/overrides/etc/mysql/my.cnf
> +max_allowed_packet = 50M
Why is this set to 50M? Not that I know it's right/wrong, but you should explain what each option does. Including the character set and timezone options, etc.

2022-10-01 00:02 UTC, MingcongBai commented on extra-database/mariadb/autobuild/overrides/etc/mysql/my.cnf
> +open-files-limit = 8192
Ditto my notes above.

2022-10-01 00:02 UTC, MingcongBai commented on extra-database/mariadb/autobuild/postinst
> +	echo "Your config file stays unmodified."
This could be confusing - configuration files are handled by dpkg's conffiles mechanism.

2022-10-01 00:02 UTC, MingcongBai commented on extra-database/mariadb/autobuild/postinst
> +	echo "You may run \`systemctl start mysqld.service' to start MariaDB."
To launch the MariaDB daemon *

2022-10-01 00:02 UTC, MingcongBai commented on extra-database/mariadb/autobuild/postinst
> +	echo "========"
Better to use an empty line.

2022-10-01 00:02 UTC, MingcongBai commented on extra-database/mariadb/autobuild/postinst
> +	install -dm700 /var/db/mysql
Don't do this. Doing so will result in this directory getting lost in `aoscbootstrap`. Use `tmpfiles.d` instead.

2022-10-01 00:02 UTC, MingcongBai commented on extra-database/mariadb/autobuild/usergroup
> +user mysql 89 mysql /var/db/mysql "MariaDB Daemon User" /bin/false
Rewrite this into `sysusers.d`, and add `tmpfiles.d`.

2022-10-01 00:02 UTC, MingcongBai commented on extra-web/httpd/autobuild/beyond
> +chown -v -R 207:207 "$PKGDIR"/srv/www
Okay, any files you have chown/chgrp'd here should really be handled by `tmpfiles.d`.

2022-10-01 00:02 UTC, MingcongBai commented on extra-web/httpd/autobuild/beyond
> +# index.apache.html is the default index page
Use abinfo, and explain better please - what did you do to what effect.

2022-10-01 00:02 UTC, MingcongBai commented on extra-web/httpd/autobuild/overrides/etc/httpd/conf/httpd.conf
> +#
Where did this file come from and what have you changed?

2022-10-01 00:02 UTC, MingcongBai commented on extra-web/httpd/autobuild/overrides/etc/httpd/conf/modules.conf
> +#
Ditto notes from last file.

2022-10-01 00:02 UTC, MingcongBai commented on extra-web/httpd/autobuild/overrides/etc/httpd/sites-available/default.conf
> +# Default site for Apache
Ditto.

2022-10-01 00:02 UTC, MingcongBai commented on extra-web/httpd/autobuild/postinst
> +chown -R http:http /srv/www/cgi-bin
All of this should be handled by `sysusers.d` and `tmpfiles.d`.

2022-10-01 00:02 UTC, MingcongBai commented on extra-web/httpd/autobuild/postinst
> +	mkdir -p /etc/httpd/sites-enabled
Why not build it into the package? Again, operations like this won't be correctly applied when generating a system release using `aoscboostrap`, as it strips out out-of-package files (barring exceptions).

2022-10-01 00:02 UTC, MingcongBai commented on extra-web/httpd/autobuild/postinst
> +        ln -sv /etc/httpd/sites-available/default.conf /etc/httpd/sites-enabled/default.conf
Ditto above.

2022-10-01 00:02 UTC, MingcongBai commented on extra-web/nginx/autobuild/beyond
> +# sed -e 's|\<user\s\+\w\+;|user html;|g' \
Just drop the lines?

2022-10-01 00:02 UTC, MingcongBai commented on extra-web/nginx/autobuild/beyond
>  rm "$PKGDIR"/etc/nginx/*.default
Lint this script please - missing verbosity and abinfo.

2022-10-01 00:02 UTC, MingcongBai commented on extra-web/nginx/autobuild/conffiles
>  /etc/logrotate.d/nginx
One option would be to just let Autobuild3 handle conffiles generation - drop this file.

2022-10-01 00:02 UTC, MingcongBai commented on extra-web/nginx/autobuild/overrides/etc/nginx/nginx.conf
> +user http;
Needs more comment explaining what each thing does. Did you get this file from anywhere? If not, where did you learn to write this file?

2022-10-01 00:02 UTC, MingcongBai commented on extra-web/nginx/autobuild/overrides/etc/nginx/sites-available/default
> +# Default site configuration
Ditto above.

2022-10-01 00:02 UTC, MingcongBai commented on extra-web/nginx/autobuild/postinst
> +#!/bin/bash
Shebang not necessary.

2022-10-01 00:02 UTC, MingcongBai commented on extra-web/nginx/autobuild/postinst
>  chown http:log /var/log/nginx
Ditto all my notes from httpd postinst above. Don't do out-of-package operations - they don't seem necessary here.

2022-10-04 14:26 UTC, Cyanoxygen commented on extra-database/mariadb/autobuild/defines
> +             -DMYSQL_DATADIR=/var/db/mysql \
All of our RDBMS' should follow this change then.

2022-10-10 17:15 UTC, MingcongBai commented on extra-database/mariadb/autobuild/defines
> +             -DMYSQL_DATADIR=/var/db/mysql \
> All of our RDBMS' should follow this change then.

Please implement in this PR.

2022-10-31 16:11 UTC, Cyanoxygen commented
Closing, changes are kept to open for another time.

2022-10-31 16:11 UTC, closed without merging