ncbi-blast: update to 2.13.0
AOSC-Dev/aosc-os-abbs pull request #4288
Opened 2022-11-08 00:54 UTC by StephDC

Topic Description
-----------------

Upgrade `ncbi-blast+` to 2.13.0

- Enable LTO as even though it takes a lot of time, it does indeed compile
- Disable `ABSPLITDBG` as it does not produce debug symbols

Package(s) Affected
-------------------
`ncbi-blast+`: 2.13.0

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2022-11-08 01:00 UTC, StephDC commented
Tested on _Staph. aureus_ data and worked as expected.

![blasttest](https://user-images.githubusercontent.com/9734616/200448045-5e799bfe-0240-4a1e-bc8c-47e3f28e6f53.png)

2022-11-08 02:19 UTC, MingcongBai requested changes

2022-11-08 02:19 UTC, MingcongBai commented on extra-scientific/ncbi-blast+/autobuild/defines
> +ABSPLITDBG=0
Why does it not produce debug symbols? It could be compiler/linker flags that did not get passed into the build system.

2022-11-08 06:56 UTC, StephDC commented on extra-scientific/ncbi-blast+/autobuild/defines
> +ABSPLITDBG=0
Found the compiler flag that disables debug symbols and strips the file and turned it off.
Rebuilding...

2022-11-09 03:01 UTC, MingcongBai approved these changes

2022-11-09 03:01 UTC, MingcongBai requested changes

2022-11-09 03:01 UTC, MingcongBai commented on extra-scientific/ncbi-blast+/spec
> +CHKSUMS="md5::0542f0e7b148d02db0854965e78e36c4"
MD5 is not an acceptable checksum.

2022-11-09 03:36 UTC, MingcongBai approved these changes

2022-11-09 03:46 UTC, merged