mcfly: adjust oobe config
AOSC-Dev/aosc-os-abbs pull request #4301
Opened 2022-11-17 09:55 UTC by eatradish

Topic Description
-----------------

mcfly: adjust oobe config

Package(s) Affected
-------------------

mcfly: 0.6.1-1
util-base: 8

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2022-11-17 14:54 UTC, MingcongBai requested changes

2022-11-17 14:54 UTC, MingcongBai commented on extra-utils/mcfly/autobuild/beyond
> +abinfo "Installint mcfly zsh and fish script ..."
Installing *

2022-11-17 14:54 UTC, MingcongBai commented on extra-utils/mcfly/autobuild/defines
> +USECLANG=1
Describe this in commit msg.

2022-11-17 14:54 UTC, MingcongBai commented on extra-utils/mcfly/autobuild/postinst
> +mcfly will be loaded automatically the next time you start the bash shell, or if you are using the bash shell and loading it immediately, type:
McFly will be loaded automatically the next time you enter the Bash shell. If you would like to load McFly for your current shell session, please input the following command:

2022-11-17 14:54 UTC, MingcongBai commented on extra-utils/mcfly/autobuild/postinst
> +If you are using Zsh and want to load it automatically on next startup, add the following statement to your `~/.zshrc` :
If you are using Zsh and want to load McFly automatically, please append the following line to `~/.zshrc` :

2022-11-17 14:54 UTC, MingcongBai commented on extra-utils/mcfly/autobuild/postinst
> +If you are using Fish and want to load it automatically on next startup, add the following to your `~/.config/fish/config.fish` :
If you are using Fish and want to load McFly automatically, please append the following line to `~/.config/fish/config.fish`:

2022-11-17 14:54 UTC, MingcongBai commented on extra-utils/mcfly/autobuild/postinst
> +"
Trailing blank line here.

2022-11-18 05:28 UTC, eatradish commented
@MingcongBai Done

2022-11-18 05:29 UTC, MingcongBai submitted a review, later dismissed

2022-11-18 05:57 UTC, MingcongBai approved these changes, later dismissed

2022-11-18 05:59 UTC, MingcongBai approved these changes

2022-11-18 06:29 UTC, merged