NVIDIA driver + vulkan survey Dec 22'
AOSC-Dev/aosc-os-abbs pull request #4323
Opened 2022-12-04 06:22 UTC by cthbleachbit

Topic Description
-----------------

This PR udpates nvidia drivers and vulkan stack to their respective latest versions.

Package(s) Affected
-------------------

- nvidia
- libglvnd, libglvnd+32
- vulkan-headers
- vulkan-loader, vulkan-loader+32
- spirv-headers
- spirv-tools
- vkd3d, vkd3d+32
- wine

Build Order
-----------

nvidia libglvnd libglvnd+32 vulkan-headers vulkan-loader vulkan-loader+32 spirv-headers spirv-tools vkd3d vkd3d+32 wine

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] RISC-V 64-bit `riscv64`

2022-12-04 06:23 UTC, MingcongBai requested changes

2022-12-04 06:23 UTC, MingcongBai commented on extra-libs/spirv-headers/autobuild/beyond
> +ln -svf "/usr/include/spirv" "${PKGDIR}/opt/32/include/"
Use relative link here.

2022-12-04 06:23 UTC, MingcongBai commented on extra-libs/vulkan-headers/autobuild/defines
> +ABTYPE=cmake
Outline why cmake is used in place of cmakeninja here, in a comment.

2022-12-04 06:23 UTC, MingcongBai commented on extra-x11/nvidia/spec
> +
Trailing blank line?

2022-12-04 06:33 UTC, MingcongBai approved these changes

2022-12-07 01:39 UTC, merged

2022-12-07 01:56 UTC, cthbleachbit commented
Note: wine now requires llvm to generate arm64 PE executable and couldn't be build for now. This issue will be corrected in a future topic.