v2raya: new, 2.0.1
AOSC-Dev/aosc-os-abbs pull request #4397
Opened 2023-01-31 16:31 UTC by RedL0tus

Topic Description
-----------------

Introduce v2raya, a Project V client with WebUI (closes #4369).

Package(s) Affected
-------------------

`v2raya: new, 2.0.1`

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2023-02-01 04:53 UTC, MingcongBai commented
`v2raya.service` LGTM on AArch64:

![图片](https://user-images.githubusercontent.com/5006263/215954828-9d1565c0-6114-4860-a93e-ccec97108823.png)

`v2raya-lite.service` (WTF is this?) hangs at GeoIP data download with no network activity:

![图片](https://user-images.githubusercontent.com/5006263/215954860-b40fd9c4-1761-41a2-8933-85e803c23a5c.png)

2023-02-02 03:17 UTC, CalciteW commented
> `v2raya.service` LGTM on AArch64:
> 
> ![图片](https://user-images.githubusercontent.com/5006263/215954828-9d1565c0-6114-4860-a93e-ccec97108823.png)
> 
> `v2raya-lite.service` (WTF is this?) hangs at GeoIP data download with no network activity:
> 
> ![图片](https://user-images.githubusercontent.com/5006263/215954860-b40fd9c4-1761-41a2-8933-85e803c23a5c.png)

Problems with `v2raya-lite.service` can be solved by `systemctl restart`

2023-02-02 03:18 UTC, CalciteW commented
Problems with `v2raya-lite.service` can be solved by `systemctl restart`

2023-02-02 08:04 UTC, MingcongBai commented
> this problem with `v2raya-lite.service` can be solved by running `systemctl restart`

@RedL0tus I think it could still be worth reporting this issue to upstream (since you mentioned that the service was poorly written). Another option is to just forgo the `-lite` service.

2023-02-02 09:05 UTC, RedL0tus commented
> > this problem with `v2raya-lite.service` can be solved by running `systemctl restart`
> 
> @RedL0tus I think it could still be worth reporting this issue to upstream (since you mentioned that the service was poorly written). Another option is to just forgo the `-lite` service.

Well actually it's my bad. `v2ray-lite.service` is supposed to be an user service, it works just fine in that case. But I still think it requires some modification:
 - I found that when launching `v2raya` with `--lite`, it defaults to `${HOME}/.local/share/v2ray/`. Maybe we should explicitly set that to something like `${HOME}/.config/v2raya`?
 - Its `After` field is a bit weird. The "lite" mode shouldn't have any routing-related capability, yet `v2raya-lite.service` uses the same values for `v2raya.service`.

2023-02-02 09:06 UTC, MingcongBai commented
@RedL0tus To the second point, I'm not sure what you mean - are you talking about the launch path?

To the final point, please consult the upstream for possible clarification/fixes.

2023-02-02 09:12 UTC, RedL0tus commented
> @RedL0tus To the second point, I'm not sure what you mean - are you talking about the launch path?
> 
> To the final point, please consult the upstream for possible clarification/fixes.

@MingcongBai  LMAO I deleted the most important part for the second point by mistake.

I mean its configuration path is not explicitly stated in the unit file. The default one uses `v2ray` instead of `v2raya` as directory name. IMO that might not be a good idea.

2023-02-02 09:13 UTC, MingcongBai commented
@RedL0tus I see. Would the $HOME variable work in systemd units? That might be something to double check.

2023-02-02 09:18 UTC, RedL0tus commented
> @RedL0tus I see. Would the $HOME variable work in systemd units? That might be something to double check.

@MingcongBai It should work, or we could use the [`%E` specifier](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Specifiers) here (and that might be a better idea).

2023-02-02 09:19 UTC, MingcongBai commented
@RedL0tus Got it.

2023-02-04 05:55 UTC, MingcongBai requested changes

2023-02-04 05:55 UTC, MingcongBai commented on extra-network/v2raya/autobuild/defines
> +PKGDES="A client of Project V with web GUI"
A client for

2023-02-04 05:55 UTC, MingcongBai commented on extra-network/v2raya/spec
> +CHKUPDATE="git::url=https://github.com/v2rayA/v2rayA.git;pattern=v2.*"
Use anitya whenever possible. They are the most reliable.

2023-02-05 03:32 UTC, RedL0tus commented on extra-network/v2raya/autobuild/defines
> +PKGDES="A client of Project V with web GUI"
Done

2023-02-06 22:27 UTC, MingcongBai approved these changes

2023-02-10 11:30 UTC, merged