kubo: new, 0.18.1
AOSC-Dev/aosc-os-abbs pull request #4450
Opened 2023-03-03 03:30 UTC by dynos01

Topic Description
-----------------
kubo: new, 0.18.1

Package(s) Affected
-------------------
kubo: new, 0.18.1

Security Update?
----------------
No

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2023-03-03 09:05 UTC, MingcongBai requested changes

2023-03-03 09:05 UTC, MingcongBai commented on extra-network/kubo/autobuild/build
> +install -Dvm644 "$SRCDIR"/ipfs-completion.bash -t "$PKGDIR"/usr/share/bash-completion/completions/
Please ensure that a `newline` exists for end-of-file. This applies for all the files you have committed.

2023-03-03 09:25 UTC, dynos01 commented on extra-network/kubo/autobuild/build
> +install -Dvm644 "$SRCDIR"/ipfs-completion.bash -t "$PKGDIR"/usr/share/bash-completion/completions/
I've added newlines to all files commited.

2023-03-03 09:30 UTC, MingcongBai approved these changes

2023-03-07 08:38 UTC, MingcongBai requested changes

2023-03-07 08:38 UTC, MingcongBai commented on extra-network/kubo/autobuild/build
> +cmd/ipfs/ipfs commands completion bash > "$SRCDIR"/ipfs-completion.bash
Absolute path here. `"$SRCDIR"/cmd/ipfs/ipfs ...`, it is also recommended to wrap wide lines.

2023-03-07 08:38 UTC, MingcongBai commented on extra-network/kubo/autobuild/prepare
> +export GOFLAGS="-buildmode=pie -trimpath -modcacherw"
All of these are not necessary. Autobuild3 defines all these flags internally.

2023-03-07 08:38 UTC, MingcongBai commented on extra-network/kubo/spec
> +CHKSUMS="sha256::4dc65c1177fe2ff339c64063643276112efa029117d0810f14422208dd6a3c32"
You should add a CHKUPDATE field indicating a way to automatically check for updates. This is done with [aosc-findupdate](https://github.com/AOSC-Dev/aosc-findupdate). We usually use the `anitya` type, using Fedora's [Anitya](https://release-monitoring.org/).

Please register an account there and submit `kubo` as one of the software to track. After you are done, you will get an update-check ID. For instance, Bash, at https://release-monitoring.org/project/166/, means that it has an ID of 166.

In this case, then, the CHKUPDATE line should go something like this.

```
CHKUPDATE="anitya::id=166"
```

2023-03-07 08:39 UTC, MingcongBai commented on extra-network/kubo/spec
> +CHKSUMS="sha256::4dc65c1177fe2ff339c64063643276112efa029117d0810f14422208dd6a3c32"
We require this information for all packages, where possible.

2023-03-07 15:30 UTC, dynos01 commented
![kubo](https://user-images.githubusercontent.com/12680076/223468972-adee4545-3bf4-4840-91a8-264bf36c6db1.png)

2023-03-07 22:24 UTC, MingcongBai approved these changes

2023-03-07 22:24 UTC, merged