mips64r6el Cross Toolchain: new
AOSC-Dev/aosc-os-abbs pull request #4467
Opened 2023-03-22 05:09 UTC by Cyanoxygen

Topic Description
-----------------

This topic brings MIPS64 R6 cross build toolchain.

Package(s) Affected
-------------------

- `binutils+cross-mips64r6el`
- `gcc+cross-mips64r6el`

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2023-03-22 15:53 UTC, cthbleachbit commented on app-devel/binutils+cross-mips64r6el/autobuild/build
> +../configure --prefix=/opt/abcross/mips64r6el --target=mipsisa64r6el-aosc-linux-gnuabi64 \
Nit: Split each parameter on a separate line

2023-03-22 15:53 UTC, cthbleachbit commented on app-devel/gcc+cross-mips64r6el/autobuild/build
> +AR=ar ../configure --prefix=/opt/abcross/mips64r6el --target=mipsisa64r6el-aosc-linux-gnuabi64 \
- Split parameters into separate lines.
- Why we need an `AR=ar` here?

2023-03-22 15:53 UTC, cthbleachbit commented on app-devel/gcc+cross-mips64r6el/autobuild/build
> +	--enable-__cxa_atexit --disable-altivec --disable-fixed-point --with-arch=mips64r6 --with-tune=mips64r6 \
Altivec is only valid for power architecture and is irrelavant for mips64r6. Please remove `--disable-altivec`

2023-03-23 06:28 UTC, Cyanoxygen commented
Testing
--------

This toolchain is able to build simple program, i.e. program written with only C library functions.

![image](https://user-images.githubusercontent.com/29174191/227121555-34b0b8f9-8f98-44fe-aa88-74e89b417a54.png)

2023-03-23 06:31 UTC, MingcongBai requested changes

2023-03-23 06:31 UTC, MingcongBai commented on app-devel/binutils+cross-mips64r6el/autobuild/beyond
> +rm $PKGDIR/opt/abcross/mips64r6el/share/info/dir
Missing verbosity, quote $PKGDIR.

2023-03-23 06:31 UTC, MingcongBai commented on app-devel/binutils+cross-mips64r6el/autobuild/build
> +mkdir -p build
Absolute path here.

2023-03-23 06:31 UTC, MingcongBai commented on app-devel/binutils+cross-mips64r6el/autobuild/build
> +cd build
Ditto.

2023-03-23 06:31 UTC, MingcongBai commented on app-devel/binutils+cross-mips64r6el/autobuild/build
> +make DESTDIR=$PKGDIR install
Quote $PKGDIR.

2023-03-23 06:31 UTC, MingcongBai commented on app-devel/gcc+cross-mips64r6el/autobuild/beyond
> +rm $PKGDIR/opt/abcross/mips64r6el/share/info/dir
Verbosity here.

2023-03-23 06:31 UTC, MingcongBai commented on app-devel/gcc+cross-mips64r6el/autobuild/build
> +mkdir -p build
Ditto about absolute path.

2023-03-23 06:31 UTC, MingcongBai commented on app-devel/gcc+cross-mips64r6el/autobuild/build
> +cd build
Ditto.

2023-03-23 06:31 UTC, MingcongBai commented on app-devel/gcc+cross-mips64r6el/autobuild/build
> +make DESTDIR=$PKGDIR install
Quote $PKGDIR.

2023-03-23 06:31 UTC, MingcongBai commented on app-devel/gcc+cross-mips64r6el/autobuild/build
> +mkdir -p build
And verbosity.

2023-03-23 06:31 UTC, MingcongBai requested changes

2023-03-23 06:31 UTC, MingcongBai commented on app-devel/binutils+cross-mips64r6el/autobuild/build
> +mkdir -p build
And verbosity.

2023-03-24 21:34 UTC, MingcongBai approved these changes, later dismissed

2023-04-03 08:30 UTC, MingcongBai approved these changes

2023-04-03 08:31 UTC, merged