typst: new, 0.0.0+git20210626
AOSC-Dev/aosc-os-abbs pull request #4468
Opened 2023-03-24 12:29 UTC by Nyovelt

Trying to introduce typst, A LaTeX killer.

Topic Description
-----------------

No
Package(s) Affected
-------------------

No
Security Update?
----------------

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2023-03-24 15:13 UTC, Nyovelt commented
![](https://webresources.aaaab3n.moe/2023/03/b8e0443386d5bdc934c7b24b7f05fd25.png)

2023-03-24 15:17 UTC, Nyovelt commented
![](https://webresources.aaaab3n.moe/2023/03/0eee352b6892caf1518f543f2e8d0017.png)

2023-03-24 22:21 UTC, MingcongBai requested changes

2023-03-24 22:21 UTC, MingcongBai commented on app-doc/typst/spec
> +VER=0.0.0+git2023032
Upstream does have a tag - https://github.com/typst/typst/tags.

2023-03-24 22:21 UTC, MingcongBai commented on app-doc/typst/spec
> +CHKSUMS="SKIP"
CHKUPATE missing.

2023-03-24 22:21 UTC, MingcongBai commented on app-doc/typst/autobuild/defines
> +PKGDES="A new markup-based typsetting system that is designed to be as powerful as LaTeX while being much easier to learn and use."
This is too verbose for a short description and it forces a lot of subjective descriptions. Try this...

A markup-based typsetting system

This should be good enough.

2023-03-25 11:03 UTC, Nyovelt commented on app-doc/typst/spec
> +VER=0.0.0+git2023032
The thing is, based on this commit, https://github.com/typst/typst/commits/main, the release cannot be compiled unless patched to the latest commit.

2023-03-26 16:53 UTC, MingcongBai approved these changes, later dismissed

2023-04-02 07:21 UTC, MingcongBai approved these changes

2023-04-03 08:42 UTC, closed without merging