etckeeper: new, 1.18.20
AOSC-Dev/aosc-os-abbs pull request #4495
Opened 2023-04-11 12:42 UTC by jiegec

Topic Description
-----------------

Introduce [etckeeper](https://etckeeper.branchable.com/).

Package(s) Affected
-------------------

`etckeeper` 1.18.20.

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2023-04-11 18:10 UTC, MingcongBai requested changes

2023-04-11 18:10 UTC, MingcongBai commented on app-admin/etckeeper/autobuild/conffiles
> +/etc/apt/apt.conf.d/05etckeeper
No need to write this file manually. Autobuild3 can generate this file automatically, unless you want to exclude certain files.

2023-04-11 18:10 UTC, MingcongBai commented on app-admin/etckeeper/autobuild/defines
> +ABSPLITDBG=0
Missing `newline`, ditto for the two files below.

Also, is this package `noarch` (I'm guessing from `ABSPLITDBG=0`)? If so, declare `ABHOST=noarch` instead.

2023-04-11 18:10 UTC, MingcongBai commented on app-admin/etckeeper/autobuild/postinst
> +esac
Ditto missing newline.

2023-04-11 18:10 UTC, MingcongBai commented on app-admin/etckeeper/spec
> +CHKSUMS="sha256::0bb856e96f59cf582a92361294f0fc32e0a8bbc02fac3aacae0a735d11b3addd"
Please also declare `CHKUPDATE=` for automatic update checking. From [Anitya](https://release-monitoring.org/project/761/), we know that this project has a version check ID of 761.

```
CHKUPDATE="anitya::id=761"
```

Will suffice. For details on how this variable works, see this [documentation](https://github.com/AOSC-Dev/aosc-findupdate/blob/master/docs/config.zh-CN.md).

2023-04-13 03:37 UTC, MingcongBai approved these changes

2023-04-13 03:40 UTC, merged

2023-08-16 14:03 UTC, jiegec commented
Uploaded to frontier for loongarch64.

2023-08-16 14:04 UTC, MingcongBai commented
@jiegec Thanks!