Pipewire survey 20230501
AOSC-Dev/aosc-os-abbs pull request #4534
Opened 2023-05-01 20:15 UTC by OriginCode

Topic Description
-----------------

Update pipewire-related packages

Package(s) Affected
-------------------

`pipewire` 0.3.70
`wireplumber` 0.4.14

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2023-05-03 23:40 UTC, OriginCode commented
LGTM on amd64:
![圖片](https://user-images.githubusercontent.com/17294071/236073968-56e75ba4-67f3-414a-8520-1f692cf2b806.png)
![圖片](https://user-images.githubusercontent.com/17294071/236073993-262abaf6-dd2c-45f9-a1f0-1f5401a71085.png)

2023-05-04 06:06 UTC, MingcongBai requested changes

2023-05-04 06:06 UTC, MingcongBai commented on runtime-devices/libcamera/autobuild/beyond
> +# No IPA modules are installed on architecures other than amd64 and arm64 by default
Typo at "architecures."

2023-05-04 06:12 UTC, MingcongBai approved these changes

2023-05-04 06:28 UTC, merged