topgrade: add new package
AOSC-Dev/aosc-os-abbs pull request #4536
Opened 2023-05-04 09:20 UTC by Nyovelt

Topic Description
-----------------
topgrade: add new package
- Disable firmware and apt updates

Package(s) Affected
-------------------

Security Update?
----------------

```
pkg1 pkg2 pkg3 ...
```

-->

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2023-05-04 09:20 UTC, Nyovelt commented
![image](https://user-images.githubusercontent.com/18253926/236163243-df9db61a-5303-406c-a4c3-84604b3f41e5.png)

2023-05-04 09:35 UTC, MingcongBai approved these changes

2023-05-04 09:35 UTC, MingcongBai requested changes

2023-05-04 09:35 UTC, MingcongBai commented on app-admin/topgrade/autobuild/patches/disable_firmware_and_apt_updates.patch
Please rename this file according to our Styling Manual.

2023-05-05 00:30 UTC, Nyovelt commented on app-admin/topgrade/autobuild/patches/disable_firmware_and_apt_updates.patch
Renamed

2023-05-05 05:34 UTC, MingcongBai approved these changes

2023-05-05 15:51 UTC, merged