newpkg: fio-3.34
AOSC-Dev/aosc-os-abbs pull request #4542
Opened 2023-05-11 15:36 UTC by Nyovelt

Topic Description
-----------------

newpkg: fio-3.34

fio is a flexible I/O tester 

Package(s) Affected
-------------------

Security Update?
----------------

```
pkg1 pkg2 pkg3 ...
```

-->

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2023-05-11 17:01 UTC, Nyovelt commented
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/18253926/800f8be3-2863-49a1-8000-6e0a85fe1106)

2023-05-11 17:58 UTC, MingcongBai requested changes

2023-05-11 17:58 UTC, MingcongBai commented on app-benchmarks/fio/autobuild/build
> +make \
Why is there a slash after `make`?

2023-05-11 17:58 UTC, MingcongBai commented on app-benchmarks/fio/autobuild/build
> +    --prefix=/usr \
Why the slash after the last parameter.

2023-05-11 17:58 UTC, MingcongBai commented on app-benchmarks/fio/autobuild/build
> +    mandir=/usr/share/man \
Ditto.

2023-05-11 17:58 UTC, MingcongBai commented on app-benchmarks/fio/autobuild/defines
> +PKGDES="A flexible I/O tester"
What does "flexible" even mean? Please be more descriptive.

2023-05-14 17:41 UTC, MingcongBai requested changes

2023-05-14 17:41 UTC, MingcongBai commented on app-benchmarks/fio/autobuild/defines
> +PKGDES="An I/O tester and benchmark tool that is used to simulate various I/O workloads."
Please remove period point at the end of the description.

2023-05-15 04:58 UTC, MingcongBai approved these changes

2023-06-14 04:03 UTC, closed without merging