plocate: new, 1.1.18
AOSC-Dev/aosc-os-abbs pull request #4559
Opened 2023-05-24 07:20 UTC by leedagee

Topic Description
-----------------
plocate is another locate(1) implementation that runs faster than mlocate.

upstream: https://plocate.sesse.net/

Security Update?
----------------

No

Build Order
-----------

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2023-05-24 08:45 UTC, CamberLoid requested changes

2023-05-24 08:45 UTC, CamberLoid commented on app-utils/plocate/autobuild/defines
> +PKGDEP__RETRO=""
`PKGDEP__RETRO` is not required in stable branch.
```suggestion

```

2023-05-24 08:45 UTC, CamberLoid commented on app-utils/plocate/autobuild/patches/0001-missing-inttypes-h-include.patch
According to our [patches guidelines](https://wiki.aosc.io/developer/packaging/known-patch-release-rules/), you may want to mention where did you get the patch from.

2023-05-24 08:45 UTC, CamberLoid commented on app-utils/plocate/spec
> +REL=1
Unlike Arch Linux, we start revision number from 0, which means you can omit this line when firstly introducing this package or updating.

```suggestion

```

2023-05-24 08:45 UTC, CamberLoid commented on app-utils/plocate/autobuild/overrides/etc/updatedb.conf
Why override configurations?

2023-05-24 08:45 UTC, CamberLoid commented on app-utils/plocate/autobuild/patches/0001-missing-inttypes-h-include.patch
Something like `0001-Fedora-blah.patch` or `0002-Upstream-blah.patch`, otherwise you need to add some messages in the patch file.

2023-05-24 08:47 UTC, leedagee commented on app-utils/plocate/autobuild/overrides/etc/updatedb.conf
The upstream does not provide a default one.

2023-05-24 08:49 UTC, leedagee commented on app-utils/plocate/autobuild/patches/0001-missing-inttypes-h-include.patch
I wrote it. I'll add some messages.

2023-05-24 11:57 UTC, CamberLoid commented on app-utils/plocate/autobuild/overrides/etc/updatedb.conf
Copy.

2023-05-24 11:58 UTC, CamberLoid commented on app-utils/plocate/autobuild/defines
> +PKGDEP="liburing" # enable io_uring feature for better performance
Just a reminder: In AOSC, we include dependency as much as possible

2023-05-25 14:41 UTC, CamberLoid requested changes

2023-05-25 14:41 UTC, CamberLoid commented on app-utils/plocate/autobuild/overrides/usr/bin/locate
This link may not be an override. Create link in "beyond" instead.

2023-05-26 10:38 UTC, CamberLoid requested changes

2023-05-26 10:38 UTC, CamberLoid commented on app-utils/plocate/autobuild/beyond
> +ln -s plocate "$PKGDIR"/usr/bin/locate
```suggestion
ln -vs plocate "$PKGDIR"/usr/bin/locate
```

Increase verbosity

2023-05-26 10:40 UTC, CamberLoid requested changes

2023-05-26 10:40 UTC, CamberLoid commented on app-utils/plocate/autobuild/beyond
> +ln -s plocate "$PKGDIR"/usr/bin/locate
```suggestion
ln -vs plocate "$PKGDIR"/usr/bin/locate
```

Increase verbosity

2023-06-07 05:21 UTC, CamberLoid requested changes

2023-06-07 05:21 UTC, CamberLoid commented on app-utils/plocate/autobuild/beyond
> +chown -v 0:212 \
```suggestion
abinfo "Changing ownership and mod of executable ..."
chown -v 0:212 \
```

2023-06-07 05:21 UTC, CamberLoid commented on app-utils/plocate/autobuild/beyond
> +ln -vs plocate "$PKGDIR"/usr/bin/locate
```suggestion
abinfo "Creating symbolic links to locate ..."
ln -vs plocate "$PKGDIR"/usr/bin/locate
```

2023-06-07 05:24 UTC, CamberLoid submitted a review, later dismissed

2023-06-10 05:52 UTC, CamberLoid commented
Upstream released new tag 1.1.19. Updating now

2023-07-20 03:00 UTC, MingcongBai submitted a review, later dismissed

2023-08-08 12:15 UTC, MingcongBai approved these changes

2023-08-10 03:15 UTC, merged