cwm: new, 7.1
AOSC-Dev/aosc-os-abbs pull request #4568
Opened 2023-06-01 01:28 UTC by YisuiDenghua

Topic Description
-----------------

Package(s) Affected
-------------------

Security Update?
----------------

```
pkg1 pkg2 pkg3 ...
```

-->

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2023-06-01 06:29 UTC, CamberLoid requested changes

2023-06-01 06:29 UTC, CamberLoid commented on desktop-wm/cwm/spec
> +CHKUPDATE="anitya::id=123783"
Add a blank line

2023-06-03 02:46 UTC, cthbleachbit requested changes

2023-06-03 02:46 UTC, cthbleachbit commented on desktop-wm/cwm/autobuild/defines
> +PKGDEP="x11-lib bison"
bison 肯定不会是运行时依赖，需要挪到 BUILDDEP

2023-06-03 08:38 UTC, YisuiDenghua commented on desktop-wm/cwm/autobuild/defines
> +PKGDEP="x11-lib bison"
谢谢，已将 `bison` 从 `PKGDEP` 移至 `BUILDDEP`。

2023-06-03 14:39 UTC, CamberLoid commented
Independently verified cwm functionality on amd64/Hyper-V environment. 
Awaiting testing on other archs

2023-06-04 16:32 UTC, CamberLoid commented
Independently verified cwm functionality on ricsv54/qemu-riscv64-system environment.

2023-06-05 03:44 UTC, CamberLoid approved these changes, later dismissed

2023-06-05 03:47 UTC, MingcongBai requested changes

2023-06-05 03:47 UTC, MingcongBai commented on desktop-wm/cwm/autobuild/defines
> +
Trailing blank line.

2023-06-05 03:47 UTC, MingcongBai commented on desktop-wm/cwm/autobuild/defines
> +BUILDDEP="pkg-config bison"
Both should be omitted as they are part of `devel-base`.

2023-06-05 03:47 UTC, MingcongBai commented on desktop-wm/cwm/autobuild/defines
> +PKGDES="A lightweight and efficient window manager for X11"
"Efficient" is an empty word, I would just cut it. Perhaps consider rewriting the description to showcase the key features of this window manager when compared to other "lightweight" options.

2023-06-05 03:47 UTC, MingcongBai commented on desktop-wm/cwm/autobuild/overrides/usr/share/xsessions/cwm.desktop
> +Comment=A clean and simple window manager for X inspired by evilwm
Why is this inconsistent with the package description? Also, in this case, I would take the "Comment" field to describe what CWM stands for.

2023-06-05 03:47 UTC, MingcongBai commented on desktop-wm/cwm/spec
> +SRCS="tbl::https://github.com/leahneukirchen/cwm/archive/refs/tags/v$VER.tar.gz"
I would recommend using `git::` source, as these tarballs (automatically generated by GitHub) can be overwritten unintentionally.

2023-06-05 05:03 UTC, cthbleachbit approved these changes, later dismissed

2023-06-06 13:14 UTC, MingcongBai approved these changes

2023-06-06 14:17 UTC, CamberLoid approved these changes

2023-06-07 06:01 UTC, merged