Distrobox 1.4.2.1
AOSC-Dev/aosc-os-abbs pull request #4569
Opened 2023-06-01 04:32 UTC by YisuiDenghua

Topic Description
-----------------

Wrapper around podman or docker to create and start containers

Package(s) Affected
-------------------

distrobox

Security Update?
----------------

```
pkg1 pkg2 pkg3 ...
```

-->

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2023-06-01 05:00 UTC, Artoria2e5 commented
Distrobox looks good, not going to approve because I've not been packaging for too long

cwm: is bison a runtime dep or a build dep?

2023-06-01 05:11 UTC, OriginCode commented
PR title should be in the format `<package-name>: new, <version>`.

主題 PR 名應使用 `<包名>: new, <版本>` 的格式。

2023-06-01 05:16 UTC, eatradish requested changes
Please clean up your commit timeline

`cwm: new, 7.1` is not relevant for this PR

2023-06-01 05:28 UTC, YisuiDenghua commented
> Please clean up your commit timeline
> 
> `cwm: new, 7.1` is not relevant for this PR

Thanks, just deleted `cwm: new 7.1`

2023-06-01 05:28 UTC, YisuiDenghua commented
> PR title should be in the format `<package-name>: new, <version>`.
> 
> 主題 PR 名應使用 `<包名>: new, <版本>` 的格式。

Fixed, thanks.

2023-06-01 05:30 UTC, eatradish submitted a review, later dismissed

2023-06-01 05:54 UTC, YisuiDenghua commented
> Distrobox looks good, not going to approve because I've not been packaging for too long
> 
> cwm: is bison a runtime dep or a build dep?

Sorry for using Chinese. cwmrc 的 parser 是 bison 生成的

2023-06-02 10:34 UTC, Artoria2e5 commented
> cwmrc 的 parser 是 bison 生成的

我看了 Makefile, 应该只是编译时依赖，构建的时候 parse.y 变成 parse.c 变成 parse.o，运行的时候用不上

PKGDEP -> BUILDDEP

2023-06-03 02:40 UTC, cthbleachbit requested changes

2023-06-03 02:40 UTC, cthbleachbit commented on app-emulation/distrobox/autobuild/build
> +    -C "$SRCDIR"/install --prefix "$PKGDIR"/usr
```suggestion
bash "$SRCDIR"/install --prefix "$PKGDIR"/usr
```

需要修正：`-C` 是用于编写补全支持的，不是这样让你调用脚本的。bash 后面可以直接跟脚本文件名

2023-06-03 02:40 UTC, cthbleachbit commented on app-emulation/distrobox/autobuild/defines
> +ABTYPE=self
无需修正：`ABTYPE=self` 在已经手写了 build 的时候可以不写

2023-06-07 06:10 UTC, CamberLoid requested changes

2023-06-07 06:10 UTC, CamberLoid commented on app-emulation/distrobox/spec
> +SRCS="tbl::https://github.com/89luca89/distrobox/archive/refs/tags/$VER.tar.gz"
Use `git::https...` source instead

2023-06-07 06:10 UTC, CamberLoid commented on app-emulation/distrobox/autobuild/defines
> +PKGDEP="docker"
My opinion: add `bash` as PKGDEP, since this is shell script
```suggestion
PKGDEP="docker bash"
```

2023-06-07 07:24 UTC, Artoria2e5 commented on app-emulation/distrobox/autobuild/defines
> +PKGDEP="docker"
记得她之前问，群里有人说 ab 都需要 bash 不可能没有(
https://t.me/c/1096355081/710708

2023-06-07 20:56 UTC, cthbleachbit approved these changes
Tested to work with podman privileged containers. Rootless podman seems to be broken in itself, so skipping testing with rootless containers...

2023-08-15 12:57 UTC, CamberLoid approved these changes

2023-08-15 12:57 UTC, merged