bash-config: /etc/profile.d cleanup survey
AOSC-Dev/aosc-os-abbs pull request #4580
Opened 2023-06-15 00:17 UTC by leedagee

Topic Description
-----------------

[bash-config#23](https://github.com/AOSC-Dev/bash-config/pull/23) fixed a bash initialization related bug, while it reveals a wide range of flaws in our packaging work. This topic moves the misused profile.d scripts to correct directories for a consistent behavior.

Package(s) Affected
-------------------

Currently, these package provides /etc/profile.d:

- [ ] 32subsystem
- [ ] apache-ant
- [ ] apache-maven
- [ ] arduino-mk
- [ ] autojump-rs
- [x] ~bash-completion~
- [x] ~bash-startup~
- [ ] byobu
- [ ] cuda
- [ ] dotnet-host
- [ ] elfutils
- [ ] firefox
- [ ] flatpak
- [ ] fzf
- [ ] gawk
- [ ] gpm
- [ ] gradle
- [ ] grc
- [ ] hook-uname
- [ ] ksshaskpass
- [ ] libreoffice
- [ ] mercurial
- [ ] midori
- [ ] mingw+w64
- [ ] mozilla-common
- [x] nvm
- [ ] oma
- [ ] openjdk
- [ ] openjdk-11
- [ ] openjdk-8
- [ ] perl
- [ ] powershell
- [ ] qt-5
- [ ] ruby
- [ ] seahorse
- [ ] snapd
- [ ] stackless-env
- [ ] thunderbird
- [ ] udisks
- [ ] vte
- [ ] wezterm
- [ ] x11-ssh-askpass

(Strike-through means the package uses /etc/profile.d correctly, this survey topic is not applicable.)

Security Update?
----------------

No 

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2023-06-15 03:06 UTC, cthbleachbit submitted a review, later dismissed

2023-06-15 03:06 UTC, cthbleachbit commented on lang-js/nvm/autobuild/build
> +install -Dvm644 nvm_aosc.sh "${PKGDIR}/etc/bashrc.d/30-nvm.sh"
Any rationale on why this export should be a bash specifc thing? Looks like NVM_DIR should be set regardless of default shell choice.

Also note that desktop environments generally don't source `/etc/bashrc.d` but would include `/etc/profile.d`. If this environment variable were to be used by any graphical applications (say, an IDE or a graphical text editor) they will no longer see `NVM_DIR` in their environment.

2023-06-15 03:06 UTC, cthbleachbit commented on lang-js/nvm/autobuild/build
> +ln -vs ../../bashrc.d/30-nvm.sh "${PKGDIR}/etc/zsh/zshrc.d/30-nvm"
Just leave it in `/etc/profile.d`...

2023-08-08 12:14 UTC, MingcongBai requested changes

2023-08-08 12:14 UTC, MingcongBai commented on lang-js/nvm/autobuild/build
> +ln -vs /usr/share/nvm/nvm.sh "${PKGDIR}/etc/bashrc.d/30-nvm"
Use relative paths here.

2023-08-08 12:14 UTC, MingcongBai commented on lang-js/nvm/autobuild/build
> +install -Dvm644 nvm.sh "${PKGDIR}/usr/share/nvm/nvm.sh"
Missing absolute path "$SRCDIR"/...

2023-08-08 12:14 UTC, MingcongBai commented on lang-js/nvm/autobuild/build
> +cp -v *.md "${PKGDIR}/usr/share/doc/nvm/"
... Until here.

2023-08-08 12:14 UTC, MingcongBai commented on lang-js/nvm/autobuild/build
> +cp -v *.md "${PKGDIR}/usr/share/doc/nvm/"
Also, you could have just used `install -Dvm644 "$SRCDIR"/*.md -t "$PKGDIR"/usr/share/doc/nvm/`.

2023-08-18 15:43 UTC, leedagee commented
powershell is cherry picked from openssl-3.3
wezterm is left unchanged

2023-09-03 08:18 UTC, MingcongBai approved these changes

2023-09-03 08:24 UTC, merged