owntone: new, 28.6
AOSC-Dev/aosc-os-abbs pull request #4586
Opened 2023-06-20 02:27 UTC by StephDC

Topic Description
-----------------

Add new package `owntone`, a DAAP server that replaces `forked-daapd` dropped a few months ago on https://github.com/AOSC-Dev/aosc-os-abbs/commit/44454f30bed613f9e9c64071bba6e801a278a730 .

Package(s) Affected
-------------------

`owntone`: new, 28.6

Security Update?
----------------
No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2023-06-20 02:29 UTC, StephDC commented
![owntone](https://github.com/AOSC-Dev/aosc-os-abbs/assets/9734616/707dc5ea-ca10-4a5b-986d-8e955495b854)

Service tested working.

2023-06-22 13:33 UTC, MingcongBai requested changes

2023-06-22 13:33 UTC, MingcongBai commented on app-multimedia/owntone/autobuild/defines
> +PKGDES="Linux/FreeBSD DAAP (iTunes) and MPD media server with support for AirPlay 1 and 2 speakers (multiroom), Apple Remote (and compatibles), Chromecast, Spotify and internet radio"
This is way too long, make it to the point.

2023-06-22 13:33 UTC, MingcongBai commented on app-multimedia/owntone/spec
> +CHKSUM="sha256::5604d35d2a205cd7dee5b708969e2da96904600c2f5743beb207f61bb86bdc05"
Missing CHKUPDATE.

2023-06-23 12:40 UTC, MingcongBai approved these changes, later dismissed

2023-07-14 08:08 UTC, MingcongBai approved these changes

2023-07-14 08:39 UTC, merged