[DRAFT] meta: updated security-vulnerabilities-report
AOSC-Dev/aosc-os-abbs pull request #4601
Opened 2023-07-04 06:51 UTC by CamberLoid

Topic Description
-----------------

This topic/PR will update the current security vulnerabilities report template. 

While in draft status, the content is subject to be reviewed, changed and force-pushed frequently. 

Package(s) Affected
-------------------

N/A

Security Update?
----------------

Kind of

2023-07-04 07:03 UTC, MingcongBai requested changes

2023-07-04 07:03 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +# This is the draft of security vulnerabilities bug report, next version.
Leave these two lines for your PR comment.

2023-07-04 07:03 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +# This field is designed in case of the reporting issue is in a component of our package.
This field is designed for listing affected package(s) and component(s).
E.g.: libX11 in `x11-lib`.

No need for further explanation.

2023-07-04 07:03 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +      - 'Critical'
Add a "0-day" option, meaning that the vulnerability is already being used for malicious activities.

2023-07-04 07:03 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +    description: 'Comma-separated list of CVE IDs. Fill N/A if no CVE ID is assigned.'
Fill in "N/A" if no CVE ID is assigned.

2023-07-04 07:03 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +      Select the severity of reporting vulnerabilities. Refer to our wiki for details.
reported vulnerability(ies)

2023-07-04 07:03 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +      Select the severity of reporting vulnerabilities. Refer to our wiki for details.
What Wiki?

2023-07-04 07:03 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +      Choose the highest in case of multiple vulnerabilities.
Choose the highest severity out of the IDs listed.

2023-07-04 07:03 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +    label: 'Other security advisories'
Other security advisory IDs

2023-07-04 07:03 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +    description: 'Other security advisories, mailing list archive or original bug report. Please list with references to each ID.'
Other security advisory(ies), mailing list message(s), or bug report(s).

2023-07-04 07:03 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +    description: 'Other security advisories, mailing list archive or original bug report. Please list with references to each ID.'
reference(s)

2023-07-04 07:03 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +      - Links to original mail list archive;
Mailing list message

2023-07-04 07:03 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +      - Links to original issue, if applicable
Bug report *

2023-07-04 07:03 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +      Original mailing list message(s) or other description may list here.
may be listed here *

2023-07-04 07:03 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +      You may also include these following supplemental details:
You may also include supplemental details *

2023-07-04 07:03 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +      - Bug introduced in which version
Version where the bug was introduced

2023-07-04 07:03 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +      - Available PoCs (Required if the reporting target is AOSC-developed component)
"required," no need to capitalise first letter in parenthetical expressions

2023-07-04 07:03 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +      - Available PoCs (Required if the reporting target is AOSC-developed component)
is an AOSC-developed component

2023-07-04 07:03 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +      - Linked CWE if available.
CWE (Common Weakness Enumeration)

2023-07-04 07:03 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +      - Linked CWE if available.
Leave period point out - unless you want to use it on each list item.

2023-07-04 07:03 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +      Examples (for GNU tar):
This is too much work for a single CVE and risks circumvention in the long run.

2023-07-04 07:03 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +    label: 'Fixed versions or patches'
This was already done with title + label, this is not necessary.

2023-07-04 07:11 UTC, CamberLoid commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +# This is the draft of security vulnerabilities bug report, next version.
(will remove when merging)

2023-07-04 08:05 UTC, CamberLoid commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +    label: 'Fixed versions or patches'
May be called `solutions`? This field is intended to replace original `Patches`.

2023-07-05 07:28 UTC, MingcongBai requested changes

2023-07-05 07:28 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +# This is the draft of security vulnerabilities bug report, next version, revision 4.1
Drop lines 1-3 and move it to PR body. This is not necessary.

2023-07-05 07:28 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +      - 'Critical/0-day'
These are not the same, list 0-day as the highest severity.

2023-07-05 07:28 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +      Enter N/A to indicate that a regular upgrade to latest version is favoured. Otherwise, fill this field with one or more of the following:
Favored *. Pick one between American and British English.

2023-07-05 07:28 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +      - Patch(es), if a backport is advised or no new upstream release is available
comma before or

2023-07-05 07:28 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +      - Specific version, if upgrading to latest requires extra attention (please specify)
A specific non-latest version, if upgrading to the latest version may cause issue (please specify)

2023-07-05 07:28 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +      - Workaround, if no fixes from upstream is released as the report submitted
Other suggestions, such as a workaround/Errata documentation, if no fix is yet available

2023-07-24 14:52 UTC, MingcongBai requested changes

2023-07-24 14:52 UTC, MingcongBai commented on .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
> +      Additionally, `0-day` is used to indicate that the reporting vulnerabilities is being exploited for malicious activities. This is the highest severity rating regardless of its original severity
Emphasize, "is already being exploited"

2023-07-24 15:15 UTC, MingcongBai approved these changes

2023-07-24 15:15 UTC, merged