racket: update to 8.9
AOSC-Dev/aosc-os-abbs pull request #4633
Opened 2023-07-21 02:32 UTC by OriginCode

Topic Description
-----------------

Update Racket to 8.9

Package(s) Affected
-------------------

`racket` 8.9

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2023-07-21 03:12 UTC, OriginCode commented
LGTM on amd64:
![圖片](https://github.com/AOSC-Dev/aosc-os-abbs/assets/17294071/88135c20-5194-441b-8e6d-163e4e843755)

2023-07-21 17:22 UTC, MingcongBai requested changes

2023-07-21 17:22 UTC, MingcongBai commented on lang-lisp/racket/autobuild/beyond
> +ln -sv /usr/share/racket/pkgs/icons/plt-16x16.png "$PKGDIR"/usr/share/icons/hicolor/16x16/apps/drracket.png
Use relative path here.

2023-07-24 09:54 UTC, MingcongBai approved these changes

2023-07-24 09:55 UTC, merged