zotero: update to 6.0.26
AOSC-Dev/aosc-os-abbs pull request #4690
Opened 2023-08-25 14:44 UTC by Nyovelt

Topic Description
-----------------

Zotero: update to `6.0.26`
- some add-ons are not working on current version (`6.0.3`)

Package(s) Affected
-------------------

Security Update?
----------------

No

Build Order
-----------

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2023-08-25 14:55 UTC, Nyovelt commented
Works on my laptop

![Screenshot_20230825_104624](https://github.com/AOSC-Dev/aosc-os-abbs/assets/18253926/12947798-592b-4f24-9959-5a2d404dd0df)

![Screenshot_20230825_105521](https://github.com/AOSC-Dev/aosc-os-abbs/assets/18253926/9aab8882-978b-493e-8dfa-6e948429338c)

2023-08-25 16:52 UTC, Nyovelt commented
AArch64 build success

![](https://webresources.aaaab3n.moe/share/Screenshot_20230825_124557.png)

2023-08-25 19:13 UTC, Nyovelt commented
AArch64 build success

<img width="1138" alt="图片" src="https://github.com/AOSC-Dev/aosc-os-abbs/assets/18253926/1493526d-80ce-435b-a5f7-81b6cfc2ca51">

2023-09-02 09:13 UTC, MingcongBai requested changes

2023-09-02 09:13 UTC, MingcongBai commented on app-productivity/zotero/spec
> +_STANDALONE_VER=6.0.26-hotfix
You should use `${PKGVER}-hotfix` instead.

2023-09-07 07:44 UTC, MingcongBai approved these changes

2023-09-07 16:47 UTC, merged