dmenu: update to 5.2
AOSC-Dev/aosc-os-abbs pull request #4707
Opened 2023-09-11 02:56 UTC by OriginCode

Topic Description
-----------------

Update dmenu, fix dbg package splitting problem.

Package(s) Affected
-------------------

`dmenu` 5.2

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2023-09-11 07:07 UTC, MingcongBai requested changes

2023-09-11 07:07 UTC, MingcongBai commented on app-utils/dmenu/autobuild/defines
> +ABSPLITDBG=0
Why?

2023-09-11 07:08 UTC, OriginCode commented on app-utils/dmenu/autobuild/defines
> +ABSPLITDBG=0
![圖片](https://github.com/AOSC-Dev/aosc-os-abbs/assets/17294071/acdfa66d-e1ee-467b-a5eb-9a4287be1402)

2023-09-11 07:09 UTC, MingcongBai commented on app-utils/dmenu/autobuild/defines
> +ABSPLITDBG=0
Well, then it means that the flags weren't passed in properly, unless it's an ELF-less package.

2023-09-12 05:45 UTC, MingcongBai approved these changes

2023-09-12 05:49 UTC, OriginCode commented
LGTM on amd64:
![圖片](https://github.com/AOSC-Dev/aosc-os-abbs/assets/17294071/1481bcd4-e5ae-420e-a4e2-a880bb1cec8b)

2023-09-12 05:49 UTC, merged