systemd-boot-friend: update to 0.26.1
AOSC-Dev/aosc-os-abbs pull request #4737
Opened 2023-09-22 23:40 UTC by OriginCode

Topic Description
-----------------

Update systemd-boot-friend

Package(s) Affected
-------------------

`systemd-boot-friend` 0.26.1

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2023-09-23 00:20 UTC, OriginCode commented
LGTM on amd64:
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/17294071/a4d2e683-22b3-4bcc-bb61-64a9577be865)

2023-09-23 19:21 UTC, OriginCode commented
LGTM on amd64:
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/17294071/cc8b9f9b-ee9d-4f4b-8483-d5cfdf783f12)

2023-09-23 21:16 UTC, MingcongBai requested changes

2023-09-23 21:16 UTC, MingcongBai commented on app-admin/systemd-boot-friend/autobuild/defines
> +NOLTO__LOONGSON3=1
Add:

```
FIXME: Segfaults during linkage.
```

2023-09-24 20:33 UTC, RedL0tus approved these changes

2023-09-25 15:54 UTC, MingcongBai approved these changes

2023-09-25 17:50 UTC, merged