yazi: new, 0.1.5
AOSC-Dev/aosc-os-abbs pull request #4883
Opened 2023-12-07 09:53 UTC by eatradish

Topic Description
-----------------

yazi: new, 0.1.5

Package(s) Affected
-------------------

yazi: new, 0.1.5

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2023-12-07 10:15 UTC, eatradish commented
`riscv64` does not support `LuaJIT` :

```
  lj_arch.h:73:2: error: #error "No support for this architecture (yet)"
     73 | #error "No support for this architecture (yet)"
```

2023-12-07 17:44 UTC, MingcongBai commented
> `riscv64` does not support `LuaJIT` :
> 
> ```
>   lj_arch.h:73:2: error: #error "No support for this architecture (yet)"
>      73 | #error "No support for this architecture (yet)"
> ```

Just skip it for now.

2023-12-07 23:13 UTC, MingcongBai requested changes

2023-12-07 23:13 UTC, MingcongBai commented on app-utils/yazi/autobuild/defines
> +PKGDES="An terminal file manager"
A file manager for terminals

2023-12-07 23:13 UTC, MingcongBai commented on app-utils/yazi/autobuild/defines
> +# mlua-sys must be compiled with gcc
Mark this as `# FIXME:`

2023-12-08 15:54 UTC, MingcongBai requested changes

2023-12-08 15:54 UTC, MingcongBai commented on app-utils/yazi/autobuild/defines
> +PKGDES="A file manager for terminal"
for terminals

2023-12-09 04:55 UTC, MingcongBai approved these changes

2023-12-09 08:44 UTC, merged