sqlmap: new, 1.7.12
AOSC-Dev/aosc-os-abbs pull request #4908
Opened 2023-12-13 05:41 UTC by Suyun114

Topic Description
-----------------

sqlmap: new, 1.7.12

Package(s) Affected
-------------------

```
app-penetration/sqlmap
```

Security Update?
----------------

No

Test Build(s) Done
------------------

- [ ] Architecture-independent `noarch`

2023-12-13 05:44 UTC, MingcongBai requested changes

2023-12-13 05:44 UTC, MingcongBai commented on app-penetration/sqlmap/autobuild/defines
> +ABHOST=noarch
Missing newline. Please check your editor configuration.

2023-12-13 05:44 UTC, MingcongBai commented on app-penetration/sqlmap/spec
> +CHKUPDATE="anitya::id=14901"
Missing newline. Please check your editor configuration.

2023-12-13 05:44 UTC, MingcongBai commented on app-penetration/sqlmap/spec
> +SRCS="tbl::https://github.com/sqlmapproject/sqlmap/archive/$VER.tar.gz"
Please use Git source instead, as automatically generated tarballs may be re-generated - making them unreliable in the long run.

```
SRCS="git::commit=tags/$VER::https://github.com/sqlmapproject/sqlmap"
CHKSUMS="SKIP"
```

2023-12-13 05:44 UTC, MingcongBai commented on app-penetration/sqlmap/autobuild/defines
> +PKGSEC=web
Web?

2023-12-13 05:44 UTC, MingcongBai commented on app-penetration/sqlmap/autobuild/defines
> +PKGSEC=web
This is likely better described in the `database` section.

2023-12-13 05:44 UTC, MingcongBai commented on app-penetration/sqlmap/autobuild/defines
> +PKGSUG="perl"
Why not DEP?

2024-01-23 12:21 UTC, jiegec commented
1.8 is out.

2024-01-23 12:21 UTC, jiegec commented on app-penetration/sqlmap/autobuild/overrides/usr/bin/sqlmap
> +python sqlmap.py "\$@"
What if we directly run /opt/sqlmap.py?

2024-01-24 13:14 UTC, closed without merging