libplist update and fix ftbfs
AOSC-Dev/aosc-os-abbs pull request #4980
Opened 2023-12-22 08:47 UTC by HouLiXieBuRou

Topic Description
-----------------

- liplist: update to 2.3.0
    x The job requires this package to be updated and ftbfs a bit whether it is
    updated or not. The source download path was changed because the old source
    download path didn't seem to be labeled for the package, resulting in an
    error at build time "configure: error : PACKAGE_VERSION is not defined.
    Make sure to cnfigure a source tree out from git or that .tarball-version
    is present"
    
Package(s) Affected
-------------------

- libplist: 2.3.0

Security Update?
----------------

No

Build Order
-----------

```
#buildit libplist
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`

**Second Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2023-12-22 21:31 UTC, MingcongBai requested changes

2023-12-22 21:31 UTC, MingcongBai commented on runtime-common/libplist/autobuild/defines
> +# FIXME: Default to /usr/bin/cython3 path
Defaults, you are talking about the upstream.

2023-12-28 10:24 UTC, MingcongBai approved these changes

2023-12-29 08:25 UTC, HouLiXieBuRou commented
lisplist 
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/e67358ee-5051-4484-bcd4-bd412e2d32b3)
libimobiledevice
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/11c34917-542e-4a48-b217-5202599156bb)
gvfs（Binary files with rdependencies ）
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/aa5e1f2c-bb7d-4504-94c0-2f3ec78b31b5)
solid
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/6e1f8d9c-ef64-43cd-996a-617bcc5b55e3)
owntone
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/9f22a633-fdb0-4da6-bc70-b449db5b3704)
libusbmuxd
this package is a reverse dependency of libimobiledevice
libgpod
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/c93371f2-4af7-419c-815e-379d69deb623)
kodi 
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/d51b28d5-3d26-46d7-8810-e9ecbad7f538)

2023-12-29 08:25 UTC, merged