starship: update to 1.17.0
AOSC-Dev/aosc-os-abbs pull request #5024
Opened 2023-12-29 06:31 UTC by eatradish

Topic Description
-----------------

- starship: update to 1.17.0

Package(s) Affected
-------------------

- starship: 1.17.0

Security Update?
----------------

No

Build Order
-----------

```
#buildit starship
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`

**Second Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2023-12-29 06:31 UTC, eatradish commented
@aosc-buildit-bot build

2023-12-29 06:33 UTC, eatradish commented
@aosc-buildit-bot build

2023-12-29 06:34 UTC, MingcongBai submitted a review, later dismissed

2023-12-30 08:43 UTC, eatradish commented
@aosc-buildit-bot build mips64r6el

2024-01-01 14:43 UTC, eatradish commented
@aosc-buildit-bot build amd64

2024-01-01 14:44 UTC, eatradish commented
@aosc-buildit-bot build amd64

2024-01-01 14:55 UTC, eatradish commented
@aosc-buildit-bot build amd64

2024-01-01 14:57 UTC, eatradish commented
@aosc-buildit-bot build amd64

2024-01-01 15:06 UTC, eatradish commented
@aosc-buildit-bot build amd64

2024-01-01 15:06 UTC, eatradish commented
@aosc-buildit-bot build amd64

2024-01-01 15:16 UTC, eatradish commented
@aosc-buildit-bot build amd64

2024-01-01 15:23 UTC, eatradish commented
@aosc-buildit-bot build amd64

2024-01-01 15:58 UTC, eatradish commented
@aosc-buildit-bot build amd64

2024-01-01 15:59 UTC, eatradish commented
@aosc-buildit-bot build amd64

2024-01-03 02:29 UTC, eatradish commented
@aosc-buildit-bot build

2024-01-03 03:28 UTC, MingcongBai requested changes

2024-01-03 03:28 UTC, MingcongBai commented on app-utils/starship/autobuild/defines
>  CARGO_AFTER__LOONGSON3="--no-default-features --features gix-faster"
Add a FIXME note here explaining why.

2024-01-03 03:36 UTC, MingcongBai approved these changes

2024-01-03 03:37 UTC, merged

2024-01-03 03:37 UTC, eatradish commented
@aosc-buildit-bot build