XFCE Survey, 2023 Dec.
AOSC-Dev/aosc-os-abbs pull request #5044
Opened 2023-12-29 08:50 UTC by Fearyncess

Topic Description
-----------------

- xfce4-taskmanager: update to 1.5.6

- xfburn: update to 0.7.0

- xfce4-terminal: update to 1.1.1

- xfce4-panel-profiles: update to 1.0.14

- xfce4-dev-tools: update to 4.18.1

- xfdesktop: update to 4.18.1

- xfconf: update to 4.18.3

- xfce4-timer-plugin: update to 1.7.2

- thunar: update to 4.18.8

- xfce4-power-manager: update to 4.18.3

... and 95106 more commits
Package(s) Affected
-------------------

- xfce4-screensaver: 4.18.2
- xfce4-taskmanager: 1.5.6
- garcon: 4.18.1
- xfce4-appfinder: 4.18.1
- tumbler: 4.18.2
- libxfce4ui: 4.18.4
- xfce4-session: 1:4.18.3
- xfdesktop: 4.18.1
- orage: 4.18.0
- xfce4-notifyd: 0.9.3
- xfce4-pulseaudio-plugin: 0.4.8
- xfce4-calculator-plugin: 0.7.2
- xfce4-cpugraph-plugin: 1.2.10
- xfce4-netload-plugin: 1.4.1
- thunar: 4.18.8
- xfce4-weather-plugin: 0.11.1
- xfce4-mailwatch-plugin: 1.3.1
- xfce4-power-manager: 4.18.3
- mousepad: 0.6.1
- xfce4-notes-plugin: 1.10.0
- xfce4-panel: 1:4.18.5
- xfce4-datetime-plugin: 0.8.3
- xfce4-genmon-plugin: 4.2.0
- ristretto: 0.13.1
- xfce4-whiskermenu-plugin: 2.8.2
- xfce4-panel-profiles: 1.0.14
- xfce4-battery-plugin: 1.1.5
- xfce4-dev-tools: 4.18.1
- xfce4-fsguard-plugin: 1.1.3
- parole: 4.18.1
- xfconf: 4.18.3
- xfce4-terminal: 1.1.1
- gigolo: 0.5.3
- xfce4-screenshooter: 1.10.4
- xfce4-mpc-plugin: 0.5.3
- xfburn: 0.7.0
- catfish: 4.18.0
- xfce4-timer-plugin: 1.7.2
- xfce4-settings: 4.18.4
- xfce4-clipman-plugin: 1.6.5

Security Update?
----------------

No

Build Order
-----------

```
#buildit libxfce4ui mousepad xfce4-panel xfce4-genmon-plugin xfce4-appfinder garcon gigolo xfce4-mpc-plugin xfce4-notifyd xfce4-session xfce4-battery-plugin xfce4-fsguard-plugin xfce4-netload-plugin xfce4-calculator-plugin xfce4-datetime-plugin xfce4-whiskermenu-plugin xfce4-screenshooter xfce4-pulseaudio-plugin xfce4-settings xfce4-mailwatch-plugin xfce4-weather-plugin tumbler catfish xfce4-notes-plugin ristretto orage parole xfce4-clipman-plugin xfce4-screensaver xfce4-cpugraph-plugin xfce4-power-manager thunar xfce4-timer-plugin xfconf xfdesktop xfce4-dev-tools xfce4-panel-profiles xfce4-terminal xfburn xfce4-taskmanager
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`

**Second Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2023-12-29 08:54 UTC, Fearyncess commented
@aosc-buildit-bot build amd64

2023-12-29 08:58 UTC, eatradish commented
> @aosc-buildit-bot build amd64

为什么你只编译一个架构？

2023-12-29 09:01 UTC, Fearyncess commented
> > @aosc-buildit-bot build amd64
> 
> 为什么你只编译一个架构？

懒狗，等amd64走通，依赖没问题。

2023-12-29 10:28 UTC, Fearyncess reviewed
@aosc-buildit-bot build amd64

2023-12-30 11:50 UTC, Fearyncess reviewed
@aosc-buildit-bot build amd64

2023-12-30 11:58 UTC, eatradish commented
?

2023-12-30 11:59 UTC, eatradish commented
@aosc-buildit-bot build amd64

2023-12-30 17:02 UTC, Fearyncess reviewed
@aosc-buildit-bot build amd64

2024-01-21 08:30 UTC, MingcongBai requested changes

2024-01-21 08:30 UTC, MingcongBai commented on desktop-xfce/parole/spec
>  SRCS="git::commit=389d6a72b08f90c15a5a193c7da8f9df25575ec6::https://gitlab.xfce.org/apps/parole"
You probably haven't updated this yet.

2024-01-21 08:30 UTC, MingcongBai commented on desktop-xfce/xfce4-screensaver/spec
>  SRCS="git::commit=785a456fd843c574def813fdb616162812631ebf::https://gitlab.xfce.org/apps/xfce4-screensaver"
Update this actually.

2024-01-21 08:30 UTC, MingcongBai commented on runtime-desktop/gtk-layer-shell/autobuild/defines
> +ABTYPE=meson
Missing newline.

2024-01-21 08:30 UTC, MingcongBai commented on runtime-desktop/gtk-layer-shell/spec
> +CHKUPDATE="anitya::id=198568"
Missing newline.

2024-01-21 09:36 UTC, MingcongBai approved these changes, later dismissed

2024-01-23 10:11 UTC, MingcongBai requested changes

2024-01-23 10:11 UTC, MingcongBai commented on runtime-desktop/gtk-layer-shell/autobuild/defines
> +PKGDES="A library to write GTK applications that use Layer Shell."
Remove the period point at the end.

2024-01-23 10:11 UTC, MingcongBai commented on runtime-desktop/gtk-layer-shell/autobuild/defines
> +PKGDEP="gtk-3 wayland wayland-protocols gobject-introspection vala"
Are you sure that all these are runtime dependencies?

2024-01-23 10:53 UTC, Fearyncess commented on runtime-desktop/gtk-layer-shell/autobuild/defines
> +PKGDES="A library to write GTK applications that use Layer Shell."
i have sent the dot back home.

2024-01-23 14:43 UTC, MingcongBai approved these changes

2024-01-23 16:03 UTC, merged