stlink: update to 1.7.0
AOSC-Dev/aosc-os-abbs pull request #5078
Opened 2024-01-03 07:28 UTC by BC204

Topic Description
-----------------

- stlink: drop upstreamed patches

- stlink: drop Installation directories fix in prepare

- stlink: update to 1.7.0

Package(s) Affected
-------------------

- stlink: 1.7.0

Security Update?
----------------

No

Build Order
-----------

```
#buildit stlink
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-01-03 08:40 UTC, MingcongBai requested changes

2024-01-03 08:40 UTC, MingcongBai commented on app-devel/stlink/spec
>  SRCS="tbl::https://github.com/texane/stlink/archive/v$VER.tar.gz"
Please switch to Git source:

```
git::commit=tags/v$VER::https://github.com/texane/stlink
```

2024-01-03 08:40 UTC, MingcongBai commented on app-devel/stlink/spec
> +CHKSUMS="sha256::57ec1214905aedf59bee7f70ddff02316f64fa9ba5a9b6a3a64952edc5b65855"
And change this to:

```
CHKSUMS="SKIP"
```

2024-01-03 19:17 UTC, MingcongBai approved these changes

2024-01-04 02:22 UTC, BC204 commented
![截图 2024-01-04 10-21-24](https://github.com/AOSC-Dev/aosc-os-abbs/assets/109511245/c123e35d-d61d-4e55-9e58-0abaf993675d)

2024-01-04 02:22 UTC, merged