zerotier-one 1.12.2
AOSC-Dev/aosc-os-abbs pull request #5126
Opened 2024-01-11 18:08 UTC by Nyovelt

Topic Description
-----------------

- zerotier-one: update to 1.12.2
    Remove previous patch to improve performance

Package(s) Affected
-------------------

- zerotier-one: 1.12.2-1

Security Update?
----------------

No

Build Order
-----------

```
#buildit zerotier-one
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`

2024-01-11 18:10 UTC, Nyovelt commented
amd64
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/18253926/28342808-66b5-4d22-a881-d3bb96fcab60)

2024-01-12 06:25 UTC, MingcongBai requested changes

2024-01-12 06:25 UTC, MingcongBai commented on app-network/zerotier-one/spec
>  SRCS="tbl::https://github.com/zerotier/ZeroTierOne/archive/refs/tags/$VER.tar.gz"
Please use a Git tag, generated tarballs are not reliable.

2024-01-19 07:21 UTC, MingcongBai approved these changes

2024-01-19 07:21 UTC, MingcongBai commented on app-network/zerotier-one/spec
> +SRCS="git::commit=327eb9013b39809835a912c9117a0b9669f4661f::https://github.com/zerotier/ZeroTierOne"
You should be using tags.

2024-01-19 08:07 UTC, merged