libharu: update to 2.4.4
AOSC-Dev/aosc-os-abbs pull request #5136
Opened 2024-01-15 10:08 UTC by BC204

Topic Description
-----------------

- libharu: drop unneeded files remove in beyond
    - modify the location of the misplaced document
- libharu: drop upstreamed patches

- libharu: update to 2.4.4

Package(s) Affected
-------------------

- libharu: 2.4.4

Security Update?
----------------

No

Build Order
-----------

```
#buildit libharu
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

2024-01-15 10:35 UTC, BC204 commented
Use the example provided by upstream
http://libharu.org/demo/font_demo.c
![截图 2024-01-15 18-31-26](https://github.com/AOSC-Dev/aosc-os-abbs/assets/109511245/03d33da4-c377-4083-8890-9236d2762211)

2024-01-16 06:11 UTC, MingcongBai requested changes

2024-01-16 06:11 UTC, MingcongBai commented on runtime-doc/libharu/spec
> +SRCS="tbl::https://github.com/libharu/libharu/archive/v$VER.tar.gz"
Use Git snapshot instead of automatically generated tarballs.

2024-01-18 06:18 UTC, MingcongBai approved these changes

2024-01-18 07:07 UTC, merged