apitrace update to 11.1
AOSC-Dev/aosc-os-abbs pull request #5140
Opened 2024-01-18 02:31 UTC by HouLiXieBuRou

Topic Description
-----------------

- apitrace: update to 11.1

- waffle: new,1.18.0
New version apitrace requires

Package(s) Affected
-------------------

Security Update?
----------------

No

Build Order
-----------

```
#buildit waffle apitrace
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-01-18 03:19 UTC, HouLiXieBuRou commented
amd test
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/7b209a32-8b45-4528-8ab2-459ac74c7972)

2024-01-18 07:31 UTC, HouLiXieBuRou commented
arm test
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/1a19ce8e-c5ae-4e90-b8b3-6e766f13ce9d)

2024-01-19 05:21 UTC, MingcongBai requested changes

2024-01-19 05:21 UTC, MingcongBai commented on runtime-common/waffle/autobuild/defines
> +PKGDEP="cmocka libxslt"
That makes no sense. `cmocka` is a testing framework.

2024-01-19 07:21 UTC, MingcongBai approved these changes

2024-01-19 07:54 UTC, merged