Node.js: security update to 20.11.0
AOSC-Dev/aosc-os-abbs pull request #5153
Opened 2024-01-18 14:52 UTC by KexyBiscuit

Topic Description
-----------------

- nodejs: security update to 20.11.0
    - Closes #5152.
    - Supersedes #5102.

Package(s) Affected
-------------------

- nodejs: 2:20.11.0-1

Security Update?
----------------

No

Build Order
-----------

```
#buildit nodejs
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-01-18 17:21 UTC, KexyBiscuit commented
Test succeed on loongson3.
```
(ssh)root@Resonance [ ~ ] # node --version
v20.11.0
(ssh)root@Resonance [ ~ ] # npm --version
10.2.4
```

2024-01-19 05:15 UTC, MingcongBai requested changes

2024-01-19 05:15 UTC, MingcongBai commented on lang-js/nodejs/autobuild/patches/51495.patch
Please rename this file in according with our Styling Manual, or use `git format-patch`.

2024-01-19 13:07 UTC, KexyBiscuit commented on lang-js/nodejs/autobuild/patches/51495.patch
Done.

2024-01-20 00:24 UTC, MingcongBai approved these changes

2024-01-20 00:25 UTC, merged