docker: support loongarch
AOSC-Dev/aosc-os-abbs pull request #5223
Opened 2024-01-28 07:56 UTC by jiegec

Topic Description
-----------------

- docker: (loongarch64) fix missing syscall

- containerd: (loongarch64) fix missing syscall

- runc: (loongarch64) fix missing syscall

- criu: update to 3.19

Package(s) Affected
-------------------

- runc: 1.1.10
- criu: 3.19
- containerd: 1.7.10
- docker: 24.0.7+tini0.19.0

Security Update?
----------------

No

Build Order
-----------

```
#buildit criu runc containerd docker
```

Test Build(s) Done
------------------

**Experimental Architectures**

- [ ] LoongArch 64-bit `loongarch64`

2024-01-30 06:19 UTC, MingcongBai requested changes

2024-01-30 06:19 UTC, MingcongBai commented on app-admin/criu/autobuild/build
> +mkdir -p "$PKGDIR"/usr/bin
Verbosity here.

2024-01-31 01:20 UTC, jiegec commented on app-admin/criu/autobuild/build
> +mkdir -p "$PKGDIR"/usr/bin
Done

2024-01-31 02:16 UTC, MingcongBai commented
![图片](https://github.com/AOSC-Dev/aosc-os-abbs/assets/5006263/93c34ebe-c0b2-42e3-a56a-e5fbd514acdf)

Runs `amd64` Arch Linux just fine with LATX.

2024-01-31 02:16 UTC, MingcongBai approved these changes

2024-01-31 02:17 UTC, merged