binutils: update to 2.42
AOSC-Dev/aosc-os-abbs pull request #5243
Opened 2024-02-02 02:59 UTC by jiegec

Topic Description
-----------------

- bpftrace: bump REL
    Rebase patches
- binutils: update to 2.42

Package(s) Affected
-------------------

- binutils: 2.42
- bpftrace: 0.19.1-1

Security Update?
----------------

No

Build Order
-----------

```
#buildit binutils bpftrace
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-02-04 07:53 UTC, jiegec commented
bpftrace on loongarch64:

```shell
# bpftrace -e 'tracepoint:raw_syscalls:sys_enter { @[comm] = count(); }'
Attaching 1 probe...
^C

@[(sd-close)]: 2
@[httpd]: 6
@[packagekitd]: 7
@[openvpn]: 7
@[do-rsync]: 10
@[systemd-homed]: 15
@[systemd-resolve]: 15
@[dbus-daemon]: 20
@[rsync]: 26
@[systemd-machine]: 28
@[containerd]: 42
@[systemd-logind]: 43
@[bpftrace]: 46
@[systemd-journal]: 157
@[systemd]: 272
@[clash]: 582
@[sshd]: 869
@[popub-local]: 1514

```

2024-02-05 01:01 UTC, jiegec commented
TODO: reconsider mips64 patch for loongson3/mips64r6el.

2024-02-06 00:28 UTC, MingcongBai requested changes

2024-02-06 00:28 UTC, MingcongBai commented on app-devel/binutils/spec
> +VER=2.42
Please mark PKGBREAK if your intention is to rebuild the BPF-related packages for `libbfd`.

2024-02-06 01:28 UTC, jiegec commented on app-devel/binutils/spec
> +VER=2.42
Actually bpftrace only depends on libsframe from binutils, not libbfd where soname has been changed.

2024-02-06 02:56 UTC, MingcongBai commented on app-devel/binutils/spec
> +VER=2.42
> Actually bpftrace only depends on libsframe from binutils, not libbfd where soname has been changed.

So why rebuild?

2024-02-06 05:48 UTC, MingcongBai approved these changes

2024-02-06 05:49 UTC, merged