psutils update to 3.3.2
AOSC-Dev/aosc-os-abbs pull request #5271
Opened 2024-02-06 07:48 UTC by HouLiXieBuRou

Topic Description
-----------------

- psutils: update to 3.3.2

- py: update to 1.11.0
Package pytest relies on the new version of py.psutils->pytest-datafiles->pytest->py

- pytest-datafiles: new,3.0.0
Because the new version of psutils requires

- wand: new,0.6.13
Because the new version of psutils requires

- argparse-manpage: new,4.5
Because the new version of psutils requires

- pypdf: new,4.0.0
Because new psutils need

- puremagic: new,1.15
New version of psutils dependency

Package(s) Affected
-------------------

Security Update?
----------------

No

Build Order
-----------

```
#buildit puremagic pypdf argparse-manpage wand py pytest-datafiles psutils
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-02-06 09:25 UTC, HouLiXieBuRou commented
psutils bin
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/25058624-2fce-4437-8add-adcfb393232a)

2024-02-06 09:52 UTC, MingcongBai requested changes

2024-02-06 09:52 UTC, MingcongBai commented on lang-python/pypdf/spec
> +SRCS="tbl::https://github.com/py-pdf/pypdf/archive/refs/tags/$VER.tar.gz"
Use Git tag.

2024-02-06 09:52 UTC, MingcongBai commented on lang-python/py/spec
> +SRCS="tbl::https://github.com/pytest-dev/py/archive/refs/tags/$VER.tar.gz"
Use Git tag.

2024-02-06 09:52 UTC, MingcongBai commented on lang-python/argparse-manpage/spec
> +SRCS="tbl::https://github.com/praiskup/argparse-manpage/archive/refs/tags/v$VER.tar.gz"
Use Git tag.

2024-02-06 09:52 UTC, MingcongBai commented on lang-python/wand/spec
> +SRCS="tbl::https://github.com/emcconville/wand/archive/refs/tags/$VER.tar.gz"
Use Git tag.

2024-02-06 09:52 UTC, MingcongBai commented on lang-python/pytest-datafiles/spec
> +SRCS="https://github.com/omarkohl/pytest-datafiles/archive/refs/tags/3.0.0.tar.gz"
Use Git tag.

2024-02-07 09:00 UTC, MingcongBai requested changes

2024-02-07 09:00 UTC, MingcongBai commented on app-doc/psutils/autobuild/prepare
> +mkdir "${SRCDIR}"/.tempsrc
Please use absolute paths.

2024-02-07 09:44 UTC, MingcongBai approved these changes

2024-02-07 09:45 UTC, merged