inputplug: new, 0.4.0
AOSC-Dev/aosc-os-abbs pull request #5292
Opened 2024-02-10 15:14 UTC by eatradish

Topic Description
-----------------

- inputplug: new, 0.4.0

Package(s) Affected
-------------------

- inputplug: 0.4.0

Security Update?
----------------

No

Build Order
-----------

```
#buildit inputplug
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-02-12 05:41 UTC, MingcongBai requested changes

2024-02-12 05:41 UTC, MingcongBai commented on app-utils/inputplug/autobuild/beyond
> +	/usr/share/man/man1/
Install to PKGDIR!

2024-02-12 06:52 UTC, eatradish commented
@aosc-buildit-bot build

2024-02-12 15:35 UTC, eatradish commented
@aosc-buildit-bot build

2024-02-12 15:41 UTC, eatradish commented
@aosc-buildit-bot build

2024-02-13 14:10 UTC, MingcongBai approved these changes

2024-02-14 00:08 UTC, merged