yazi: update to 0.2.3
AOSC-Dev/aosc-os-abbs pull request #5305
Opened 2024-02-14 05:39 UTC by eatradish

Topic Description
-----------------

- yazi: update to 0.2.3

Package(s) Affected
-------------------

- yazi: 0.2.3

Security Update?
----------------

No

Build Order
-----------

```
#buildit yazi
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-02-14 07:59 UTC, MingcongBai requested changes

2024-02-14 07:59 UTC, MingcongBai commented on app-utils/yazi/autobuild/beyond
> +
Extraneous new line.

2024-02-15 01:29 UTC, jiegec approved these changes

2024-02-15 13:30 UTC, MingcongBai approved these changes

2024-02-15 13:31 UTC, merged

2024-02-15 13:32 UTC, eatradish commented
@aosc-buildit-bot build