open-vm-tools: update to 12.3.5
AOSC-Dev/aosc-os-abbs pull request #5331
Opened 2024-02-19 09:06 UTC by Suyun114

Topic Description
-----------------

- open-vm-tools: update to 12.3.5

Package(s) Affected
-------------------

- open-vm-tools: 12.3.5-1

Security Update?
----------------

No

Build Order
-----------

```
#buildit open-vm-tools
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`

2024-02-19 09:19 UTC, Suyun114 commented
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/108112549/ebb58cc0-35dd-4da3-8726-a0c7b1870133)

Tested on AMD64.

2024-02-19 09:38 UTC, MingcongBai requested changes, later dismissed

2024-02-19 09:38 UTC, MingcongBai commented on app-virtualization/open-vm-tools/spec
>  REL=1
Remove this.

2024-02-24 02:00 UTC, jiegec approved these changes

2024-02-24 02:00 UTC, merged