fontforge: update to 20230101
AOSC-Dev/aosc-os-abbs pull request #5370
Opened 2024-02-27 13:46 UTC by jiegec

Topic Description
-----------------

- fontforge: update to 20230101

Package(s) Affected
-------------------

- fontforge: 20230101

Security Update?
----------------

No

Build Order
-----------

```
#buildit fontforge
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-02-28 17:11 UTC, MingcongBai requested changes, later dismissed

2024-02-28 17:11 UTC, MingcongBai commented on app-creativity/fontforge/spec
>  SRCS="tbl::https://github.com/fontforge/fontforge/archive/$VER.tar.gz"
Please use Git tag.

2024-02-29 02:12 UTC, jiegec commented on app-creativity/fontforge/spec
>  SRCS="tbl::https://github.com/fontforge/fontforge/archive/$VER.tar.gz"
Done

2024-03-03 15:52 UTC, MingcongBai approved these changes

2024-03-03 15:52 UTC, merged