go: update to 1.22.0
AOSC-Dev/aosc-os-abbs pull request #5396
Opened 2024-03-01 15:03 UTC by jiegec

Topic Description
-----------------

- libguestfs: update to 1.52.0
- glide: bump REL due to go update
- dep: bump REL due to go update
- delve: update to 1.22.1
- rclone: update to 1.65.2
- hugo: update to 0.123.6
- hub: bump REL due to go update
- restic: update to 0.16.4
- pcstat: bump REL due to go update
- fzf: update to 0.46.1

... and 34 more commits

Package(s) Affected
-------------------

- rclone: 1.65.2
- hugo: 0.123.6
- git-lfs: 3.5.0
- gh: 2.44.1
- cf-tool: 1.0.0-4
- go-md2man: 2.0.3
- hub: 2.14.2+git20230617-1
- conmon: 2.1.10
- runc: 1.1.12
- snapd: 2.61.2
- direnv: 2.34.0
- restic: 0.16.4
- pcstat: 1:0.0.2-1
- fzf: 0.46.1
- automatic-component-toolkit: 1.6.0-1
- android-platform-tools: 34.0.4-1
- go: 1.22.0+tools0.18.0+net0.21.0
- dep: 0.5.4-17
- glide: 0.13.3-17
- delve: 1.22.1
- micro: 2.0.13-1
- liteide: 38.3-1
- obfs4proxy: 0.0.14
- geoipupdate: 6.1.0
- clash: 1.18.0-1
- dnscrypt: 2.1.5-1
- popub: 1:0+git20210814-2
- v2raya: 2.2.4
- kcptun: 20240107
- syncthing: 1.27.3
- graftcp: 1:0.7.2
- v2ray: 5.13.0
- frp: 0.54.0
- chisel: 1.9.1
- tailscale: 1.60.1
- kubo: 0.26.0
- v2ray-plugin: 1.3.2-1
- xray: 1.8.4
- gost: 2.11.5
- docker-compose: 2.24.6
- containerd: 1.7.13
- podman: 4.9.3+vsock0.7.2
- docker: 25.0.3+tini0.19.0
- libguestfs: 1.52.0

Security Update?
----------------

No

Build Order
-----------

```
#buildit go conmon go-md2man runc snapd containerd docker docker-compose podman cf-tool gh git-lfs android-platform-tools liteide micro chisel clash dnscrypt frp geoipupdate gost graftcp kcptun kubo obfs4proxy popub syncthing tailscale v2ray v2ray-plugin v2raya xray automatic-component-toolkit direnv fzf pcstat restic hub hugo rclone delve dep glide libguestfs
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-03-03 15:53 UTC, MingcongBai commented on app-admin/conmon/spec
>  SRCS="https://github.com/containers/conmon/archive/v$VER.tar.gz"
Use Git tag here.

2024-03-03 15:58 UTC, jiegec commented on app-admin/conmon/spec
>  SRCS="https://github.com/containers/conmon/archive/v$VER.tar.gz"
Fixed.

2024-03-03 15:58 UTC, MingcongBai requested changes

2024-03-03 15:58 UTC, MingcongBai commented on app-admin/conmon/spec
>  SRCS="https://github.com/containers/conmon/archive/v$VER.tar.gz"
Use Git tag here.

2024-03-03 15:58 UTC, MingcongBai commented on app-admin/runc/autobuild/defines
> +# Missing criu support
Make this `# FIXME: Missing criu support"`.

2024-03-03 15:58 UTC, MingcongBai commented on app-containers/containerd/autobuild/defines
> +
Trailing new line.

2024-03-03 15:58 UTC, MingcongBai commented on app-containers/containerd/autobuild/defines
> +# Missing criu support
Make this `# FIXME: Missing criu support"`.

2024-03-03 15:58 UTC, MingcongBai commented on app-containers/docker/autobuild/defines
> +# Missing criu support
Make this `# FIXME: Missing criu support"`.

2024-03-03 15:58 UTC, MingcongBai commented on app-containers/docker/autobuild/defines
> +FAIL_ARCH="!(amd64|arm64|ppc64el|loongarch64)"
Hmm, this seems inconsistent with other instances of FAIL_ARCH for missing criu?

2024-03-03 15:58 UTC, MingcongBai commented on app-network/gost/autobuild/build
> +ln -sf "$SRCDIR"/vendor .gopath/src
Please lint this script.

2024-03-03 15:58 UTC, MingcongBai commented on app-network/kcptun/autobuild/defines
> +FAIL_ARCH="loongarch64"
Why? Please leave a FIXME comment here.

2024-03-03 15:58 UTC, MingcongBai commented on app-network/kcptun/spec
>  SRCS="https://github.com/xtaci/kcptun/archive/v$VER.tar.gz"
Please use Git tag.

2024-03-03 15:58 UTC, MingcongBai commented on app-network/graftcp/spec
>  SRCS="https://github.com/hmgle/graftcp/archive/v$VER.tar.gz"
Please use Git tag.

2024-03-03 15:58 UTC, MingcongBai commented on app-network/gost/spec
>  SRCS="https://github.com/ginuerzh/gost/archive/v$VER.tar.gz"
Please use Git tag.

2024-03-03 15:58 UTC, MingcongBai commented on app-network/frp/spec
>  SRCS="tbl::https://github.com/fatedier/frp/archive/v${VER}.tar.gz"
Please use Git tag.

2024-03-03 15:58 UTC, MingcongBai commented on app-network/geoipupdate/spec
>  SRCS="https://github.com/maxmind/geoipupdate/archive/v$VER.tar.gz"
Please use Git tag.

2024-03-03 15:58 UTC, MingcongBai commented on app-network/dnscrypt/spec
>  SRCS="https://github.com/jedisct1/dnscrypt-proxy/archive/$VER.tar.gz"
Please use Git tag.

2024-03-03 15:58 UTC, MingcongBai commented on app-network/chisel/spec
>  SRCS="https://github.com/jpillora/chisel/archive/v$VER.tar.gz"
Please use Git tag.

2024-03-03 15:58 UTC, MingcongBai commented on app-devel/cf-tool/spec
>  SRCS="tbl::https://github.com/xalanq/cf-tool/archive/refs/tags/v$VER.tar.gz"
Please use Git tag.

2024-03-03 15:58 UTC, MingcongBai commented on app-containers/docker-compose/spec
>  SRCS="tbl::https://github.com/docker/compose/archive/refs/tags/v${VER}.tar.gz"
Please use Git tag.

2024-03-03 15:58 UTC, MingcongBai commented on app-network/kubo/spec
>  SRCS="tbl::https://github.com/ipfs/kubo/archive/refs/tags/v$VER.zip"
Please use Git tag.

2024-03-03 15:58 UTC, MingcongBai commented on app-network/popub/autobuild/build
> +
Trailing new line.

2024-03-03 15:58 UTC, MingcongBai commented on app-network/v2ray-plugin/autobuild/defines
> +FAIL_ARCH="loongarch64"
Why? Please leave a FIXME comment here.

2024-03-03 15:58 UTC, MingcongBai commented on app-network/v2ray-plugin/spec
>  SRCS="https://github.com/shadowsocks/v2ray-plugin/archive/v$VER.tar.gz"
Please use Git tag.

2024-03-03 15:58 UTC, MingcongBai commented on app-network/v2raya/spec
>  SRCS="https://github.com/v2rayA/v2rayA/archive/refs/tags/v${VER}.tar.gz"
Please use Git tag.

2024-03-03 15:58 UTC, MingcongBai commented on app-utils/automatic-component-toolkit/spec
>  SRCS="https://github.com/Autodesk/AutomaticComponentToolkit/archive/refs/tags/v$VER.tar.gz"
Please use Git tag.

2024-03-03 15:58 UTC, MingcongBai commented on app-utils/direnv/spec
>  SRCS="https://github.com/direnv/direnv/archive/v$VER.tar.gz"
Please use Git tag.

2024-03-03 15:58 UTC, MingcongBai commented on app-utils/fzf/spec
>  SRCS="https://github.com/junegunn/fzf/archive/$VER.tar.gz"
Please use Git tag.

2024-03-03 15:58 UTC, MingcongBai commented on app-utils/restic/spec
>  SRCS="https://github.com/restic/restic/archive/v$VER.tar.gz"
Please use Git tag.

2024-03-03 15:59 UTC, MingcongBai requested changes

2024-03-03 15:59 UTC, MingcongBai commented on app-admin/snapd/autobuild/defines
> +FAIL_ARCH="!(amd64|arm64|ppc64el|riscv64)"
Why? Please leave a FIXME comment here.

2024-03-03 15:59 UTC, MingcongBai commented on app-web/hugo/spec
>  SRCS="https://github.com/gohugoio/hugo/archive/v$VER.tar.gz"
Please use Git tag.

2024-03-03 16:51 UTC, MingcongBai requested changes

2024-03-03 16:51 UTC, MingcongBai commented on app-network/gost/autobuild/build
> +ln -sf "$SRCDIR"/vendor .gopath/src
Please use verbosity.

2024-03-03 16:51 UTC, MingcongBai commented on app-network/obfs4proxy/autobuild/build
> +go build -o obfs4proxy/obfs4proxy ./obfs4proxy
Absolute path?

2024-03-05 17:51 UTC, MingcongBai approved these changes

2024-03-05 17:52 UTC, MingcongBai approved these changes

2024-03-05 17:53 UTC, merged