fuzzel: new, 1.9.2
AOSC-Dev/aosc-os-abbs pull request #5426
Opened 2024-03-05 22:26 UTC by OriginCode

Topic Description
-----------------

- fuzzel: new, 1.9.2
    Signed-off-by: Kaiyang Wu <origincode@aosc.io>
- fcft: new, 3.1.8
    Signed-off-by: Kaiyang Wu <origincode@aosc.io>
- tllist: new, 1.1.0
    Signed-off-by: Kaiyang Wu <origincode@aosc.io>

Package(s) Affected
-------------------

- tllist: 1.1.0
- fuzzel: 1.9.2
- fcft: 3.1.8

Security Update?
----------------

No

Build Order
-----------

```
#buildit tllist fcft fuzzel
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-03-05 22:57 UTC, OriginCode commented
LGTM on amd64:
![圖片](https://github.com/AOSC-Dev/aosc-os-abbs/assets/17294071/e363e76f-5d1c-4f1d-a93e-6b2afd724a3d)

2024-03-06 00:43 UTC, MingcongBai requested changes

2024-03-06 00:43 UTC, MingcongBai commented on runtime-common/tllist/autobuild/defines
> +PKGDES="A typed linked list C header file only library"
A C header-only typed linked list library

2024-03-06 00:43 UTC, MingcongBai commented on runtime-display/fcft/autobuild/defines
> +PKGDEP="wayland wayland-protocols fontconfig freetype pixman harfbuzz libutf8proc"
Are you sure that the protocols are runtime depended?

2024-03-06 00:43 UTC, MingcongBai commented on runtime-display/fcft/autobuild/patches/0001-fix-libutf8proc-header-file-path.patch
> +From 2024894dfdff3c2467478aaaa62db471d08421b0 Mon Sep 17 00:00:00 2001
Track this at AOSC-Tracking.

2024-03-06 03:14 UTC, MingcongBai approved these changes

2024-03-06 03:14 UTC, merged