pipewire: update to 1.0.3
AOSC-Dev/aosc-os-abbs pull request #5446
Opened 2024-03-07 17:19 UTC by jiegec

Topic Description
-----------------

- pipewire: update to 1.0.3

Package(s) Affected
-------------------

- pipewire: 1.0.3

Security Update?
----------------

No

Build Order
-----------

```
#buildit pipewire
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-03-07 21:04 UTC, OriginCode commented
LGTM on amd64:
![圖片](https://github.com/AOSC-Dev/aosc-os-abbs/assets/17294071/7a03deec-9d1d-4613-97f3-ff2e8478aacc)

2024-03-07 21:04 UTC, OriginCode approved these changes

2024-03-07 21:05 UTC, OriginCode requested changes, later dismissed
Pipewire 1.0.2 and up requires libcamera 0.2.0+

2024-03-08 02:50 UTC, jiegec commented
> Pipewire 1.0.2 and up requires libcamera 0.2.0+

Fixed!

2024-03-12 18:35 UTC, OriginCode approved these changes

2024-03-13 01:15 UTC, merged