ly: new, 0.6.0
AOSC-Dev/aosc-os-abbs pull request #5473
Opened 2024-03-10 02:21 UTC by OriginCode

Topic Description
-----------------

- ly: new, 0.6.0
    Signed-off-by: Kaiyang Wu <origincode@aosc.io>

Package(s) Affected
-------------------

- ly: 0.6.0

Security Update?
----------------

No

Build Order
-----------

```
#buildit ly
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-03-10 03:11 UTC, OriginCode commented
LGTM on amd64:
Logged in with Ly (Sway)
![圖片](https://github.com/AOSC-Dev/aosc-os-abbs/assets/17294071/da284f29-b179-4f74-9857-1037969fdc1d)

2024-03-10 03:17 UTC, OriginCode commented
Pending Fedora Anitya to recover its service.

2024-03-10 14:08 UTC, MingcongBai requested changes

2024-03-10 14:08 UTC, MingcongBai commented on desktop-displaymanagers/ly/autobuild/defines
> +PKGDES="A lightweight TUI display manager"
A display manager with terminal user interface

2024-03-11 00:54 UTC, Cyanoxygen approved these changes

2024-03-11 01:20 UTC, MingcongBai approved these changes

2024-03-11 01:20 UTC, merged