NVIDIA driver 550.54.14 + CUDA 12.4
AOSC-Dev/aosc-os-abbs pull request #5474
Opened 2024-03-10 03:30 UTC by cthbleachbit

Topic Description
-----------------

This PR updates nvidia drivers and cuda to support using nvcc with GCC 13.

Package(s) Affected
-------------------

Build Order
-----------

```
#buildit nvidia cuda
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`

2024-03-10 14:07 UTC, MingcongBai requested changes

2024-03-10 14:07 UTC, MingcongBai commented on runtime-display/nvidia/autobuild/build
>      return $?
Please use absolute paths where possible.

2024-03-10 21:27 UTC, OriginCode commented
LGTM on SwayWM, NVIDIA 550 fixes some flickering.

2024-03-10 21:27 UTC, OriginCode submitted a review, later dismissed

2024-03-11 00:08 UTC, Cyanoxygen approved these changes, later dismissed

2024-03-11 00:55 UTC, Cyanoxygen approved these changes

2024-03-11 01:20 UTC, MingcongBai approved these changes

2024-03-11 01:21 UTC, merged