plzip: update to 1.11
AOSC-Dev/aosc-os-abbs pull request #5499
Opened 2024-03-14 09:34 UTC by BC204

Topic Description
-----------------

- plzip: migrate to autobuild4
- plzip: update to 1.11

Package(s) Affected
-------------------

- plzip: 1.11

Security Update?
----------------

No

Build Order
-----------

```
#buildit plzip
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-03-14 09:46 UTC, jiegec approved these changes, later dismissed
<img width="635" alt="image" src="https://github.com/AOSC-Dev/aosc-os-abbs/assets/6127678/96a6bc64-7c98-4843-89ff-cd782e08c4ec">

2024-03-14 17:21 UTC, MingcongBai requested changes, later dismissed

2024-03-14 17:21 UTC, MingcongBai commented on app-utils/plzip/autobuild/build
Please lint this script.

2024-03-15 04:42 UTC, jiegec approved these changes

2024-03-16 05:02 UTC, merged