FTBFS fix for loongarch batch #10
AOSC-Dev/aosc-os-abbs pull request #5525
Opened 2024-03-18 05:44 UTC by jiegec

Topic Description
-----------------

- toluapp: fix PKGSEC
- concurrencykit: migrate to ab4
- compsize: update to 1.5
- cmix: update to 20
- chemtool: fix FTBFS

Package(s) Affected
-------------------

- cmix: 20
- compsize: 1.5
- toluapp: 1.0.93-1
- chemtool: 1.6.14-4
- concurrencykit: 0.7.1-1

Security Update?
----------------

No

Build Order
-----------

```
#buildit chemtool cmix compsize concurrencykit toluapp
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-03-18 07:21 UTC, MingcongBai submitted a review, later dismissed

2024-03-18 07:44 UTC, jiegec commented
concurrencykit soname downgraded from libck.so.3 to libck.so.0 ???

2024-03-18 07:46 UTC, jiegec commented
Since there are no library reverse dependencies of concurrencykit, it is okay.

2024-03-18 15:54 UTC, MingcongBai requested changes

2024-03-18 15:54 UTC, MingcongBai commented on app-utils/cmix/autobuild/build
> +install -Dvm755 cmix "$PKGDIR"/usr/bin/cmix
Use absolute paths here, i.e. `"$SRCDIR"/cmix`.

2024-03-20 02:49 UTC, jiegec commented on app-utils/cmix/autobuild/build
> +install -Dvm755 cmix "$PKGDIR"/usr/bin/cmix
Fixed

2024-03-21 01:40 UTC, MingcongBai approved these changes

2024-03-21 01:40 UTC, merged