FTBFS fix for loongarch batch #13
AOSC-Dev/aosc-os-abbs pull request #5531
Opened 2024-03-18 14:18 UTC by jiegec

Topic Description
-----------------

- zutils: migrate to ab4
- lziprecover: migrate to ab4
- aranym: migrate to ab4
- x11-lib: migrate to ab4
- opencryptoki: migrate to ab4

Package(s) Affected
-------------------

- lziprecover: 1.21-2
- zutils: 1.7-5
- x11-lib: 7.7.20231031-1
- aranym: 1.1.0-1
- opencryptoki: 3.21.0-1

Security Update?
----------------

No

Build Order
-----------

```
#buildit opencryptoki x11-lib aranym lziprecover zutils
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-03-18 15:56 UTC, MingcongBai requested changes

2024-03-18 15:56 UTC, MingcongBai commented on app-utils/lziprecover/autobuild/build
> +./configure ${AUTOTOOLS_DEF[@]} \
"$SRCDIR"/configure

2024-03-19 00:53 UTC, jiegec commented on app-utils/lziprecover/autobuild/build
> +./configure ${AUTOTOOLS_DEF[@]} \
Fixed.

2024-03-21 01:43 UTC, MingcongBai approved these changes

2024-03-21 01:43 UTC, merged