units: update to 2.23
AOSC-Dev/aosc-os-abbs pull request #5580
Opened 2024-03-25 10:32 UTC by BC204

Topic Description
-----------------

- units: disable reconf to avoid covering patch
- units: move /usr/com => /usr/share/com
- units: fix unexpected path(s) in package
- units: update to 2.23

Package(s) Affected
-------------------

- units: 2.23

Security Update?
----------------

No

Build Order
-----------

```
#buildit units
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-03-25 12:51 UTC, MingcongBai requested changes

2024-03-25 12:51 UTC, MingcongBai commented on app-utils/units/autobuild/patches/0001-units-fix-unexpected-path.patch
Just patch configure.in or configure.ac.

2024-03-26 03:37 UTC, BC204 commented
Test on amd
![units-2 23](https://github.com/AOSC-Dev/aosc-os-abbs/assets/109511245/f90bd923-270c-41b4-ad19-22b5b5d4c848)

2024-03-26 06:37 UTC, MingcongBai approved these changes

2024-03-26 06:37 UTC, merged