7-zip: create DEBUG build using GCC
AOSC-Dev/aosc-os-abbs pull request #5624
Opened 2024-03-31 07:47 UTC by ouankou

Topic Description
-----------------

 - 7-zip: Resolve Clang build failure on Loongson3 by using GCC instead.

Package(s) Affected
-------------------

 - 7-zip: 23.01

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

Architectural progress for secondary ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

Architectural progress for experimental ports does not impede on merging of this topic.

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-03-31 13:22 UTC, jiegec approved these changes, later dismissed

2024-03-31 13:32 UTC, MingcongBai requested changes
Your commit message is trying to do two things at once:

1. You have fixed debug builds on GCC
2. Clang happens to not work on Loongson 3 (this is collateral)

Also, can you make sure that Autobuild flags are passed in correctly? I have just read the build log and I see no Autobuild flags being passed.

2024-03-31 16:03 UTC, ouankou commented
> Your commit message is trying to do two things at once:
> 
> 1. You have fixed debug builds on GCC
> 2. Clang happens to not work on Loongson 3 (this is collateral)
> 
> Also, can you make sure that Autobuild flags are passed in correctly? I have just read the build log and I see no Autobuild flags being passed.

I'll address the missed autobuild flags.

For the commit message, which one is preferred? Or something else?

```
# 1
7-zip: fix debug builds on GCC and resolve Clang build failure on Loongson3

# 2
7-zip: fix debug builds on GCC
  - Add an option to enable debug build
  - Resolve Clang build failure on Loongson3

#3
7-zip: fix debug builds on GCC
  - Resolve Clang build failure on Loongson3
```

2024-03-31 16:32 UTC, MingcongBai commented
@ouankou Variant 2 is best but I would specify that "This allows 7-zip to build on loongson3 as it previously failed with Clang."

2024-04-01 09:07 UTC, MingcongBai approved these changes

2024-04-01 09:07 UTC, merged