gdal: update to 3.8.4
AOSC-Dev/aosc-os-abbs pull request #5625
Opened 2024-03-31 13:13 UTC by jiegec

Topic Description
-----------------

- gdal: update to 3.8.4

Package(s) Affected
-------------------

- gdal: 3.8.4

Security Update?
----------------

No

Build Order
-----------

```
#buildit gdal
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-04-05 14:15 UTC, MingcongBai requested changes

2024-04-05 14:15 UTC, MingcongBai commented on runtime-scientific/opencv/spec
>  SRCS="tbl::https://github.com/opencv/opencv/archive/$VER.tar.gz
Use Git snapshot.

2024-04-05 14:33 UTC, jiegec commented on runtime-scientific/opencv/spec
>  SRCS="tbl::https://github.com/opencv/opencv/archive/$VER.tar.gz
Done

2024-04-06 12:42 UTC, MingcongBai approved these changes

2024-04-06 12:42 UTC, merged