optenv32 Survey: Towards the Steam Native Runtime (Wave 1: Reworked Toolchain & Base Libraries)
AOSC-Dev/aosc-os-abbs pull request #5707
Opened 2024-04-09 15:29 UTC by Cyanoxygen

Topic Description
-----------------

This PR overhauls the entire 32-bit (i686) subsystem of AOSC OS (optenv32), and make it complete enough to support the Steam Native Runtime.

Package(s) Affected
-------------------

TBD

Security Update?
----------------

No

Prerequisites
----------

- [x] AOSC-Dev/autobuild4#10

Build Order
-----------

### Base packages

Base packages should be built in order, manual intervention REQUIRED:

#### Bootstrapping the toolchain

```
ciel build autobuild4 binutils+32:+stage2 gcc+32:+stage2 linux+api+32:+stage2 glibc+32:+stage2 libxcrypt
```

And then, refresh the local package repo, and start the container, install the packages, then build stage 2 gcc+32 again. This time the stage 2 GCC will be complete enough to build the stage 3 GCC, since it then ships libstdc++.

```
ciel repo init <instance>
ciel sh -i <instance>
apt update
apt install autobuild4 gcc+32 glibc+32
acbs-build gcc+32:+stage2
```

#### Base libraries: Wave 1

```
ciel build zlib+32 gmp+32 mpfr+32 mpc+32 binutils+32 gcc+32 glibc+32 libxcrypt+32 gcc+32 ncurses+32 readline+32 expat+32 icu+32 xz+32 bzip2+32 db+32
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] 32-bit Optional Environment `optenv32`

2024-05-10 03:32 UTC, Cyanoxygen commented
After building glibc+32 with `-mstackrealign`, Steam is able to start games, the games run perfectly as expected.

Proton games are not tested though.

2024-05-13 10:44 UTC, jiegec commented
Can't compile i686 binary manually:

```shell
$ /opt/32/bin/g++ test.cpp -o test
/usr/bin/ld: /opt/32/lib/gcc/i686-aosc-linux-gnu/13.2.0/liblto_plugin.so: error loading plugin: /opt/32/lib/gcc/i686-aosc-linux-gnu/13.2.0/liblto_plugin.so: wrong ELF class: ELFCLASS32
collect2: error: ld returned 1 exit status
```

2024-05-13 11:26 UTC, Cyanoxygen commented
> Can't compile i686 binary manually:
> 
> ```shell
> $ /opt/32/bin/g++ test.cpp -o test
> /usr/bin/ld: /opt/32/lib/gcc/i686-aosc-linux-gnu/13.2.0/liblto_plugin.so: error loading plugin: /opt/32/lib/gcc/i686-aosc-linux-gnu/13.2.0/liblto_plugin.so: wrong ELF class: ELFCLASS32
> collect2: error: ld returned 1 exit status
> ```

hmmm, must find a way to tell gcc to find the correct linker. For now please `export PATH=/opt/32/bin:$PATH`.

2024-05-13 13:53 UTC, MingcongBai requested changes

2024-05-13 13:53 UTC, MingcongBai commented on runtime-optenv32/binutils+32/autobuild/beyond
> +cp -v include/libiberty.h "$PKGDIR"/opt/32/include
"$SRCDIR"/include/libiberty.h

2024-05-13 13:53 UTC, MingcongBai commented on runtime-optenv32/binutils+32/autobuild/beyond.stage2
> +rm -r "$PKGDIR"/opt/32/share
Verbosity here.

2024-05-13 13:53 UTC, MingcongBai commented on runtime-optenv32/binutils+32/autobuild/prepare
> +sed -i "/ac_cpp=/s/\$CPPFLAGS/\$CPPFLAGS -O2/" "$SRCDIR"/libiberty/configure
Lint this script.

2024-05-13 13:53 UTC, MingcongBai commented on runtime-optenv32/devel-base+32/autobuild/build
> +mkdir "$PKGDIR"
Verbosity here.

2024-05-13 13:53 UTC, MingcongBai commented on runtime-optenv32/devel-base+32/autobuild/build
> +mkdir "$PKGDIR"
Also, why not `ABTYPE=dummy`?

2024-05-13 13:53 UTC, MingcongBai commented on runtime-optenv32/gcc+32/autobuild/prepare.stage2
> +tar xf "$SRCDIR"/../gmp-${__GMP_VER}.tar.xz
Verbosity for all `tar` commands.

2024-05-13 13:53 UTC, MingcongBai commented on runtime-optenv32/glibc+32/autobuild/beyond
> +ln -sv /opt/32/lib/ld-linux.so.2 "$PKGDIR"/usr/lib/ld-linux.so.2
Use relative path.

2024-05-13 13:53 UTC, MingcongBai commented on runtime-optenv32/gcc+32/autobuild/build.stage2
> +if [ -d "$PKGDIR"/opt/32/share ] ; then
Do you not know if these exist?

2024-05-13 13:53 UTC, MingcongBai commented on runtime-optenv32/glibc+32/autobuild/build.stage2
> +ln -sv /opt/32/lib/ld-linux.so.2 "$PKGDIR"/usr/lib/ld-linux.so.2
Relative path here.

2024-05-13 13:53 UTC, MingcongBai commented on runtime-optenv32/glibc+32/autobuild/build.stage2
> +cd "$SRCDIR"
This is not necessary.

2024-05-13 13:53 UTC, MingcongBai commented on runtime-optenv32/glibc+32/autobuild/prepare.stage2
> +
Trailing blank line.

2024-05-13 13:53 UTC, MingcongBai commented on runtime-optenv32/libxcrypt+32/autobuild/build
> +rm -r "$BLDDIR"
Verbosity here.

2024-05-13 13:53 UTC, MingcongBai commented on runtime-optenv32/linux+api+32/autobuild/defines.stage2
> +NOLTO=1
What...?

2024-05-13 13:53 UTC, MingcongBai commented on runtime-optenv32/linux+api+32/spec
> +VER=6.7.2
Sync with main tree.

2024-05-13 13:53 UTC, MingcongBai commented on runtime-optenv32/ncurses+32/autobuild/beyond
> +	ln -s ${lib}w.pc "$PKGDIR"/opt/32/lib/pkgconfig/${lib}.pc
Verbosity here.

2024-05-13 13:53 UTC, MingcongBai commented on runtime-optenv32/readline+32/spec
> +CHKSUMS="sha256::3feb7171f16a84ee82ca18a36d7b9be109a52c04f492a053331d7d1095007c35"
You may want to create symlinks for 6 and 7.

2024-05-13 13:53 UTC, MingcongBai commented on runtime-optenv32/zlib+32/autobuild/build
> +CC=i686-aosc-linux-gnu-gcc \
Lint this script.

2024-05-13 13:53 UTC, MingcongBai commented on runtime-optenv32/zlib+32/spec
> +SRCS="http://zlib.net/zlib-$VER.tar.xz"
No HTTPS?

2024-05-18 13:12 UTC, MingcongBai approved these changes

2024-05-18 13:12 UTC, merged