hysteria: 2.4.0, new
AOSC-Dev/aosc-os-abbs pull request #5715
Opened 2024-04-10 18:23 UTC by Nyovelt

Topic Description
-----------------

- hyseria: new, 2.4.0

Package(s) Affected
-------------------

- hysteria: 2.4.0-1

Security Update?
----------------

No

Build Order
-----------

```
#buildit hysteria
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`

2024-04-12 14:02 UTC, MingcongBai requested changes

2024-04-12 14:02 UTC, MingcongBai commented on app-network/hysteria/autobuild/defines
> +PKGDES="a network proxy software."
A multi-protocol network proxy

2024-04-12 14:02 UTC, MingcongBai commented on app-network/hysteria/autobuild/build
> +install -dm755 "$PKGDIR"/etc/hysteria/
Verbosity here.

2024-04-12 14:02 UTC, MingcongBai commented on app-network/hysteria/autobuild/build
> +install -Dm644 "$SRCDIR"/LICENSE.md \
This is unnecessary, Autobuild will handle this.

2024-04-12 14:02 UTC, MingcongBai commented on app-network/hysteria/spec
> +REL=1
We start at 0, please remove this line.

2024-04-17 02:31 UTC, jiegec commented
Ping @MingcongBai

2024-04-18 09:30 UTC, MingcongBai approved these changes

2024-04-18 09:30 UTC, merged