soundtouch update to 2.3.3
AOSC-Dev/aosc-os-abbs pull request #5775
Opened 2024-04-29 08:09 UTC by HouLiXieBuRou

Topic Description
-----------------

- unnamed-sdvx-clone: fix build and bump rel
    Delete excess beyond operation
- desmume: bump REL
- dolphin-emu: bump REL
- gstreamer: bump REL
- soundtouch: update to 2.3.3

Package(s) Affected
-------------------

Security Update?
----------------

No

Build Order
-----------

```
#buildit soundtouch unnamed-sdvx-clonegstreamer dolphin-emu desmume
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-04-30 10:01 UTC, HouLiXieBuRou commented
amd64
soundtouch
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/39fa456b-5454-480b-b8ea-11269bb8d755)
unnamed-sdvx-clone
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/5a70fc7f-155f-482e-9a26-81e305e0b381)
gstreame
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/686bb61d-b350-4d67-bf20-bf8b99b01be5)
dolphin-emu
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/65250226-a244-446a-828e-fbb4e88a990b)
desmume
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/aaef57d3-414c-48b7-ac92-026e65523ce9)

arm64
soundtouch
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/cf537dc7-7df7-4780-8f5f-dca1b11d3d38)
gstearmer
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/f0b69161-a81b-4ffb-ba7e-629019a1fad0)
dolphin-emu
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/77470d5e-5f07-4b09-bb5e-c309ebf65a4e)

2024-04-30 10:16 UTC, Cyanoxygen requested changes, later dismissed

2024-04-30 10:16 UTC, Cyanoxygen commented on app-games/unnamed-sdvx-clone/autobuild/beyond
> +install -Dm755 "$SRCDIR"/abbuild/bin/usc-game "$PKGDIR"/usr/bin
use `$BLDDIR`.

2024-04-30 10:16 UTC, Cyanoxygen commented on app-games/unnamed-sdvx-clone/autobuild/defines
> +ABSPLITDBG=0
This needs further investigation as it is a compiled binary.

2024-05-03 00:15 UTC, jiegec approved these changes

2024-05-04 02:44 UTC, merged