Fractal: new, 7
AOSC-Dev/aosc-os-abbs pull request #5829
Opened 2024-05-05 05:46 UTC by OriginCode

Topic Description
-----------------

- fractal: new, 7
    Signed-off-by: Kaiyang Wu <origincode@aosc.io>
- libshumate: new, 1.2.1
    Signed-off-by: Kaiyang Wu <origincode@aosc.io>

Package(s) Affected
-------------------

- fractal: 7
- libshumate: 1.2.1

Security Update?
----------------

No

Build Order
-----------

```
#buildit libshumate fractal
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-05-05 21:47 UTC, OriginCode commented
LGTM on amd64:
![圖片](https://github.com/AOSC-Dev/aosc-os-abbs/assets/17294071/e6e3e11f-8652-448d-a0ff-0de2e9cbff22)

2024-05-06 01:09 UTC, MingcongBai requested changes

2024-05-06 01:09 UTC, MingcongBai commented on desktop-gnome/fractal/autobuild/defines
> +PKGDES="A Matrix messaging app for GNOME"
A Matrix messaging client for GNOME

2024-05-06 01:09 UTC, MingcongBai commented on desktop-gnome/fractal/spec
> +# FIXME: APT does not recognize single digit version
single digit version without REL *

2024-05-06 01:09 UTC, MingcongBai commented on desktop-gnome/libshumate/autobuild/defines
> +PKGDES="A GTK toolkit providing widgets for embedded maps"
GTK toolkit widgets for embedded maps

2024-05-06 01:13 UTC, MingcongBai approved these changes

2024-05-06 02:15 UTC, merged