gstreamer-0-10: drop
AOSC-Dev/aosc-os-abbs pull request #5846
Opened 2024-05-07 05:59 UTC by jiegec

Topic Description
-----------------

- qt-4: bump REL due to gstreamer-0-10 removal
- libnice: bump REL due to gstreamer-0-10 removal
- gst-plugins-*-0-10: drop
- gstreamer-0-10: drop

Package(s) Affected
-------------------

- libnice: 0.1.17-2
- qt-4: 4.8.7-20

Security Update?
----------------

No

Build Order
-----------

```
#buildit libnice qt-4
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-05-07 08:13 UTC, MingcongBai approved these changes

2024-05-07 08:14 UTC, MingcongBai requested changes

2024-05-07 08:14 UTC, MingcongBai commented on runtime-optenv32/wxgtk+32/autobuild/defines
>  NOLTO=1
Bump REL.

2024-05-07 08:14 UTC, MingcongBai commented on runtime-optenv32/wxgtk-3+32/autobuild/defines
Bump REL.

2024-05-07 08:14 UTC, MingcongBai requested changes

2024-05-07 08:14 UTC, MingcongBai commented on app-utils/mugshot/autobuild/defines
> +PKGDEP="accountsservice dbus-python py3cairo pygobject-3 pexpect"
Bump REL.

2024-05-07 19:43 UTC, MingcongBai submitted a review, later dismissed

2024-05-07 19:43 UTC, MingcongBai commented on runtime-optenv32/32subsystem/autobuild/defines
> +gst-plugins-ugly-1-0+32 gstreamer-1-0+32 gtk-2+32 gtk-3+32 harfbuzz+32 icu+32  \
There should be a version change for this package.

2024-05-08 14:12 UTC, jiegec commented
wxgtk+32 dropped.

2024-05-09 02:33 UTC, jiegec commented
Maybe we can drop gstreamer-0-10 first, skipping gstreamer-0-10+32.

2024-05-09 03:05 UTC, Cyanoxygen commented
Optenv32 part of this PR will be done in the Wave 2.

2024-05-09 03:05 UTC, Cyanoxygen approved these changes

2024-05-09 03:33 UTC, merged