musescore: update to 4.3.0
AOSC-Dev/aosc-os-abbs pull request #5861
Opened 2024-05-07 16:07 UTC by jiegec

Topic Description
-----------------

- musescore: update to 4.3.0

Package(s) Affected
-------------------

- musescore: 4.3.0

Security Update?
----------------

No

Build Order
-----------

```
#buildit musescore
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`

2024-05-07 19:36 UTC, MingcongBai approved these changes

2024-05-07 19:41 UTC, MingcongBai requested changes, later dismissed
A couple issues with Desktop integration:

- The `.desktop` entry names the application confusingly as "MU 4.3," it should be "MuseScore."
- The update checking function should be stripped per the Styling Manual.

2024-05-13 02:54 UTC, jiegec commented
> A couple issues with Desktop integration:
> 
>     * The `.desktop` entry names the application confusingly as "MU 4.3," it should be "MuseScore."
> 
>     * The update checking function should be stripped per the Styling Manual.

Fixed

2024-05-18 13:31 UTC, MingcongBai submitted a review, later dismissed

2024-05-18 15:29 UTC, jiegec commented
Changed to use upstream .desktop file titled `MuseScore Studio 4.3`.

2024-05-20 09:08 UTC, Cyanoxygen approved these changes

2024-05-20 09:33 UTC, merged