dbus-python update to 1.3.2
AOSC-Dev/aosc-os-abbs pull request #5873
Opened 2024-05-08 03:05 UTC by HouLiXieBuRou

Topic Description
-----------------

- musicbox: bump REL
- xboxdrv: fix build and bump REL
    Added several patches.
    0000: fix xboxdrv.1 errors reported by lintian
    Fix all hyphen-used-as-minus-sign and spelling-error-in-manpage reports.
    0001: fix handling *flags environment variables containing >1 flags
    0002: use python3 print()
    0003: port xboxdrvctl to python3
    0004: scons 4.2.0 no longer has env.has_key()
    Check env as an array.
    0005: use the new input_event 64-bit-compliant api
- virt-manager: bump REL
- variety: bump REL
- tuned: bump REL
- totem: bump REL
- throttled: bump REL
- terminator: bump REL
- system-config-printer: bump REL
- solaar: bump REL

... and 30 more commits

Package(s) Affected
-------------------

Security Update?
----------------

No

Build Order
-----------

```
#buildit dbus-python a2jmidid avahi blueberry blueman cadence calibre cdemu-client cinnamon firewalld gajim gedit-plugins gpodder hplip ibus jack lvm2 mate-applets mate-dock-applet mate-hud meld mpdris2 mugshot musicbox notify2 onboard orca pyqt5 secretstorage slip snapper-gui solaar system-config-printer terminator throttled totem tuned variety virt-manager xboxdrv xpra
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-05-17 08:52 UTC, HouLiXieBuRou commented
amd64
avahi
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/beed3b66-69b1-4f16-b6d5-142d0ec82c99)
ladish
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/ad5088d6-f410-41c9-98c2-fdfc3513b6e3)
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/1eb83a2e-c669-4bb2-9288-e25693f36da2)
cadence
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/aeae639f-88c3-4b4e-a0e9-c61b8b07f88e)
xboxdrv
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/fd83cee8-95ac-4a13-b783-46aad00898bb)
a2jmidid
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/37a33744-6dd4-4b0e-ab5b-331c1cf80fe6)
zita....
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/104555544/cdd47412-4fae-4038-ac4e-698d418600a0)

2024-05-27 07:32 UTC, Cyanoxygen requested changes

2024-05-27 07:32 UTC, Cyanoxygen commented on app-multimedia/cadence/autobuild/build
> +
Please add informative output in this script.

2024-05-27 07:32 UTC, Cyanoxygen commented on app-network/avahi/autobuild/prepare
>  wget https://github.com/lathiat/avahi/raw/master/service-type-database/build-db \
This download must be handled by ACBS.

2024-05-27 07:32 UTC, Cyanoxygen commented on app-network/avahi/autobuild/prepare
> +export PYTHON=/usr/bin/python3
Please add extra output for this.

2024-05-28 05:39 UTC, Cyanoxygen approved these changes

2024-05-28 05:42 UTC, merged