rpcbind: update to 1.2.6
AOSC-Dev/aosc-os-abbs pull request #6074
Opened 2024-05-20 14:12 UTC by jiegec

Topic Description
-----------------

- rpcbind: update to 1.2.6
    Co-authored-by: Chen (@jiegec) <c@jia.je>

Package(s) Affected
-------------------

- rpcbind: 1.2.6

Security Update?
----------------

No

Build Order
-----------

```
#buildit rpcbind
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-05-20 14:37 UTC, MingcongBai requested changes

2024-05-20 14:37 UTC, MingcongBai commented on app-network/rpcbind/autobuild/patches/rpcbind-sunrpc.patch
This file name is not compliant with the Styling Manual. You should also make it a Git formatted patch so that people know what the point of this patch is.

2024-05-21 14:15 UTC, jiegec commented on app-network/rpcbind/autobuild/patches/rpcbind-sunrpc.patch
Dropped

2024-05-21 14:30 UTC, MingcongBai approved these changes

2024-05-21 14:30 UTC, merged