qtcreator: update to 13.0.1
AOSC-Dev/aosc-os-abbs pull request #6097
Opened 2024-05-20 16:58 UTC by jiegec

Topic Description
-----------------

- qtcreator: update to 13.0.1
    Co-authored-by: Chen (@jiegec) <c@jia.je>

Package(s) Affected
-------------------

- qtcreator: 13.0.1

Security Update?
----------------

No

Build Order
-----------

```
#buildit qtcreator
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-05-21 13:31 UTC, MingcongBai approved these changes

2024-05-21 13:33 UTC, MingcongBai requested changes
Does not launch.

```
qtcreator: error while loading shared libraries: libExtensionSystem.so.13: cannot open shared object file: No such file or directory
```

Possibly due to changes in our default RPATH flags.

2024-05-22 06:12 UTC, MingcongBai approved these changes

2024-05-22 06:13 UTC, merged

2024-05-23 07:40 UTC, jiegec commented
Fix upstreamed and merged: https://codereview.qt-project.org/c/qt-creator/qt-creator/+/562304