binutils+w64: update to 2.42
AOSC-Dev/aosc-os-abbs pull request #6225
Opened 2024-05-24 08:30 UTC by jiegec

Topic Description
-----------------

- binutils+w64: update to 2.42

Package(s) Affected
-------------------

- binutils+w64: 2.42

Security Update?
----------------

No

Build Order
-----------

```
#buildit binutils+w64
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-05-26 15:04 UTC, MingcongBai requested changes

2024-05-26 15:04 UTC, MingcongBai commented on runtime-optenvw64/binutils+w64/autobuild/build
>      mkdir $SRCDIR/binutils-${_target} && cd $SRCDIR/binutils-${_target}
Quote SRCDIR throughout.

2024-05-26 15:04 UTC, MingcongBai commented on runtime-optenvw64/binutils+w64/autobuild/build
>      make install DESTDIR=$PKGDIR
And PKGDIR.

2024-06-04 14:13 UTC, jiegec commented on runtime-optenvw64/binutils+w64/autobuild/build
>      mkdir $SRCDIR/binutils-${_target} && cd $SRCDIR/binutils-${_target}
Fixed

2024-06-04 14:13 UTC, jiegec commented on runtime-optenvw64/binutils+w64/autobuild/build
>      make install DESTDIR=$PKGDIR
Fixed.

2024-06-12 14:58 UTC, MingcongBai approved these changes

2024-06-12 14:58 UTC, merged