fcron: update to 3.3.1
AOSC-Dev/aosc-os-abbs pull request #6528
Opened 2024-06-05 07:13 UTC by jiegec

Topic Description
-----------------

- fcron: update to 3.3.1

Package(s) Affected
-------------------

- fcron: 3.3.1

Security Update?
----------------

No

Build Order
-----------

```
#buildit fcron
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-06-07 00:48 UTC, MingcongBai requested changes

2024-06-07 00:48 UTC, MingcongBai commented on app-admin/fcron/autobuild/prepare
>  getent group fcron >/dev/null || groupadd -g 33 fcron
23 or 33?

2024-06-07 00:54 UTC, MingcongBai commented
This pull request is expected to resolve #6393

2024-06-07 01:17 UTC, jiegec commented on app-admin/fcron/autobuild/prepare
>  getent group fcron >/dev/null || groupadd -g 33 fcron
Fixed

2024-06-07 01:26 UTC, OriginCode commented
@MingcongBai @jiegec It seems that the issue still persists.
![圖片](https://github.com/AOSC-Dev/aosc-os-abbs/assets/17294071/04e44d80-68e4-4797-a995-e73e58ff0151)

2024-06-12 14:06 UTC, MingcongBai approved these changes

2024-06-12 14:58 UTC, MingcongBai requested changes
Still broken:

```
2024-06-12 22:57:40 ERROR could not open file mingcongbai.orig.tmp: Permission denied
```

2024-06-13 06:27 UTC, jiegec commented
> Still broken:
> 
> ```
> 2024-06-12 22:57:40 ERROR could not open file mingcongbai.orig.tmp: Permission denied
> ```

The permission is correct if you have not installed the wrong version. The user id won't change if it was already created.

2024-06-13 21:10 UTC, OriginCode commented
> > Still broken:
> > ```
> > 2024-06-12 22:57:40 ERROR could not open file mingcongbai.orig.tmp: Permission denied
> > ```
> 
> The permission is correct if you have not installed the wrong version. The user id won't change if it was already created.

![圖片](https://github.com/AOSC-Dev/aosc-os-abbs/assets/17294071/d58117c2-1763-4176-8032-f8d8977be0c9)

Uhh, no?

2024-06-14 02:37 UTC, jiegec commented
> > > Still broken:
> > > ```
> > > 2024-06-12 22:57:40 ERROR could not open file mingcongbai.orig.tmp: Permission denied
> > > ```
> > 
> > 
> > The permission is correct if you have not installed the wrong version. The user id won't change if it was already created.
> 
> ![圖片](https://private-user-images.githubusercontent.com/17294071/339554036-d58117c2-1763-4176-8032-f8d8977be0c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzI5MzQsIm5iZiI6MTcxODMzMjYzNCwicGF0aCI6Ii8xNzI5NDA3MS8zMzk1NTQwMzYtZDU4MTE3YzItMTc2My00MTc2LTgwMzItZjhkODk3N2JlMGM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAyMzcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMzg0NmM4ZDkxNDk0ZmFmZTkxZmRiODZjOTU1YmI2NWE4YzZlOGQxMGExZTcyNWIzYzgwZTRmYTFlYzg4NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cqnZs8H8G__UPGleE_qmf8expq9xNkSIgFMlZyDrHsI)
> 
> Uhh, no?

Please check the fcron user id in your own system.

2024-06-14 07:42 UTC, OriginCode commented
> > > > Still broken:
> > > > ```
> > > > 2024-06-12 22:57:40 ERROR could not open file mingcongbai.orig.tmp: Permission denied
> > > > ```
> > > 
> > > 
> > > The permission is correct if you have not installed the wrong version. The user id won't change if it was already created.
> > 
> > 
> > ![圖片](https://private-user-images.githubusercontent.com/17294071/339554036-d58117c2-1763-4176-8032-f8d8977be0c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzI5MzQsIm5iZiI6MTcxODMzMjYzNCwicGF0aCI6Ii8xNzI5NDA3MS8zMzk1NTQwMzYtZDU4MTE3YzItMTc2My00MTc2LTgwMzItZjhkODk3N2JlMGM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAyMzcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMzg0NmM4ZDkxNDk0ZmFmZTkxZmRiODZjOTU1YmI2NWE4YzZlOGQxMGExZTcyNWIzYzgwZTRmYTFlYzg4NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cqnZs8H8G__UPGleE_qmf8expq9xNkSIgFMlZyDrHsI)
> > Uhh, no?
> 
> Please check the fcron user id in your own system.

`fcron:x:33:33::/var/spool/fcron:/bin/bash`

2024-06-19 01:54 UTC, jiegec commented
> > > > > Still broken:
> > > > > ```
> > > > > 2024-06-12 22:57:40 ERROR could not open file mingcongbai.orig.tmp: Permission denied
> > > > > ```
> > > > 
> > > > 
> > > > The permission is correct if you have not installed the wrong version. The user id won't change if it was already created.
> > > 
> > > 
> > > ![圖片](https://private-user-images.githubusercontent.com/17294071/339554036-d58117c2-1763-4176-8032-f8d8977be0c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzI5MzQsIm5iZiI6MTcxODMzMjYzNCwicGF0aCI6Ii8xNzI5NDA3MS8zMzk1NTQwMzYtZDU4MTE3YzItMTc2My00MTc2LTgwMzItZjhkODk3N2JlMGM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAyMzcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMzg0NmM4ZDkxNDk0ZmFmZTkxZmRiODZjOTU1YmI2NWE4YzZlOGQxMGExZTcyNWIzYzgwZTRmYTFlYzg4NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cqnZs8H8G__UPGleE_qmf8expq9xNkSIgFMlZyDrHsI)
> > > Uhh, no?
> > 
> > 
> > Please check the fcron user id in your own system.
> 
> `fcron:x:33:33::/var/spool/fcron:/bin/bash`

Then you will have to chown `/var/spool/fcron` to fcron manually. It was created with wrong UID as owner.

2024-06-19 01:57 UTC, MingcongBai commented
> > > > > > Still broken:
> > > > > > ```
> > > > > > 2024-06-12 22:57:40 ERROR could not open file mingcongbai.orig.tmp: Permission denied
> > > > > > ```
> > > > > 
> > > > > 
> > > > > The permission is correct if you have not installed the wrong version. The user id won't change if it was already created.
> > > > 
> > > > 
> > > > ![圖片](https://private-user-images.githubusercontent.com/17294071/339554036-d58117c2-1763-4176-8032-f8d8977be0c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzI5MzQsIm5iZiI6MTcxODMzMjYzNCwicGF0aCI6Ii8xNzI5NDA3MS8zMzk1NTQwMzYtZDU4MTE3YzItMTc2My00MTc2LTgwMzItZjhkODk3N2JlMGM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAyMzcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMzg0NmM4ZDkxNDk0ZmFmZTkxZmRiODZjOTU1YmI2NWE4YzZlOGQxMGExZTcyNWIzYzgwZTRmYTFlYzg4NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cqnZs8H8G__UPGleE_qmf8expq9xNkSIgFMlZyDrHsI)
> > > > Uhh, no?
> > > 
> > > 
> > > Please check the fcron user id in your own system.
> > 
> > 
> > `fcron:x:33:33::/var/spool/fcron:/bin/bash`
> 
> Then you will have to chown `/var/spool/fcron` to fcron manually. It was created with wrong UID as owner.

Can we use a `d` entry in `tmpfiles.d`?

See [tmpfiles.d(5)](https://man7.org/linux/man-pages/man5/tmpfiles.d.5.html)

2024-06-19 02:04 UTC, jiegec commented
To reiterate: the UID mismatch problem only exists because you have previously installed the buggy version. If you are installing fcron from a clean system, or upgraded from the current stable version, there are no issues.

2024-06-19 02:11 UTC, MingcongBai commented
> To reiterate: the UID mismatch problem only exists because you have previously installed the buggy version. If you are installing fcron from a clean system, or upgraded from the current stable version, there are no issues.

But wouldn't the `tmpfiles.d` configuration serve as a corrective in case there are any other permission problems?

2024-06-19 02:13 UTC, jiegec commented
> > To reiterate: the UID mismatch problem only exists because you have previously installed the buggy version. If you are installing fcron from a clean system, or upgraded from the current stable version, there are no issues.
> 
> But wouldn't the `tmpfiles.d` configuration serve as a corrective in case there are any other permission problems?

You can add it if you want to.

2024-06-19 05:52 UTC, OriginCode commented
LGTM on loongarch64:
![image](https://github.com/AOSC-Dev/aosc-os-abbs/assets/17294071/8be4c7f1-ccb6-473f-a11c-9aba01b10f27)

2024-06-19 05:52 UTC, OriginCode approved these changes

2024-06-19 05:55 UTC, MingcongBai approved these changes

2024-06-19 05:55 UTC, merged