lx-music-desktop: new, 2.8.0
AOSC-Dev/aosc-os-abbs pull request #6658
Opened 2024-06-15 08:05 UTC by xunpod

Topic Description
-----------------

- lx-music-desktop: new, 2.8.0

Package(s) Affected
-------------------

- lx-music-desktop: 2.8.0

Security Update?
----------------

No

Build Order
-----------

```
#buildit lx-music-desktop
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`

2024-06-17 15:31 UTC, MingcongBai commented
![图片](https://github.com/AOSC-Dev/aosc-os-abbs/assets/5006263/81e54ad2-33c6-49ce-b4e7-968b556467d4)

I don't seem to be able to play anything here.

2024-06-17 15:32 UTC, MingcongBai requested changes

2024-06-17 15:32 UTC, MingcongBai commented on app-multimedia/lx-music-desktop/autobuild/beyond
> +mkdir -pv "$PKGDIR"/usr/share/lx-music-desktop/
Use `install -Dvm644` here.

2024-06-17 15:32 UTC, MingcongBai commented on app-multimedia/lx-music-desktop/autobuild/defines
> +PKGPROV="lx-music"
Please mark FAIL_ARCH.

2024-06-17 15:32 UTC, MingcongBai commented on app-multimedia/lx-music-desktop/autobuild/overrides/usr/share/applications/lx-music-desktop.desktop
> +Name=LX Music
Localise this.

2024-06-17 15:32 UTC, MingcongBai commented on app-multimedia/lx-music-desktop/autobuild/defines
> +PKGDES="A music searching assistant and player based on Electon"
An Internet music streaming client and collection manager

2024-06-18 06:04 UTC, xunpod commented
> ![图片](https://private-user-images.githubusercontent.com/5006263/340362236-81e54ad2-33c6-49ce-b4e7-968b556467d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2ODkyMTcsIm5iZiI6MTcxODY4ODkxNywicGF0aCI6Ii81MDA2MjYzLzM0MDM2MjIzNi04MWU1NGFkMi0zM2M2LTQ5Y2UtYjRlNy05NjhiNTU2NDY3ZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMDUzNTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTBlZGI2NzVmYmZiNmE5NGU4MjY4ZTViZTQyNDdmMjRhNDY3YmM4OTViODQ5MjFiNDhjNWRlOTVlNDBiMTE0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BnVcEX1tyan9LiF7UqhsracA8x-HjVFdeY7Pb5ShWJE)
> 
> I don't seem to be able to play anything here.



> ![图片](https://private-user-images.githubusercontent.com/5006263/340362236-81e54ad2-33c6-49ce-b4e7-968b556467d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTA3MTUsIm5iZiI6MTcxODY5MDQxNSwicGF0aCI6Ii81MDA2MjYzLzM0MDM2MjIzNi04MWU1NGFkMi0zM2M2LTQ5Y2UtYjRlNy05NjhiNTU2NDY3ZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMDYwMDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzg3MTMwNDU1NjY3OWIxZTdmNDJiNWE1NjkzOWE5MzU1NTczYTdmMWE4ODliNWZlMTk4ZDMxMWU5ODAxNWFjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-a8L0cVEhAwugFrB5FsJgsckYliXeewdxOPvv3gLzZE)
> 
> I don't seem to be able to play anything here.

It's a normal phenomenon. Due to some reasons, a custom source is required for the first use.

2024-06-25 13:56 UTC, MingcongBai commented
Let's not introduce this package until the upstream figures out a way to make this software work out of the box.

2024-06-25 13:56 UTC, closed without merging