iodine: update to 0.8.0
AOSC-Dev/aosc-os-abbs pull request #7026
Opened 2024-07-16 05:23 UTC by SkyBird233

Topic Description
-----------------

- iodine: update to 0.8.0

Package(s) Affected
-------------------

- iodine: 0.8.0

Security Update?
----------------

No

Build Order
-----------

```
#buildit iodine
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-07-16 15:55 UTC, MingcongBai requested changes
Both services failed to launch, seems that the CLI usage has changed:

![image](https://github.com/user-attachments/assets/fcd573a9-811b-468d-8913-d23342e0bfee)

2024-07-17 12:38 UTC, SkyBird233 commented
> Both services failed to launch, seems that the CLI usage has changed

Services of iodine also require options defined in `/etc/sysconfig/iodine-{client,server}`. Works after defining them.

2024-07-19 13:56 UTC, MingcongBai commented
> > Both services failed to launch, seems that the CLI usage has changed
> 
> Services of iodine also require options defined in `/etc/sysconfig/iodine-{client,server}`. Works after defining them.

Then something should be defined before hand... If we can't, we'd need to write a debconf prompt for this package to instruct the user.

2024-07-20 04:02 UTC, SkyBird233 commented
I believe it's not meaningful to start iodine without the user's configuration, unless it's for local testing, as it necessitates setting up real subdomains. 

For reference, iodine-0.7.0 on AOSC OS, 0.8.0 on Arch Linux and 0.7.0 on Debian require additional configuration before starting iodine and its systemd services.

If prompts are still necessary in this case, could you pleasr provide some detailed suggestions?

2024-08-07 01:34 UTC, MingcongBai commented
> I believe it's not meaningful to start iodine without the user's configuration, unless it's for local testing, as it necessitates setting up real subdomains.
> 
> For reference, iodine-0.7.0 on AOSC OS, 0.8.0 on Arch Linux and 0.7.0 on Debian require additional configuration before starting iodine and its systemd services.
> 
> If prompts are still necessary in this case, could you pleasr provide some detailed suggestions?

I think at least a debconf prompt (please reference other packages with `autobuild/templates`) which points the user to relevant documentation and configuration files (what do the users need to change before starting the service?) would be good.

2024-08-13 07:08 UTC, MingcongBai requested changes

2024-08-13 07:08 UTC, MingcongBai commented on app-network/iodine/autobuild/templates
> +Description: Extra config required for iodine services
```
Description: Extra configuration required for iodine services
  Before you start iodine's client and server services via systemd, please edit the following files to your specific needs:
 .
 /etc/sysconfig/iodine-client: Client configuration.
 /etc/sysconfig/iodine-server: Server configuration.
 .
 For details on how to setup the aforementioned configurations, please see iodine(8).
Description-zh_CN.UTF-8: iodine 服务需要额外设置
 在启动 iodine 客户端或服务端前，您需要预先编辑如下配置文件：
 .
 /etc/sysconfig/iodine-client：客户端配置文件
 /etc/sysconfig/iodine-server：服务端配置文件
 .
 有关上述配置的编写方式，请详见 iodine(7)。
```

2024-08-13 07:08 UTC, MingcongBai commented on app-network/iodine/spec
>  SRCS="https://github.com/yarrick/iodine/archive/refs/tags/v$VER.tar.gz"
Use Git tag.

2024-08-13 07:31 UTC, MingcongBai approved these changes
LGTM on AMD64.

2024-08-13 07:34 UTC, merged