pcsx2: update to 2.0.3
AOSC-Dev/aosc-os-abbs pull request #7054
Opened 2024-07-17 01:26 UTC by MingcongBai

Topic Description
-----------------

- pcsx2: update to 2.0.3
    Co-authored-by: 白铭骢 (Mingcong Bai) (@MingcongBai) <jeffbai@aosc.io>

Package(s) Affected
-------------------

- pcsx2: 2.0.3

Security Update?
----------------

No

Build Order
-----------

```
#buildit pcsx2
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`

2024-07-17 14:11 UTC, StephDC commented
![pcsx2](https://github.com/user-attachments/assets/af60ea1d-eaae-4b47-960a-e5d345ae0e77)

Works, but somehow the window title still remained 1.7.0 (+git)

2024-07-17 18:22 UTC, stdmnpkg requested changes
not actually updated

2024-07-17 18:22 UTC, stdmnpkg commented on app-games/pcsx2/spec
>  SRCS="git::commit=${__COMMIT}::https://github.com/PCSX2/pcsx2"
consider use tag?

2024-10-05 15:01 UTC, jiegec approved these changes, later dismissed

2024-10-05 15:01 UTC, MingcongBai commented
This package would require a Vulkan stack upgrade to build.

2025-02-10 00:09 UTC, jiegec commented
Requires patched third party components, see https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pcsx2

2026-03-12 15:44 UTC, MingcongBai commented
To be superseded by 2.6.3.

2026-03-12 15:44 UTC, closed without merging