Chromium, Google Chrome: update to 126.0.6478.182
AOSC-Dev/aosc-os-abbs pull request #7058
Opened 2024-07-17 02:32 UTC by MingcongBai

Topic Description
-----------------

- google-chrome: update to 126.0.6478.182
- chromium: update to 126.0.6478.182

Package(s) Affected
-------------------

Security Update?
----------------

No

Build Order
-----------

```
#buildit chromium-google-chrome
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-07-18 02:25 UTC, jiegec commented
缺一个 patch：https://salsa.debian.org/chromium-team/chromium/-/blob/master/debian/patches/upstream/blink-header2.patch?ref_type=heads

2024-07-18 03:15 UTC, MingcongBai commented
> 缺一个 patch：https://salsa.debian.org/chromium-team/chromium/-/blob/master/debian/patches/upstream/blink-header2.patch?ref_type=heads

多谢，我重试下

2024-07-19 13:43 UTC, Cyanoxygen commented
Tested on amd64.
![image](https://github.com/user-attachments/assets/ae4d92f5-ecc9-4bac-918c-d6536c070035)

2024-07-19 13:43 UTC, MingcongBai reviewed
Tested good on LoongArch: 

![图片](https://github.com/user-attachments/assets/10986011-ebd9-4e19-8d0e-ecc90743e08c)

2024-07-19 13:45 UTC, Cyanoxygen requested changes

2024-07-19 13:45 UTC, Cyanoxygen commented on app-web/chromium/autobuild/patches/wget-log
> +--2024-07-18 11:14:52--  https://salsa.debian.org/chromium-team/chromium/-/raw/master/debian/patches/upstream/blink-header2.patch?ref_type=heads
Wait! you can not put `wget-log` in the source tree. It is a log file.

2024-07-19 13:55 UTC, Cyanoxygen approved these changes

2024-07-19 13:55 UTC, merged