verilator: update to 5.026
AOSC-Dev/aosc-os-abbs pull request #7060
Opened 2024-07-17 02:42 UTC by rickliu2000

Topic Description
-----------------

- verilator: update to 5.026

Package(s) Affected
-------------------

- verilator: 5.026

Security Update?
----------------

No

Build Order
-----------

```
#buildit verilator
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-07-19 13:40 UTC, MingcongBai requested changes

2024-07-19 13:40 UTC, MingcongBai commented on app-electronics/verilator/autobuild/build
Why? This package seems to come with a genuine Autotools build system.

2024-07-20 14:06 UTC, MingcongBai approved these changes

2024-07-20 14:08 UTC, MingcongBai requested changes
Builds are failing.

2024-07-20 14:44 UTC, rickliu2000 commented
> Builds are failing.

Builds are passing now.

2024-07-20 14:46 UTC, MingcongBai approved these changes

2024-07-20 15:12 UTC, merged

2024-07-20 15:12 UTC, rickliu2000 commented
Merged，closing