tesseract: update to 5.4.1
AOSC-Dev/aosc-os-abbs pull request #7141
Opened 2024-07-19 08:37 UTC by BC204

Topic Description
-----------------

- opencv: bump REL due to tesseract update
- tesseract: update to 5.4.1
    - Fix the wrong anitya id
    - modify path of tesseract_fast in beyond

Package(s) Affected
-------------------

- opencv: 4.9.0-3
- tesseract: 5.4.1

Security Update?
----------------

No

Build Order
-----------

```
#buildit tesseract opencv
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-07-30 03:18 UTC, BC204 commented
Test on amd

Example picture
![musicbox-0 3 1](https://github.com/user-attachments/assets/3ac8a7a3-431b-4979-a88a-bdc5b225c659)

Test result
![tesseract-5 4 1](https://github.com/user-attachments/assets/040a9a8a-5656-47a6-8e30-cbeace1084fa)

2024-07-30 03:24 UTC, MingcongBai requested changes
Wow, what a soname...

```
 0x000000000000000e (SONAME)             Library soname: [libtesseract.so.5.4.1]
```

However, according to the [Packages site](https://packages.aosc.io/revdep/tesseract), you seem to be missing rebuilds. Please also update the PKGBREAK line in `defines`.

2024-08-13 02:52 UTC, MingcongBai requested changes
Tested good on LoongArch

2024-08-13 02:52 UTC, MingcongBai commented on app-utils/tesseract/autobuild/beyond
> +pushd ../tessdata_fast
This should be `"$SRCDIR"/../tessdata_fast`.

2024-08-13 07:32 UTC, MingcongBai approved these changes

2024-08-13 07:33 UTC, merged