Core 11.4.4
AOSC-Dev/aosc-os-abbs pull request #7222
Opened 2024-07-22 13:51 UTC by Fearyncess

Topic Description
-----------------

- aosc-aaa: update to 11.4.4
- glibc: change name resolution behavior in nsswitch.conf
    - Replace mdns with mdns_minimal as we don't need to resolve non-local domains.
    - Use resolve module before dns.
    - Use systemd-resolved instead of resolvconf.

Package(s) Affected
-------------------

- aosc-aaa: 11.4.4
- glibc: 1:2.38-4

Security Update?
----------------

No

Build Order
-----------

```
#buildit glibc aosc-aaa
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [x] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-07-23 06:41 UTC, MingcongBai requested changes
Non-local IPv6 pings still delayed by seconds before returning ~50ms latencies.

![图片](https://github.com/user-attachments/assets/8b07ec05-3757-40c3-92c5-8cda278e5fcd)

2024-07-23 16:12 UTC, KexyBiscuit commented
#7230 merged into this.

2024-07-25 16:06 UTC, MingcongBai approved these changes
Approving as others can't reproduce my issue. Let's address my specific issue in the next release.

2024-07-26 07:13 UTC, KexyBiscuit approved these changes

2024-07-27 06:11 UTC, merged