xorg-server: backport patches from upstream master branch
AOSC-Dev/aosc-os-abbs pull request #7284
Opened 2024-07-27 07:38 UTC by Icenowy

Topic Description
-----------------

- xorg-server: backport a bunch of patches from xserver master
    These backports majorly affects glamor and modesetting DDX.
    Significant things include proper Glamor GLES support, Modesetting DDX
    TearFree.
    Some bugfix-alike patches are backported too.
    Signed-off-by: Icenowy Zheng <uwu@icenowy.me>

Package(s) Affected
-------------------

- xorg-server: 21.1.13+backport

Security Update?
----------------

No

Build Order
-----------

```
#buildit xorg-server
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

2024-07-29 06:34 UTC, eatradish approved these changes

2024-07-29 07:07 UTC, MingcongBai requested changes
Tests pending. There is a lot of changes in this topic and we should be more cautious.

Blocking for feedback.

2024-07-30 03:36 UTC, OriginCode commented
LGTM on amd64:
![圖片](https://github.com/user-attachments/assets/b705f4da-da46-47df-be98-617e1321efae)

2024-08-04 11:36 UTC, Icenowy commented
Going to switch to an as-needed backporting policy.

2024-08-04 11:36 UTC, closed without merging