git-filter-repo: new, 2.45.0
AOSC-Dev/aosc-os-abbs pull request #7458
Opened 2024-08-02 15:12 UTC by xtexChooser

Topic Description
-----------------

- git-filter-repo: new, 2.45.0
- git-extras: new, 7.2.0

Package(s) Affected
-------------------

- git-filter-repo: 2.45.0

Security Update?
----------------

No

Build Order
-----------

```
#buildit git-filter-repo
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] Architecture-independent `noarch`

2024-08-04 10:42 UTC, OriginCode requested changes

2024-08-04 10:42 UTC, OriginCode commented on app-devel/git-filter-repo/autobuild/build
> +
Remove the empty line.

2024-08-04 10:42 UTC, OriginCode commented on app-devel/git-filter-repo/autobuild/defines
> +
Same.

2024-08-04 10:42 UTC, OriginCode commented on app-devel/git-filter-repo/autobuild/patch
> +
Same too.

2024-08-06 14:43 UTC, MingcongBai requested changes

2024-08-06 14:43 UTC, MingcongBai commented on app-devel/git-filter-repo/autobuild/build
> +cd "$SRCDIR"
This is not necessary, every script starts from this location.

2024-08-06 14:43 UTC, MingcongBai commented on app-devel/git-filter-repo/autobuild/patch
> +abinfo "Applying patches ..."
This file is not necessary, Autobuild applies all patches in autobuild/patches/ sequentially.

2024-08-06 21:46 UTC, OriginCode requested changes

2024-08-06 21:46 UTC, OriginCode commented on app-devel/git-filter-repo/autobuild/defines
> +PKGDEP="git"
Looks like it depends on Python too?

2024-08-07 23:00 UTC, OriginCode approved these changes, later dismissed

2024-08-12 05:17 UTC, eatradish approved these changes, later dismissed

2024-08-12 09:10 UTC, OriginCode approved these changes, later dismissed

2024-08-12 09:14 UTC, OriginCode approved these changes

2024-08-12 09:14 UTC, OriginCode approved these changes

2024-08-12 09:14 UTC, MingcongBai approved these changes

2024-08-12 09:14 UTC, merged