git-absorb: new, 0.6.15
AOSC-Dev/aosc-os-abbs pull request #7459
Opened 2024-08-02 15:53 UTC by xtexChooser

Topic Description
-----------------

- git-absorb: new, 0.6.15

Package(s) Affected
-------------------

- git-absorb: 0.6.15

Security Update?
----------------

No

Build Order
-----------

```
#buildit git-absorb
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-08-04 10:45 UTC, OriginCode requested changes

2024-08-04 10:45 UTC, OriginCode commented on app-devel/git-absorb/autobuild/defines
> +NOLTO=1
Why NOLTO? Explain your reason in a FIXME comment.

2024-08-07 23:02 UTC, OriginCode requested changes, later dismissed

2024-08-07 23:02 UTC, OriginCode commented on app-devel/git-absorb/autobuild/defines
> +NOLTO=1
Then we only need to disable LTO for loongson3. Use `NOLTO__LOONGSON3=1` instead.

2024-08-14 10:13 UTC, xtexChooser commented
LGTM on amd64
![image](https://github.com/user-attachments/assets/dbe949b5-7a68-4b9a-b1a5-b8bf1ea9c8b6)

2024-08-14 10:13 UTC, MingcongBai approved these changes

2024-08-14 10:18 UTC, merged