botan-3: new, 3.5.0
AOSC-Dev/aosc-os-abbs pull request #7469
Opened 2024-08-03 07:35 UTC by xtexChooser

Topic Description
-----------------

- botan-3: new, 3.5.0

Package(s) Affected
-------------------

- botan-3: 3.5.0

Security Update?
----------------

No

Build Order
-----------

```
#buildit botan-3
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-08-03 08:21 UTC, xtexChooser commented
tested on amd64
![image](https://github.com/user-attachments/assets/c149b133-97c9-43fa-b323-26d84af6b6b4)
also tested building keepassxc (#7462) against botan-3.

2024-08-06 14:13 UTC, MingcongBai reviewed
File conflicts:

```
正在解压 botan-3 (3.5.0) ...
dpkg: 处理归档 /var/cache/apt/archives/botan-3_3.5.0_loongarch64.deb (--unpack)时出错：
 正试图覆盖 /usr/share/man/man1/botan.1.xz，它同时被包含于软件包 botan-2 2.12.1-1
在处理时有错误发生：
 /var/cache/apt/archives/botan-3_3.5.0_loongarch64.deb
```

2024-08-06 14:14 UTC, MingcongBai requested changes

2024-08-06 14:14 UTC, MingcongBai commented on runtime-cryptography/botan-3/autobuild/beyond
> +
Extraneous newline.

2024-08-06 14:14 UTC, MingcongBai commented on runtime-cryptography/botan-3/autobuild/beyond
> +mv "$PKGDIR"/usr/bin/botan "$PKGDIR"/usr/bin/botan3
Missing verbosity.

2024-08-06 14:14 UTC, MingcongBai commented on runtime-cryptography/botan-3/autobuild/build
> +./configure.py --prefix=/usr \
Missing absolute path and abinfo.

2024-08-06 14:14 UTC, MingcongBai commented on runtime-cryptography/botan-3/autobuild/build
> +
Extraneous newline.

2024-08-06 14:14 UTC, MingcongBai commented on runtime-cryptography/botan-3/autobuild/defines
> +
Extraneous newline.

2024-08-07 08:31 UTC, closed without merging