git-interactive-rebase-tool: new, 2.4.1
AOSC-Dev/aosc-os-abbs pull request #7472
Opened 2024-08-03 12:29 UTC by xtexChooser

Topic Description
-----------------

- git-interactive-rebase-tool: new, 2.4.1

Package(s) Affected
-------------------

- git-interactive-rebase-tool: 2.4.1

Security Update?
----------------

No

Build Order
-----------

```
#buildit git-interactive-rebase-tool
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-08-03 13:14 UTC, eatradish requested changes, later dismissed

2024-08-03 13:14 UTC, eatradish commented on app-devel/git-interactive-rebase-tool/autobuild/defines
> +
Useless empty line

2024-08-03 13:14 UTC, eatradish commented on app-devel/git-interactive-rebase-tool/spec
> +
Useless empty line

2024-08-03 14:05 UTC, xtexChooser commented
lgtm on amd64
![image](https://github.com/user-attachments/assets/d5e6b7ef-5cce-4dbb-a057-e09ed9a5989f)

2024-08-06 13:57 UTC, MingcongBai requested changes

2024-08-06 13:57 UTC, MingcongBai commented on app-devel/git-interactive-rebase-tool/autobuild/prepare
> +export RUSTFLAGS="$RUSTFLAGS -Clink-args=-fuse-ld=bfd"
Why was this needed? Please leave a "# FIXME:" comment.

2024-08-14 10:14 UTC, MingcongBai approved these changes

2024-08-15 00:31 UTC, merged