passt: new, 2024.07.26
AOSC-Dev/aosc-os-abbs pull request #7480
Opened 2024-08-04 08:44 UTC by xtexChooser

Topic Description
-----------------

- passt: new, 2024.07.26

Package(s) Affected
-------------------

- passt: 2024.07.26

Security Update?
----------------

No

Build Order
-----------

```
#buildit passt
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-08-04 12:20 UTC, xtexChooser commented
tested on amd64
https://github.com/AOSC-Dev/aosc-os-abbs/pull/7477#issuecomment-2267523459

2024-08-06 10:02 UTC, eatradish requested changes

2024-08-06 10:02 UTC, eatradish commented on app-network/passt/autobuild/defines
> +PKGDEP=""
remove it?

2024-08-06 10:08 UTC, eatradish approved these changes

2024-08-06 10:08 UTC, merged