mangohud: update to 0.7.2
AOSC-Dev/aosc-os-abbs pull request #7592
Opened 2024-08-08 10:52 UTC by OriginCode

Topic Description
-----------------

- mangohud+32: update to 0.7.2
    Signed-off-by: Kaiyang Wu <origincode@aosc.io>
- mangohud: update to 0.7.2
    Signed-off-by: Kaiyang Wu <origincode@aosc.io>
- nlohmann-json+32: new, 3.11.3
    Signed-off-by: Kaiyang Wu <origincode@aosc.io>
- wayland+32: new, 1.23.0
    Signed-off-by: Kaiyang Wu <origincode@aosc.io>

Package(s) Affected
-------------------

- mangohud: 0.7.2

Security Update?
----------------

No

Build Order
-----------

```
#buildit mangohud
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-08-08 11:29 UTC, OriginCode commented
LGTM on amd64:
![圖片](https://github.com/user-attachments/assets/7618308f-5aea-48cf-a38a-6335f95cde77)

2024-08-08 16:25 UTC, MingcongBai requested changes

2024-08-08 16:25 UTC, MingcongBai commented on runtime-optenv32/nlohmann-json+32/autobuild/build
> +ln -sv /usr/include/nlohmann "$PKGDIR"/opt/32/include/nlohmann
Use relative paths for symlinks for avoid cross-contamination when accessing the rootfs from an external system.

2024-08-08 16:25 UTC, MingcongBai commented on runtime-optenv32/nlohmann-json+32/autobuild/defines
> +ABHOST=noarch
This should be `ABHOST=optenv32`.

2024-08-09 01:24 UTC, MingcongBai approved these changes

2024-08-09 01:24 UTC, merged