dust: new, 1.1.1
AOSC-Dev/aosc-os-abbs pull request #7604
Opened 2024-08-09 09:34 UTC by purofle

Topic Description
-----------------

- dust: new, 1.1.1

Package(s) Affected
-------------------

- dust: new, 1.1.1

Security Update?
----------------

No

Build Order
-----------

```
#buildit dust
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

Architectural progress for secondary ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-08-10 04:44 UTC, eatradish requested changes

2024-08-10 04:44 UTC, eatradish commented on app-utils/dust/autobuild/defines
> +PKGDES="A more intuitive version of du in rust"
```
saki@MagMilk [ oma@master ] $ ldd /home/saki/.cargo/bin/dust
        linux-vdso.so.1 (0x00007fbc39920000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fbc395d6000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fbc39200000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fbc39922000)
```

Add `PKGDEP="glibc gcc-runtime"`

2024-08-10 04:46 UTC, eatradish requested changes

2024-08-10 04:46 UTC, eatradish commented on app-utils/dust/autobuild/defines
> +ABSPLITDBG=0
Why?

2024-08-11 09:30 UTC, eatradish commented
LGTM on AMD64:

![图片](https://github.com/user-attachments/assets/3c73b865-36e2-403d-a9a5-8e7bf148448b)

2024-08-11 10:09 UTC, eatradish commented
Also LGTM in AArch64 and LoongArch64

2024-08-11 10:09 UTC, eatradish approved these changes, later dismissed

2024-08-11 10:10 UTC, MingcongBai requested changes

2024-08-11 10:10 UTC, MingcongBai commented on app-utils/dust/autobuild/defines
> +PKGDES="A more intuitive version of du in rust"
A TUI disk usage analyzer

2024-08-11 10:10 UTC, MingcongBai commented on app-utils/dust/autobuild/defines
> +# FIXME: ld.lld is not support loongson3
FIXME: ld.lld is not yet available.

2024-08-11 10:12 UTC, MingcongBai approved these changes

2024-08-11 10:12 UTC, merged