tuned: update to 2.24.0
AOSC-Dev/aosc-os-abbs pull request #7630
Opened 2024-08-11 05:35 UTC by MingcongBai

Topic Description
-----------------

- tuned: update to 2.24.0
    Co-authored-by: 白铭骢 (Mingcong Bai) (@MingcongBai) <jeffbai@aosc.io>

Package(s) Affected
-------------------

- tuned: 2.24.0

Security Update?
----------------

No

Build Order
-----------

```
#buildit tuned
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] Architecture-independent `noarch`

2024-11-06 09:10 UTC, OriginCode requested changes

2024-11-06 09:10 UTC, OriginCode commented on app-admin/tuned/spec
>  SRCS="tbl::https://github.com/redhat-performance/tuned/archive/refs/tags/v$VER.tar.gz"
Use git source.

2024-12-03 06:05 UTC, KexyBiscuit commented on app-admin/tuned/spec
>  SRCS="tbl::https://github.com/redhat-performance/tuned/archive/refs/tags/v$VER.tar.gz"
Done.

2024-12-08 16:55 UTC, OriginCode approved these changes

2024-12-09 00:39 UTC, OriginCode commented
As suggested by @q234rty , we may also include `tuned-ppd` by using `make install-ppd` in the build file and mark this package as conflicting with power-profiles-daemon.

2025-01-11 02:50 UTC, MingcongBai commented
> As suggested by @q234rty , we may also include `tuned-ppd` by using `make install-ppd` in the build file and mark this package as conflicting with power-profiles-daemon.

Let's work on this later.

2025-01-11 02:50 UTC, merged