systemd: disable tint-by-default in *spawn and in systemd-run
AOSC-Dev/aosc-os-abbs pull request #7663
Opened 2024-08-12 14:29 UTC by MingcongBai

Topic Description
-----------------

- systemd: disable tint-by-default in *spawn and in systemd-run
    Let's face it, it's weird and we have much better ways to notify the user
    about a system running in a container. Change the default behavior (tint by
    default) to only tint when the user specifies a --background= parameter.

Package(s) Affected
-------------------

- systemd: 1:256.4-1

Security Update?
----------------

No

Build Order
-----------

```
#buildit systemd
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-08-14 10:55 UTC, MingcongBai commented
Background works, but `--background` seems not to function properly (no matter what color was specified, the background was always tinted blue).

![图片](https://github.com/user-attachments/assets/ac03eaea-480b-417e-80c8-06d89bf30b58)

2024-08-15 04:54 UTC, KexyBiscuit requested changes

2024-08-15 04:54 UTC, KexyBiscuit commented on app-admin/systemd/autobuild/patches/0002-presets-disable-systemd-networkd-systemd-networkd-wa.patch
> ++disable systemd-resolved.service
Why is this patch still around?

2024-08-15 04:56 UTC, KexyBiscuit commented on app-admin/systemd/autobuild/patches/0002-presets-disable-systemd-networkd-systemd-networkd-wa.patch
> ++disable systemd-resolved.service
@OriginCode No consensus was made around this, please revert this patch. Also, move **systemd-networkd** presets to **aosc-os-presets-base** package.

2024-08-15 04:59 UTC, KexyBiscuit commented on app-admin/systemd/autobuild/patches/0002-presets-disable-systemd-networkd-systemd-networkd-wa.patch
> ++disable systemd-resolved.service
@MingcongBai patches have been updated, please rebase this.

2024-08-17 09:20 UTC, KexyBiscuit approved these changes

2024-08-18 00:24 UTC, OriginCode commented
LGTM on amd64:
![圖片](https://github.com/user-attachments/assets/bdbc4fad-0783-44dd-b3ef-0be77285ee2d)

2024-08-18 00:24 UTC, merged