ffmpeg (FFmpeg): update to 7.0.2
AOSC-Dev/aosc-os-abbs pull request #7710
Opened 2024-08-15 15:41 UTC by MingcongBai

Topic Description
-----------------

Update FFmpeg to 7.0.2 and rebuild reverse dependencies as needed.

Package(s) Affected
-------------------

- aegisub: 3.2.2+git20231203-2
- akode: 14.1.2-2
- alsa-plugins: 1.2.12-1
- aubio: 0.4.9-4
- audacious: 4.4-4
- blender: 4.0.2-3
- chromaprint: 1.5.1-1
- cmus: 2.11.0-2
- corsixth: 1:0.67-1
- ddnet: 18.4-1
- deadbeef: 1.9.6-2
- digikam: 8.4.0-2
- dolphin-emu: 1:2407-2
- ffmpeg: 7.0.2
- ffmpegthumbnailer: 2.2.2-1
- ffmpegthumbs: 23.08.5-1
- ffms2: 5.0
- freerdp: 2:3.6.3
- gegl-0.4: 0.4.48-2
- gnome-boxes: 42.3-2
- goldendict: 1:1.5.0-1
- gpac: 2.4.0
- gstreamer: 1.24.7
- gtk-4: 4.14.2-1
- gtk-update-icon-cache: 4.14.2-1
- guvcview: 2.1.0-1
- haruna: 0.12.3-2
- harvid: 0.9.1
- k3b: 23.08.5-2
- k3b-trinity: 14.1.2-2
- k9copy-trinity: 14.1.2-1
- kfilemetadata: 5.115.0-1
- kid3: 3.9.5
- kodi: 1:21.1
- kpipewire: 5.27.11-1
- libde265: 1.0.8-4
- makemkv: 1.17.7
- mgba: 0.10.3-1
- mixxx: 2.4.1-4
- mlt: 7.26.0
- mocp: 2.6.0~svn.r3005
- moonlight-embedded: 2.5.3-2
- moonlight-qt: 4.3.0-2
- mpd: 0.23.15-6
- mplayer: 1:1.5
- mpv: 0.38.0-1
- neatvnc: 0.7.1-1
- obs-studio: 30.2.3-1
- openmw: 0.48.0+git20240902
- openscenegraph: 3:3.6.5-4
- osu-lazer: 2024.817.0-1
- owntone: 28.9-2
- pipewire: 1.2.3-1
- ppsspp: 1.17.1-1
- qmmp: 1.6.5-2
- qt-5: 1:5.15.13+webengine5.15.16+webkit5.212.0+kde20240408-6
- qt-5-doc: 1:5.15.13+webengine5.15.16+webkit5.212.0+kde20240408-6
- qt-6: 6.7.2-3
- remmina: 1.4.35
- scrcpy: 2.4-1
- simplescreenrecorder: 0.4.4
- telegram-desktop: 5.4.1
- tigervnc: 1.14.0+xserver21.1.13
- tracker-miners: 3.3.1-3
- unpaper: 1:7.0.0
- vlc: 3.0.21-3
- weston: 13.0.3
- xine-lib: 1.2.13-2
- xjadeo: 0.8.13-1
- xpra: 6.1.2

Security Update?
----------------

No

Build Order
-----------

```
#buildit ffmpeg:-pkgbreak groups/ffmpeg-rebuilds groups/ffms2-rebuilds groups/freerdp-rebuilds tigervnc ffmpeg
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

2024-09-05 05:56 UTC, MingcongBai commented
Building manually to avert unstable Internet connections on some buildbots.

2024-09-13 22:44 UTC, OriginCode commented
Smoke tests on amd64:
blender
![圖片](https://github.com/user-attachments/assets/bcf94613-9f3e-4c98-a52a-887501377002)
mixxx
![圖片](https://github.com/user-attachments/assets/2c06d372-ceb6-4e23-85e5-869516812e19)
guvcview
![圖片](https://github.com/user-attachments/assets/9689a7e2-467e-43d8-9e30-c535ba087c46)
scrcpy
![圖片](https://github.com/user-attachments/assets/ba4d7e0f-e14a-4107-aabe-c22ed33d8a24)
unpaper (I don't have scanned files)
![圖片](https://github.com/user-attachments/assets/5cfb5bfc-e1d0-4888-9a41-b2311281bf31)
corsixth
![圖片](https://github.com/user-attachments/assets/68bb2fc6-b49c-4da1-a7c0-f1baad9a32b4)
ddnet
![圖片](https://github.com/user-attachments/assets/02f4382f-f976-41fe-900b-f8b5ecd14ce9)
dolphin-emu
![圖片](https://github.com/user-attachments/assets/198c43c4-3354-469b-baa3-23aef02fc006)
mgba
![圖片](https://github.com/user-attachments/assets/20d1a9db-4ced-42fc-82c5-13167fa383f6)
osu-lazer
![圖片](https://github.com/user-attachments/assets/b5afd174-21ed-4d9b-b0a0-2e80f6911f35)
ppsspp
![圖片](https://github.com/user-attachments/assets/d05d00eb-65b2-4c6c-824f-e5993c37c83d)
goldendict
![圖片](https://github.com/user-attachments/assets/a9e490e7-98b1-46d3-808a-c0c38f87d886)
aubio (No valid test files)
![圖片](https://github.com/user-attachments/assets/b911307f-9327-4617-926d-d9151734fbd7)
cmus
![圖片](https://github.com/user-attachments/assets/49c1916c-81f3-4f67-8097-3ecb9f415d11)
deadbeef
![圖片](https://github.com/user-attachments/assets/748ea939-ad2b-4bdb-8009-81ef19821e1d)
ffmpegthumbnailer
![圖片](https://github.com/user-attachments/assets/1dc568c5-72f5-40d2-9247-e6b9fb0f5443)
aegisub **SIGSEGV**
![圖片](https://github.com/user-attachments/assets/0d78e4aa-d5a2-439f-9191-33bd5096c139)
gpac **Black screen on amd64, SIGSEGV on loongarch64**
harvid (No test env)
![圖片](https://github.com/user-attachments/assets/bb994441-dbdd-48d0-8b5a-e037cce472c6)
kid3
![圖片](https://github.com/user-attachments/assets/590bd583-454c-478c-ae4b-d3e6de8ac8e9)

2024-09-19 08:39 UTC, OriginCode commented
makemkv (**PENDING DROP, ORPHANING**)
![圖片](https://github.com/user-attachments/assets/598669f5-d5d9-430d-abe1-137f9d7eff59)
mocp
![圖片](https://github.com/user-attachments/assets/b6a68c3c-3a81-4e6f-a225-19b89354d746)
moonlight-embedded
![圖片](https://github.com/user-attachments/assets/af5acde2-90ec-49f8-8877-66cf297618dc)
moonlight-qt
![圖片](https://github.com/user-attachments/assets/9ae7776f-3370-4ab0-9d6a-797c4c38b994)
mpd
![圖片](https://github.com/user-attachments/assets/a0e9afb4-392b-4cae-997d-259d17dd7e39)
mpv
![圖片](https://github.com/user-attachments/assets/6407a855-b1bc-4646-bb3c-f64cebae6fb6)
obs-studio
![圖片](https://github.com/user-attachments/assets/1a57f19a-8eb7-4c44-b38f-4172a3442c4c)
owntone
![圖片](https://github.com/user-attachments/assets/6a95cfaf-233e-4903-8f72-98c6d25008b8)
pipewire: working
qmmp
![圖片](https://github.com/user-attachments/assets/c0c6af72-e7a9-4a54-8833-ecf5262b8780)

2024-09-19 08:59 UTC, OriginCode commented
simplescreenrecorder
![Screenshot_20240919_015857](https://github.com/user-attachments/assets/3a8b640b-3441-4da0-a558-327b19e915ab)

2024-09-19 09:14 UTC, OriginCode commented
vlc
![圖片](https://github.com/user-attachments/assets/0c74fa2f-844f-433d-a656-7d87eb660eb8)
xjadeo
![圖片](https://github.com/user-attachments/assets/891cc695-3471-40b0-b06b-64412cd62d4a)
freerdp
![圖片](https://github.com/user-attachments/assets/1dcb28a1-6246-4416-bf21-c114ea4e3170)
remmina
![圖片](https://github.com/user-attachments/assets/4af97e35-a59f-4d62-b1ca-eea796e14d9d)
gnome-boxes (**SIGTRAP, conflicting symbols**)
![圖片](https://github.com/user-attachments/assets/dfa4a523-695b-411d-a819-26c1fdf1a97a)
xpra (**Need copy-repo**)
![圖片](https://github.com/user-attachments/assets/e08af922-1fa7-40d3-97df-02fb410f00af)
telegram-desktop
![圖片](https://github.com/user-attachments/assets/13f85f5f-6598-43ac-81e9-c60096170a1d)
tracker-miners (**No test env**)

2024-09-20 08:29 UTC, OriginCode commented
k3b
![圖片](https://github.com/user-attachments/assets/37c847d6-58bb-43b6-abb7-80930021ef2c)
digikam
![圖片](https://github.com/user-attachments/assets/51194649-6eb5-4e40-b2c6-c8479cddcb84)
k3b-trinity
![圖片](https://github.com/user-attachments/assets/ff38d9b4-00cc-4509-8229-40572da290f3)
k9copy-trinity
![圖片](https://github.com/user-attachments/assets/90517dcc-1b53-4b55-9073-cfafed8fc31a)
synfig (**Missing reworked package**)
openmw (**Installs 3rd party software, and fails to do so**)
![圖片](https://github.com/user-attachments/assets/e4670b57-0ee4-4e63-a179-f6e426dba1c6)
![圖片](https://github.com/user-attachments/assets/6306e8e4-341e-47a9-b27d-99fd0c6a6205)
kodi (**Black screen when playing video, audio works**)
![圖片](https://github.com/user-attachments/assets/e614c0c7-c9bd-4aab-8171-e46ceefd0e05)
audacious
![圖片](https://github.com/user-attachments/assets/24e8d881-8e3a-4e16-b06a-0f518b734856)
mplayer
![圖片](https://github.com/user-attachments/assets/173e22d5-7400-4175-9954-09e2bd20371b)
hmcl
![圖片](https://github.com/user-attachments/assets/576d48ea-7c71-477a-add9-216d7b2adb7c)
openscenegraph
![圖片](https://github.com/user-attachments/assets/ea99dcf9-e58e-4479-9bbb-c6a367088000)
tigervnc (**Missing font?**)
![圖片](https://github.com/user-attachments/assets/805d33f6-72af-4f2c-b750-f50813d14c3b)

2024-09-24 12:04 UTC, MingcongBai commented
>  tigervnc (Missing font?)

@OriginCode `vncviewer` is fine here:

![图片](https://github.com/user-attachments/assets/8d8e7cbe-81d0-424e-9a24-473e1df33e00)

2024-09-24 13:27 UTC, MingcongBai commented
Fixed OpenMW:

![图片](https://github.com/user-attachments/assets/33d344e1-d3c9-4385-9100-b55d654f8e08)

`gnome-boxes` and `makemkv` has been dropped.

2024-09-24 13:30 UTC, MingcongBai commented
@OriginCode KODI works well for me here (Wayland issue?):

![图片](https://github.com/user-attachments/assets/a98cbd47-848e-4dbd-a20d-09fd85c9cb01)

2024-09-24 13:32 UTC, MingcongBai commented
Neither `aegisub` nor `gpac` segfault'd on AMD64, but the latter did segfault on LoongArch. Hmm.

2024-09-28 09:46 UTC, OriginCode commented
> Neither `aegisub` nor `gpac` segfault'd on AMD64, but the latter did segfault on LoongArch. Hmm.

`aegisub` does not work with native Wayland, upstream issue https://github.com/Aegisub/Aegisub/issues/180
Use `GDK_BACKEND=x11` to force it use X11 as a workaround.

2024-09-28 10:26 UTC, OriginCode commented
> @OriginCode KODI works well for me here (Wayland issue?):
> 
> ![图片](https://private-user-images.githubusercontent.com/5006263/370303944-a98cbd47-848e-4dbd-a20d-09fd85c9cb01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MTc1OTUsIm5iZiI6MTcyNzUxNzI5NSwicGF0aCI6Ii81MDA2MjYzLzM3MDMwMzk0NC1hOThjYmQ0Ny04NDhlLTRkYmQtYTIwZC0wOWZkODVjOWNiMDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjhUMDk1NDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjc0YTY0MDE5MWE0NjRkYzhiYWE0MWRlMjNkZGRjNTg3MjYxY2MzMjIzY2U0ODQwNzgwMzRkMDIxNDAzMDI0ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2dniotXgsUeZpxhWYcjvKU_OODGxXvTZQgjAfSHO0eM)

Workaround supplying `--viewing=X11` to force it using X11 on Wayland works.

2024-09-28 16:02 UTC, MingcongBai commented
Dropping gpac (and ogmrip as a result), the latter is barely maintained and is the sole dependee.

This topic should be good to go. cc @OriginCode

2024-09-28 21:06 UTC, OriginCode requested changes

2024-09-28 21:06 UTC, OriginCode commented on app-multimedia/ffmpegthumbnailer/autobuild/defines
> -ABTYPE=cmake
Why removing `ABTYPE`?

2024-09-29 03:19 UTC, MingcongBai commented on app-multimedia/ffmpegthumbnailer/autobuild/defines
> -ABTYPE=cmake
Fixed. I meant to specify `cmakeninja`.

2024-09-29 03:50 UTC, OriginCode approved these changes

2024-09-29 03:50 UTC, merged

2024-10-06 06:03 UTC, jiegec reviewed
gnome-remote-desktop needs to be removed from gnome-base as well.