kanshi: new, 1.7.0
AOSC-Dev/aosc-os-abbs pull request #7775
Opened 2024-08-23 09:51 UTC by OriginCode

Topic Description
-----------------

- kanshi: new, 1.7.0
    Signed-off-by: Kaiyang Wu <origincode@aosc.io>
- libscfg: new, 0.1.1
    Signed-off-by: Kaiyang Wu <origincode@aosc.io>

Package(s) Affected
-------------------

- kanshi: 1.7.0
- libscfg: 0.1.1

Security Update?
----------------

No

Build Order
-----------

```
#buildit libscfg kanshi
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-08-23 10:23 UTC, OriginCode commented
LGTM on amd64:
![圖片](https://github.com/user-attachments/assets/814f167f-7744-498d-9d4f-09b4dcbd97d8)

2024-08-24 01:45 UTC, MingcongBai requested changes

2024-08-24 01:45 UTC, MingcongBai commented on app-utils/kanshi/autobuild/overrides/usr/lib/systemd/user/kanshi.service
> +ExecCondition=/bin/sh -c '[ -n "$WAYLAND_DISPLAY" ]'
Seems weird but okay...

2024-08-24 01:45 UTC, MingcongBai commented on runtime-common/libscfg/autobuild/defines
> +PKGDES="A C library for scfg"
What is scfg?

2024-08-24 10:42 UTC, MingcongBai approved these changes

2024-08-24 10:43 UTC, merged