split lxgwnewcleargothic and lxgwfasmartgothic font
AOSC-Dev/aosc-os-abbs pull request #7783
Opened 2024-08-24 19:32 UTC by stdmnpkg

Topic Description
-----------------

- lxgwnewcleargothic-font: update to 1.200
- lxgwfasmartgothic-font: new, 1.200, split from lxgwnewcleargothic-font

Package(s) Affected
-------------------

Security Update?
----------------

No

Build Order
-----------

```
#buildit lxgwfasmartgothic-font lxgwnewcleargothic-font
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-08-25 10:04 UTC, eatradish requested changes, later dismissed
Should create a transitional package and recommend NeoXiHei and Fasmartgothic?

2024-08-26 01:57 UTC, MingcongBai requested changes

2024-08-26 01:57 UTC, MingcongBai commented on desktop-fonts/lxgwfasmartgothic-font/autobuild/defines
> +PKGBREAK="lxgwnewcleargothic<=1.124"
Wrong package name reference:

```
dpkg: 处理归档 /tmp/apt-dpkg-install-AXSBep/08-lxgwneoxihei-font_1.200~pre20240825T192121Z_all.deb (--unpack)时出错：
 正试图覆盖 /usr/share/fonts/TTF/LxgwNeoXiHei-Book.ttf，它同时被包含于软件包 lxgwnewcleargothic-font 1.124
```

2024-08-26 01:57 UTC, MingcongBai commented on desktop-fonts/lxgwneoxihei-font/autobuild/defines
> +PKGBREAK="lxgwnewcleargothic<=1.124"
Ditto.

2024-08-29 01:24 UTC, MingcongBai approved these changes
Tested good on LoongArch.

2024-08-29 01:24 UTC, merged