intel-compute-runtime: update to 24.31.30508.7
AOSC-Dev/aosc-os-abbs pull request #7877
Opened 2024-09-02 20:27 UTC by ouankou

Topic Description
-----------------

- intel-compute-runtime: update to 24.31.30508.7
    Dependencies:
    - intel-graphics-compiler: update to 1.0.17384.11
    - metee: update to 4.2.0
    - igsc: update to 0.9.3
    - level-zero: update to 1.17.39
    - intel-gmmlib: update to 22.5.1

Package(s) Affected
-------------------

Security Update?
----------------

No

Build Order
-----------

```
#buildit intel-gmmlib metee igsc level-zero intel-graphics-compiler intel-compute-runtime
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-09-02 21:10 UTC, ouankou commented
Tested on  14900K.

```bash
ouankou@yoimiya [ ~ ] $ clinfo -l
Platform #0: Intel(R) OpenCL Graphics
 `-- Device #0: Intel(R) Graphics [0xa780]
Platform #1: rusticl

ouankou@yoimiya [ ~ ] $ clpeak

Platform: Intel(R) OpenCL Graphics
  Device: Intel(R) Graphics [0xa780]
    Driver version  : 24.31.30508 (Linux x64)
    Compute units   : 32
    Clock frequency : 1650 MHz

    Global memory bandwidth (GBPS)
      float   : 39.52
      float2  : 39.83
      float4  : 40.43
      float8  : 37.68
      float16 : 31.50

    Single-precision compute (GFLOPS)
      float   : 823.94
      float2  : 814.15
      float4  : 820.08
      float8  : 520.79
      float16 : 517.08

    Half-precision compute (GFLOPS)
      half   : 1597.66
      half2  : 1582.61
      half4  : 1597.32
      half8  : 1587.30
      half16 : 1445.09

    No double precision support! Skipped

    Integer compute (GIOPS)
      int   : 277.72
      int2  : 187.51
      int4  : 179.07
      int8  : 170.23
      int16 : 206.67

    Integer compute Fast 24bit (GIOPS)
      int   : 277.63
      int2  : 187.52
      int4  : 179.10
      int8  : 170.25
      int16 : 206.68

    Transfer bandwidth (GBPS)
      enqueueWriteBuffer              : 20.59
      enqueueReadBuffer               : 18.94
      enqueueWriteBuffer non-blocking : 19.53
      enqueueReadBuffer non-blocking  : 18.99
      enqueueMapBuffer(for read)      : 397682.16
        memcpy from mapped ptr        : 18.76
      enqueueUnmap(after write)       : 3579139.25
        memcpy to mapped ptr          : 20.13

    Kernel launch latency : 160.39 us
```

2024-09-03 01:38 UTC, MingcongBai requested changes
Code looks fine but please split the commits - one package each.

2024-09-03 02:07 UTC, ouankou commented
> Code looks fine but please split the commits - one package each.

Done. The changes are split into six commits, one for each package.

2024-09-03 02:14 UTC, MingcongBai approved these changes

2024-09-03 03:00 UTC, merged