trivy: new, 0.55.0
AOSC-Dev/aosc-os-abbs pull request #7935
Opened 2024-09-07 14:33 UTC by xtexChooser

Topic Description
-----------------

- trivy: new, 0.55.0
- goreleaser: new, 2.2.0

Package(s) Affected
-------------------

Security Update?
----------------

No

Build Order
-----------

```
#buildit goreleaser trivy
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-09-08 00:22 UTC, xtexChooser commented
LGTM on AMD64

![image](https://github.com/user-attachments/assets/738161c8-037c-463c-a957-905aecb9c5f7)

2024-09-09 06:14 UTC, MingcongBai requested changes

2024-09-09 06:14 UTC, MingcongBai commented on app-devel/trivy/autobuild/build
> +chmod +x "$PKGDIR"/usr/bin/trivy
Verbosity here.

2024-09-22 15:06 UTC, MingcongBai approved these changes

2024-09-22 15:07 UTC, merged