kitty: update to 0.36.2
AOSC-Dev/aosc-os-abbs pull request #7951
Opened 2024-09-09 10:50 UTC by OriginCode

Topic Description
-----------------

- kitty: update to 0.36.2
    Co-authored-by: Kaiyang Wu (@OriginCode) <self@origincode.me>

Package(s) Affected
-------------------

- kitty: 0.36.2

Security Update?
----------------

No

Build Order
-----------

```
#buildit kitty
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-09-09 10:57 UTC, OriginCode commented
Requires `Symbols Nerd Font Mono` font for BUILDDEP.

2024-09-09 11:17 UTC, OriginCode commented
LGTM on amd64:
![圖片](https://github.com/user-attachments/assets/6e5d3de8-3a43-4cdc-9966-97d3fb3b1b48)

2024-09-09 16:36 UTC, MingcongBai requested changes

2024-09-09 16:36 UTC, MingcongBai commented on desktop-fonts/symbols-nerd-font/autobuild/build
> +install -Dm644 -t "$PKGDIR"/usr/share/fonts/TTF "$SRCDIR"/*.ttf
Verbosity and abinfo please.

2024-09-10 01:04 UTC, MingcongBai approved these changes

2024-09-10 01:04 UTC, merged