openjdk-23: new, 23+ga
AOSC-Dev/aosc-os-abbs pull request #8025
Opened 2024-09-17 14:53 UTC by xtexChooser

Topic Description
-----------------

- openjfx-23: new, 23+ga
- openjdk-23: new, 23+ga

Package(s) Affected
-------------------

- openjdk-23: 3:23+ga
- openjfx-23: 23+ga

Security Update?
----------------

No

Build Order
-----------

```
#buildit openjdk-23 openjfx-23
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-09-17 15:55 UTC, xtexChooser commented
LGTM on AMD64 by starting Minecraft 1.21 vanilla

2024-09-18 14:47 UTC, MingcongBai commented
Tested good with Minecraft on LoongArch.

2024-09-18 14:48 UTC, MingcongBai requested changes

2024-09-18 14:48 UTC, MingcongBai commented on lang-java/openjfx-23/autobuild/gradle.properties
> +
Extraneous newline.

2024-09-18 14:48 UTC, MingcongBai commented on lang-java/openjfx-23/autobuild/defines
> +PKGDES="Open source implementation of JavaFX"
Please add "(version 23)" or something similar.

2024-09-18 14:48 UTC, MingcongBai commented on lang-java/openjfx-23/autobuild/defines
> +PKGDEP="openjfx-common ffmpeg gst-plugins-base-1-0 gtk-2 openjdk qt-5 webkit2gtk"
Use `gstreamer` for all GStreamer dependencies.

2024-09-18 14:48 UTC, MingcongBai commented on lang-java/openjdk-23/autobuild/defines.stage2
> +PKGDES="OpenJDK Java Runtime Environment (JRE), Java Development Environment (JDK), and IcedTea-Web"
Please mark version in description - also, are you sure that IcedTea is included?

2024-09-21 09:49 UTC, MingcongBai approved these changes

2024-09-21 09:59 UTC, merged