Core 11.6.0
AOSC-Dev/aosc-os-abbs pull request #8043
Opened 2024-09-19 14:28 UTC by MingcongBai

Topic Description
-----------------

- aosc-aaa: update to 11.6.0
- glibc: add recommends for glibc-legacy
    Optional dependency for legacy compatibility.
- glibc-legacy: new
    This package provides legacy compatibility symlinks for removed glibc sonames.
- isl: update to 0.27
- aosc-aaa: change sysctl parameters
    - Remove inappropriate kernel.pid_max, net.ipv4.tcp_tw_recycle parameters.
    - Remove nonexistent net.ipv6.conf.all.rp_filter parameter.
    Ref: https://github.com/AOSC-Dev/aosc-os-abbs/issues/8020

Package(s) Affected
-------------------

- aosc-aaa: 11.6.0
- glibc: 1:2.38-7
- glibc-legacy: 0
- isl: 1:0.27

Security Update?
----------------

No

Build Order
-----------

```
#buildit isl glibc-legacy glibc aosc-aaa
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-09-19 14:29 UTC, eatradish approved these changes, later dismissed

2024-09-20 09:08 UTC, MingcongBai commented
Tested good on LoongArch, JetBrains IntelliJ IDEA launches out-of-the-box (previously requiring `libutil.so`:

![Screenshot_20240920_170438](https://github.com/user-attachments/assets/5a6177d3-06c6-4273-be1a-9b57c2b2d4a0)

Also, no more errors from `systemd-sysctl.service`.

2024-09-20 09:11 UTC, KexyBiscuit requested changes
```shell
kexybiscuit@ProArtB550-CREATOR [ ~ ] $ cd /usr/lib/legacy/glibc/
kexybiscuit@ProArtB550-CREATOR [ glibc ] $ ls -al
total 8
drwxr-xr-x 2 root root 4096 Sep 20 17:10 .
drwxr-xr-x 3 root root 4096 Sep 20 17:10 ..
lrwxrwxrwx 1 root root   12 Sep 19 22:33 libanl.so.1 -> ../libc.so.6
lrwxrwxrwx 1 root root   12 Sep 19 22:33 libdl.so.2 -> ../libc.so.6
lrwxrwxrwx 1 root root   12 Sep 19 22:33 libnsl.so.1 -> ../libc.so.6
lrwxrwxrwx 1 root root   12 Sep 19 22:33 librt.so.1 -> ../libc.so.6
lrwxrwxrwx 1 root root   12 Sep 19 22:33 libutil.so.1 -> ../libc.so.6
kexybiscuit@ProArtB550-CREATOR [ glibc ] $ file libanl.so.1
libanl.so.1: broken symbolic link to ../libc.so.6
```

2024-09-20 09:11 UTC, KexyBiscuit commented on core-libs/glibc-legacy/autobuild/build
> +    ln -sv ../libc.so.6 \
```suggestion
    ln -sv ../../libc.so.6 \
```

2024-09-20 09:23 UTC, KexyBiscuit approved these changes
LGTM.

```shell
kexybiscuit@ProArtB550-CREATOR [ ~ ] $ file /usr/lib/legacy/glibc/libutil.so.1
/usr/lib/legacy/glibc/libutil.so.1: symbolic link to ../../libc.so.6
kexybiscuit@ProArtB550-CREATOR [ ~ ] $ ldd /usr/lib/legacy/glibc/libutil.so.1
        /usr/lib/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f8ac9932000)
        linux-vdso.so.1 (0x00007ffe239c9000)
kexybiscuit@ProArtB550-CREATOR [ ~ ] $ ldd /usr/lib/libc.so.6
        /usr/lib/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f2d599cb000)
        linux-vdso.so.1 (0x00007ffedb7ee000)
```

2024-09-20 09:26 UTC, merged