bottles: update to 51.13
AOSC-Dev/aosc-os-abbs pull request #8068
Opened 2024-09-23 09:02 UTC by BC204

Topic Description
-----------------

- bottles: update to 51.13
    Add PKGDEP and BUILDDEP

Package(s) Affected
-------------------

- bottles: 51.13

Security Update?
----------------

No

Build Order
-----------

```
#buildit bottles
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] Architecture-independent `noarch`

2024-09-24 01:49 UTC, MingcongBai requested changes

2024-09-24 01:49 UTC, MingcongBai commented on app-utils/bottles/autobuild/defines
>  ABHOST=noarch
Bump Epoch as 51 < 2022.

2025-01-20 07:33 UTC, xtexChooser approved these changes, later dismissed

2025-01-20 09:31 UTC, BC204 commented
Test on amd64
![bottles-51 13](https://github.com/user-attachments/assets/3f74a524-4391-4ed6-a810-3170f4c03d5d)

2025-02-26 02:41 UTC, BC204 commented
Last week, bottles were able to play _SCP - Containment Breach_ normally, but after the system update, for some reason, the following error message appeared, waiting to be fixed.
![FileNo](https://github.com/user-attachments/assets/2f8cdc39-e7d2-465e-bd6a-d9b5dd3cf992)
![wait](https://github.com/user-attachments/assets/0860bd23-7e95-444c-9099-92f6218b7663)

2025-03-05 08:12 UTC, closed without merging