cloud-init: update to 24.3.1
AOSC-Dev/aosc-os-abbs pull request #8090
Opened 2024-09-25 18:19 UTC by leavelet

Topic Description
-----------------

- cloud-init: update to 24.3.1

Package(s) Affected
-------------------

- cloud-init: 24.3.1

Security Update?
----------------

No

Build Order
-----------

```
#buildit cloud-init
```

Test Build(s) Done
------------------

2024-09-25 18:23 UTC, KexyBiscuit reviewed
LGTM, pending test results.

2024-09-25 18:35 UTC, leavelet commented
> LGTM, pending test results.

I will test it on the new cloud images. Maybe we don't need to merge for now.

2024-10-17 17:17 UTC, stdmnpkg requested changes
not works on my  x86-64 virtual machine, nothing has been set by it

![image](https://github.com/user-attachments/assets/6a7900ef-872e-4c7d-aea8-4a12e4c410d8)

2024-10-17 18:19 UTC, leavelet commented
Found an issue, we should add nc.openbsd to its dependency
https://github.com/canonical/cloud-init/issues/5809

2025-02-07 16:44 UTC, leavelet commented
Closed as bump to 24.4.1

2025-02-07 16:50 UTC, closed without merging