tenacity: new, 1.3.3
AOSC-Dev/aosc-os-abbs pull request #8137
Opened 2024-10-01 09:29 UTC by Icenowy

Topic Description
-----------------

- tenacity: new, 1.3.3
    Signed-off-by: Icenowy Zheng <uwu@icenowy.me>

Package(s) Affected
-------------------

- tenacity: 1.3.3

Security Update?
----------------

No

Build Order
-----------

```
#buildit tenacity
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-10-01 09:44 UTC, Icenowy commented
![图片](https://github.com/user-attachments/assets/1165244e-14f7-4764-893e-0727b77fdb48)

Smoke test on AMD64.

2024-10-01 13:26 UTC, MingcongBai requested changes

2024-10-01 13:26 UTC, MingcongBai commented on app-creativity/tenacity/autobuild/beyond
> +rm -v "$PKGDIR"/usr/share/pixmaps/gnome-mime-application-x-audacity-project.xpm
Please consider making this an alternative, lest the file manager would not be able to show the correct icon for associated MIME types.

2025-11-17 10:32 UTC, stydxm commented
close for stale

2025-11-17 10:32 UTC, closed without merging