waylyrics: new, 0.3.16
AOSC-Dev/aosc-os-abbs pull request #8153
Opened 2024-10-03 13:00 UTC by xtexChooser

Topic Description
-----------------

- waylyrics: new, 0.3.16

Package(s) Affected
-------------------

- waylyrics: 0.3.16

Security Update?
----------------

No

Build Order
-----------

```
#buildit waylyrics
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-10-04 00:45 UTC, xtexChooser commented
Tested-by: ~~~

![image](https://github.com/user-attachments/assets/f3aa497d-577e-4fe9-94fc-c414f78358bd)

2024-10-05 13:26 UTC, MingcongBai requested changes

2024-10-05 13:26 UTC, MingcongBai commented on app-multimedia/waylyrics/autobuild/beyond
> +cp -r "$SRCDIR"/res/icons "$PKGDIR"/usr/share/icons
Verbosity here.

2024-10-05 13:26 UTC, MingcongBai commented on app-multimedia/waylyrics/autobuild/beyond
> +cp -r "$SRCDIR"/themes "$PKGDIR"/usr/share/waylyrics/themes
Verbosity here.

2024-10-05 15:44 UTC, MingcongBai approved these changes

2024-10-05 15:44 UTC, merged