[RC] linux-kernel: update to 6.10.13-rc1
AOSC-Dev/aosc-os-abbs pull request #8157
Opened 2024-10-04 05:01 UTC by KexyBiscuit

Topic Description
-----------------

- kernel-tools: update to 6.10.13-rc1
    - Synchronize patches from linux-kernel.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux+kernel: update to 6.10.13
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel: update to 6.10.13-rc1
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.10.13-rc1, current HEAD is 1ff3c61179459176de07d47c3714f9c32fc75da5.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>

Package(s) Affected
-------------------

- kernel-tools: 6.10.13-0.1
- linux+kernel: 3:6.10.13
- linux-kernel-${__VER}: 1:6.10.13-0.1

Security Update?
----------------

No

Build Order
-----------

```
#buildit linux-kernel linux+kernel kernel-tools
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-10-04 08:00 UTC, KexyBiscuit commented
Smoke testing passed on AMD64 generation 2, AMD64 generation 1 and Armv8-A generation 2 Hyper-V VMs.

![image](https://github.com/user-attachments/assets/2034ef33-4150-4eb7-ba0a-adadef5fc42d)
![image](https://github.com/user-attachments/assets/d369efd8-0840-423b-b160-aced5e3a0ee0)
![image](https://github.com/user-attachments/assets/4e6ef407-63fe-46f4-a336-554d74d6ff2f)

2024-10-04 08:12 UTC, KexyBiscuit commented
Smoke testing passed on AMD64 VMware VM.

- Product: VMware® Workstation 17 Pro
- Version: 17.6.0 build-24238078
- Host OS version: Windows 11 Enterprise, 64-bit (Build 27718.1000) 10.0.27718
- Accelerate 3D graphics: on
- Firmware type: UEFI
- Host VBS Mode: on

![image](https://github.com/user-attachments/assets/7737cb47-a6cd-4bc5-81f0-ac74a4f89513)

2024-10-04 08:37 UTC, KexyBiscuit commented
![图片](https://github.com/user-attachments/assets/3e40b46d-1f0f-4c3c-a212-3f0764f79091)

2024-10-04 09:31 UTC, KexyBiscuit commented
![图片](https://github.com/user-attachments/assets/73144a95-dc8d-41ca-87c8-8eea22ca6fe5)

2024-10-04 10:18 UTC, KexyBiscuit commented
![图片](https://github.com/user-attachments/assets/fef59334-f896-440f-ac93-d15bf6ecbd03)

2024-10-04 10:56 UTC, KexyBiscuit commented
![图片](https://github.com/user-attachments/assets/e7adce42-2de5-4193-8b39-56ba7bd8ad0e)

2024-10-04 11:08 UTC, KexyBiscuit commented
![图片](https://github.com/user-attachments/assets/e8d5a8f9-fd8b-4ebd-8d64-b31c62bbd4f6)

2024-10-04 11:20 UTC, KexyBiscuit commented
![图片](https://github.com/user-attachments/assets/c4af58b2-cd6a-437b-89a4-2763e1ec97f5)

2024-10-05 03:38 UTC, KexyBiscuit commented
Smoke testing passed on AMD64 VMware VM with 6.10.13.

2024-10-08 03:32 UTC, MingcongBai requested changes

2024-10-08 03:32 UTC, MingcongBai commented on runtime-kernel/linux-kernel/autobuild/ppc64el/config
Hmm, we sure about this?

2024-10-08 03:39 UTC, MingcongBai commented
Tested good on LoongArch (THTF Chaorui L680-T2).

2024-10-08 05:55 UTC, KexyBiscuit commented on runtime-kernel/linux-kernel/autobuild/ppc64el/config
In https://github.com/torvalds/linux/commit/44ac4625ea002deecd0c227336c95b724206c698, the config is marked as broken.

2024-10-08 05:57 UTC, MingcongBai approved these changes

2024-10-08 05:57 UTC, merged