[RC] linux-kernel-lts: update to 6.6.54-rc2
AOSC-Dev/aosc-os-abbs pull request #8158
Opened 2024-10-04 05:50 UTC by KexyBiscuit

Topic Description
-----------------

- linux+kernel+lts: update to 6.6.54
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel-lts: update to 6.6.54-rc2
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.6.54-rc2, current HEAD is 8af09869134566852395b8aea9b2640106dc51e6.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>

Package(s) Affected
-------------------

- linux+kernel+lts: 2:6.6.54
- linux-kernel-lts-${__VER}: 6.6.54-0.2

Security Update?
----------------

No

Build Order
-----------

```
#buildit linux-kernel-lts linux+kernel+lts
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-10-04 08:03 UTC, KexyBiscuit commented
Smoke testing passed on AMD64 generation 2, AMD64 generation 1 and Armv8-A generation 2 Hyper-V VMs.

![image](https://github.com/user-attachments/assets/ea6b6425-a98c-4271-9a86-b8e8c9d110a9)
![image](https://github.com/user-attachments/assets/538a18ee-0c57-4c4c-ab27-a9cb69914fb9)
![image](https://github.com/user-attachments/assets/147fa4d0-dd0b-44f8-a662-c4cc350e33e8)

2024-10-04 08:14 UTC, KexyBiscuit commented
Smoke testing passed on AMD64 VMware VM.

- Product: VMware® Workstation 17 Pro
- Version: 17.6.0 build-24238078
- Host OS version: Windows 11 Enterprise, 64-bit (Build 27718.1000) 10.0.27718
- Accelerate 3D graphics: on
- Firmware type: UEFI
- Host VBS Mode: on

![image](https://github.com/user-attachments/assets/34cff6f3-3fb3-4dcd-9fa8-d48fa36a6d19)

2024-10-04 08:41 UTC, KexyBiscuit commented
![图片](https://github.com/user-attachments/assets/a2485a63-108c-4f6a-922d-272dd52a07e4)

2024-10-04 09:34 UTC, KexyBiscuit commented
![图片](https://github.com/user-attachments/assets/99cb384c-89de-45cb-97bf-a93ae30a5601)

2024-10-04 10:21 UTC, KexyBiscuit commented
![图片](https://github.com/user-attachments/assets/697957d1-5f2a-47b6-a23e-7b2e6dfdf0fa)

2024-10-04 10:58 UTC, KexyBiscuit commented
![图片](https://github.com/user-attachments/assets/cb060623-5825-4379-bdab-6bc8007c9246)

2024-10-04 11:10 UTC, KexyBiscuit commented
![图片](https://github.com/user-attachments/assets/4e425562-8396-49f4-88ec-ba14a9948e59)

2024-10-04 11:22 UTC, KexyBiscuit commented
![图片](https://github.com/user-attachments/assets/4df97a63-42f7-4fd8-b8cd-ca6cf11b195b)

2024-10-05 03:39 UTC, KexyBiscuit commented
Smoke testing passed on AMD64 VMware VM with 6.6.54.

2024-10-08 03:33 UTC, MingcongBai requested changes

2024-10-08 03:33 UTC, MingcongBai commented on runtime-kernel/linux-kernel-lts/autobuild/ppc64el/config
Ditto from mainline, is this intended?

2024-10-08 03:39 UTC, MingcongBai commented
Tested good on LoongArch (THTF Chaorui L680-T2).

2024-10-08 05:55 UTC, KexyBiscuit commented on runtime-kernel/linux-kernel-lts/autobuild/ppc64el/config
In https://github.com/torvalds/linux/commit/44ac4625ea002deecd0c227336c95b724206c698, the config is marked as broken.

2024-10-08 05:57 UTC, MingcongBai approved these changes

2024-10-08 05:57 UTC, merged