httpie: update to 3.2.3
AOSC-Dev/aosc-os-abbs pull request #8161
Opened 2024-10-04 15:28 UTC by stdmnpkg

Topic Description
-----------------

- httpie: update to 3.2.3
    Co-authored-by: (@stdmnpkg)

Package(s) Affected
-------------------

- httpie: 3.2.3

Security Update?
----------------

No

Build Order
-----------

```
#buildit httpie
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] Architecture-independent `noarch`

2024-10-04 15:30 UTC, stdmnpkg commented
fix [CVE-2023-48052](https://nvd.nist.gov/vuln/detail/CVE-2023-48052)

> Missing SSL certificate validation in HTTPie v3.2.2 allows attackers to eavesdrop on communications between the host and server via a man-in-the-middle attack.

2024-10-05 08:42 UTC, stdmnpkg commented
works, or more exactly, as broken as previous version on my loongarch64 machine.

additional dependency required, at least require `rich`, also require `pygments` 2.12 which we are on 2.10, ssl cert verification always failed

2024-10-05 13:24 UTC, MingcongBai commented
> works, or more exactly, as broken as previous version on my loongarch64 machine.
> 
> additional dependency required, at least require `rich`, also require `pygments` 2.12 which we are on 2.10, ssl cert verification always failed

Please address at least the dependency issues in this topic.

2024-10-10 20:35 UTC, stdmnpkg commented
works on my x86-64 machine

![image](https://github.com/user-attachments/assets/60f06bd0-fd35-4369-903f-08d3b59c650f)

2024-10-10 20:37 UTC, KexyBiscuit requested changes

2024-10-10 20:37 UTC, KexyBiscuit commented on app-web/httpie/autobuild/defines
> +PKGDEP="rich defusedxml multidict pygments pysocks requests toolbelt rich"
Redundant dependencies.

2024-10-10 20:39 UTC, KexyBiscuit approved these changes
LGTM.

2024-10-10 21:07 UTC, merged