godot: add loongarch64 support
AOSC-Dev/aosc-os-abbs pull request #8162
Opened 2024-10-04 20:09 UTC by stdmnpkg

Topic Description
-----------------

- godot: add loongarch64 support

Package(s) Affected
-------------------

- godot: 4.3-1

Security Update?
----------------

No

Build Order
-----------

```
#buildit godot
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-10-04 20:22 UTC, stdmnpkg commented
see also https://github.com/godotengine/godot/pull/97822

2024-10-05 13:23 UTC, MingcongBai requested changes

2024-10-05 13:23 UTC, MingcongBai commented on app-devel/godot/autobuild/build
> +elif [[ "${CROSS:-$ARCH}" = "loongarch64" ]]; then
Use `ab_match_arch` instead.

2024-10-06 22:43 UTC, OriginCode approved these changes

2024-10-07 16:43 UTC, stdmnpkg commented
works on my x86-64 machine

![image](https://github.com/user-attachments/assets/c2168ec3-08a2-41d0-86b6-49dd15362bc8)

2024-10-07 16:49 UTC, stdmnpkg commented
works on my loongarch64 machine

![图片](https://github.com/user-attachments/assets/0f50ee00-750a-4546-92e7-9c5e1fc0b80c)
![图片](https://github.com/user-attachments/assets/fddbf6c0-b68b-4fb3-9a9f-6d53dcb3928a)

2024-10-08 01:50 UTC, MingcongBai approved these changes

2024-10-08 01:50 UTC, merged