kmscon: improve default configuration
AOSC-Dev/aosc-os-abbs pull request #8268
Opened 2024-10-11 06:41 UTC by MingcongBai

Topic Description
-----------------

- kmscon: improve default configuration
    - Introduce a template for all per-session configurations.
    - Enable hardware acceleration by default to improve performance.
- kmscon: enable hwaccel by default

Package(s) Affected
-------------------

- kmscon: 9.0.0-2

Security Update?
----------------

No

Build Order
-----------

```
#buildit kmscon
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-10-16 04:39 UTC, KexyBiscuit commented
Smoke testing passed on AMD64 generation 2, AMD64 generation 1 and Armv8-A generation 2 Hyper-V VMs.

2024-10-16 04:47 UTC, KexyBiscuit commented
Smoke testing passed on AMD64 VMware VM.

- Product: VMware® Workstation 17 Pro
- Version: 17.6.1 build-24319023
- Host OS version: Windows 11 Enterprise, 64-bit (Build 27723.1000) 10.0.27723
- Accelerate 3D graphics: on
- Firmware type: UEFI
- Host VBS Mode: on

2024-10-16 05:27 UTC, KexyBiscuit commented
Smoke testing passed on 战神Z8-KP7S2 with Optimus on.
Smoke testing FAILED on 战神Z8-KP7S2 with NVIDIA graphics only, same as before.

2024-10-16 07:03 UTC, KexyBiscuit commented
Smoke testing passed on RedmiBook 16 (锐龙版).

2024-10-16 07:03 UTC, KexyBiscuit commented
Smoke testing passed on Surface Pro (5th Gen).

2024-10-16 07:27 UTC, KexyBiscuit commented
Smoke testing passed on ROG Ally (2023).

2024-10-16 07:34 UTC, KexyBiscuit commented
Smoke testing passed on Latitude D630.

2024-10-16 08:07 UTC, KexyBiscuit approved these changes
Smoke testing passed on 8 amd64 and 1 arm64 test systems.

Tested-by: Kexy Biscuit <kexybiscuit@aosc.io>

2024-10-16 08:07 UTC, KexyBiscuit requested changes, later dismissed
Smoke testing FAILED on 战神Z8-KP7S2 with NVIDIA graphics only, log attached.

https://github.com/AOSC-Dev/aosc-os-abbs/pull/8268#issuecomment-2415764081

2025-05-28 02:06 UTC, MingcongBai commented
> Smoke testing FAILED on 战神Z8-KP7S2 with NVIDIA graphics only, log attached.
> 
> [#8268 (comment)](https://github.com/AOSC-Dev/aosc-os-abbs/pull/8268#issuecomment-2415764081)

Should be good now, as we now enable modesetting on NVIDIA (`nvidia_drm`).

2025-05-28 02:10 UTC, neko205-mx commented
Works well in both discrete GPU direct connection and hybrid output modes.

NVIDIA GeForce RTX 3050 Laptop

 i5-12450H

2025-05-28 02:11 UTC, neko205-mx approved these changes

2025-05-28 02:13 UTC, merged