nestopia: update to 1.52.1
AOSC-Dev/aosc-os-abbs pull request #8311
Opened 2024-10-15 14:32 UTC by MingcongBai

Topic Description
-----------------

- nestopia: update to 1.52.1
    Co-authored-by: 白铭骢 (Mingcong Bai) (@MingcongBai) <jeffbai@aosc.io>

Package(s) Affected
-------------------

- nestopia: 1.52.1

Security Update?
----------------

No

Build Order
-----------

```
#buildit nestopia
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-10-17 09:51 UTC, OriginCode requested changes

2024-10-17 09:51 UTC, OriginCode commented on app-games/nestopia/spec
>  SRCS="tbl::https://github.com/0ldsk00l/nestopia/archive/refs/tags/$VER.tar.gz"
Use git source.

2024-10-22 06:24 UTC, MingcongBai commented on app-games/nestopia/spec
>  SRCS="tbl::https://github.com/0ldsk00l/nestopia/archive/refs/tags/$VER.tar.gz"
Addressed.

2024-10-22 06:36 UTC, MingcongBai commented
Tested good on AMD64:

![图片](https://github.com/user-attachments/assets/03745354-3595-40ca-84c7-19d4eba85287)

2024-10-22 06:37 UTC, OriginCode approved these changes

2024-10-22 06:38 UTC, merged