sunshine: let hardware decoding support by default
AOSC-Dev/aosc-os-abbs pull request #8452
Opened 2024-10-31 07:35 UTC by miwu04

Topic Description
-----------------

- sunshine: let hardware decoding support by default

Package(s) Affected
-------------------

- sunshine: 0.23.1-1

Security Update?
----------------

No

Build Order
-----------

```
#buildit sunshine
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`

**Secondary Architectures**

- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2024-11-01 08:39 UTC, MingcongBai requested changes

2024-11-01 08:39 UTC, MingcongBai commented on app-multimedia/sunshine/autobuild/defines
> +PKGRECOM="avahi mesa ffnvcodec"
ffnvcodec is a header-only package and should be a build dependency.

2024-11-01 08:39 UTC, MingcongBai commented on app-multimedia/sunshine/autobuild/defines
> +PKGRECOM="avahi mesa ffnvcodec"
Mesa should be a runtime dependency.

2024-11-01 15:23 UTC, KexyBiscuit approved these changes
LGTM, good job.

2024-11-02 05:02 UTC, MingcongBai approved these changes
Nice work.

2024-11-02 05:02 UTC, merged