docker:  fix errors
AOSC-Dev/aosc-os-abbs pull request #8454
Opened 2024-10-31 09:22 UTC by mouyase

- can't load configs from "/etc/docker/daemon.json"
	- remove "/etc/conf.d/docker", it's inappropriate

Topic Description
-----------------

Package(s) Affected
-------------------

docker

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

Architectural progress for secondary ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-10-31 09:28 UTC, MingcongBai requested changes

2024-10-31 09:28 UTC, MingcongBai commented on app-containers/docker/autobuild/overrides/usr/lib/systemd/system/docker.service
> +WantedBy=multi-user.target
Missing newline at EOF.

2024-10-31 09:28 UTC, MingcongBai commented on app-containers/docker/autobuild/overrides/usr/lib/systemd/system/docker.service
>  [Unit]
Where did this service come from (you wrote it, or from another distribution)? If the latter, please note the source of the service file in your Git commit message.

2024-10-31 09:28 UTC, MingcongBai commented on app-containers/docker/autobuild/overrides/etc/conf.d/docker
This will likely need a maintscript handler. I will handle it on my end.

2024-10-31 09:28 UTC, MingcongBai commented on app-containers/docker/autobuild/overrides/usr/lib/systemd/system/docker.service
> +WantedBy=multi-user.target
Bump REL in `spec` to mark this package update as a revision.

2024-11-08 13:10 UTC, MingcongBai requested changes

2024-11-08 13:10 UTC, MingcongBai commented on app-containers/docker/autobuild/postinst
Seems unnecessary to do it three times... When is this most appropriate?

2024-11-08 13:50 UTC, mouyase commented on app-containers/docker/autobuild/postinst
https://man.archlinux.org/man/extra/dpkg/dpkg-maintscript-helper.1.en#Removing_a_conffile

>Current implementation: the preinst checks if the conffile has been modified, if yes it's left on place otherwise it's renamed to old-conffile.dpkg-remove. On configuration, the postinst removes old-conffile.dpkg-remove and renames old-conffile to new-conffile if old-conffile is still available. On abort-upgrade/abort-install, the postrm renames old-conffile.dpkg-remove back to old-conffile if required.

So must do it three times.

2024-11-09 03:37 UTC, MingcongBai commented on app-containers/docker/autobuild/postinst
I see, my bad.

2024-11-09 03:37 UTC, MingcongBai approved these changes, later dismissed

2024-11-09 04:41 UTC, MingcongBai submitted a review, later dismissed

2024-11-09 09:44 UTC, MingcongBai approved these changes

2024-11-09 09:44 UTC, merged