docker: update to 27.3.1+tini0.19.0
AOSC-Dev/aosc-os-abbs pull request #8467
Opened 2024-11-01 11:28 UTC by KexyBiscuit

Topic Description
-----------------

- docker: update to 27.3.1+tini0.19.0
    Co-authored-by: Kexy Biscuit (@KexyBiscuit) <kexybiscuit@outlook.com>

Package(s) Affected
-------------------

- docker: 27.3.1+tini0.19.0

Security Update?
----------------

No

Build Order
-----------

```
#buildit docker
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2024-11-04 03:23 UTC, MingcongBai commented
Missing version information:

```
root@JellyNote [ mingcongbai ] # docker --version
Docker version unknown-version, build unknown-commit
```

But container works:

![image](https://github.com/user-attachments/assets/a01341e1-e5f9-4214-b9c1-2e20445ba4a0)

2024-11-04 03:24 UTC, MingcongBai requested changes, later dismissed
Please fix version display/

2024-11-05 12:16 UTC, KexyBiscuit commented
> Please fix version display.

Fixed.

```shell
(ssh)kexybiscuit@vmaoscos001 [ ~ ] $ docker --version
Docker version 27.3.1, build ce1223035a
```

2024-11-06 09:10 UTC, OriginCode approved these changes

2024-11-06 09:12 UTC, merged