mihomo-party: new, 1.5.6
AOSC-Dev/aosc-os-abbs pull request #8492
Opened 2024-11-02 17:45 UTC by miwu04

Topic Description
-----------------

- mihomo-party: new,1.5.6

Package(s) Affected
-------------------

- mihomo-party: 1.5.6

Security Update?
----------------

No

Build Order
-----------

```
#buildit mihomo-party
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`

**Secondary Architectures**

- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

2024-11-03 09:03 UTC, miwu04 commented
![Screenshot_20241103_160225](https://github.com/user-attachments/assets/10fe8b1f-8fb8-4c6f-8f0a-4a94baaead38)
LGTM,AMD64

2024-11-03 15:48 UTC, MingcongBai requested changes

2024-11-03 15:48 UTC, MingcongBai commented on app-network/mihomo-party/autobuild/build
> +else
What about `ppc64el`, which you indicated to be supported?

2024-11-03 15:48 UTC, MingcongBai commented on app-network/mihomo-party/autobuild/build
> +else
What about ppc64el, which you indicated to be supported?

2024-11-03 15:48 UTC, MingcongBai commented on app-network/mihomo-party/autobuild/build
> +    aberr "Unsupported architecture, check `FAIL_ARCH` in defines!"
This code won't be reached since Autobuild would exit out at FAIL_ARCH.

2024-11-03 15:48 UTC, MingcongBai commented on app-network/mihomo-party/autobuild/build
> +sed -i "s/productName: Mihomo Party/productName: mihomo-party/" "$SRCDIR"/electron-builder.yml
No `sed` please (we won't know whether the operation succeeded, or even worked expectedly), this should be a patch.

2024-11-03 15:48 UTC, MingcongBai commented on app-network/mihomo-party/autobuild/build
> +export CI=true
What is this for? Please explain.

2024-11-03 15:48 UTC, MingcongBai commented on app-network/mihomo-party/autobuild/overrides/usr/share/applications/mihomo-party.desktop
> +Comment[zh_CN]=另一个 Mihomo GUI
This is not helpful at all, what does it actually do?

2024-11-03 15:48 UTC, MingcongBai commented on app-network/mihomo-party/autobuild/defines
> +PKGDES="Another Mihomo GUI"
Please make this description more helpful.

2024-11-03 15:48 UTC, MingcongBai commented on app-network/mihomo-party/autobuild/defines
> +FAIL_ARCH="(loongson3|riscv64|loongarch64|ppc64el)"
Perhaps take a page out of `clash-verge-rev`, which builds on LoongArch with a patch for rollup.

2024-11-03 15:48 UTC, MingcongBai commented on app-network/mihomo-party/autobuild/defines
> +
Extraneous newline.

2024-11-03 15:48 UTC, MingcongBai commented on app-network/mihomo-party/autobuild/postinst
> +fi
None of this is necessary (did you copy all these from Arch?). We have triggers to handle this.

2024-11-03 15:48 UTC, MingcongBai commented on app-network/mihomo-party/spec
> +ENVREQ__AMD64="total_mem_per_core=3"
Missing newline at end-of-file.

2024-11-03 15:48 UTC, MingcongBai commented on app-network/mihomo-party/spec
> +SRCS="tbl::https://github.com/mihomo-party-org/mihomo-party/archive/refs/tags/v$VER.tar.gz"
Do not use automatically packaged tarballs. See our [Styling Manual](https://wiki.aosc.io/zh/developer/packaging/package-styling-manual/#yuan-ma-wen-jian).

2024-11-03 16:00 UTC, MingcongBai requested changes

2024-11-03 16:00 UTC, MingcongBai commented on app-network/mihomo-party/autobuild/defines
> +FAIL_ARCH="(loongson3|riscv64|loongarch64|ppc64el)"
Might as well go with:

```
FAIL_ARCH="!(amd64|arm64)"
```

2024-11-04 11:55 UTC, MingcongBai requested changes

2024-11-04 11:55 UTC, MingcongBai commented on app-admin/cloud-init/spec
>  CHKUPDATE="anitya::id=11545"
Missing newline at EOF.

2024-11-04 11:55 UTC, MingcongBai commented on app-network/mihomo-party/autobuild/defines
> +# FIXME: Vite not supported on loongson3, riscv64,loongarch64.
Missing a space after the last comma.

2024-11-04 14:45 UTC, MingcongBai requested changes

2024-11-04 14:45 UTC, MingcongBai commented on app-network/mihomo-party/spec
> +ENVREQ__AMD64="total_mem_per_core=3"
Missing CHKUPDATE.

2024-11-08 12:54 UTC, MingcongBai approved these changes
Yep!

![image](https://github.com/user-attachments/assets/bc60d992-6e79-4828-9833-d14a2d3bfc2f)

2024-11-08 12:55 UTC, merged