git-delta: new, 0.18.2
AOSC-Dev/aosc-os-abbs pull request #8493
Opened 2024-11-03 01:01 UTC by poscat0x04

Topic Description
-----------------

Adds git-delta

Package(s) Affected
-------------------

- git-delta

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`

2024-11-03 04:06 UTC, stdmnpkg requested changes

2024-11-03 04:06 UTC, stdmnpkg commented on app-devel/git-delta/spec
> +SRCS="https://github.com/dandavison/delta/archive/refs/tags/$VER.tar.gz"
use git instead of tarball

2024-11-03 04:06 UTC, stdmnpkg commented on app-devel/git-delta/autobuild/beyond
> +  etc/completion/completion.bash \
`"$SRCDIR"/etc/......`

2024-11-03 04:06 UTC, stdmnpkg commented on app-devel/git-delta/autobuild/beyond
> +install -vDm644 \
add some log, e.g. `abinfo "Installing shell completion ..."`

2024-11-03 04:10 UTC, stdmnpkg commented
is this package amd64 only?

2024-11-03 04:54 UTC, poscat0x04 commented
I've only tested it on x86, although I think it should work on every platform that its dependencies work.

2024-11-03 05:44 UTC, stdmnpkg commented
https://buildit.aosc.io/pipelines/11803

failed on loongarch64, loongson3, ppc64el

looks like our mdbook is too old, updated in #8494

2024-11-04 03:26 UTC, MingcongBai requested changes

2024-11-04 03:26 UTC, MingcongBai commented on app-devel/git-delta/autobuild/beyond
> +cd manual
Use absolute path here.

2024-11-04 03:26 UTC, MingcongBai commented on app-devel/git-delta/autobuild/beyond
> +
Drop this newline.

2024-11-04 03:26 UTC, MingcongBai commented on app-devel/git-delta/autobuild/beyond
> +mkdir -p "$PKGDIR"/usr/share/doc/git-delta
Verbosity please.

2024-11-04 03:26 UTC, MingcongBai commented on app-devel/git-delta/autobuild/beyond
> +cp -r html "$PKGDIR"/usr/share/doc/git-delta
Verbosity and absolute path missing.

2024-11-04 03:26 UTC, MingcongBai commented on app-devel/git-delta/autobuild/beyond
> +
Drop this newline.

2024-11-04 03:26 UTC, MingcongBai commented on app-devel/git-delta/autobuild/prepare
> +export RUSTONIG_SYSTEM_LIBONIG=1
Why was this needed? Please add a comment explaining why:

```
# Note: ...
```

2024-11-04 03:26 UTC, MingcongBai commented on app-devel/git-delta/spec
> +SRCS="git::commit=tags/$VER::https://github.com/dandavison/delta.git"
This package should be named `delta` with a `PKGPROV` to `git-delta`. We follow upstream project names by principle.

2024-11-05 19:06 UTC, stdmnpkg requested changes

2024-11-05 19:06 UTC, stdmnpkg commented on app-devel/delta/autobuild/defines
> +# linker errors while building serde
annotate this with FIXME

```
# FIXME: linker errors while building serde
# (copy paste actual error message here so we can grep them when fix is available)
```

2024-11-06 01:12 UTC, stdmnpkg approved these changes

2024-11-08 13:05 UTC, MingcongBai approved these changes

2024-11-08 13:05 UTC, merged