feeluown: update to 4.1.7
AOSC-Dev/aosc-os-abbs pull request #8523
Opened 2024-11-05 10:10 UTC by Fearyncess

Topic Description
-----------------

- feeluown: update to 4.1.7
- feeluown-ytmusic: update to 0.4.4
- feeluown-qqmusic: update to 1.0.5
- feeluown-netease: update to 1.0.3
- feeluown-bilibili: update to 0.4.1

Package(s) Affected
-------------------

- feeluown: 1:4.1.7
- feeluown-bilibili: 0.4.1
- feeluown-netease: 1.0.3
- feeluown-qqmusic: 1.0.5
- feeluown-ytmusic: 0.4.4

Security Update?
----------------

No

Build Order
-----------

```
#buildit feeluown feeluown-netease feeluown-qqmusic feeluown-ytmusic feeluown-bilibili
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] Architecture-independent `noarch`

2024-11-05 10:40 UTC, Fearyncess commented
![图片](https://github.com/user-attachments/assets/1d3ea602-58fa-443b-a2f8-fd4a3fb1dd21)
feeluown 4.1.7, with Netease Music plugin, LGTM

2024-11-06 02:01 UTC, OriginCode requested changes

2024-11-06 02:01 UTC, OriginCode commented on app-multimedia/feeluown-bilibili/spec
>  SRCS="git::commit=v${VER}::https://github.com/feeluown/feeluown-bilibili"
Use `tags/v$VER`.

2024-11-06 02:01 UTC, OriginCode commented on app-multimedia/feeluown-netease/spec
>  SRCS="git::commit=v${VER}::https://github.com/feeluown/feeluown-netease"
Same here.

2024-11-06 02:01 UTC, OriginCode commented on app-multimedia/feeluown-ytmusic/spec
>  SRCS="git::commit=v${VER}::https://github.com/feeluown/feeluown-ytmusic"
Same.

2024-11-06 04:08 UTC, OriginCode commented
bilibili and QQ Music LGTM
![圖片](https://github.com/user-attachments/assets/acd68f96-1930-4d49-ae63-73addee17232)
![圖片](https://github.com/user-attachments/assets/d8806f3d-b0f9-47fc-b629-21e3cdffbc72)

2024-11-06 04:09 UTC, OriginCode commented
YouTube Music **NOT** LGTM
![圖片](https://github.com/user-attachments/assets/8496eb2d-fb19-4fd7-a7d5-28aa8693c6c4)

2024-11-06 09:56 UTC, Fearyncess commented
![图片](https://github.com/user-attachments/assets/01078927-bf56-4b6b-9eba-6ae3ff9e9b04)
searching in youtube music works after `ytmusicapi` updated to 1.8.2

2025-01-02 14:03 UTC, closed without merging