sing-box: add completion files
AOSC-Dev/aosc-os-abbs pull request #8535
Opened 2024-11-07 05:38 UTC by CAB233

Topic Description
-----------------

- sing-box: add completion files
    - Remove outdated FAIL_ARCH.
    - Enable reproducible tag and other GOFLAGS.
    - Clean up prepare and build.

Package(s) Affected
-------------------

- sing-box: 1.10.1-1

Security Update?
----------------

No

Build Order
-----------

```
#buildit sing-box
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-11-07 07:09 UTC, CAB233 commented
LGTM on amd64
```fish
> sing-box version
sing-box version 1.10.1

Environment: go1.23.1 linux/amd64
Tags: with_gvisor,with_quic,with_wireguard,with_grpc,with_ech,with_utls,with_reality_server,with_acme,with_dhcp,with_clash_api,with_v2ray_api
Revision: b80ec55ba0aafc60774e19c409e55ced50ddaab3
CGO: enabled
```
![bash](https://github.com/user-attachments/assets/3cebb6ab-2e20-4a07-ba61-5efc6bf405ee)
![zsh](https://github.com/user-attachments/assets/679b2919-e89f-4f31-8e2f-53292e7dd32f)
![fish](https://github.com/user-attachments/assets/683a5979-fd82-4c8c-b463-00bb07c2aa32)

2024-11-08 03:32 UTC, MingcongBai requested changes

2024-11-08 03:32 UTC, MingcongBai commented on app-network/sing-box/autobuild/prepare
> +if [[ "${CROSS:-$ARCH}" != "loongson3" ]]; then
Please use:

```
if ! ab_match_arch loongson3; then
    ...
fi
```

2024-11-08 13:51 UTC, CAB233 commented on app-network/sing-box/autobuild/prepare
> +if [[ "${CROSS:-$ARCH}" != "loongson3" ]]; then
fixed

2024-11-09 03:31 UTC, MingcongBai approved these changes

2024-11-09 03:31 UTC, merged