i3: update to 4.24
AOSC-Dev/aosc-os-abbs pull request #8537
Opened 2024-11-07 06:39 UTC by OriginCode

Topic Description
-----------------

- i3: update to 4.24
    Co-authored-by: Kaiyang Wu (@OriginCode) <self@origincode.me>

Package(s) Affected
-------------------

- i3: 4.24

Security Update?
----------------

No

Build Order
-----------

```
#buildit i3
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-11-07 12:49 UTC, OriginCode commented
LGTM on amd64
![圖片](https://github.com/user-attachments/assets/4f833aaa-1005-458b-94a1-45842a4ab717)

2024-11-07 12:50 UTC, MingcongBai commented
> ```diff
> +-rwxr-xr-x     ./usr/share/man/man1/i3-dump-log.1.xz
> +-rwxr-xr-x     ./usr/share/man/man1/i3-input.1.xz
> +-rwxr-xr-x     ./usr/share/man/man1/i3-migrate-config-to-v4.1.xz
> +-rwxr-xr-x     ./usr/share/man/man1/i3-msg.1.xz
> +-rwxr-xr-x     ./usr/share/man/man1/i3-nagbar.1.xz
> ```

Incorrect permission bits on some man pages.

2024-11-08 03:09 UTC, MingcongBai commented
> > ```diff
> > +-rwxr-xr-x     ./usr/share/man/man1/i3-dump-log.1.xz
> > +-rwxr-xr-x     ./usr/share/man/man1/i3-input.1.xz
> > +-rwxr-xr-x     ./usr/share/man/man1/i3-migrate-config-to-v4.1.xz
> > +-rwxr-xr-x     ./usr/share/man/man1/i3-msg.1.xz
> > +-rwxr-xr-x     ./usr/share/man/man1/i3-nagbar.1.xz
> > ```
> 
> Incorrect permission bits on some man pages.

Issue reported upstream https://github.com/i3/i3/issues/6297.

2024-11-08 11:59 UTC, MingcongBai requested changes

2024-11-08 11:59 UTC, MingcongBai commented on desktop-wm/i3/autobuild/beyond
> +for m in *.1; do
```bash
install -Dvm644 "$SRCDIR"/man/*.1 \
    -t "$PKGDIR"/usr/share/man/man1/
```

2024-11-08 12:09 UTC, MingcongBai approved these changes

2024-11-08 12:10 UTC, merged