cowsay: update to 3.8.3
AOSC-Dev/aosc-os-abbs pull request #8569
Opened 2024-11-10 04:45 UTC by KexyBiscuit

Topic Description
-----------------

- cowsay: update to 3.8.3
    Co-authored-by: Kexy Biscuit (@KexyBiscuit) <kexybiscuit@outlook.com>

Package(s) Affected
-------------------

- cowsay: 3.8.3

Security Update?
----------------

No

Build Order
-----------

```
#buildit cowsay
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] Architecture-independent `noarch`

2024-11-11 21:10 UTC, stdmnpkg commented
works on my x86-64 machine

```
studentmain@MeowPC3E [ ~ ] $ cowsay --version | cowsay
 _______________________________________
/ /usr/bin/cowsay version 3.8.3 calling \
| Getopt::Std::getopts (version 1.13),  |
\ running under Perl version 5.36.3.    /
 ---------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

2024-11-13 01:47 UTC, MingcongBai requested changes

2024-11-13 01:47 UTC, MingcongBai commented on app-utils/cowsay/autobuild/build
> +make install DESTDIR="$PKGDIR" \
Missing abinfo.

2024-11-13 01:51 UTC, MingcongBai approved these changes

2024-11-13 02:08 UTC, merged