pngquant: update to 3.0.3
AOSC-Dev/aosc-os-abbs pull request #8613
Opened 2024-11-13 07:09 UTC by BC204

Topic Description
-----------------

- pngquant: update to 3.0.3
    Add BUILDDEP due to the changed build methods

Package(s) Affected
-------------------

- pngquant: 3.0.3

Security Update?
----------------

No

Build Order
-----------

```
#buildit pngquant
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-11-13 15:32 UTC, MingcongBai requested changes

2024-11-13 15:32 UTC, MingcongBai commented on app-utils/pngquant/autobuild/prepare
> +export CARGO_TARGET_DIR=target
What is this for?

2024-11-13 15:32 UTC, MingcongBai commented on app-utils/pngquant/autobuild/defines
> +NOLTO=1
Why? At least leave a FIXME comment here.

2024-11-13 15:32 UTC, MingcongBai commented on app-utils/pngquant/autobuild/defines
> +BUILDDEP="cargo llvm rustc"
`cargo` is part of `rustc`. Drop it.

2024-11-13 15:32 UTC, MingcongBai commented on app-utils/pngquant/autobuild/beyond
> +install -Dm644 "$SRCDIR"/COPYRIGHT \
This is not necessary.

2024-11-13 19:21 UTC, stdmnpkg approved these changes, later dismissed
works on my x86-64 machine

```
studentmain@MeowPC3E [ Desktop ] $ pngquant hundred-thousandth.png 
studentmain@MeowPC3E [ Desktop ] $ ls hundred-thousandth* -alh
-rw-rw-r-- 1 studentmain studentmain 440K Nov 13 19:19 hundred-thousandth-fs8.png
-rw------- 1 studentmain studentmain 1.0M Aug 12 18:54 hundred-thousandth.png
studentmain@MeowPC3E [ Desktop ] $ ffprobe -hide_banner hundred-thousandth-fs8.png 
Input #0, png_pipe, from 'hundred-thousandth-fs8.png':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: png, pal8(pc, gbr/unknown/unknown), 3840x2400 [SAR 5669:5669 DAR 8:5], 25 fps, 25 tbr, 25 tbn
studentmain@MeowPC3E [ Desktop ] $ ffprobe -hide_banner hundred-thousandth.png 
Input #0, png_pipe, from 'hundred-thousandth.png':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: png, rgba(pc, gbr/unknown/unknown), 3840x2400 [SAR 5669:5669 DAR 8:5], 25 fps, 25 tbr, 25 tbn
```

2024-11-14 05:15 UTC, MingcongBai approved these changes

2024-11-14 05:15 UTC, merged