pstate-frequency: update to 3.15.2
AOSC-Dev/aosc-os-abbs pull request #8700
Opened 2024-11-19 16:26 UTC by MingcongBai

Topic Description
-----------------

- pstate-frequency: update to 3.15.2
    Co-authored-by: 白铭骢 (Mingcong Bai) (@MingcongBai) <jeffbai@aosc.io>

Package(s) Affected
-------------------

- pstate-frequency: 3.15.2

Security Update?
----------------

No

Build Order
-----------

```
#buildit pstate-frequency
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

2024-11-27 21:29 UTC, OriginCode requested changes

2024-11-27 21:29 UTC, OriginCode commented on app-admin/pstate-frequency/spec
>  SRCS="https://github.com/pyamsoft/pstate-frequency/archive/$VER.tar.gz"
Use git source.

2025-01-11 01:39 UTC, OriginCode approved these changes

2025-01-11 02:49 UTC, MingcongBai commented
LGTM on TGL:

```
mingcongbai@JellyNote [ ~ ] $ pstate-frequency -G -r
pstate-frequency <3.15.2>
    CPU[0]    ->  2950MHz
    CPU[1]    ->  4220MHz
    CPU[2]    ->  3498MHz
    CPU[3]    ->  1911MHz
    CPU[4]    ->   398MHz
    CPU[5]    ->   400MHz
    CPU[6]    ->  3069MHz
    CPU[7]    ->  3925MHz
mingcongbai@JellyNote [ ~ ] $ pstate-frequency -G -c
pstate-frequency <3.15.2>
    CPU_DRIVER   -> intel_pstate
    CPU_GOVERNOR -> powersave
    TURBO        -> 0 [ON]
    EPP          -> performance
    CPU_MIN      -> 8% [400MHz]
    CPU_MAX      -> 100% [5000MHz]
mingcongbai@JellyNote [ ~ ] $ 
```

2025-01-11 02:49 UTC, merged