neomutt: update to 20241114
AOSC-Dev/aosc-os-abbs pull request #8731
Opened 2024-11-20 16:01 UTC by MingcongBai

Topic Description
-----------------

- neomutt: update to 20241114
    Co-authored-by: 白铭骢 (Mingcong Bai) (@MingcongBai) <jeffbai@aosc.io>

Package(s) Affected
-------------------

- neomutt: 20241114

Security Update?
----------------

No

Build Order
-----------

```
#buildit neomutt
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-11-24 03:59 UTC, OriginCode requested changes

2024-11-24 03:59 UTC, OriginCode commented on app-web/neomutt/spec
>  SRCS="tbl::https://github.com/neomutt/neomutt/archive/$VER.tar.gz"
Use git source instead.

2024-11-26 03:15 UTC, MingcongBai commented on app-web/neomutt/spec
>  SRCS="tbl::https://github.com/neomutt/neomutt/archive/$VER.tar.gz"
Addressed in the following revision.

2024-11-26 03:32 UTC, OriginCode approved these changes

2024-11-26 03:32 UTC, OriginCode commented
Tests pending.

2024-11-26 03:35 UTC, MingcongBai commented
Smoke testing passed on AMD64:

![图片](https://github.com/user-attachments/assets/ac426125-db37-4c5e-bc7e-9b69424f87f3)

2024-11-26 03:35 UTC, merged