usbmux: Rebuild against libplist 2.3.0
AOSC-Dev/aosc-os-abbs pull request #8773
Opened 2024-11-25 12:36 UTC by Cyanoxygen

Topic Description
-----------------

- usbmuxd: rebuild against libplist 2.3.0
- double-conversion: update to 3.3.0
    Signed-off-by: 某亚瑟 <mouyase@aosc.io>

Package(s) Affected
-------------------

Security Update?
----------------

No

Build Order
-----------

```
#buildit usbmux
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-12-27 13:15 UTC, Cyanoxygen commented
Testing
--------

LGTM on amd64, my iPhone can now share its network connection to my PC:

![image](https://github.com/user-attachments/assets/928559c5-09c9-4668-b06f-4674edd89827)

2024-12-27 13:19 UTC, MingcongBai requested changes

2024-12-27 13:19 UTC, MingcongBai commented on runtime-common/libplist/autobuild/beyond
> +	install -Dm644 "$SRCDIR"/cython/plist.pxd \
Verbosity here.

2024-12-27 13:19 UTC, MingcongBai commented on runtime-common/libplist/spec
> +UPSTREAM_VER=2.6.0
Unnecessary duplication.

2024-12-27 13:19 UTC, MingcongBai commented on runtime-devices/libimobiledevice-glue/spec
> +VER="$UPSTREAM_VER"
Unnecessary duplication.

2024-12-28 01:08 UTC, MingcongBai approved these changes

2024-12-28 01:08 UTC, merged