rustdesk: rebuild for Spiral markers
AOSC-Dev/aosc-os-abbs pull request #8858
Opened 2024-12-03 04:07 UTC by miwu04

Topic Description
-----------------

- libvdpau: rebuild for Spiral markers
- gstreamer: rebuild for Spiral markers
- libayatana-indicator: rebuild for Spiral markers

Package(s) Affected
-------------------

- gstreamer: 1.24.7-3
- libayatana-indicator: 0.9.4-1
- libvdpau: 1.5-1

Security Update?
----------------

No

Build Order
-----------

```
#buildit libayatana-indicator gstreamer libvdpau
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-12-05 15:59 UTC, miwu04 commented
![image](https://github.com/user-attachments/assets/7bc92c05-39e4-4d59-9a09-ee0283da3f04)
LGTM

2024-12-06 13:24 UTC, MingcongBai requested changes

2024-12-06 13:24 UTC, MingcongBai commented on app-multimedia/pipewire/autobuild/defines
> +PKGPROV="gstreamer1.0-pipewire_spiral"
Please add:

```
# FIXME: Autobuild is not yet capable of generating Spiral markers for gstreamer1.0-* modules.
```

2024-12-06 13:27 UTC, miwu04 commented on app-multimedia/pipewire/autobuild/defines
> +PKGPROV="gstreamer1.0-pipewire_spiral"
done

2024-12-06 13:28 UTC, MingcongBai approved these changes

2024-12-06 14:23 UTC, merged