timeshift: new, 24.06.5
AOSC-Dev/aosc-os-abbs pull request #8899
Opened 2024-12-07 10:07 UTC by miwu04

Topic Description
-----------------

- timeshift: new, 24.06.5

Package(s) Affected
-------------------

- timeshift: 24.06.5

Security Update?
----------------

No

Build Order
-----------

```
#buildit timeshift
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`

2024-12-08 04:58 UTC, miwu04 commented
![342ad0a962f9e2a2f805769c00225b7d](https://github.com/user-attachments/assets/0e0de968-4427-4b34-a17f-bc8e0fed4c4a)

2024-12-09 09:41 UTC, eatradish requested changes

2024-12-09 09:41 UTC, eatradish commented on app-utils/timeshift/autobuild/defines
> +FAIL_ARCH="!(amd64|arm64)"
Why?

2024-12-09 09:41 UTC, eatradish commented on app-utils/timeshift/autobuild/defines
> +PKGDEP="at-spi2-core glibc cairo gdk-pixbuf libgee glib gnutls gtk-3 json-glib pango pcre2 vte x11-lib zlib rsync psmisc"
dependencies from `ldd` output:

```
atk
at-spi2-atk
at-spi2-core
brotli
bzip2
cairo
cryptsetup
dbus
expat
fontconfig
freetype
fribidi
gcc
gcc-runtime
gdk-pixbuf
glib
glibc
gmp
gnutls
graphite
gtk-3
harfbuzz
icu
json-c
json-glib
libcap
libdatrie
libepoxy
libffi
libgee
libidn2
libjpeg-turbo
libpng
libtasn1
libthai
libtiff
libunistring
libwebp
libxau
libxcb
libxdmcp
libxkbcommon
lvm2
nettle
openssl
p11-kit
pango
pcre2
pixman
systemd
util-linux-runtime
vte
wayland
x11-lib
xz
zlib
zstd
```

Step:

```bash
for i in `ldd /usr/bin/timeshift | choose 2`; do oma provides --no-progress $i >> 1; done
cat 1 | choose -f ":" 0 | sort | uniq
```

2024-12-09 09:52 UTC, eatradish commented on app-utils/timeshift/autobuild/defines
> +PKGDEP="at-spi2-core glibc cairo gdk-pixbuf libgee glib gnutls gtk-3 json-glib pango pcre2 vte x11-lib zlib rsync psmisc"
A better way:

```bash
for i in `readelf -d /usr/bin/timeshift | grep NEEDED | choose 2 | choose -f "：" 1 | choose -f "\[" 0 | choose -f "\]" 0`; do oma provides --no-progress $i >> 1; done
cat 1 | choose -f ":" 0 | sort | uniq
```

2024-12-09 10:03 UTC, eatradish commented on app-utils/timeshift/autobuild/defines
> +FAIL_ARCH="!(amd64|arm64)"
```bash
for i in `LANG=C readelf -d /usr/bin/timeshift | grep NEEDED | choose -1 | choose -f "\[" 0 | choose -f "\]" 0`; do oma provides --no-progress $i >> 1; done
cat 1 | choose -f ":" 0 | sort | uniq
```

Result:

```
gcc+cross-mips64r6el
gdk-pixbuf
gdk-pixbuf+32
glib
glib+32
glibc
glibc+32
gtk-3
gtk-3+32
json-glib
json-glib-dbg
libgee
vte
```

2024-12-14 13:18 UTC, eatradish requested changes
```
saki@MagMilk [ ~ ] $ timeshift-gtk
timeshift-gtk: error while loading shared libraries: libxapp.so.1: cannot open shared object file: No such file or directory
```

2024-12-14 13:27 UTC, miwu04 commented
> ```
> saki@MagMilk [ ~ ] $ timeshift-gtk
> timeshift-gtk: error while loading shared libraries: libxapp.so.1: cannot open shared object file: No such file or directory
> ```
done

2024-12-14 13:43 UTC, eatradish approved these changes

2024-12-15 05:00 UTC, merged