Lua CHKUPDATE fixes
AOSC-Dev/aosc-os-abbs pull request #8905
Opened 2024-12-08 05:13 UTC by xtexChooser

Topic Description
-----------------

- lua-5.3: fix anitya project
- lua-5.4: fix anitya project
- lua: transitionalise for lua-5.1
    X-AOSC-mktransitionpac-transition-package: lua
    X-AOSC-mktransitionpac-new-package: lua-5.1
    X-AOSC-mktransitionpac-directory: lang-lua
    X-AOSC-mktransitionpac-section: devel
    X-AOSC-mktransitionpac-epoch: 2
- lua-5.1: new, 5.1.5
    X-AOSC-copypac-from: lua
    X-AOSC-copypac-version: 5.1.5
    X-AOSC-copypac-section: lang-lua

Package(s) Affected
-------------------

- lua: 2:0
- lua-5.1: 5.1.5-5
- lua-5.3: 1:5.3.6-2
- lua-5.4: 5.4.7-1

Security Update?
----------------

No

Build Order
-----------

```
#buildit lua-5.1 lua-5.3 lua-5.4 lua
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-12-09 02:45 UTC, OriginCode requested changes

2024-12-09 02:45 UTC, OriginCode commented on lang-lua/lua-5.1/autobuild/defines
> +
Remove the empty line.

2024-12-09 02:45 UTC, OriginCode commented on lang-lua/lua/autobuild/defines.stage2
> +PKGDEP=""
May just remove the PKGDEP?

2024-12-09 02:45 UTC, OriginCode commented on lang-lua/lua-5.1/autobuild/build
> +mkdir -p abdist/usr/share/man/man1
Add some verbosity.

2024-12-09 02:45 UTC, OriginCode commented on lang-lua/lua-5.1/autobuild/build
> +ln -s luac5.1 abdist/usr/bin/luac
Add some verbosity here too.

2024-12-18 02:48 UTC, OriginCode submitted a review, later dismissed

2024-12-18 02:48 UTC, OriginCode commented on lang-lua/lua/autobuild/build
> +mkdir "$PKGDIR"
Add verbosity.

2024-12-18 02:48 UTC, OriginCode commented on lang-lua/lua/autobuild/build.stage2
> +mkdir "$PKGDIR"
Add verbosity here too.

2024-12-21 07:43 UTC, MingcongBai requested changes
Still missing a lot of `abinfo` throughout...

2025-01-20 09:06 UTC, MingcongBai approved these changes

2025-01-20 09:06 UTC, merged