grub-btrfs: new,4.13
AOSC-Dev/aosc-os-abbs pull request #8907
Opened 2024-12-08 07:06 UTC by Shyliuli

Topic Description
-----------------
引入新包grub-btrfs
作用：为grub加入引导至btrfs快照的能力

Package(s) Affected
-------------------
grub-btrfs

Security Update?
----------------

No

Test Build(s) Done
------------------

- [x] Architecture-independent `noarch`

2024-12-08 12:06 UTC, stdmnpkg requested changes, later dismissed

2024-12-08 12:06 UTC, stdmnpkg commented on app-utils/grub-btrfs/spec
> +CHKSUMS="sha256::c493d0d5a6548c01993641ce586c98d461cabe40df4dff79d974d0c59068ff1d"
for git source, use SKIP as checksum

2024-12-08 12:06 UTC, stdmnpkg commented on app-utils/grub-btrfs/autobuild/defines
> +ABSPLITDBG=no
`ABSPLITDBG=0`

we prefer 0/1 for boolean value instead of yes/no

2024-12-08 12:06 UTC, stdmnpkg commented on app-utils/grub-btrfs/spec
> +REL=0
delete this, it's the default value

2024-12-08 12:06 UTC, stdmnpkg commented on app-utils/grub-btrfs/autobuild/defines
> +ABSPLITDBG=no
is this package really architecture independent?

if yes, add `ABHOST=noarch` and remove `ABSPLITDBG=0`

2024-12-08 12:06 UTC, stdmnpkg commented on app-utils/grub-btrfs/autobuild/defines
> +PKGDES="grub-btrfs is a tool that enhances the GRUB bootloader by adding a sub-menu for Btrfs snapshots, allowing users to easily boot into various snapshots for better system management and recovery
reword the description, see [AOSC OS Package Styling Manual chapter 2.3](https://wiki.aosc.io/developer/packaging/package-styling-manual/#descriptions)

`A tool that add sub-menu for Btrfs snapshots to GRUB bootloader` ?

2024-12-08 12:16 UTC, OriginCode requested changes

2024-12-08 12:16 UTC, OriginCode commented on app-utils/grub-btrfs/autobuild/defines
> +ABTYPE=self
No need to specify ABTYPE=self if there is a build file.

2024-12-08 12:16 UTC, OriginCode commented on app-utils/grub-btrfs/spec
> +CHKUPDATE="github::repo=Antynea/grub-btrfs;sort_version=true"
May use https://release-monitoring.org/ instead.

2024-12-08 15:41 UTC, Shyliuli commented on app-utils/grub-btrfs/spec
> +CHKUPDATE="github::repo=Antynea/grub-btrfs;sort_version=true"
No such package....

2024-12-08 16:42 UTC, OriginCode submitted a review, later dismissed

2024-12-08 16:42 UTC, OriginCode commented on app-utils/grub-btrfs/spec
> +CHKSUMS="SKIP"
Add `CHKUPDATE`

2024-12-08 16:42 UTC, OriginCode commented on app-utils/grub-btrfs/autobuild/build
> +
Remove the empty line.

2024-12-08 16:46 UTC, OriginCode commented on app-utils/grub-btrfs/spec
> +CHKUPDATE="github::repo=Antynea/grub-btrfs;sort_version=true"
Add one

2024-12-09 05:05 UTC, stdmnpkg commented on app-utils/grub-btrfs/spec
> +CHKSUMS="SKIP"
use `anitya::id=375790`, see https://release-monitoring.org/project/375790/

2024-12-09 05:23 UTC, Shyliuli commented
Just now, I cleared the blank lines, and created this project on release-monitoring.org, and updated the spec file to automatically check for updates.

2024-12-09 05:26 UTC, MingcongBai commented
> Just now, I cleared the blank lines, and created this project on release-monitoring.org, and updated the spec file to automatically check for updates.

Please use `git rebase -i stable` to revise your commit messages (I would recommend squashing them), according to our [Styling Manual](https://wiki.aosc.io/zh/developer/packaging/package-styling-manual/).

2024-12-09 05:44 UTC, Shyliuli commented
> > Just now, I cleared the blank lines, and created this project on release-monitoring.org, and updated the spec file to automatically check for updates.
> 
> Please use `git rebase -i stable` to revise your commit messages (I would recommend squashing them), according to our [Styling Manual](https://wiki.aosc.io/zh/developer/packaging/package-styling-manual/).

Is this okay....?

2024-12-09 06:17 UTC, MingcongBai requested changes

2024-12-09 06:17 UTC, MingcongBai commented on app-utils/grub-btrfs/autobuild/defines
> +PKGDES="A tool that add sub-menu for Btrfs snapshots to GRUB bootloader"
Tool to add a sub-menu for BtrFS snapshots to the GRUB bootloader

2024-12-09 06:25 UTC, MingcongBai approved these changes

2024-12-09 06:26 UTC, merged