geant4: update to 11.3.0
AOSC-Dev/aosc-os-abbs pull request #8919
Opened 2024-12-09 14:04 UTC by CAB233

Topic Description
-----------------

- geant4: update to 11.3.0
    - Move to app-scientific
    - Use anitya to check for updates

Package(s) Affected
-------------------

- geant4: 11.3.0

Security Update?
----------------

No

Build Order
-----------

```
#buildit geant4
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-12-10 04:42 UTC, CAB233 commented
[dickens-8919.txt](https://github.com/user-attachments/files/18071877/dickens-8919.txt)

2024-12-10 09:01 UTC, CAB233 commented
Test on amd64. If your visualization with OpenGLStoreQt cause segmentation fault, try to use `/vis/open TSG`
![](https://github.com/user-attachments/assets/8cf3bee9-62c9-443e-8963-52c07fd6fba2)

2024-12-12 05:48 UTC, CAB233 commented
Add environment variable in `/etc/profile.d/geant4.sh` to resolve OpenGL compatibility issues with some GPUs by using a specified graphics system.

Update dickecks: [dickens-8919.txt](https://github.com/user-attachments/files/18106087/dickens-8919.txt)

2024-12-12 05:54 UTC, MingcongBai requested changes

2024-12-12 05:54 UTC, MingcongBai commented on app-scientific/geant4/autobuild/overrides/etc/profile.d/geant4.sh
Please symlink this to /etc/bashrc.d as well so that non-login sessions can also take advantage of this.

2024-12-13 01:38 UTC, CAB233 commented
update: [dickens-8919.txt](https://github.com/user-attachments/files/18119492/dickens-8919.txt)

2024-12-13 04:08 UTC, MingcongBai approved these changes

2024-12-13 04:08 UTC, merged