fscan: new, 1.8.4
AOSC-Dev/aosc-os-abbs pull request #8925
Opened 2024-12-10 07:27 UTC by neko205-mx

Topic Description
-----------------

fscan: new, 1.8.4

Package(s) Affected
-------------------

fscan: new, 1.8.4

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

Architectural progress for secondary ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-12-10 07:30 UTC, eatradish submitted a review, later dismissed

2024-12-10 07:30 UTC, eatradish commented on app-utils/fscan/spec
> +
Unnecessary new line

2024-12-10 07:30 UTC, MingcongBai requested changes

2024-12-10 07:30 UTC, MingcongBai commented on app-utils/fscan/autobuild/defines
> +PKGDES="An intranet comprehensive scanning tool"
A comprehensive intranet scanning tool

2024-12-10 07:30 UTC, MingcongBai commented on app-utils/fscan/autobuild/defines
> +BUILDDEP="go"
There must be some sort of binary dependency since it's a dynamic ELF.

2024-12-10 07:30 UTC, MingcongBai commented on app-utils/fscan/spec
> +
Missing `CHKUPDATE`.

2024-12-10 07:34 UTC, stdmnpkg requested changes

2024-12-10 07:34 UTC, stdmnpkg commented on app-utils/fscan/spec
> +CHKSUMS="sha256::24e0aeac234e458ff1cdfd1b0d8f1d2b4fd920582a420fb1091f7cafa18fe33c"
```suggestion
SRCS="git::commit=tags/$VER::https://github.com/shadow1ng/fscan.git"
CHKSUMS="SKIP"
```

2024-12-10 07:42 UTC, MingcongBai commented on app-utils/fscan/spec
> +
See https://github.com/AOSC-Dev/aosc-findupdate/blob/master/docs/config.zh-CN.md

2024-12-10 09:08 UTC, stdmnpkg approved these changes, later dismissed

2024-12-11 07:25 UTC, neko205-mx commented
添加补丁 问题点位于软件引入的`github.com/shadow1ng/grdp v1.0.3` 其中使用了`github.com/icodeface/tls v0.0.0-20190904083142-17aec93c60e5 // indirect` 是一个分支实现，对某些架构支持不完善，将其修改为官方的crypto/tls即可，补丁修改了grdp的实现到我fork的版本，简单测试功能都正常，后续没有大问题我会去找作者提pull

2024-12-11 08:17 UTC, neko205-mx commented
### debug

在对fscan这个包进行打包的时候出现了longarch64与riscv架构无法编译的问题，看log发现问题出现于github.com/icodeface/tls这个软件包

![.png](https://s2.loli.net/2024/12/11/kBrXSPMlnGZezAf.png)

查找这个包的github地址发现这是一个基于官方tls的分支实现

https://github.com/icodeface/tls

![.png](https://s2.loli.net/2024/12/11/qfeaCDW7Lk2HUvZ.png)

https://github.com/icodeface/tls/tree/master/internal/cpu

导航到路径发现可能是架构支持的代码，并没有longarch64的支持代码 riscv的支持也只有一个占位符

于是便思考，是否可以放弃这个tls支持，走官方支持，那么就要先找到哪个代码使用了这依赖，我clone了fscan的代码

通过`go mod why`查找可以找到

```shell
❯ go mod why -m github.com/icodeface/tls
go: downloading github.com/shadow1ng/grdp v1.0.3
go: downloading github.com/icodeface/tls v0.0.0-20190904083142-17aec93c60e5
# github.com/icodeface/tls
github.com/shadow1ng/fscan/Plugins
github.com/tomatome/grdp/core
github.com/icodeface/tls
```

不难看出依赖关系是

```shell
github.com/shadow1ng/fscan/Plugins
└── github.com/tomatome/grdp/core
    └── github.com/icodeface/tls
```

关键在于`github.com/tomatome/grdp/core`而通过`go.mod`可以看到其被替换为了作者自己fork的版本`https://github.com/shadow1ng/grdp`再次跟踪到`core/socket.go`

![.png](https://s2.loli.net/2024/12/11/hvpwOnREagxjy1H.png)

这应该是原作者引入的，注释掉了官方实现原作者仓库可以证实这一点`https://github.com/tomatome/grdp/blob/master/core/socket.go`





于是解决方案就是 再fork一份将分支实现换回官方实现，再通过补丁将依赖换过去这个是我fork的修改历史

https://github.com/neko205-mx/grdp/commits/master/

补丁文件

```diff
From 8b6bbfff43ec660c2bcbd6263150bc9059c1c907 Mon Sep 17 00:00:00 2001
From: Neko205 <neko200553@gmail.com>
Date: Wed, 11 Dec 2024 10:18:55 +0800
Subject: [PATCH] =?UTF-8?q?=09=E4=BF=AE=E6=94=B9=EF=BC=9A=20=20=20=20=20go?=
 =?UTF-8?q?.mod=09=E4=BF=AE=E6=94=B9=EF=BC=9A=20=20=20=20=20go.sum?=
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

---
 go.mod | 3 +--
 1 file changed, 1 insertion(+), 2 deletions(-)

diff --git a/go.mod b/go.mod
index 9322059..e3f3a33 100644
--- a/go.mod
+++ b/go.mod
@@ -34,7 +34,6 @@ require (
 	github.com/hashicorp/errwrap v1.0.0 // indirect
 	github.com/hashicorp/go-multierror v1.1.1 // indirect
 	github.com/huin/asn1ber v0.0.0-20120622192748-af09f62e6358 // indirect
-	github.com/icodeface/tls v0.0.0-20190904083142-17aec93c60e5 // indirect
 	github.com/lunixbochs/struc v0.0.0-20200707160740-784aaebc1d40 // indirect
 	github.com/mattn/go-colorable v0.0.9 // indirect
 	github.com/mattn/go-isatty v0.0.3 // indirect
@@ -50,6 +49,6 @@ require (
 	honnef.co/go/tools v0.0.1-2019.2.3 // indirect
 )

-replace github.com/tomatome/grdp v0.0.0-20211231062539-be8adab7eaf3 => github.com/shadow1ng/grdp v1.0.3
+replace github.com/tomatome/grdp v0.0.0-20211231062539-be8adab7eaf3 => github.com/neko205-mx/grdp v0.1.0

 replace github.com/C-Sto/goWMIExec v0.0.1-deva.0.20210704154847-b8ebd6464a06 => github.com/shadow1ng/goWMIExec v0.0.2
--
2.47.1



```

2024-12-12 05:32 UTC, stdmnpkg submitted a review, later dismissed
works on my x86-64 machine

```
studentmain@MeowPC3F [ ~ ] $ fscan -h 192.168.31.100

   ___                              _    
  / _ \     ___  ___ _ __ __ _  ___| | __ 
 / /_\/____/ __|/ __| '__/ _` |/ __| |/ /
/ /_\\_____\__ \ (__| | | (_| | (__|   <    
\____/     |___/\___|_|  \__,_|\___|_|\_\   
                     fscan version: 1.8.4
start infoscan
192.168.31.100:22 open
192.168.31.100:8080 open
192.168.31.100:1080 open
[*] alive ports len is: 3
start vulscan
[*] WebTitle http://192.168.31.100:8080 code:400 len:0      title:None
已完成 3/3
[*] 扫描结束,耗时: 14.215744268s
```

works on my loongarch64 machine

```
(ssh)studentmain@a-long-loooooong-ago [ ~ ] $ fscan -h 192.168.31.100

   ___                              _    
  / _ \     ___  ___ _ __ __ _  ___| | __ 
 / /_\/____/ __|/ __| '__/ _` |/ __| |/ /
/ /_\\_____\__ \ (__| | | (_| | (__|   <    
\____/     |___/\___|_|  \__,_|\___|_|\_\   
                     fscan version: 1.8.4
start infoscan
192.168.31.100:8080 open
192.168.31.100:22 open
192.168.31.100:1080 open
[*] alive ports len is: 3
start vulscan
[*] WebTitle http://192.168.31.100:8080 code:400 len:0      title:None
已完成 3/3
[*] 扫描结束,耗时: 14.231832599s
```

2024-12-12 07:16 UTC, MingcongBai approved these changes

2024-12-12 07:16 UTC, merged