nuclei: new, 3.3.7
AOSC-Dev/aosc-os-abbs pull request #8980
Opened 2024-12-16 07:10 UTC by neko205-mx

Topic Description
-----------------

nuclei: new, 3.3.7

Package(s) Affected
-------------------
- nuclei 3.3.7

Security Update?
----------------

No 

Build Order
-----------

```
#buildit nuclei
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

Architectural progress for secondary ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-12-16 09:28 UTC, OriginCode requested changes

2024-12-16 09:28 UTC, OriginCode commented on app-utils/nuclei/autobuild/build
> +
Remove the empty line.

2024-12-16 09:28 UTC, OriginCode commented on app-utils/nuclei/autobuild/defines
> +BUILDDEP="go"
No PKGDEP? Really?

2024-12-16 09:30 UTC, eatradish requested changes, later dismissed

2024-12-16 09:30 UTC, eatradish commented on app-utils/nuclei/autobuild/build
> +abinfo "shell is  go build -v -o "nuclei"  "$SRCDIR/cmd/nuclei""
Contains redundant spaces

2024-12-16 10:07 UTC, OriginCode requested changes

2024-12-16 10:07 UTC, OriginCode commented on app-utils/nuclei/autobuild/build
>  abinfo "shell is  go build -v -o "nuclei"  "$SRCDIR/cmd/nuclei""
No need to tell the command that's being run.

2024-12-16 10:07 UTC, OriginCode commented on app-utils/nuclei/autobuild/build
>  abinfo "install nuclei..."
Capitalize "install"

2024-12-16 10:31 UTC, neko205-mx commented
longarch working fine
![图片](https://github.com/user-attachments/assets/79fd2955-ecfc-4a2f-9184-b9669c13931d)
arm working fine
![图片](https://github.com/user-attachments/assets/b5f19623-fa77-4247-b01e-bafe3e52baaa)
amd64 working fine
![图片](https://github.com/user-attachments/assets/06b848d4-ef61-4af6-bd41-2fe1cb52580c)

2024-12-16 10:35 UTC, MingcongBai requested changes

2024-12-16 10:35 UTC, MingcongBai commented on app-utils/nuclei/autobuild/defines
> +
Add:

```
FIXME: Autobuild does not yet support splitting debug symbols from Go executables.
```

2024-12-16 10:35 UTC, MingcongBai commented on app-utils/nuclei/autobuild/build
> +abinfo "INSTALL nuclei..."
This should be:

```
abinfo "Building nuclei ...```
```

2024-12-16 10:35 UTC, MingcongBai commented on app-utils/nuclei/autobuild/build
> +
Here:

```
abinfo "Installing nuclei ..."
```

2024-12-16 10:35 UTC, MingcongBai commented on app-utils/nuclei/autobuild/build
> +install -Dvm644 'LICENSE.md' "$PKGDIR/usr/share/licenses/nuclei/LICENSE"
This should be installed in `/usr/share/doc/nuclei`.

2024-12-16 13:22 UTC, OriginCode requested changes

2024-12-16 13:22 UTC, OriginCode commented on app-utils/nuclei/autobuild/build
> +install -Dvm644 'LICENSE.md' "$PKGDIR/usr/share/doc/nuclei/LICENSE"
Use absolute paths.

2024-12-16 13:45 UTC, MingcongBai requested changes

2024-12-16 13:45 UTC, MingcongBai commented on app-utils/nuclei/autobuild/defines
> +ABSPLITDBG=0
The comment below should go above this line.

2024-12-16 13:45 UTC, MingcongBai commented on app-utils/nuclei/autobuild/defines
> +PKGDES="Fast template-based vulnerability scanner"
Remove "Fast":

Template-based vulnerability scanner

2024-12-16 13:45 UTC, MingcongBai commented on app-utils/nuclei/autobuild/build
> +install -Dvm644 'LICENSE.md' "$PKGDIR"/usr/share/doc/nuclei/LICENSE
Why drop the .md suffix?

2024-12-16 18:20 UTC, MingcongBai requested changes

2024-12-16 18:20 UTC, MingcongBai commented on app-utils/nuclei/autobuild/build
> +install -Dvm644 "$SRCDIR"/LICENSE.md "$PKGDIR"/usr/share/doc/nuclei/LINCENSE.md
Typo.

2024-12-16 18:20 UTC, MingcongBai commented on app-utils/nuclei/autobuild/build
> +install -Dvm644 "$SRCDIR"/README*.md -t "$PKGDIR"/usr/share/doc/nuclei
You can actually simplify:

```
install -Dvm644 "$SRCDIR"/README*.md "$SRCDIR"/LICENSE.md \
    -t "$PKGDIR"/usr/share/doc/nuclei/
```

2024-12-16 18:20 UTC, MingcongBai commented on app-utils/nuclei/autobuild/defines
> +# FIXME: Autobuild does not yet support splitting debug symbols from Go executables.\
Extraneous \ at the end of the comment.

2024-12-16 18:21 UTC, MingcongBai commented on app-utils/nuclei/autobuild/defines
> +BUILDDEP="go"
Would be nice to have an empty line before the comment, just to make the code more readable.

2024-12-17 02:53 UTC, OriginCode requested changes

2024-12-17 02:53 UTC, OriginCode commented on app-utils/nuclei/autobuild/build
> +    -t "$PKGDIR"/usr/share/doc/nuclei/
Add a final newline. It seems that your editor didn't follow the [editorconfig](https://editorconfig.org/), you may install a corresponding plugin/extension for your editor or use the editors listed on the website that support editorconfig.

2024-12-17 03:24 UTC, OriginCode approved these changes

2024-12-17 03:25 UTC, OriginCode approved these changes

2024-12-21 05:33 UTC, MingcongBai approved these changes

2024-12-21 05:33 UTC, merged