ghostty: add: ghostty, 1.0.0
AOSC-Dev/aosc-os-abbs pull request #9079
Opened 2024-12-27 03:56 UTC by mouyase

Topic Description
-----------------

- add: ghostty, 1.0.0

Package(s) Affected
-------------------

- ghostty: 1.0.0

Security Update?
----------------

No

Build Order
-----------

```
#buildit ghostty
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-12-31 23:43 UTC, xtexChooser commented
`add: ghostty, 1.0.0`: should be `ghostty: new, 1.0.0`

2025-01-05 09:31 UTC, eatradish commented
LGTM on AMD64:

![图片](https://github.com/user-attachments/assets/2a366cfa-3d2d-4855-a0a3-cbbf36ea98ee)

2025-01-05 09:35 UTC, MingcongBai requested changes

2025-01-05 09:35 UTC, MingcongBai commented on app-utils/ghostty/autobuild/defines
> +PKGDES="A GPU-accelerated cross-platform terminal emulator and multiplexer"
Remove "cross-platform" as it's irrelevant information.

2025-01-05 09:35 UTC, MingcongBai commented on app-utils/ghostty/autobuild/defines
> +# zig does not support non amd64 architecture
Add "FIXME:" prefix.

2025-01-05 09:39 UTC, MingcongBai requested changes
Seems to be some trouble with pipe handling:

![图片](https://github.com/user-attachments/assets/1fa5678d-bd86-4477-8181-6c20c3804b9f)

2025-01-05 09:45 UTC, MingcongBai commented
Issue reported upstream:

https://github.com/ghostty-org/ghostty/discussions/4613

2025-02-20 08:04 UTC, eatradish commented
> Issue reported upstream:
> 
> [ghostty-org/ghostty#4613](https://github.com/ghostty-org/ghostty/discussions/4613)

![图片](https://github.com/user-attachments/assets/8603fa3d-1ec1-4d71-8a0f-cbb42c977a20)

Upstream fixed this problem?

2025-02-22 18:14 UTC, MingcongBai approved these changes

2025-02-22 18:14 UTC, merged