amarok: new, 3.2.0
AOSC-Dev/aosc-os-abbs pull request #9110
Opened 2024-12-30 04:02 UTC by prcups

Topic Description
-----------------

- amarok: new, 3.2.0
- libmygpo-qt: new, 1.1.0
- libofa: apply patches from archlinux to pass build

Package(s) Affected
-------------------

- libofa: 0.9.3-6

Security Update?
----------------

No

Build Order
-----------

```
#buildit libofa  libmygpo-qt  amarok
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-12-30 06:05 UTC, eatradish requested changes
![图片](https://github.com/user-attachments/assets/97734e96-ad25-443d-8f65-88d76bff1dd7)

2024-12-31 17:44 UTC, stdmnpkg commented
does not compute

```
Application: Amarok (amarok), signal: Segmentation fault

[KCrash Handler]
#4  __GI_memcpy () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:523
#5  0x00007f46ce4f63d1 in bitmap_copy () at /usr/lib/libsamba-util.so.0
#6  0x00007f4689c66da6 in SQL_SELECT::test_quick_select(THD*, Bitmap<64u>, unsigned long long, unsigned long long, bool, bool, bool, bool, Item_func::Bitmap) () at /usr/lib/libmariadbd.so.19
#7  0x00007f4689f3e19b in Sql_cmd_delete::delete_from_single_table(THD*) () at /usr/lib/libmariadbd.so.19
#8  0x00007f4689f4087e in Sql_cmd_delete::execute_inner(THD*) () at /usr/lib/libmariadbd.so.19
#9  0x00007f4689b43752 in Sql_cmd_dml::execute(THD*) () at /usr/lib/libmariadbd.so.19
#10 0x00007f4689bbc054 in mysql_execute_command(THD*, bool) () at /usr/lib/libmariadbd.so.19
#11 0x00007f4689bbe7e9 in mysql_parse(THD*, char*, unsigned int, Parser_state*) () at /usr/lib/libmariadbd.so.19
#12 0x00007f4689bbfc0a in dispatch_command(enum_server_command, THD*, char*, unsigned int, bool) () at /usr/lib/libmariadbd.so.19
#13 0x00007f46899648eb in ??? () at /usr/lib/libmariadbd.so.19
#14 0x00007f4689954d3e in mysql_send_query () at /usr/lib/libmariadbd.so.19
#15 0x00007f4689954da1 in mysql_real_query () at /usr/lib/libmariadbd.so.19
#16 0x00007f46a80130ac in ??? () at /usr/lib/qt5/plugins/amarok_storage-mysqlestorage.so
#17 0x00007f46a80f3ac4 in DatabaseUpdater::deleteOrphanedByDirectory(QString const&) () at /usr/lib/libamarok-sqlcollection.so.1
#18 0x00007f46a81122a7 in SqlRegistry::SqlRegistry(Collections::SqlCollection*) () at /usr/lib/libamarok-sqlcollection.so.1
#19 0x00007f46a80fce98 in Collections::SqlCollection::SqlCollection(QSharedPointer<SqlStorage> const&) () at /usr/lib/libamarok-sqlcollection.so.1
#20 0x00007f46a80fd899 in Collections::SqlCollectionFactory::createSqlCollection(QSharedPointer<SqlStorage>) const () at /usr/lib/libamarok-sqlcollection.so.1
#21 0x00007f46bc04ecbd in ??? () at /usr/lib/qt5/plugins/amarok_collection-mysqlcollection.so
#22 0x00007f46dc090010 in Plugins::PluginManager::checkPluginEnabledStates() () at /usr/lib/libamaroklib.so.1
#23 0x00007f46dc084c71 in Plugins::PluginManager::PluginManager(QObject*) () at /usr/lib/libamaroklib.so.1
#24 0x00007f46dc084d70 in Plugins::PluginManager::instance() () at /usr/lib/libamaroklib.so.1
#25 0x00007f46dc072859 in MainWindow::MainWindow() () at /usr/lib/libamaroklib.so.1
#26 0x00007f46dc06cc4f in App::continueInit() () at /usr/lib/libamaroklib.so.1
#27 0x000055808dc78666 in ??? ()
#28 0x00007f46da061fc8 in __libc_start_call_main (main=main@entry=0x55808dc73900, argc=argc@entry=1, argv=argv@entry=0x7ffe8012cd98) at ../sysdeps/nptl/libc_start_call_main.h:58
#29 0x00007f46da06208b in __libc_start_main_impl (main=0x55808dc73900, argc=1, argv=0x7ffe8012cd98, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe8012cd88) at ../csu/libc-start.c:360
#30 0x000055808dc78e55 in ??? ()
[Inferior 1 (process 195416) detached]
```

2025-01-03 07:12 UTC, prcups commented
> does not compute
> 
> ```
> Application: Amarok (amarok), signal: Segmentation fault
> 
> [KCrash Handler]
> #4  __GI_memcpy () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:523
> #5  0x00007f46ce4f63d1 in bitmap_copy () at /usr/lib/libsamba-util.so.0
> #6  0x00007f4689c66da6 in SQL_SELECT::test_quick_select(THD*, Bitmap<64u>, unsigned long long, unsigned long long, bool, bool, bool, bool, Item_func::Bitmap) () at /usr/lib/libmariadbd.so.19
> #7  0x00007f4689f3e19b in Sql_cmd_delete::delete_from_single_table(THD*) () at /usr/lib/libmariadbd.so.19
> #8  0x00007f4689f4087e in Sql_cmd_delete::execute_inner(THD*) () at /usr/lib/libmariadbd.so.19
> #9  0x00007f4689b43752 in Sql_cmd_dml::execute(THD*) () at /usr/lib/libmariadbd.so.19
> #10 0x00007f4689bbc054 in mysql_execute_command(THD*, bool) () at /usr/lib/libmariadbd.so.19
> #11 0x00007f4689bbe7e9 in mysql_parse(THD*, char*, unsigned int, Parser_state*) () at /usr/lib/libmariadbd.so.19
> #12 0x00007f4689bbfc0a in dispatch_command(enum_server_command, THD*, char*, unsigned int, bool) () at /usr/lib/libmariadbd.so.19
> #13 0x00007f46899648eb in ??? () at /usr/lib/libmariadbd.so.19
> #14 0x00007f4689954d3e in mysql_send_query () at /usr/lib/libmariadbd.so.19
> #15 0x00007f4689954da1 in mysql_real_query () at /usr/lib/libmariadbd.so.19
> #16 0x00007f46a80130ac in ??? () at /usr/lib/qt5/plugins/amarok_storage-mysqlestorage.so
> #17 0x00007f46a80f3ac4 in DatabaseUpdater::deleteOrphanedByDirectory(QString const&) () at /usr/lib/libamarok-sqlcollection.so.1
> #18 0x00007f46a81122a7 in SqlRegistry::SqlRegistry(Collections::SqlCollection*) () at /usr/lib/libamarok-sqlcollection.so.1
> #19 0x00007f46a80fce98 in Collections::SqlCollection::SqlCollection(QSharedPointer<SqlStorage> const&) () at /usr/lib/libamarok-sqlcollection.so.1
> #20 0x00007f46a80fd899 in Collections::SqlCollectionFactory::createSqlCollection(QSharedPointer<SqlStorage>) const () at /usr/lib/libamarok-sqlcollection.so.1
> #21 0x00007f46bc04ecbd in ??? () at /usr/lib/qt5/plugins/amarok_collection-mysqlcollection.so
> #22 0x00007f46dc090010 in Plugins::PluginManager::checkPluginEnabledStates() () at /usr/lib/libamaroklib.so.1
> #23 0x00007f46dc084c71 in Plugins::PluginManager::PluginManager(QObject*) () at /usr/lib/libamaroklib.so.1
> #24 0x00007f46dc084d70 in Plugins::PluginManager::instance() () at /usr/lib/libamaroklib.so.1
> #25 0x00007f46dc072859 in MainWindow::MainWindow() () at /usr/lib/libamaroklib.so.1
> #26 0x00007f46dc06cc4f in App::continueInit() () at /usr/lib/libamaroklib.so.1
> #27 0x000055808dc78666 in ??? ()
> #28 0x00007f46da061fc8 in __libc_start_call_main (main=main@entry=0x55808dc73900, argc=argc@entry=1, argv=argv@entry=0x7ffe8012cd98) at ../sysdeps/nptl/libc_start_call_main.h:58
> #29 0x00007f46da06208b in __libc_start_main_impl (main=0x55808dc73900, argc=1, argv=0x7ffe8012cd98, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe8012cd88) at ../csu/libc-start.c:360
> #30 0x000055808dc78e55 in ??? ()
> [Inferior 1 (process 195416) detached]
> ```

Phonon needs a backend to play audio. I recommend adding phonon-backend-gstreamer as a dependency to phonon.

2025-01-03 07:13 UTC, MingcongBai commented
> > does not compute
> > ```
> > Application: Amarok (amarok), signal: Segmentation fault
> > 
> > [KCrash Handler]
> > #4  __GI_memcpy () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:523
> > #5  0x00007f46ce4f63d1 in bitmap_copy () at /usr/lib/libsamba-util.so.0
> > #6  0x00007f4689c66da6 in SQL_SELECT::test_quick_select(THD*, Bitmap<64u>, unsigned long long, unsigned long long, bool, bool, bool, bool, Item_func::Bitmap) () at /usr/lib/libmariadbd.so.19
> > #7  0x00007f4689f3e19b in Sql_cmd_delete::delete_from_single_table(THD*) () at /usr/lib/libmariadbd.so.19
> > #8  0x00007f4689f4087e in Sql_cmd_delete::execute_inner(THD*) () at /usr/lib/libmariadbd.so.19
> > #9  0x00007f4689b43752 in Sql_cmd_dml::execute(THD*) () at /usr/lib/libmariadbd.so.19
> > #10 0x00007f4689bbc054 in mysql_execute_command(THD*, bool) () at /usr/lib/libmariadbd.so.19
> > #11 0x00007f4689bbe7e9 in mysql_parse(THD*, char*, unsigned int, Parser_state*) () at /usr/lib/libmariadbd.so.19
> > #12 0x00007f4689bbfc0a in dispatch_command(enum_server_command, THD*, char*, unsigned int, bool) () at /usr/lib/libmariadbd.so.19
> > #13 0x00007f46899648eb in ??? () at /usr/lib/libmariadbd.so.19
> > #14 0x00007f4689954d3e in mysql_send_query () at /usr/lib/libmariadbd.so.19
> > #15 0x00007f4689954da1 in mysql_real_query () at /usr/lib/libmariadbd.so.19
> > #16 0x00007f46a80130ac in ??? () at /usr/lib/qt5/plugins/amarok_storage-mysqlestorage.so
> > #17 0x00007f46a80f3ac4 in DatabaseUpdater::deleteOrphanedByDirectory(QString const&) () at /usr/lib/libamarok-sqlcollection.so.1
> > #18 0x00007f46a81122a7 in SqlRegistry::SqlRegistry(Collections::SqlCollection*) () at /usr/lib/libamarok-sqlcollection.so.1
> > #19 0x00007f46a80fce98 in Collections::SqlCollection::SqlCollection(QSharedPointer<SqlStorage> const&) () at /usr/lib/libamarok-sqlcollection.so.1
> > #20 0x00007f46a80fd899 in Collections::SqlCollectionFactory::createSqlCollection(QSharedPointer<SqlStorage>) const () at /usr/lib/libamarok-sqlcollection.so.1
> > #21 0x00007f46bc04ecbd in ??? () at /usr/lib/qt5/plugins/amarok_collection-mysqlcollection.so
> > #22 0x00007f46dc090010 in Plugins::PluginManager::checkPluginEnabledStates() () at /usr/lib/libamaroklib.so.1
> > #23 0x00007f46dc084c71 in Plugins::PluginManager::PluginManager(QObject*) () at /usr/lib/libamaroklib.so.1
> > #24 0x00007f46dc084d70 in Plugins::PluginManager::instance() () at /usr/lib/libamaroklib.so.1
> > #25 0x00007f46dc072859 in MainWindow::MainWindow() () at /usr/lib/libamaroklib.so.1
> > #26 0x00007f46dc06cc4f in App::continueInit() () at /usr/lib/libamaroklib.so.1
> > #27 0x000055808dc78666 in ??? ()
> > #28 0x00007f46da061fc8 in __libc_start_call_main (main=main@entry=0x55808dc73900, argc=argc@entry=1, argv=argv@entry=0x7ffe8012cd98) at ../sysdeps/nptl/libc_start_call_main.h:58
> > #29 0x00007f46da06208b in __libc_start_main_impl (main=0x55808dc73900, argc=1, argv=0x7ffe8012cd98, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe8012cd88) at ../csu/libc-start.c:360
> > #30 0x000055808dc78e55 in ??? ()
> > [Inferior 1 (process 195416) detached]
> > ```
> 
> Phonon needs a backend to play audio. I recommend adding phonon-backend-gstreamer as a dependency to phonon.

Sure, go ahead.

2025-01-03 07:54 UTC, prcups commented
Due to buggy performance and slow maintaining of amarok, I decide to give up add amarok to aosc tree. Remaining fix will be upload in another pull request.

2025-01-03 07:54 UTC, closed without merging

2025-01-03 15:33 UTC, BenderBlog commented
Additional comment: Amarok requires a maria-db to work, and that's why I give up packing it:P

2025-01-03 16:28 UTC, stdmnpkg commented
> Additional comment: Amarok requires a maria-db to work, and that's why I give up packing it:P

> #15 0x00007f4689954da1 in mysql_real_query () at /usr/lib/libmariadbd.so.19

so instead of accidentally linked to `libmariadbd` as i once believe, it intentionally linked to `libmariadbd`? amazing!