gamemode: new, 1.8.2
AOSC-Dev/aosc-os-abbs pull request #9123
Opened 2024-12-31 11:14 UTC by neko205-mx

Topic Description
-----------------

gamemode: new, 1.8.2

Package(s) Affected
-------------------

gamemode: new, 1.8.2

Security Update?
----------------

No

Build Order
-----------

```
#buildit gamemode
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

Architectural progress for secondary ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2024-12-31 11:19 UTC, neko205-mx commented
![image](https://github.com/user-attachments/assets/12ade2b4-64f7-4159-95fa-48ac8c64f0ba)
amd64 running well

2024-12-31 11:46 UTC, neko205-mx commented
```
(ssh)root@Apocalypse [ g ] # gamemoded -t
: Loading config
Loading config file [/usr/share/gamemode/gamemode.ini]
: Running tests

:: Basic client tests
:: Passed

:: Dual client tests
gamemode request succeeded and is active
Quitting by request...
:: Passed

:: Gamemoderun and reaper thread tests
...Waiting for child to quit...
...Waiting for reaper thread (reaper_frequency set to 5 seconds)...
:: Passed

:: Supervisor tests
:: Passed

:: Feature tests
::: Verifying CPU governor setting
ERROR: glob failed for cpu governors: (No such file or directory)
ERROR: glob failed for cpu governors: (No such file or directory)
ERROR: Governor was not set to performance (was actually )!
::: Failed!
::: Verifying Scripts
::: Passed (no scripts configured to run)
::: Verifying GPU Optimisations
::: Passed (gpu optimisations not configured to run)
::: Verifying renice
::: Passed (no renice configured)
::: Verifying ioprio
::: Passed
ERROR: :: Failed!
: Tests Failed!
```
The loongarch is running with a Cpu error, but that should be fixable via configuration, but I don't have the equipment for it on hand.

2025-01-01 05:22 UTC, neko205-mx commented
```
(ssh)root@Zinfandel [ g ] # gamemoded -t
: Loading config
Loading config file [/usr/share/gamemode/gamemode.ini]
: Running tests

:: Basic client tests
:: Passed

:: Dual client tests
gamemode request succeeded and is active
Quitting by request...
:: Passed

:: Gamemoderun and reaper thread tests
...Waiting for child to quit...
...Waiting for reaper thread (reaper_frequency set to 5 seconds)...
:: Passed

:: Supervisor tests
:: Passed

:: Feature tests
::: Verifying CPU governor setting
::: Passed
::: Verifying Scripts
::: Passed (no scripts configured to run)
::: Verifying GPU Optimisations
::: Passed (gpu optimisations not configured to run)
::: Verifying renice
::: Passed (no renice configured)
::: Verifying ioprio
::: Passed
:: Passed

: All Tests Passed!
(ssh)root@Zinfandel [ g ] # 
```
arm running well

2025-01-02 08:51 UTC, OriginCode requested changes

2025-01-02 08:51 UTC, OriginCode commented on app-games/gamemode/autobuild/defines
> +BUILDDEP="git meson"
No need to include `git` as a BUILDDEP.

2025-01-12 05:49 UTC, OriginCode requested changes, later dismissed

2025-01-12 05:49 UTC, OriginCode commented on app-games/gamemode/autobuild/templates
> + 使得'gamemode'默认启动
部分引号和逗号请使用 zh_CN 规范。

2025-01-12 05:49 UTC, OriginCode commented on app-games/gamemode/autobuild/templates
> + systemctl --user enable gamemoded
Consider using `--now` to start the service too?

2025-01-12 05:49 UTC, OriginCode commented on app-games/gamemode/autobuild/defines
> +BUILDDEP="meson debconf"
No need to refer `debconf` here.

2025-01-14 08:25 UTC, neko205-mx commented on app-games/gamemode/autobuild/defines
> +BUILDDEP="meson debconf"
![image](https://github.com/user-attachments/assets/c81cacb6-909e-41e0-af33-3b2939ee75c9)
error

debconf is required

2025-01-14 08:38 UTC, MingcongBai requested changes

2025-01-14 08:38 UTC, MingcongBai commented on app-games/gamemode/autobuild/defines
> +BUILDDEP="meson debconf"
debconf should be PKGDEP.

2025-01-14 08:38 UTC, MingcongBai commented on app-games/gamemode/autobuild/defines
> +PKGDES="A daemon/lib combo that allows games to request a set of optimisations be temporarily applied to the host OS"
A daemon to temporarily apply optimized system parameters for gaming workloads

2025-01-14 08:38 UTC, MingcongBai commented on app-games/gamemode/autobuild/templates
> + To enable all features of 'gamemode', add the user to the 'gamemode' group.
```
To enable all GameMode features, add your user to the `gamemode' group with the following command:
.
sudo usermod -aG gamemode <username>
.
After adding your user to the group, please re-login for the changes to take effect.
.
You may also enable GameMode automatically as you log in with the following command:
.
systemctl --user enable gamemoded
```

No need for `--now` as it will take effect with a relogin.

2025-01-14 08:38 UTC, MingcongBai commented on app-games/gamemode/autobuild/templates
> +Description: Gamemode User Group Configuration
GameMode Configuration

2025-01-14 08:38 UTC, MingcongBai commented on app-games/gamemode/autobuild/templates
> +Description-zh_CN.UTF-8: Gamemode 用户组配置要求
GameMode 配置贴士

2025-01-14 08:38 UTC, MingcongBai commented on app-games/gamemode/autobuild/templates
> + 要启用‘gamemode’的所有功能，需将用户添加到‘gamemode’用户组。
```
要利用 GameMode 的所有功能，请使用如下命令将您的用户添加到 `gamemode' 用户组：
.
sudo usermod -aG gamemode <用户名>
.
完成后，请重新登录以使更改生效。
.
如果您希望在登录时默认启用 GameMode，输入如下命令：
.
systemctl enable gamemode --user
.
即可让 GameMode 的登录自启动。
```

2025-01-14 08:51 UTC, MingcongBai requested changes

2025-01-14 08:51 UTC, MingcongBai commented on app-games/gamemode/autobuild/defines
> +
Extraneous new line

2025-01-14 08:51 UTC, MingcongBai commented on app-games/gamemode/autobuild/defines
> +PKGDEP="glibc gcc gcc-runtime dbus libnih polkit debconf"
Wait, why is gcc needed?

2025-01-20 07:21 UTC, neko205-mx commented
```
(ssh)root@Hydaelyn [ g ] # gamemoded -test
: Loading config
Loading config file [/usr/share/gamemode/gamemode.ini]
: Running tests

:: Basic client tests
:: Passed

:: Dual client tests
gamemode request succeeded and is active
Quitting by request...
:: Passed

:: Gamemoderun and reaper thread tests
...Waiting for child to quit...
...Waiting for reaper thread (reaper_frequency set to 5 seconds)...
:: Passed

:: Supervisor tests
:: Passed

:: Feature tests
::: Verifying CPU governor setting
::: Passed
::: Verifying Scripts
::: Passed (no scripts configured to run)
::: Verifying GPU Optimisations
::: Passed (gpu optimisations not configured to run)
::: Verifying renice
::: Passed (no renice configured)
::: Verifying ioprio
::: Passed
:: Passed

: All Tests Passed!
```
new deb running well

2025-01-20 07:26 UTC, MingcongBai approved these changes
LGTM.

2025-01-20 07:27 UTC, merged