ciel: update to 3.8.6
AOSC-Dev/aosc-os-abbs pull request #9129
Opened 2024-12-31 23:41 UTC by xtexChooser

Topic Description
-----------------

- ciel: update to 3.8.6

Package(s) Affected
-------------------

- ciel: 3.8.6

Security Update?
----------------

No

Build Order
-----------

```
#buildit ciel
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

2025-01-03 01:24 UTC, MingcongBai commented
Still incorrectly enables read-only TREE in migrated workspaces.

2025-01-04 09:30 UTC, MingcongBai commented
> Still incorrectly enables read-only TREE in migrated workspaces.

My mistake, I probably forgot to reload the instance. It actually works properly.

2025-01-04 09:30 UTC, MingcongBai requested changes

2025-01-04 09:30 UTC, MingcongBai commented on app-devel/ciel/autobuild/beyond
>  PREFIX="$PKGDIR/usr/" ./install-assets.sh
Missing abinfo.

2025-01-04 09:52 UTC, xtexChooser commented
Superseded by #9164

2025-01-04 09:52 UTC, closed without merging